### ISSUE TITLE
sofajraft快照存储查询

### ISSUE THREAD

**Issue by chenzhanpeng** [sofastack/sofa-jraft#1008]
快照加载恢复，保存快照，这一块的有无用Rhedkv实现，这样提供给客户端调用比较方便，这块的DMEO有无，文档内容比较少，初期使用得大量翻源码有些场景才能明白，可以完善一下文档吗谢谢

**Comment by fengjiachun** [comment]
rheakv 的快照实现参考这里：https://github.com/sofastack/sofa-jraft/blob/9caaab1098a4be041b73194c4ec8efe0018dfe84/jraft-rheakv/rheakv-core/src/main/java/com/alipay/sofa/jraft/rhea/storage/AbstractKVStoreSnapshotFile.java#L48
