### ISSUE TITLE
存在一个命令可能被执行两次的风险

### ISSUE THREAD

**Issue by xuziyang** [sofastack/sofa-jraft#1014]
客户端发送一条命令到Leader 节点，Leader 可能在执行命令之后但响应客户端之前宕机，此时客户端再去寻找下一个 Leader，同一个命令就会被执行两次

就是说，客户端协议设计有缺陷

**Comment by killme2008** [comment]
这不是 raft 算法要解决的问题。任何远程调用都有这个问题，需要应用层自己设计解决。
