### ISSUE TITLE
有一个大对象，可能会超过多个g，需要存在快照里面

### ISSUE THREAD

**Issue by chenzhanpeng** [sofastack/sofa-jraft#1016]
当我序列化保存到磁盘文件的时候，大了就会慢，请问下sofajraft有什么现成的工具包，或者技术，能实现高速存储，恢复吗，还可以分豁文件，比如多少mb分割成一个小文件

**Comment by fengjiachun** [comment]
快照如何保存，jraft 没有提供什么工具包，快照本身完全是在业务状态机中实现，jraft 只是”触发“快照保存
