### ISSUE TITLE
Raft's own rocksdb instance during snapshot

### ISSUE THREAD

**Issue by asad-awadia** [sofastack/sofa-jraft#1024]
### Your question

During `onSnapshotSave` jraft guarantees that there are no more writes going to the state machine

but what about jraft's own rocksdb? Is that also stopped? Are new write requests being written into the log and not being sent to the statemachine? Or is raft's own rocksdb also locked fully?

### Environment

- SOFAJRaft version:
- JVM version (e.g. `java -version`): 11
- OS version (e.g. `uname -a`): linux
- Maven version: 3.5.4

**Comment by killme2008** [comment]
It will be blocked until the snapshot finishes. So you must carefully implement the `onSnasphotSave` callback, capture the snapshot synchronously, and then save it into persistent storage asynchronously.
