### ISSUE TITLE
最新版本rpc支持gprc么?

### ISSUE THREAD

**Issue by googlefan** [sofastack/sofa-jraft#1027]
### Your question
我在使用1.3.13版本jraft进行分布式文件系统的功能开发,rpc 使用的是bolt rpc,编解码使用的hessian 协议, 该协议应该是不支持流式编解码的,这样的话,在处理大文件时 ,rpc 处理会占用很大的堆内存,而且效率也非常低, 如果换成grpc, 编解码使用protobuf,应该是能提升整体的性能的,所以想问一下,咱们最新版本 支持grpc 了么? 
关联issue #748 @fengjiachun  有空帮忙看一下哈
### Environment

- SOFAJRaft version:1.3.13
- JVM version (e.g. `java -version`):openjdk11
- OS version (e.g. `uname -a`):centos
- Maven version:3.18
- IDE version:idea

**Comment by fengjiachun** [comment]
支持，关联 issue 里不是有回答吗

**Comment by googlefan** [comment]
> 支持，关联 issue 里不是有回答吗

我跟踪 RPC factory  实现 没 注意到 grpc呢, 我看默认的rpc 就有 bolt的. 而且 serialize 接口的实现也只有 hessian 的实现类型

**Comment by googlefan** [comment]
啊 估计是我理解错了,  根据讨论的issue 我以为Jraft 只有 在 log 的storage 里应用了grpc 的优化
