### ISSUE TITLE
有什么办法能在选举时携带一些额外信息

### ISSUE THREAD

**Issue by funky-eyes** [sofastack/sofa-jraft#1028]
### Your question

之前有提过类似问题，但是解决方案是采用的其他，比如选完leader后，主动发一起一条同步信息把leader的元数据共享给其他节点，但是无法做到follower的数据共享给所有节点，我们目前有个需求是每个节点有一些不同的元数据，希望在选举完时，每个成员都知道所有成员的元数据，比如所有成员的业务端口，选举可能用的是一个端口，但是通信可能用的http端口，这个http端口可能每个节点还都不同，能确定的只有raft端口，所以需要一个这样的元数据共享来得到所有节点的确实数据和状态

### Your scenes

Describe your use scenes (why need this feature)

### Your advice

Describe the advice or solution you'd like

### Environment

- SOFAJRaft version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by killme2008** [comment]
你需要一个分布式 KV，可以在 state machine 里维护一个 hashmap(node id -> metadata)，所有节点可以都往 leader 发送 task 去写入这个 hashmap，那么所有信息既然就同步到所有节点。

可以考虑用jraft 自带的 rheakv

**Comment by funky-eyes** [comment]
> 你需要一个分布式 KV，可以在 state machine 里维护一个 hashmap(node id -> metadata)，所有节点可以都往 leader 发送 task 去写入这个 hashmap，那么所有信息既然就同步到所有节点。
> 
> 可以考虑用jraft 自带的 rheakv

非leader节点可以创建task发进去吗？我怎么记得是不行的？

**Comment by VampireDX** [comment]
我的理解是，jraft 本身就是一个基于raft协议的分布式状态同步机，不应该额外引入其他分布式KV
