### ISSUE TITLE
Does Raft have a mechanism for regularly cleaning up large logs?

### ISSUE THREAD

**Issue by stone-98** [sofastack/sofa-jraft#1031]
### Your question

Does Raft have a mechanism for regularly cleaning up large logs?

### Your scenes

Describe your use scenes (why need this feature)

### Your advice

Describe the advice or solution you'd like

### Environment

- SOFAJRaft version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by killme2008** [comment]
Please enabling the snapshot, then the jraft will truncate the old logs after do a snapshot.

**Comment by killme2008** [comment]
You can find more info at https://www.sofastack.tech/en/projects/sofa-jraft/jraft-user-guide/

section 2.6 Snapshot service.

**Comment by stone-98** [comment]
@killme2008 Hello, what I mean is that there are too many raft.log files (referring to application logs).

**Comment by stone-98** [comment]
okk,I understand.
