### ISSUE TITLE
method ServerStreamHelper.getServerStream cannot take ServerStream from ForwardingServerCall.SimpleForwardingServerCall

### ISSUE THREAD

**Issue by AlchemyDing** [sofastack/sofa-jraft#1043]
### Describe the bug

method ServerStreamHelper.getServerStream cannot take ServerStream from ForwardingServerCall.SimpleForwardingServerCall.
serverCall is usually enhanced to ForwardingServerCall.SimpleForwardingServerCall by skywalking-agent or opentelemetry-javaagent,etc.At this point, ServerCallImpl will become the delegate of SimpleForwardingServerCall.
When nacos use enhancement such as opentelemetry javaagent or skywalking javaagent,etc, the server cannot connect to the client.
associate [issue](https://github.com/alibaba/nacos/issues/11422)
### Expected behavior
[ServerStreamHelper.getServerStream](https://github.com/sofastack/sofa-jraft/blob/master/jraft-extension/rpc-grpc-impl/src/main/java/io/grpc/internal/ServerStreamHelper.java) can take ServerStream from ForwardingServerCall.SimpleForwardingServerCall
### Actual behavior
[ServerStreamHelper.getServerStream](https://github.com/sofastack/sofa-jraft/blob/master/jraft-extension/rpc-grpc-impl/src/main/java/io/grpc/internal/ServerStreamHelper.java) cannot take ServerStream from ForwardingServerCall.SimpleForwardingServerCall
### How to resolve
add  judgement for ForwardingServerCall.SimpleForwardingServerCall
### Minimal yet complete reproducer code (or GitHub URL to code)
[ServerStreamHelper.getServerStream](https://github.com/sofastack/sofa-jraft/blob/master/jraft-extension/rpc-grpc-impl/src/main/java/io/grpc/internal/ServerStreamHelper.java)

**Comment by AlchemyDing** [comment]
if you think it needs to be fixed, please assign this issue to me

**Comment by fengjiachun** [comment]
Please feel free to make any necessary fix. Thank you. @AlchemyDing
