### ISSUE TITLE
关于发布计划

### ISSUE THREAD

**Issue by LinHuiG** [sofastack/sofa-jraft#1052]
### Your question

你好，1.3.13版本是在今年的4月份发布的，已经过去半年多了，这期间修复了不少bug（比如日志阻塞心跳等问题），是否有计划什么时候为这些fix发布一个新版本呢

### Environment

- SOFAJRaft version:1.3.13
- JVM version (e.g. `java -version`):1.8_202
- OS version (e.g. `uname -a`):centos7.8
- Maven version:3.8.1
- IDE version:idea 2023.2.5

**Comment by killme2008** [comment]
@fengjiachun  I think we can release a new version next week or month.

**Comment by fengjiachun** [comment]
> @fengjiachun I think we can release a new version next week or month.

LGTM cc @LinHuiG

**Comment by LinHuiG** [comment]
> > @fengjiachun I think we can release a new version next week or month.
> 
> LGTM cc @LinHuiG

感谢~~

**Comment by fengjiachun** [comment]
I am planning to release a new version this month. Before this, we need to pass the Jepsen test.

**Comment by fengjiachun** [comment]
https://github.com/sofastack/sofa-jraft/issues/1064
