### ISSUE TITLE
Does JRaft guarantee idempotency?

### ISSUE THREAD

**Issue by ye-xiaowei** [sofastack/sofa-jraft#1053]
When I send a write request it times out and does a retransmit (network packet loss may have occurred). Will the write be performed 2 times at this point?

**Comment by fengjiachun** [comment]
sofajraft doesn't guarantee idempotency.
Generally, this can be solved at the upper layer. The client can carry a unique id , and the your own stat-machine can make idempotent decisions based on this id.
