### ISSUE TITLE
support higher rocksdb version

### ISSUE THREAD

**Issue by leizhiyuan** [sofastack/sofa-jraft#1057]
### Your question

Describe your question clearly

<img width="1570" alt="image" src="https://github.com/sofastack/sofa-jraft/assets/2684384/61fa1af5-7c0b-4d0d-91a6-a6b9e9c4a216">

in higher version of rocksdb， org.rocksdb,BlockBasedTableConfig.blockCacheCompressedSize()j has been removed
https://github.com/facebook/rocksdb/blob/8d50a7c9df2352e4949aa456206bbd7b9ee49620/java/src/main/java/org/rocksdb/BlockBasedTableConfig.java#L13
### Your scenes

Describe your use scenes (why need this feature)

### Your advice

Describe the advice or solution you'd like

remove this settings

### Environment

- SOFAJRaft version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by fengjiachun** [comment]
Hi, @leizhiyuan , thank you for pointing out this issue, would you be willing to send a pull request to address it?

**Comment by leizhiyuan** [comment]
> Hi, @leizhiyuan , thank you for pointing out this issue, would you be willing to send a pull request to address it?

ok,we use jraft in rocketmq 
https://github.com/apache/rocketmq/pull/7301

rocketmq has a repackage  rocskdb verison based on higher rocksdb version
