### ISSUE TITLE
请教个问题：任务应用到多数派状态机决定条件是怎样的？？？对于kv系统是否因为这个导致数据丢失。

### ISSUE THREAD

**Issue by zxuanhong** [sofastack/sofa-jraft#1087]
### Your question

1. 由于提交任务完成是通过判断是否应用到多数派状态机；
2. 比如kv系统，三个参与者(1,2,3)。1、2两个参与者任务已经应用到状态机。一旦领导转移或者重新选举到3，3节点数据怎么跟上1，2了(他变为领导者了，应该是依据他的日志进行回放的吧)。
3. 如果不更上，那岂不是数据存在丢失了。
4. 是否有配置，要求task一定应用到所有存活参与者。
5. 或者说我怎么保证整个raft集群启动好后，保证所有参与则数据是能够完全跟上leader的。而不会出现部分更上，部分跟不上

### Environment

- SOFAJRaft version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by shihuili1218** [comment]
数据不全的成员，不会成为leader

**Comment by zxuanhong** [comment]
@shihuili1218 那如果调用转移了。因为集群数量一旦多的话，这个参与者丢失一点数据(没有onApply)。那个节点也少一个点。我是否可以认为，这样重复下来整个集群各个节点数据都变得不一致了。是否整个集群都不会在出现leader了

**Comment by shihuili1218** [comment]
强制转移本就是一个危险操作。

另外多数派是为了容错，你说的有没有配置可以让其强制复制到所有节点，这个功能下版本会有，就是pr 1040

**Comment by zxuanhong** [comment]
@shihuili1218 好的，非常感谢。还有能否支持节点间一对一或广播方式通信。这样方便领导节点通过订阅通道直接发送消息到集群中。以前atomix中用起来比较爽。

**Comment by zxuanhong** [comment]
@shihuili1218 请教个问题

**Comment by zxuanhong** [comment]
@shihuili1218 在请教个问题，对于如果使用NWR模型的pr 1040,我想实现所有节点数据一致。那请问这个计算时是使用存活的节点计算还是基础初始化整个节点了。我的意思，如果我不熟一个7个参与者的raft集群。如果down调2个基于NWR如果使用7个节点来计算，还能正常吗(因为已经有两个掉线或者挂掉了)，真实用的只有5个参与者
