### ISSUE TITLE
能否通过spi开放集群成员合法性校验，同时允许成员携带额外信息(用户自行实现成员合法性校验时使用)

### ISSUE THREAD

**Issue by zxuanhong** [sofastack/sofa-jraft#1090]
### Your question

1. 在容器环境，容器的重启可能会导致节点ip变化，如果一直利用ip+port去做成员合法性校验，对容器环境很不友好(当然可以利用域名，但这降低了灵活性，也增加了复杂度)
2. 在atomix中校验其实不是与ip端口绑定，他是与节点id绑定，同时也能携带节点的一些额外信息。
3. 希望jraft可以通过spi开放校验逻辑，让用户自行决定怎么校验成员的合法性，同时可以传入冗余信息，以便校验时利用这些冗余信息进行一定的判断。atomix参考代码如下：
<img width="971" alt="image" src="https://github.com/sofastack/sofa-jraft/assets/62740686/42f0e509-439c-4e7f-afb5-a19b7bd15bc0">
4. 个人认为这能提jraft的灵活性，特别是在容器环境。同时也不违反raft协议本身。

### Environment

- SOFAJRaft version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by fengjiachun** [comment]
这是个不错的功能，不过对于目前的 jraft 不容易实现，在 jraft 中地址信息记录在 Endpoint 对象中，通信层也是直接使用这个 Endpoint 的，没有一个 id 到地址的映射。
不知道使用域名能否解决你的问题

**Comment by zxuanhong** [comment]
@fengjiachun 其实通信还是ip模式，你注意看atomix，他有nodeid，还有对应的address。域名肯定能，但是这降低了灵活性

**Comment by zxuanhong** [comment]
@fengjiachun 而且我觉得能在容器化项目大规模应用，这个还真是很需要的功能，虽然可以使用像k8s的dns地址来配置，到其实还是会遇到很大问题

**Comment by fengjiachun** [comment]
如果你已经有设计思路，可以提高方案上来看看讨论下？

**Comment by zxuanhong** [comment]
@fengjiachun 我抽时间先在验证下可行性。

**Comment by funky-eyes** [comment]
我支持这个改动，我一直期望可以有这样的功能，目前我使用了svc的域名来代理nodeid，避免了容器下ip容易变化的问题，但是这样对部署带来的改动比较多

**Comment by funky-eyes** [comment]
并且我们也想在安全度上做提升，如何去验证一个想要加入的成员的合法性也是一个问题。

**Comment by zxuanhong** [comment]
@fengjiachun @funky-eyes 最近有点忙，上周做了一点。估计下星期后才有时间继续

**Comment by funky-eyes** [comment]
> @fengjiachun @funky-eyes 最近有点忙，上周做了一点。估计下星期后才有时间继续

期待，不过向下兼容上我觉得要考虑下，避免升级的时候老的集群信息中没有nodeid起不来或者有其他问题等。

**Comment by zxuanhong** [comment]
@funky-eyes ok。我需要先在我项目探索下可行性。不过有更好的方案也可以提出来，参考下。

**Comment by funky-eyes** [comment]
或许你可以把当前的设计方案在issue里画一下，我们一起讨论下看下是否有更优解？

**Comment by fengjiachun** [comment]
> > @fengjiachun @funky-eyes 最近有点忙，上周做了一点。估计下星期后才有时间继续
> 
> 期待，不过向下兼容上我觉得要考虑下，避免升级的时候老的集群信息中没有nodeid起不来或者有其他问题等。

是的，需要向前兼容

**Comment by zxuanhong** [comment]
@fengjiachun 很抱歉带来不好的消息。基于内部讨论，目前我们做法要能试下大规模集群。因此内部成员会基于jraft进行大概。比如成员确定这块会使用SWIM协议进行调整(在大规模集群下心跳机制是一种消耗巨大的机制)。目前这种做法与jraft完全背离。因此我将关闭当前issue.
