### ISSUE TITLE
压测性能耗时较高，200多ms

### ISSUE THREAD

**Issue by danhuiwang** [sofastack/sofa-jraft#1106]
[hostname=jraft-02-74d9bddb68-c4hfv][appname=jraft][][][2024-06-05T17:08:20.634+0800][metrics-logger-reporter-1-thread-1][INFO][Slf4jReporter.java,473,log] [type=GAUGE, name=jraft-fsm-caller-disruptor.buffer-size, value=16384] ## '' 
[hostname=jraft-02-74d9bddb68-c4hfv][appname=jraft][][][2024-06-05T17:08:20.634+0800][metrics-logger-reporter-1-thread-1][INFO][Slf4jReporter.java,473,log] [type=GAUGE, name=jraft-fsm-caller-disruptor.remaining-capacity, value=16361] ## '' 
[hostname=jraft-02-74d9bddb68-c4hfv][appname=jraft][][][2024-06-05T17:08:20.634+0800][metrics-logger-reporter-1-thread-1][INFO][Slf4jReporter.java,473,log] [type=GAUGE, name=jraft-log-manager-disruptor.buffer-size, value=16384] ## '' 
[hostname=jraft-02-74d9bddb68-c4hfv][appname=jraft][][][2024-06-05T17:08:20.634+0800][metrics-logger-reporter-1-thread-1][INFO][Slf4jReporter.java,473,log] [type=GAUGE, name=jraft-log-manager-disruptor.remaining-capacity, value=16383] ## '' 
[hostname=jraft-02-74d9bddb68-c4hfv][appname=jraft][][][2024-06-05T17:08:20.634+0800][metrics-logger-reporter-1-thread-1][INFO][Slf4jReporter.java,473,log] [type=GAUGE, name=jraft-node-impl-disruptor.buffer-size, value=16384] ## '' 
[hostname=jraft-02-74d9bddb68-c4hfv][appname=jraft][][][2024-06-05T17:08:20.634+0800][metrics-logger-reporter-1-thread-1][INFO][Slf4jReporter.java,473,log] [type=GAUGE, name=jraft-node-impl-disruptor.remaining-capacity, value=16384] ## '' 
[hostname=jraft-02-74d9bddb68-c4hfv][appname=jraft][][][2024-06-05T17:08:20.634+0800][metrics-logger-reporter-1-thread-1][INFO][Slf4jReporter.java,473,log] [type=GAUGE, name=jraft-read-only-service-disruptor.buffer-size, value=16384] ## '' 
[hostname=jraft-02-74d9bddb68-c4hfv][appname=jraft][][][2024-06-05T17:08:20.634+0800][metrics-logger-reporter-1-thread-1][INFO][Slf4jReporter.java,473,log] [type=GAUGE, name=jraft-read-only-service-disruptor.remaining-capacity, value=16384] ## '' 
[hostname=jraft-02-74d9bddb68-c4hfv][appname=jraft][][][2024-06-05T17:08:20.634+0800][metrics-logger-reporter-1-thread-1][INFO][Slf4jReporter.java,473,log] [type=GAUGE, name=raft-rpc-client-thread-pool.active, value=0] ## '' 
[hostname=jraft-02-74d9bddb68-c4hfv][appname=jraft][][][2024-06-05T17:08:20.634+0800][metrics-logger-reporter-1-thread-1][INFO][Slf4jReporter.java,473,log] [type=GAUGE, name=raft-rpc-client-thread-pool.completed, value=18] ## '' 
[hostname=jraft-02-74d9bddb68-c4hfv][appname=jraft][][][2024-06-05T17:08:20.634+0800][metrics-logger-reporter-1-thread-1][INFO][Slf4jReporter.java,473,log] [type=GAUGE, name=raft-rpc-client-thread-pool.pool-size, value=18] ## '' 
[hostname=jraft-02-74d9bddb68-c4hfv][appname=jraft][][][2024-06-05T17:08:20.634+0800][metrics-logger-reporter-1-thread-1][INFO][Slf4jReporter.java,473,log] [type=GAUGE, name=raft-rpc-client-thread-pool.queued, value=0] ## '' 
[hostname=jraft-02-74d9bddb68-c4hfv][appname=jraft][][][2024-06-05T17:08:20.634+0800][metrics-logger-reporter-1-thread-1][INFO][Slf4jReporter.java,473,log] [type=GAUGE, name=replicator-jraft/jraft-01:9090.append-entries-times, value=415359] ## '' 
[hostname=jraft-02-74d9bddb68-c4hfv][appname=jraft][][][2024-06-05T17:08:20.634+0800][metrics-logger-reporter-1-thread-1][INFO][Slf4jReporter.java,473,log] [type=GAUGE, name=replicator-jraft/jraft-01:9090.block-times, value=27] ## '' 
[hostname=jraft-02-74d9bddb68-c4hfv][appname=jraft][][][2024-06-05T17:08:20.634+0800][metrics-logger-reporter-1-thread-1][INFO][Slf4jReporter.java,473,log] [type=GAUGE, name=replicator-jraft/jraft-01:9090.consecutive-error-times, value=0] ## '' 
[hostname=jraft-02-74d9bddb68-c4hfv][appname=jraft][][][2024-06-05T17:08:20.634+0800][metrics-logger-reporter-1-thread-1][INFO][Slf4jReporter.java,473,log] [type=GAUGE, name=replicator-jraft/jraft-01:9090.heartbeat-times, value=9850] ## '' 
[hostname=jraft-02-74d9bddb68-c4hfv][appname=jraft][][][2024-06-05T17:08:20.634+0800][metrics-logger-reporter-1-thread-1][INFO][Slf4jReporter.java,473,log] [type=GAUGE, name=replicator-jraft/jraft-01:9090.install-snapshot-times, value=0] ## '' 
[hostname=jraft-02-74d9bddb68-c4hfv][appname=jraft][][][2024-06-05T17:08:20.634+0800][metrics-logger-reporter-1-thread-1][INFO][Slf4jReporter.java,473,log] [type=GAUGE, name=replicator-jraft/jraft-01:9090.locked, value=0] ## '' 
[hostname=jraft-02-74d9bddb68-c4hfv][appname=jraft][][][2024-06-05T17:08:20.635+0800][metrics-logger-reporter-1-thread-1][INFO][Slf4jReporter.java,473,log] [type=GAUGE, name=replicator-jraft/jraft-01:9090.log-lags, value=1] ## '' 
[hostname=jraft-02-74d9bddb68-c4hfv][appname=jraft][][][2024-06-05T17:08:20.635+0800][metrics-logger-reporter-1-thread-1][INFO][Slf4jReporter.java,473,log] [type=GAUGE, name=replicator-jraft/jraft-01:9090.next-index, value=9343997] ## '' 
[hostname=jraft-02-74d9bddb68-c4hfv][appname=jraft][][][2024-06-05T17:08:20.635+0800][metrics-logger-reporter-1-thread-1][INFO][Slf4jReporter.java,473,log] [type=GAUGE, name=replicator-jraft/jraft-01:9090.probe-times, value=5952] ## '' 
[hostname=jraft-02-74d9bddb68-c4hfv][appname=jraft][][][2024-06-05T17:08:20.635+0800][metrics-logger-reporter-1-thread-1][INFO][Slf4jReporter.java,473,log] [type=GAUGE, name=replicator-jraft/jraft-01:9090.running-state, value=0] ## '' 
[hostname=jraft-02-74d9bddb68-c4hfv][appname=jraft][][][2024-06-05T17:08:20.635+0800][metrics-logger-reporter-1-thread-1][INFO][Slf4jReporter.java,473,log] [type=GAUGE, name=replicator-jraft/jraft-01:9090.state, value=3] ## '' 
[hostname=jraft-02-74d9bddb68-c4hfv][appname=jraft][][][2024-06-05T17:08:20.635+0800][metrics-logger-reporter-1-thread-1][INFO][Slf4jReporter.java,473,log] [type=GAUGE, name=replicator-jraft/jraft-03:9090.append-entries-times, value=414436] ## '' 
[hostname=jraft-02-74d9bddb68-c4hfv][appname=jraft][][][2024-06-05T17:08:20.635+0800][metrics-logger-reporter-1-thread-1][INFO][Slf4jReporter.java,473,log] [type=GAUGE, name=replicator-jraft/jraft-03:9090.block-times, value=0] ## '' 
[hostname=jraft-02-74d9bddb68-c4hfv][appname=jraft][][][2024-06-05T17:08:20.635+0800][metrics-logger-reporter-1-thread-1][INFO][Slf4jReporter.java,473,log] [type=GAUGE, name=replicator-jraft/jraft-03:9090.consecutive-error-times, value=0] ## '' 
[hostname=jraft-02-74d9bddb68-c4hfv][appname=jraft][][][2024-06-05T17:08:20.635+0800][metrics-logger-reporter-1-thread-1][INFO][Slf4jReporter.java,473,log] [type=GAUGE, name=replicator-jraft/jraft-03:9090.heartbeat-times, value=10106] ## '' 
[hostname=jraft-02-74d9bddb68-c4hfv][appname=jraft][][][2024-06-05T17:08:20.635+0800][metrics-logger-reporter-1-thread-1][INFO][Slf4jReporter.java,473,log] [type=GAUGE, name=replicator-jraft/jraft-03:9090.install-snapshot-times, value=0] ## '' 
[hostname=jraft-02-74d9bddb68-c4hfv][appname=jraft][][][2024-06-05T17:08:20.636+0800][metrics-logger-reporter-1-thread-1][INFO][Slf4jReporter.java,473,log] [type=GAUGE, name=replicator-jraft/jraft-03:9090.locked, value=0] ## '' 
[hostname=jraft-02-74d9bddb68-c4hfv][appname=jraft][][][2024-06-05T17:08:20.636+0800][metrics-logger-reporter-1-thread-1][INFO][Slf4jReporter.java,473,log] [type=GAUGE, name=replicator-jraft/jraft-03:9090.log-lags, value=1] ## '' 
[hostname=jraft-02-74d9bddb68-c4hfv][appname=jraft][][][2024-06-05T17:08:20.636+0800][metrics-logger-reporter-1-thread-1][INFO][Slf4jReporter.java,473,log] [type=GAUGE, name=replicator-jraft/jraft-03:9090.next-index, value=9343997] ## '' 
[hostname=jraft-02-74d9bddb68-c4hfv][appname=jraft][][][2024-06-05T17:08:20.636+0800][metrics-logger-reporter-1-thread-1][INFO][Slf4jReporter.java,473,log] [type=GAUGE, name=replicator-jraft/jraft-03:9090.probe-times, value=5822] ## '' 
[hostname=jraft-02-74d9bddb68-c4hfv][appname=jraft][][][2024-06-05T17:08:20.636+0800][metrics-logger-reporter-1-thread-1][INFO][Slf4jReporter.java,473,log] [type=GAUGE, name=replicator-jraft/jraft-03:9090.running-state, value=0] ## '' 
[hostname=jraft-02-74d9bddb68-c4hfv][appname=jraft][][][2024-06-05T17:08:20.636+0800][metrics-logger-reporter-1-thread-1][INFO][Slf4jReporter.java,473,log] [type=GAUGE, name=replicator-jraft/jraft-03:9090.state, value=3] ## '' 
[hostname=jraft-02-74d9bddb68-c4hfv][appname=jraft][][][2024-06-05T17:08:20.636+0800][metrics-logger-reporter-1-thread-1][INFO][Slf4jReporter.java,473,log] [type=HISTOGRAM, name=append-logs-bytes, count=97662, min=52, max=24728, mean=2221.598267403763, stddev=2458.5580568673154, p50=1279.0, p75=3101.0, p95=7288.0, p98=8938.0, p99=10685.0, p999=24728.0] ## '' 
[hostname=jraft-02-74d9bddb68-c4hfv][appname=jraft][][][2024-06-05T17:08:20.637+0800][metrics-logger-reporter-1-thread-1][INFO][Slf4jReporter.java,473,log] [type=HISTOGRAM, name=append-logs-count, count=97662, min=1, max=95, mean=6.739355958656585, stddev=9.630308550330655, p50=4.0, p75=8.0, p95=17.0, p98=30.0, p99=55.0, p999=95.0] ## '' 
[hostname=jraft-02-74d9bddb68-c4hfv][appname=jraft][][][2024-06-05T17:08:20.637+0800][metrics-logger-reporter-1-thread-1][INFO][Slf4jReporter.java,473,log] [type=HISTOGRAM, name=fsm-apply-tasks-count, count=20502, min=1, max=93, mean=29.660510649769922, stddev=19.371570213334397, p50=31.0, p75=43.0, p95=62.0, p98=71.0, p99=76.0, p999=87.0] ## '' 
[hostname=jraft-02-74d9bddb68-c4hfv][appname=jraft][][][2024-06-05T17:08:20.638+0800][metrics-logger-reporter-1-thread-1][INFO][Slf4jReporter.java,473,log] [type=HISTOGRAM, name=replicate-entries-bytes, count=709190, min=52, max=15115, mean=579.4934353145965, stddev=911.6855512819872, p50=236.0, p75=911.0, p95=1822.0, p98=2486.0, p99=3578.0, p999=15115.0] ## '' 
[hostname=jraft-02-74d9bddb68-c4hfv][appname=jraft][][][2024-06-05T17:08:20.638+0800][metrics-logger-reporter-1-thread-1][INFO][Slf4jReporter.java,473,log] [type=HISTOGRAM, name=replicate-entries-count, count=709190, min=1, max=204, mean=1.7996319699182945, stddev=5.25519816349254, p50=1.0, p75=2.0, p95=4.0, p98=6.0, p99=14.0, p999=41.0] ## '' 
[hostname=jraft-02-74d9bddb68-c4hfv][appname=jraft][][][2024-06-05T17:08:20.639+0800][metrics-logger-reporter-1-thread-1][INFO][Slf4jReporter.java,473,log] [type=HISTOGRAM, name=replicator-jraft/jraft-01:9090.replicate-inflights-count, count=421311, min=1, max=225, mean=9.098304828817968, stddev=11.916786926057629, p50=7.0, p75=11.0, p95=18.0, p98=26.0, p99=68.0, p999=133.0] ## '' 
[hostname=jraft-02-74d9bddb68-c4hfv][appname=jraft][][][2024-06-05T17:08:20.639+0800][metrics-logger-reporter-1-thread-1][INFO][Slf4jReporter.java,473,log] [type=HISTOGRAM, name=replicator-jraft/jraft-03:9090.replicate-inflights-count, count=420258, min=1, max=231, mean=10.72205243331258, stddev=14.749281845768005, p50=8.0, p75=12.0, p95=22.0, p98=54.0, p99=86.0, p999=174.0] ## '' 
[hostname=jraft-02-74d9bddb68-c4hfv][appname=jraft][][][2024-06-05T17:08:20.640+0800][metrics-logger-reporter-1-thread-1][INFO][Slf4jReporter.java,473,log] [type=TIMER, name=append-logs, count=97662, min=1.0, max=141.0, mean=3.7942122646459446, stddev=9.772673431291325, p50=3.0, p75=3.0, p95=4.0, p98=7.0, p99=11.0, p999=141.0, m1_rate=215.50654072331147, m5_rate=106.38331201552123, m15_rate=67.29236456577213, mean_rate=95.22333473811265, rate_unit=events/second, duration_unit=milliseconds] ## '' 
[hostname=jraft-02-74d9bddb68-c4hfv][appname=jraft][][][2024-06-05T17:08:20.640+0800][metrics-logger-reporter-1-thread-1][INFO][Slf4jReporter.java,473,log] [type=TIMER, name=fsm-apply-tasks, count=20502, min=0.0, max=177.0, mean=18.90173680473389, stddev=21.02952623844567, p50=16.0, p75=24.0, p95=58.0, p98=83.0, p99=118.0, p999=177.0, m1_rate=49.59336494876102, m5_rate=24.888325729129594, m15_rate=14.743414241538295, mean_rate=20.85873926782069, rate_unit=events/second, duration_unit=milliseconds] ## '' 
[hostname=jraft-02-74d9bddb68-c4hfv][appname=jraft][][][2024-06-05T17:08:20.640+0800][metrics-logger-reporter-1-thread-1][INFO][Slf4jReporter.java,473,log] [type=TIMER, name=fsm-commit, count=20502, min=0.0, max=149.0, mean=18.17615050923885, stddev=18.34313732626914, p50=16.0, p75=25.0, p95=41.0, p98=72.0, p99=97.0, p999=149.0, m1_rate=49.59336494876102, m5_rate=24.888325729129594, m15_rate=14.743414241538295, mean_rate=20.858733529202528, rate_unit=events/second, duration_unit=milliseconds] ## '' 
[hostname=jraft-02-74d9bddb68-c4hfv][appname=jraft][][][2024-06-05T17:08:20.640+0800][metrics-logger-reporter-1-thread-1][INFO][Slf4jReporter.java,473,log] [type=TIMER, name=fsm-snapshot-load, count=1, min=2531.0, max=2531.0, mean=2531.0, stddev=0.0, p50=2531.0, p75=2531.0, p95=2531.0, p98=2531.0, p99=2531.0, p999=2531.0, m1_rate=5.4584303014450984E-9, m5_rate=0.006140978124982921, m15_rate=0.06262761126843666, mean_rate=9.517822679677518E-4, rate_unit=events/second, duration_unit=milliseconds] ## '' 
[hostname=jraft-02-74d9bddb68-c4hfv][appname=jraft][][][2024-06-05T17:08:20.641+0800][metrics-logger-reporter-1-thread-1][INFO][Slf4jReporter.java,473,log] [type=TIMER, name=fsm-snapshot-save, count=3, min=38.0, max=438.0, mean=38.65302370364745, stddev=7.234033967432937, p50=38.0, p75=38.0, p95=38.0, p98=38.0, p99=93.0, p999=93.0, m1_rate=2.2977874186484991E-4, m5_rate=0.013695984169369499, m15_rate=0.07921180633541745, mean_rate=0.0035077970912932676, rate_unit=events/second, duration_unit=milliseconds] ## '' 
[hostname=jraft-02-74d9bddb68-c4hfv][appname=jraft][][][2024-06-05T17:08:20.641+0800][metrics-logger-reporter-1-thread-1][INFO][Slf4jReporter.java,473,log] [type=TIMER, name=fsm-start-following, count=1, min=0.0, max=0.0, mean=0.0, stddev=0.0, p50=0.0, p75=0.0, p95=0.0, p98=0.0, p99=0.0, p999=0.0, m1_rate=7.008763242274035E-9, m5_rate=0.006455832806271975, m15_rate=0.06368015159471634, mean_rate=9.638486443833783E-4, rate_unit=events/second, duration_unit=milliseconds] ## '' 
[hostname=jraft-02-74d9bddb68-c4hfv][appname=jraft][][][2024-06-05T17:08:20.641+0800][metrics-logger-reporter-1-thread-1][INFO][Slf4jReporter.java,473,log] [type=TIMER, name=fsm-stop-following, count=1, min=0.0, max=0.0, mean=0.0, stddev=0.0, p50=0.0, p75=0.0, p95=0.0, p98=0.0, p99=0.0, p999=0.0, m1_rate=1.7528496438887437E-8, m5_rate=0.007754841566344407, m15_rate=0.06769308502134817, mean_rate=0.001017399667634769, rate_unit=events/second, duration_unit=milliseconds] ## '' 
[hostname=jraft-02-74d9bddb68-c4hfv][appname=jraft][][][2024-06-05T17:08:20.642+0800][metrics-logger-reporter-1-thread-1][INFO][Slf4jReporter.java,473,log] [type=TIMER, name=handle-heartbeat-requests, count=116, min=0.0, max=4.0, mean=0.1279687964964816, stddev=0.4546421604539739, p50=0.0, p75=0.0, p95=1.0, p98=1.0, p99=1.0, p999=4.0, m1_rate=3.85191205531326E-7, m5_rate=0.3236380534824856, m15_rate=3.1441321349547344, mean_rate=0.11180651681526926, rate_unit=events/second, duration_unit=milliseconds] ## '' 
[hostname=jraft-02-74d9bddb68-c4hfv][appname=jraft][][][2024-06-05T17:08:20.642+0800][metrics-logger-reporter-1-thread-1][INFO][Slf4jReporter.java,473,log] [type=TIMER, name=pre-vote, count=16, min=2.0, max=26.0, mean=5.926510506888008, stddev=6.17105735042818, p50=3.0, p75=6.0, p95=26.0, p98=26.0, p99=26.0, p999=26.0, m1_rate=4.084218733428912E-8, m5_rate=0.03851805840173319, m15_rate=0.3813714050245136, mean_rate=0.015259872629458247, rate_unit=events/second, duration_unit=milliseconds] ## '' 
[hostname=jraft-02-74d9bddb68-c4hfv][appname=jraft][][][2024-06-05T17:08:20.643+0800][metrics-logger-reporter-1-thread-1][INFO][Slf4jReporter.java,473,log] [type=TIMER, name=replicate-entries, count=709190, min=2.0, max=114.0, mean=6.422132247261436, stddev=7.935356450896956, p50=5.0, p75=6.0, p95=9.0, p98=21.0, p99=43.0, p999=101.0, m1_rate=1568.1643502877023, m5_rate=763.1205506996324, m15_rate=482.1548879298965, mean_rate=691.489259490716, rate_unit=events/second, duration_unit=milliseconds] ## '' 
[hostname=jraft-02-74d9bddb68-c4hfv][appname=jraft][][][2024-06-05T17:08:20.645+0800][metrics-logger-reporter-1-thread-1][INFO][Slf4jReporter.java,473,log] [type=TIMER, name=request-vote, count=2, min=4.0, max=22.0, mean=13.0, stddev=9.0, p50=22.0, p75=22.0, p95=22.0, p98=22.0, p99=22.0, p999=22.0, m1_rate=1.6559750875140836E-8, m5_rate=0.01334930798413044, m15_rate=0.12878330861506987, mean_rate=0.001949899087058909, rate_unit=events/second, duration_unit=milliseconds] ## '' 
[hostname=jraft-02-74d9bddb68-c4hfv][appname=jraft][][][2024-06-05T17:08:20.646+0800][metrics-logger-reporter-1-thread-1][INFO][Slf4jReporter.java,473,log] [type=TIMER, name=save-raft-meta, count=1, min=11.0, max=11.0, mean=11.0, stddev=0.0, p50=11.0, p75=11.0, p95=11.0, p98=11.0, p99=11.0, p999=11.0, m1_rate=8.279875437570418E-9, m5_rate=0.00667465399206522, m15_rate=0.06439165430753493, mean_rate=9.749566611807717E-4, rate_unit=events/second, duration_unit=milliseconds] ## '' 
[hostname=jraft-02-74d9bddb68-c4hfv][appname=jraft][][][2024-06-05T17:08:20.646+0800][metrics-logger-reporter-1-thread-1][INFO][Slf4jReporter.java,473,log] [type=TIMER, name=truncate-log-prefix, count=3, min=3.0, max=3.0, mean=2.9999999999999996, stddev=4.656612873077392E-16, p50=3.0, p75=3.0, p95=3.0, p98=3.0, p99=3.0, p999=3.0, m1_rate=2.498926180984849E-4, m5_rate=0.013935045818009037, m15_rate=0.07965644689915864, mean_rate=0.0035101174195726016, rate_unit=events/second, duration_unit=milliseconds] ## '' 

相应的jraft 监控参数如上

**Comment by danhuiwang** [comment]
能帮忙看看nodeoption 里哪个参数需要调，目前都是默认参数，磁盘io 600，最大能支持6000

**Comment by killme2008** [comment]
几个关键指标，写日志存储：
```
[type=TIMER, name=append-logs, count=97662, min=1.0, max=141.0, mean=3.7942122646459446, stddev=9.772673431291325, p50=3.0, p75=3.0, p95=4.0, p98=7.0, p99=11.0, p999=141.0, m1_rate=215.50654072331147, m5_rate=106.38331201552123, m15_rate=67.29236456577213, mean_rate=95.22333473811265, rate_unit=events/second, duration_unit=milliseconds]
```

均值 3.7 ms ，还好。

Apply 状态机：
```
[type=TIMER, name=fsm-apply-tasks, count=20502, min=0.0, max=177.0, mean=18.90173680473389, stddev=21.02952623844567, p50=16.0, p75=24.0, p95=58.0, p98=83.0, p99=118.0, p999=177.0, m1_rate=49.59336494876102, m5_rate=24.888325729129594, m15_rate=14.743414241538295, mean_rate=20.85873926782069, rate_unit=events/second, duration_unit=milliseconds]
```

均值 18.9 ms，也还 ok

复制日志到 follower
```
type=TIMER, name=replicate-entries, count=709190, min=2.0, max=114.0, mean=6.422132247261436, stddev=7.935356450896956, p50=5.0, p75=6.0, p95=9.0, p98=21.0, p99=43.0, p999=101.0, m1_rate=1568.1643502877023, m5_rate=763.1205506996324, m15_rate=482.1548879298965, mean_rate=691.489259490716, rate_unit=events/second, duration_unit=milliseconds] 
```
均值是 6.4s ms，所以也正常。

总结， jraft 应该不是你压测的瓶颈，看看你在 jraft 调用之前的代码吧，问题可能在那。
