### ISSUE TITLE
请教一个changePeers的问题

### ISSUE THREAD

**Issue by ye-xiaowei** [sofastack/sofa-jraft#1117]
### Your question

假设一开始的节点是 123，leader 是 1. 然后 changePeers 是 345.

1. 45 catchup
2. 12、45 apply C new & C old
3. 12、45 apply C new
4. client 收到 changePeers 成功
5. 12 宕机
6. 4 become leader

那这个时候 3 节点并不知道 C new 是不是就加不回去了。

**Comment by killme2008** [comment]
4 become leader 后会去探测 follower 的 log 状况，然后发起 append entries 来补上或者更正。

**Comment by ye-xiaowei** [comment]
@killme2008 当我把一个节点配置成 [127.0.0.1:8080] 另外一个节点配置成 [127.0.0.1:8080, 127.0.0.1:8081] 的时候，在控制台看见
`ignore PreVoteRequest from 127.0.0.1:8081 as it is not in conf <ConfigurationEntry` 然后想着是不是在changePeers的时候也会出现这个问题
