### ISSUE TITLE
Followers failed to append committed log entries

### ISSUE THREAD

**Issue by lizhanhui** [sofastack/sofa-jraft#1128]
### Describe the bug

Followers failed to append committed log entries
> 2024-07-15 17:06:42:679 WARN [NodeImpl] Node <RAFT_GROUP_3/xxx.svc.cluster.local:8080> reject term_unmatched AppendEntriesRequest from xxx.svc.cluster.local:8080, term=29, prevLogIndex=892599, prevLogTerm=29, localPrevLogTerm=0, lastLogIndex=892586, entriesSize=1.

### Expected behavior
localPrevLogTerm == prevLogTerm

### Actual behavior
localPrevLogTerm is always 0

### Steps to reproduce
[RocketMQ MQTT Meta](https://github.com/apache/rocketmq-mqtt/tree/main/mqtt-meta) module is built on top of JRaft. Benchmark insertion with a 3-node raft group.

### Environment

- SOFAJRaft version: 1.3.14
- JVM version (e.g. `java -version`): 8
- OS version (e.g. `uname -a`): EL8
- Maven version:
- IDE version:

**Comment by killme2008** [comment]
缺少足够信息，无从判断。
