### ISSUE TITLE
Release blocker of v1.3.15

### ISSUE THREAD

**Issue by shihuili1218** [sofastack/sofa-jraft#1137]
- [x] https://github.com/sofastack/sofa-jraft/pull/1136
- [x] https://github.com/sofastack/sofa-jraft/pull/1135
- [x] https://github.com/sofastack/sofa-jraft/pull/1084

**Comment by en-hui** [comment]
啥时候发啊？等日期呢？

**Comment by shihuili1218** [comment]
很快，我把测试跑完就发

**Comment by shihuili1218** [comment]
atomic.bridge

**Comment by shihuili1218** [comment]
configuration-test: remove and add a random node

2024-08-10 07:37:04,369{GMT}	INFO	[main] jepsen.core: {:perf
 {:latency-graph {:valid? true},
  :rate-graph {:valid? true},
  :valid? true},
 :linear
 {:valid? true,
  :configs
  ({:model {:value 3},
    :last-op
    {:process 3,
     :type :ok,
     :f :read,
     :value 3,
     :index 5903,
     :time 143851352035},
    :pending
    [{:process 1,
      :type :invoke,
      :f :write,
      :value 3,
      :index 5116,
      :time 105221470443}]}
   {:model {:value 3},
    :last-op
    {:process 3,
     :type :ok,
     :f :read,
     :value 3,
     :index 5903,
     :time 143851352035},
    :pending []}),
  :final-paths ()},
 :timeline {:valid? true},
 :valid? true}


Everything looks good! ヽ(‘ー`)ノ

**Comment by shihuili1218** [comment]
crash-test: killing random nodes and restarting them

2024-08-10 07:27:44,988{GMT}	INFO	[main] jepsen.core: {:perf
 {:latency-graph {:valid? true},
  :rate-graph {:valid? true},
  :valid? true},
 :linear
 {:valid? true, :model {:value 3}, :final-paths (), :configs ()},
 :timeline {:valid? true},
 :valid? true}


Everything looks good! ヽ(‘ー`)ノ

**Comment by shihuili1218** [comment]
partition-test: Cuts the network into randomly chosen halves

2024-08-10 07:24:27,635{GMT}	INFO	[main] jepsen.core: {:perf
 {:latency-graph {:valid? true},
  :rate-graph {:valid? true},
  :valid? true},
 :indep
 {:valid? true,
  :results
  {0
   {:timeline {:valid? true},
    :linear
    {:valid? true, :model {:value 2}, :final-paths (), :configs ()},
    :valid? true},
   7
   {:timeline {:valid? true},
    :linear
    {:valid? true, :model {:value 4}, :final-paths (), :configs ()},
    :valid? true},
   20
   {:timeline {:valid? true},
    :linear
    {:valid? true,
     :configs
     ({:model {:value 2},
       :last-op
       {:process 3,
        :type :ok,
        :f :write,
        :value 2,
        :index 4217,
        :time 46307542457},
       :pending []}),
     :final-paths ()},
    :valid? true},
   27
   {:timeline {:valid? true},
    :linear
    {:valid? true,
     :configs
     ({:model {:value 1},
       :last-op
       {:process 2,
        :type :ok,
        :f :write,
        :value 1,
        :index 5539,
        :time 60329830961},
       :pending []}),
     :final-paths ()},
    :valid? true},
   1
   {:timeline {:valid? true},
    :linear
    {:valid? true,
     :configs
     ({:model {:value 1},
       :last-op
       {:process 1,
        :type :ok,
        :f :write,
        :value 1,
        :index 408,
        :time 5344837874},
       :pending []}),
     :final-paths ()},
    :valid? true},
   24
   {:timeline {:valid? true},
    :linear
    {:valid? true,
     :configs
     ({:model {:value 3},
       :last-op
       {:process 0,
        :type :ok,
        :f :cas,
        :value [4 3],
        :index 5021,
        :time 54917071007},
       :pending []}),
     :final-paths ()},
    :valid? true},
   4
   {:timeline {:valid? true},
    :linear
    {:valid? true,
     :configs
     ({:model {:value 1},
       :last-op
       {:process 4,
        :type :ok,
        :f :read,
        :value 1,
        :index 1005,
        :time 12625479701},
       :pending []}),
     :final-paths ()},
    :valid? true},
   15
   {:timeline {:valid? true},
    :linear
    {:valid? true,
     :configs
     ({:model {:value 1},
       :last-op
       {:process 0,
        :type :ok,
        :f :read,
        :value 1,
        :index 3213,
        :time 35742882756},
       :pending []}),
     :final-paths ()},
    :valid? true},
   21
   {:timeline {:valid? true},
    :linear
    {:valid? true,
     :configs
     ({:model {:value 3},
       :last-op
       {:process 3,
        :type :ok,
        :f :read,
        :value 3,
        :index 4417,
        :time 48482966884},
       :pending []}),
     :final-paths ()},
    :valid? true},
   13
   {:timeline {:valid? true},
    :linear
    {:valid? true,
     :configs
     ({:model {:value 2},
       :last-op
       {:process 0,
        :type :ok,
        :f :write,
        :value 2,
        :index 2817,
        :time 31631154826},
       :pending []}),
     :final-paths ()},
    :valid? true},
   22
   {:timeline {:valid? true},
    :linear
    {:valid? true,
     :configs
     ({:model {:value 1},
       :last-op
       {:process 2,
        :type :ok,
        :f :cas,
        :value [2 1],
        :index 4622,
        :time 50503977545},
       :pending []}),
     :final-paths ()},
    :valid? true},
   6
   {:timeline {:valid? true},
    :linear
    {:valid? true,
     :configs
     ({:model {:value 1},
       :last-op
       {:process 3,
        :type :ok,
        :f :read,
        :value 1,
        :index 1409,
        :time 16968302706},
       :pending []}),
     :final-paths ()},
    :valid? true},
   25
   {:timeline {:valid? true},
    :linear
    {:valid? true, :model {:value 0}, :final-paths (), :configs ()},
    :valid? true},
   17
   {:timeline {:valid? true},
    :linear
    {:valid? true,
     :configs
     ({:model {:value 1},
       :last-op
       {:process 3,
        :type :ok,
        :f :read,
        :value 1,
        :index 3615,
        :time 40099576899},
       :pending []}),
     :final-paths ()},
    :valid? true},
   3
   {:timeline {:valid? true},
    :linear
    {:valid? true,
     :configs
     ({:model {:value 4},
       :last-op
       {:process 2,
        :type :ok,
        :f :read,
        :value 4,
        :index 799,
        :time 10418691824},
       :pending []}),
     :final-paths ()},
    :valid? true},
   12
   {:timeline {:valid? true},
    :linear
    {:valid? true,
     :configs
     ({:model {:value 4},
       :last-op
       {:process 4,
        :type :ok,
        :f :cas,
        :value [1 4],
        :index 2609,
        :time 29439537330},
       :pending []}),
     :final-paths ()},
    :valid? true},
   2
   {:timeline {:valid? true},
    :linear
    {:valid? true,
     :configs
     ({:model {:value 1},
       :last-op
       {:process 0,
        :type :ok,
        :f :read,
        :value 1,
        :index 601,
        :time 8416011664},
       :pending
       [{:process 1,
         :type :invoke,
         :f :write,
         :value 2,
         :index 427,
         :time 5616886169}]}
      {:model {:value 1},
       :last-op
       {:process 0,
        :type :ok,
        :f :read,
        :value 1,
        :index 601,
        :time 8416011664},
       :pending []}),
     :final-paths ()},
    :valid? true},
   23
   {:timeline {:valid? true},
    :linear
    {:valid? true, :model {:value 1}, :final-paths (), :configs ()},
    :valid? true},
   19
   {:timeline {:valid? true},
    :linear
    {:valid? true, :model {:value 3}, :final-paths (), :configs ()},
    :valid? true},
   11
   {:timeline {:valid? true},
    :linear
    {:valid? true, :model {:value 4}, :final-paths (), :configs ()},
    :valid? true},
   9
   {:timeline {:valid? true},
    :linear
    {:valid? true,
     :configs
     ({:model {:value 4},
       :last-op
       {:process 3,
        :type :ok,
        :f :read,
        :value 4,
        :index 2011,
        :time 23186745243},
       :pending []}),
     :final-paths ()},
    :valid? true},
   5
   {:timeline {:valid? true},
    :linear
    {:valid? true,
     :configs
     ({:model {:value 3},
       :last-op
       {:process 4,
        :type :ok,
        :f :write,
        :value 3,
        :index 1209,
        :time 14822489248},
       :pending []}),
     :final-paths ()},
    :valid? true},
   14
   {:timeline {:valid? true},
    :linear
    {:valid? true,
     :configs
     ({:model {:value 1},
       :last-op
       {:process 4,
        :type :ok,
        :f :write,
        :value 1,
        :index 3015,
        :time 33621832717},
       :pending []}),
     :final-paths ()},
    :valid? true},
   26
   {:timeline {:valid? true},
    :linear
    {:valid? true,
     :configs
     ({:model {:value 1},
       :last-op
       {:process 6,
        :type :ok,
        :f :read,
        :value 1,
        :index 5427,
        :time 59063300716},
       :pending []}),
     :final-paths ()},
    :valid? true},
   16
   {:timeline {:valid? true},
    :linear
    {:valid? true,
     :configs
     ({:model {:value 4},
       :last-op
       {:process 0,
        :type :ok,
        :f :write,
        :value 4,
        :index 3416,
        :time 37816745135},
       :pending []}),
     :final-paths ()},
    :valid? true},
   10
   {:timeline {:valid? true},
    :linear
    {:valid? true, :model {:value 4}, :final-paths (), :configs ()},
    :valid? true},
   18
   {:timeline {:valid? true},
    :linear
    {:valid? true,
     :configs
     ({:model {:value 2},
       :last-op
       {:process 6,
        :type :ok,
        :f :write,
        :value 2,
        :index 3819,
        :time 42176296339},
       :pending []}),
     :final-paths ()},
    :valid? true},
   8
   {:timeline {:valid? true},
    :linear
    {:valid? true,
     :configs
     ({:model {:value 2},
       :last-op
       {:process 3,
        :type :ok,
        :f :read,
        :value 2,
        :index 1808,
        :time 20999323996},
       :pending []}),
     :final-paths ()},
    :valid? true}},
  :failures []},
 :valid? true}


Everything looks good! ヽ(‘ー`)ノ

**Comment by shihuili1218** [comment]
partition-majority-test: Cuts the network into randomly majority groups

2024-08-10 07:22:02,221{GMT}	INFO	[main] jepsen.core: {:perf
 {:latency-graph {:valid? true},
  :rate-graph {:valid? true},
  :valid? true},
 :linear
 {:valid? true,
  :configs
  ({:model {:value 4},
    :last-op
    {:process 2,
     :type :ok,
     :f :read,
     :value 4,
     :index 5623,
     :time 144662206966},
    :pending []}),
  :final-paths ()},
 :timeline {:valid? true},
 :valid? true}


Everything looks good! ヽ(‘ー`)ノ

**Comment by shihuili1218** [comment]
pause-test: pausing random node with SIGSTOP/SIGCONT


2024-08-10 07:30:48,519{GMT}	INFO	[main] jepsen.core: {:perf
 {:latency-graph {:valid? true},
  :rate-graph {:valid? true},
  :valid? true},
 :linear
 {:valid? true,
  :configs
  ({:model {:value 4},
    :last-op
    {:process 3,
     :type :ok,
     :f :read,
     :value 4,
     :index 5937,
     :time 143361283164},
    :pending []}),
  :final-paths ()},
 :timeline {:valid? true},
 :valid? true}


Everything looks good! ヽ(‘ー`)ノ

**Comment by fengjiachun** [comment]
Thank you  @shihuili1218
