### ISSUE TITLE
无法和springboot3.X 系列兼容

### ISSUE THREAD

**Issue by double-7** [sofastack/sofa-jraft#1150]
包名：jraft-rheakv-core
版本：1.3.15.bugfix
现象：
1. jraft-rheakv-core 该版本使用log4j2中的log4j-slf4j-impl/src/main/java/org/apache/logging/slf4j/Log4jLogger.java类进行创建时在log4j2-2.19.0版本时API发生变更，故无法使用大于等于log4j2-2.19.0版本
2. springboot 3.X 系列在使用log4j2 时使用的API 最低log4j2-2.19.0版本
问题：
请问什么时候可以更新log4j2 依赖包

**Comment by fengjiachun** [comment]
rheakv 不依赖 log4j 这种具体实现，是说 sl4j 吧？我们考虑升级下 sl4j ？ @shihuili1218

**Comment by double-7** [comment]
> rheakv 不依赖 log4j 这种具体实现，是说 sl4j 吧？我们考虑升级下 sl4j ？ @shihuili1218

我上面说的更正一下，jraft-rheakv-core 依赖 sofa-bolt1.67 依赖 sofa-common-tools1.0.12 ，而sofa-common-tools1.0.12 有log4j2 的具体API调用和springboot 3 依赖版本产生了冲突。我试了下最新版本sofa-common-tools2.1.1 是可以的。所以应该是更新sofa-bolt不然回和springboot3 + log4j2产生冲突

**Comment by fengjiachun** [comment]
sofa-bolt 在你的项目里直接依赖并覆盖掉 jraft 的即可

**Comment by fengjiachun** [comment]
没其他问题关闭了
