### ISSUE TITLE
一段时间没有产生entry，所有segment文件删除后，无法获取上一个entry的term

### ISSUE THREAD

**Issue by bruden** [sofastack/sofa-jraft#1156]
### Describe the bug

一段时间没有产生entry，所有segment文件删除后，发送下一个entry时需要获取上一个entry的term，报错

```
2024-10-08 18:00:01.473 WARN  SegmentFile - Try to read data from segment file /mnt/log/LogitStorage/LogSegment/0000000000000000001.s out of comitted position, logIndex=50002, readPos=26, wrotePos=269880, flushPos=0.
```

应该将以下三个地方的`firstIndexKept`参数的+1去掉：
https://github.com/sofastack/sofa-jraft/blob/99d6afeb1c01b1ca7b275542e99065bf06a5b6d1/jraft-core/src/main/java/com/alipay/sofa/jraft/storage/impl/LogManagerImpl.java#L636

https://github.com/sofastack/sofa-jraft/blob/99d6afeb1c01b1ca7b275542e99065bf06a5b6d1/jraft-core/src/main/java/com/alipay/sofa/jraft/storage/impl/LogManagerImpl.java#L646

https://github.com/sofastack/sofa-jraft/blob/99d6afeb1c01b1ca7b275542e99065bf06a5b6d1/jraft-core/src/main/java/com/alipay/sofa/jraft/storage/impl/LogManagerImpl.java#L699

**Comment by killme2008** [comment]
1. 不要手动去删文件。
2. 不再推荐使用这个存储，默认 rocksdb 即可，后面会废弃掉。

**Comment by bruden** [comment]
segment文件是生成snapshot后自动删除的
