### ISSUE TITLE
jraft服务端不停接收USR2信号，导致不停往几个log文件写内容，把服务器磁盘打满

### ISSUE THREAD

**Issue by forever-funny** [sofastack/sofa-jraft#1159]
### jraft服务端不停接收USR2信号，导致不停往几个log文件写内容，把服务器磁盘打满
我们的一个java服务引用了jraft服务端，最近在运行过程中发现jraft会往默认容器目录不停打印几个log文件，直至把磁盘占满。
打印的日志文件有：
node_describe.log
node_metrics.log
thread_pool_metrics.log

分析了源码发现从SignalHelper类开始追踪，发现jraft会在接收一个USR2信号时打印以上日志文件及内容；
现在搞不清楚是谁在不停的往我们进程的jraft发送这个USR2信号？这个和jraft版本有关系么？是jraft的bug还是服务器问题？

### 备注
1、我们的服务同时也引用了nacos客户端1.4.6版本，并连接nacos服务端2.2.3做服务的配置管理和订阅功能。

### Environment

- SOFAJRaft version:
- jraft-core版本：1.3.13
- jdk版本：openjdk 11.0.16+8
- 运行的linux为：centos6.9版本

**Comment by killme2008** [comment]
找你们的运维人员，查找下谁在发送 USR2 信号。

这个机制是 jraft 内置的，用于调试的方式。正常来讲，不应该往生产进程发这个信号的。

**Comment by forever-funny** [comment]
请问这个是linux服务器往进程发的么？我们好几台这样的机器，有些机器有接收这个信息，有的机器却没有。

**Comment by fengjiachun** [comment]
`kill -s SIGUSR2 pid`

jraft 接收如上指令产生的 USR2 次信号，具体见这个文档的 11 小节：https://www.sofastack.tech/projects/sofa-jraft/jraft-user-guide/

一般这个指令是人为执行的

**Comment by killme2008** [comment]
> 请问这个是linux服务器往进程发的么？我们好几台这样的机器，有些机器有接收这个信息，有的机器却没有。

要么是人为，要么是什么自动化程序发的。找你们管理员看下审计日志调查下就知道了。
