### ISSUE TITLE
如何解决集群中的单点压力问题

### ISSUE THREAD

**Issue by lijingjing0212** [sofastack/sofa-jraft#1160]
### Your question

在一个由3个节点组成的集群中，所有外界的写入请求，都会被集中在 leader节点上，对于一个需要频繁写入的系统来说，如何解决单个节点上的高并发问题呢？

**Comment by killme2008** [comment]
Multi-raft 就是解决这个问题的，拆分多个分组，当然前提是你的状态机能水平切分，如果不能，那就无解了。

multi-raft 本质上就是分片，比如三个节点，你可以搞三个分组，然后将 leader 打散到三个分组。
