### ISSUE TITLE
Refactor JRaftHelper

### ISSUE THREAD

**Issue by killme2008** [sofastack/sofa-jraft#139]
JRaftHelper 的下列方法需要重构下：

* `copyNodeOptionsFrom`
* `copyRaftOptionsFrom`

更建议通过让 NodeOptions 和 RaftOptions 实现`com.alipay.sofa.jraft.util.Copiable` 接口来实现。

**Comment by zongtanghu** [comment]
I will have a try to resolve this issue and improve code quality of jraft. @fengjiachun
