### ISSUE TITLE
新增namespace概念，便于客户端动态变更region

### ISSUE THREAD

**Issue by swgu** [sofastack/sofa-jraft#150]
如题，我们的场景是利用rheakv保存多个集群的meta信息；为了区分集群利用集群名称做前缀，每当新增一个集群时，为了使数据分布均衡，必须重新修改配置文件的region信息，否则很容易造成数据倾斜（集群名做前缀）；
需求：能否新增namespace概念，region信息通过模板动态生成，新增namespace时，对rheakv server/client均无感知。

**Comment by fengjiachun** [comment]
数据倾斜的问题建议还是依靠 pd 来 balance
