### ISSUE TITLE
Scan/Iter接口只返回Key信息

### ISSUE THREAD

**Issue by swgu** [sofastack/sofa-jraft#151]
我们rheakv保存的数据如下：
<key1:Blob1> <key2: Blob2> ...
Blob对象很大，甚至可能在1M左右

有时候我们只需要获取当前的 key 列表，不需要Blob对象，目前返回的Entry包含这两部分，会对集群的资源造成不必要的浪费；能否提供API只返回Key对象，减少资源消耗，提高性能；

**Comment by fengjiachun** [comment]
@swgu scan/iter 最新的 master 代码已经支持只返回 key 对象，这个 issue 就先关闭了
