### ISSUE TITLE
RocksRawKVStore 内的读写锁的目的是什么？

### ISSUE THREAD

**Issue by zhuam** [sofastack/sofa-jraft#173]
private final ReadWriteLock  readWriteLock = new ReentrantReadWriteLock();

就是为了 backupDB & restoreBackup 吗？在 raft snapshot 的时候使用，这个代价会不会很高，造成暂时的阻塞不可用～～

**Comment by zhuam** [comment]
直接拿 Rocksdb 的 Snapshot 遍历, 然后生成自定一个 snapshot file是不是更好

**Comment by fengjiachun** [comment]
> 就是为了 backupDB & restoreBackup 吗？在 raft snapshot 的时候使用，这个代价会不会很高，造成暂时的阻塞不可用～～

是的 backupDB/restoreBackup 时可能会有线性一致读请求（不走 raft log），需要 writeLock
对于走 raft log 的请求，和 snapshot 操作本就是串行的，没有锁竞争

> 直接拿 Rocksdb 的 Snapshot 遍历, 然后生成自定一个 snapshot file是不是更好

RocksRawKVStore 还有另一种基于 ingest sst 的 snapshot 方式， 就是类似你说的方式，对应 writeSstSnapshot/readSstSnapshot 两个方法，只 readLock 即可，不需要 writeLock

**Comment by zhuam** [comment]
tks
