### ISSUE TITLE
JRaftServiceFactory何时可用

### ISSUE THREAD

**Issue by fanhualta** [sofastack/sofa-jraft#174]
你好，https://github.com/sofastack/sofa-jraft/pull/110 这个pr中添加的功能是可以自定义JRaftServiceFactory，但是maven中相应的1.2.5版本中没有进行包更新，所以如果是以maven方式使用贵项目的话是没有办法直接进行自定制使用的。虽然可以自己本地进行编译install的方式强制指定本地的maven库来解决，但是由于我们的产品是需要交付给用户使用的，所以想请问下这个功能开放可否同步到maven库中的1.2.5版本中？

**Comment by killme2008** [comment]
@fanhualta  我们新版本预计在 6 月底前发布，如果着急的话，需要自己先打包使用，不过不推荐，因为目前 master 代码还没有经过严格的 jepsen 测试。

**Comment by fanhualta** [comment]
> @fanhualta 我们新版本预计在 6 月底前发布，如果着急的话，需要自己先打包使用，不过不推荐，因为目前 master 代码还没有经过严格的 jepsen 测试。

好的，谢谢
