### ISSUE TITLE
关于rheakv region的疑问

### ISSUE THREAD

**Issue by winflex** [sofastack/sofa-jraft#175]
```
final StoreEngineOptions storeOpts = StoreEngineOptionsConfigured.newConfigured() //
                .withStorageType(StorageType.RocksDB)
                .withRocksDBOptions(RocksDBOptionsConfigured.newConfigured().withDbPath(Configs.DB_PATH).config())
                .withRaftDataPath(Configs.RAFT_DATA_PATH)
                .withServerAddress(new Endpoint("127.0.0.1", 8181))
                .withRegionEngineOptionsList(MultiRegionEngineOptionsConfigured.newConfigured().withStartKey(Long.valueOf(1), "xxx").withStartKey(Long.valueOf(2), "sss").config())
                .withCommonNodeOptions(nodeOptions)
                .config();
```
请问：
1. 如果要有多个region，是不是需要像上面这样手动在代码指定？
2. 如果是，那以什么原则来指定region的startKey或者endKey？

**Comment by fengjiachun** [comment]
多个 region 分两种情况
1. 不使用 pd 模块，那么 multi region 就是固定的（没有自动分裂能力等），需要在 rheakv 第一次启动时指定 region 个数以及所有 region 的 startKey 和 endKey，可以通过代码的方式，也可以通过 yaml 配置文件的方式，[这里有一个 yaml 的例子](https://github.com/sofastack/sofa-jraft/blob/master/jraft-example/config/benchmark_client.yaml)
2. 使用 pd 的话你可以不必配置 region 相关，程序运行过程中会根据数据量大小自动分裂为多 region

startKey 和 endKey 是要根据你自己的使用场景来划分流量的方式（rheakv 是按照 range 分片实现的 multi raft group）

1. 通常你可以预估你的业务里不同 range 的 keys 的大致流量，这样就可以按照流量均匀的配置 [startKey, endKey)

2. 若上一条办不到，也可以通过业务类型、应用、集群等信息来划分，需要你自己给 key 拼一个前缀，比如有 a、b、c 三类业务，你可以分 3 个 region， key 为 a_xxx、b_xxx、c_xxx 的形式

**Comment by winflex** [comment]
自动分裂模式下，是谁来决定什么时候要分裂的？我粗略看了下代码，分裂的源头应该是DefaultRheaKVCliService#rangeSplit方法是吗？我理解这个方法相当于通过rpc向region leader发起分裂请求，但是我没看到有任何地方调用该方法

**Comment by fengjiachun** [comment]
@winflex HeartbeatSender 和 InstructionProcessor
主要原理是各个 region 主动向 pd （placementDriver） server 上报心跳，pd 模块计算/分析并下发指令

**Comment by fengjiachun** [comment]
可以先看一下[这篇文档](https://github.com/sofastack/sofa-jraft/wiki/JRaft-RheaKV-%E7%94%A8%E6%88%B7%E6%8C%87%E5%8D%97)

**Comment by winflex** [comment]
@fengjiachun 好的谢谢

**Comment by fengjiachun** [comment]
没有其他问题的话先关闭了
