### ISSUE TITLE
关于readindex

### ISSUE THREAD

**Issue by Yuanxiangz** [sofastack/sofa-jraft#177]
### Your question

有个问题问一下，刚看到readindex部分。如下代码readFollower会调用leader的readindex，如果这样的话readfollower并不能降低leader的读请求量，那readfollower的意义在哪儿

    private void readFollower(final ReadIndexRequest request, final RpcResponseClosure<ReadIndexResponse> closure) {
        if (this.leaderId == null || this.leaderId.isEmpty()) {
            closure.run(new Status(RaftError.EPERM, "No leader at term %d.", this.currTerm));
            return;
        }
        // send request to leader.
        final ReadIndexRequest newRequest = ReadIndexRequest.newBuilder() //
            .mergeFrom(request) //
            .setPeerId(this.leaderId.toString()) //
            .build();
        this.rpcService.readIndex(this.leaderId.getEndpoint(), newRequest, -1, closure);
    }

### Your scenes

Describe your use scenes (why need this feature)

### Your advice

Describe the advice or solution you'd like

### Environment

- SOFAJRaft version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by killme2008** [comment]
看你怎么理解“读”。 

真正降低的是你**对状态机的业务数据的读取量**，原来都需要集中在 leader ，现在可以在 follower 读取，降低 Leader 的业务数据的读负载，而 readIndex 调用的本身的开销并无法降低的。

**Comment by Yuanxiangz** [comment]
多谢回复  我又仔细看了下代码  最初以为业务流程会走我贴的那段代码   后来发现那段代码是背后状态机同步log里的一部分   异步逻辑看起来真复杂   能保证这么复杂的逻辑高效运行   jraft NB

**Comment by Yuanxiangz** [comment]
简单写了个调用流程有相同疑惑的也可以看下 https://zhuanlan.zhihu.com/p/68069836    刚开始阅读，如有问题请指正

**Comment by killme2008** [comment]
写的很好，感谢 :+1:
