### ISSUE TITLE
(feat) CompareAndPut API

### ISSUE THREAD

**Issue by fengjiachun** [sofastack/sofa-jraft#189]
### Your question

Similar to `AtomicLong.compareAndSet` in Java, the difference is that we do not compare by '==' but compare by bytes.

### Your scenes

Many people need this feature

### Your advice

API :
```
/**
 * Atomically sets the value to the given updated value
 * if the current value equal (compare bytes) the expected value.
 *
 * @param key the key retrieve the value
 * @param expect the expected value
 * @param update the new value
 * @return true if successful. False return indicates that the actual
 * value was not equal to the expected value.
 */
CompletableFuture<Boolean> compareAndPut(final byte[] key, final byte[] expect, final byte[] update);

Boolean bCompareAndPut(final byte[] key, final byte[] expect, final byte[] update);
```

### Environment

- SOFAJRaft version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by SteNicholas** [comment]
@fengjiachun 我先认领下，谢谢。

**Comment by fengjiachun** [comment]
> @fengjiachun 我先认领下，谢谢。

OK
