### ISSUE TITLE
(feat) batch delete api

### ISSUE THREAD

**Issue by fengjiachun** [sofastack/sofa-jraft#194]
### Your advice

```
CompletableFuture<Boolean> delete(final List<byte[]> keys);

Boolean bDelete(final List<byte[]> keys);
```

### Environment

- SOFAJRaft version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by SteNicholas** [comment]
@fengjiachun 我认领
