### ISSUE TITLE
(feat) batch putIfAbsent impl

### ISSUE THREAD

**Issue by fengjiachun** [sofastack/sofa-jraft#199]
### Your question

Provide `RocksRawKVStore#batchPutIfAbsent` method to improve performance, similar `batchPut, batchGetAndPut, etc.`

### Environment

- SOFAJRaft version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by SteNicholas** [comment]
@fengjiachun 我认领
