### ISSUE TITLE
membership change (one-stage change)

### ISSUE THREAD

**Issue by he11oboy1247** [sofastack/sofa-jraft#207]
### Your question

The 391 line of nextStage() |NodeImpl.java| function commits with 
"// Skip joint consensus since only one peers has been changed here. Make
// it a one-stage change to be compatible with the legacy
 // implementation".
When changing group member by removing one node or adding one node, the (this.nchanges) = 1, the function will return, not change the stage status(still STAGE_CATCHING_UP), and not apply the new conf. Thus the group cant make any changes after. So, does this function not implemented yet?

### Your scenes

Describe your use scenes (why need this feature)

### Your advice

Describe the advice or solution you'd like

### Environment

- SOFAJRaft version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by fengjiachun** [comment]
> not change the stage status(still STAGE_CATCHING_UP),

```
case STAGE_CATCHING_UP:
if (this.nchanges > 1) {
    // ...
    return;
}
// no `break` here.
case STAGE_JOINT:
```

**Comment by he11oboy1247** [comment]
> > not change the stage status(still STAGE_CATCHING_UP),
> 
> ```
> case STAGE_CATCHING_UP:
> if (this.nchanges > 1) {
>     // ...
>     return;
> }
> // no `break` here.
> case STAGE_JOINT:
> ```

i know, thank you very much !!!
