### ISSUE TITLE
请教一个关于 Rocksdb 的性能问题

### ISSUE THREAD

**Issue by zhuam** [sofastack/sofa-jraft#211]
我们使用Rocksdb 的过程中并发多个线程，get 毛刺太多也太大，不知道你们是否遇到？

https://github.com/facebook/rocksdb/issues/5560

**Comment by fengjiachun** [comment]
不知道是否跟 cache_index_and_filter_blocks 有关系，请参考一下这个 PR #156

**Comment by fengjiachun** [comment]
相关信息
https://github.com/facebook/rocksdb/issues/3961
https://github.com/facebook/rocksdb/wiki/Partitioned-Index-Filters

**Comment by killme2008** [comment]
这个跟 jraft 没关系，我关闭了。
