### ISSUE TITLE
(feat) 移除对 jackson 的依赖

### ISSUE THREAD

**Issue by fengjiachun** [sofastack/sofa-jraft#212]
### Your question

可以在 example 模块以及 unit test 中继续依赖，但需要升级版本 https://github.com/sofastack/sofa-jraft/network/alert/pom.xml/com.fasterxml.jackson.core:jackson-databind/open

### Environment

- SOFAJRaft version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by SteNicholas** [comment]
@fengjiachun 我认领下。
