### ISSUE TITLE
(feat) upgrade sofa-bolt to v1.6.1

### ISSUE THREAD

**Issue by fengjiachun** [sofastack/sofa-jraft#226]
### Your question

For better perf, see https://github.com/sofastack/sofa-bolt/pull/161

### Your advice
1. upgrade bolt to v1.6.1
2. benchmark with rheakv

### Environment

- SOFAJRaft version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by SteNicholas** [comment]
@fengjiachun 我来升级~

**Comment by fengjiachun** [comment]
> @fengjiachun 我来升级~

ok， tks

**Comment by fengjiachun** [comment]
https://github.com/sofastack/sofa-bolt/releases/tag/v1.6.1
