### ISSUE TITLE
Modify the counter example to avoid misunderstanding

### ISSUE THREAD

**Issue by fengjiachun** [sofastack/sofa-jraft#228]
### Your question

In Counter demo, the get request is not readIndex read, the user will imitate the demo in his own implementation, who will be misled.

### Environment

- SOFAJRaft version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by masaimu** [comment]
### Your question 
In Counter demo, the get request is not readIndex read, the user will imitate the demo in his own implementation, who will be misled.
### Your scenes 
### Your advice 
### Environment 
- SOFAJRaft version: 
- JVM version (eg java -version): 
- OS version (eg uname -a): 
- Maven version: 
- IDE version:

**Comment by masaimu** [comment]
Maybe I can optimize it when i prepare the SOFAJRaft live.

**Comment by killme2008** [comment]
@masaimu  这个可以做下。
