### ISSUE TITLE
Remove the redundanct codes for RepeatedTimer Class

### ISSUE THREAD

**Issue by zongtanghu** [sofastack/sofa-jraft#231]
Your question
I have found the method runOnceNow() in the RepeatedTimer class which is in the sofa-core module has small issue.It's not necessary to call the  schedule() method after run() method.Because the run() method has already calling schedule() method inside.

Your scenes
As above describe.

Your advice
I has already polish the codes and remove the schedule() method inside.

Environment
SOFAJRaft version:
JVM version (e.g. java -version):
OS version (e.g. uname -a):
Maven version:
IDE version:

**Comment by fengjiachun** [comment]
@killme2008
