### ISSUE TITLE
(feat) Enhancement with `RepeatedTimer`

### ISSUE THREAD

**Issue by fengjiachun** [sofastack/sofa-jraft#234]
### Your question

`RepeatedTimer` is implementation by `java.util.Timer`, there are some defects: 
1. Timer support for scheduling is based on absolute time.
2. If an exception is thrown TimerTask unchecked.
3. Timer single-threaded tasks, task execution time may be lost or inaccurate.

Maybe we need a better implementation.

### Environment

- SOFAJRaft version: 1.2.5
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by zongtanghu** [comment]
I think we can implent the multiple level TimingWheel, refer to kafka. @fengjiachun

**Comment by zongtanghu** [comment]
Can I participate in design a new enhancement RepeatedTimer with you? @fengjiachun
