### ISSUE TITLE
Optimize ReplicatorOptions class to implement Copiable interface.

### ISSUE THREAD

**Issue by zongtanghu** [sofastack/sofa-jraft#241]
Your question
I found that ReplicatorOptions class has a copy() method,but it didn't implement  Copiable interface.So,the ReplicatorOptions class didn't keep the code style with other class,such as RaftOptions and NodeOptions.

Your scenes
Your advice
I want modify this class and make it implement Copiable interface to keep  the code style with other class.

Environment
SOFAJRaft version: 1.2.5
JVM version (e.g. java -version):
OS version (e.g. uname -a):
Maven version:
IDE version:

**Comment by fengjiachun** [comment]
Please do send a PR. Thanks in advance @zongtanghu
