### ISSUE TITLE
Async snapshot of rheakv-rocksdb

### ISSUE THREAD

**Issue by fengjiachun** [sofastack/sofa-jraft#244]
### Your question

We know that saving a snapshot of state-machine  is very time consuming and requires blocking the state-machine.

### Your scenes

We can get the snapshot of rocksdb in a synchronous way. rocksdb can guarantee that we will not read the newly applied data, then we read the data asynchronously and save the snpashot of the state-machine.

### Your advice

We need to pay attention to the following points:
1. rocksdb cannot be closed during saving a snapshot, otherwise it may cause the process  crash
2. If the asynchronous save snapshot fails, we may need to halt the state-machine
3. Something else ？

### Environment

- SOFAJRaft version: 1.2.6
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by SteNicholas** [comment]
@fengjiachun Please assign to me,thanks.
