### ISSUE TITLE
Implement for ReplicatorGroupTest Unit Class

### ISSUE THREAD

**Issue by zongtanghu** [sofastack/sofa-jraft#246]
Your question
I found that ReplicatorGroupTest wasn't implemented.So it is an empty class.

Your scenes
Your advice
I have already implement the ReplicatorGroupTest in my local enviroment and putforward a pr later.

Environment
SOFAJRaft version: 1.2.5
JVM version (e.g. java -version):
OS version (e.g. uname -a):
Maven version:
IDE version:

**Comment by fengjiachun** [comment]
Please do send a PR. Thanks in advance @zongtanghu
