### ISSUE TITLE
Nodes can only be written by leaders, while pre-vote requires other nodes to pass the official vote. When there is only one node left, even the leader cannot be selected. Even if other nodes are restarted, there is no way to add nodes. Can be manually restarted, this design. . . This problem becomes very helpless in a stateless container environment.

### ISSUE THREAD

**Issue by zhujie616** [sofastack/sofa-jraft#257]
rt

**Comment by killme2008** [comment]
raft 本身就要求是有状态的，无状态的为何要达成一致性？ 你这个问题本身就比较奇怪了。

**Comment by fengjiachun** [comment]
> 当节点挂到只剩下一个时，连 leader 都选不出来

跟 pre-vote 无关，paxos，zab，raft 等分布式一致性协议都要求半数以上节点存活才可提供服务，都是 CP 系统，不是 AP，类似的 zk，etcd 都是一样

> 即使其他节点重启了，也没办法往里加节点
重启后 IP/Host 变了的话是需要走 raft membership change 流程重新加入 group 的，不然没法保证数据一致性

这是 etcd 的一个解决类似问题的方式，供参考 https://github.com/coreos/etcd-operator
