### ISSUE TITLE
Priority-based semi-deterministic leader election

### ISSUE THREAD

**Issue by killme2008** [sofastack/sofa-jraft#264]
## Purpose
The main goal is to prioritize member nodes for next leader election. Raft uses randomized timer so that it is hard to make a deterministic decision. In this library, leader election will be still probabilistic, but more predictable.

https://github.com/eBay/NuRaft/blob/master/docs/leader_election_priority.md

**Comment by zongtanghu** [comment]
@fengjiachun  I can have a try!You can assign this task to me!

**Comment by killme2008** [comment]
@zongtanghu Great, it's yours. 😄

**Comment by zongtanghu** [comment]
> @zongtanghu Great, it's yours.

Thanks to give me this chance.

**Comment by zongtanghu** [comment]
![Leader_Election_Priority_Phase1](https://user-images.githubusercontent.com/5010883/66974230-0edf7c00-f0cd-11e9-8074-517c617b3aaa.jpg)
![Leader_Election_Priority_Phase2](https://user-images.githubusercontent.com/5010883/66974234-1010a900-f0cd-11e9-84d6-f3f727c46a64.jpg)

**Comment by zongtanghu** [comment]
**==============================================================================**

**NodeOptions Class**
(1)Add new attribute:
private int electionPriority(can set a initial value,such as "1");

**==============================================================================**

**PeerId Class**
(1)Add new attribute:
private int priority;(When Node init,it can be set to NodeOptions.electionPriority)

**==============================================================================**

**Node interface**
(1)Add a method:
getNodeTargetPriority();

**==============================================================================**

**NodeImpl Class**
(1)Add new attribute:
private int targetPriority;

(2)In "NodeImpl.handleAppendEntriesRequest" Method:

In the branch of code: "if (entriesCount == 0) {}"
add the logical codes aboved.
"When the current leader is alive, whenever a follower receives heartbeat, it updates its target priority to the initial value: max(priority of all nodes)."

(3)In the "NodeImpl.handleElectionTimeout" Method:
Add the logical codes,

Step1.compares its local target priority with its own priority.
If NodeOptions.electionPriority < targetPriority, it does not initiate leader election and waits for the next election timeout. So,it return directly and waits for the next election timeout.

Step2.If next leader is not elected until next election timeout, it exponentially lessens its local target priority, for example target_priority = target_priority * 0.8. And the minimum value of target priority should be 1.

**So,here we are adding some logical below codes in the stepDown() method.Here,we maybe add a counter to represent whether the node is elected failurely secondly.
If there's no leader during this election time,we use"targetPriority = targetPriority * 0.8"* * 

**==============================================================================**

**RpcRequests.AppendEntriesRequest**
(1)Add new attribute:
priority_
Here,maybe the code in the "RpcRequests" need to be generated automatically.

**==============================================================================**

**Replicator**
(1)In "fillCommonFields" set "priority"(its own local priority) value to AppendEntriesRequest.Builder rb 
for heartbeat attribute content values;

**Comment by zongtanghu** [comment]
Hi @fengjiachun please help to review my detailed design!Thanks!

**Comment by fengjiachun** [comment]
Maybe we do not need to add the priority attribute to the PeerId? @zongtanghu

**Comment by zongtanghu** [comment]
> Maybe we do not need to add the priority attribute to the PeerId? @zongtanghu

Okay,I see it.I will add a variable attribute named priority to NodeImpl.Thus,it's not necessary to add the priority attribute to the PeerId. @fengjiachun

**Comment by zongtanghu** [comment]
> Maybe we do not need to add the priority attribute to the PeerId? @zongtanghu

As discussed online,I will also add the priority attribute to the PeerId ,because Configuration includes list of peers, so that one node can get priority of all nodes in a JRaft group cluster.

**Comment by fengjiachun** [comment]
> > Maybe we do not need to add the priority attribute to the PeerId? @zongtanghu
> 
> As discussed online,I will also add the priority attribute to the PeerId ,because Configuration includes list of peers, so that one node can get priority of all nodes in a JRaft group cluster. @fengjiachun

👌

**Comment by zongtanghu** [comment]
And I will add a percent value for that "target_priority = target_priority * 0.8" in the NodeOption Class. @fengjiachun
