### ISSUE TITLE
Abstract communication layer to avoid strong dependence on bolt

### ISSUE THREAD

**Issue by fengjiachun** [sofastack/sofa-jraft#268]
1. jraft is provided to users as lib. Many times users want to unify the rpc communication layer in their own systems. They may not want to rely on bolt. Currently, jraft relies heavily on bolt, and users must rely heavily on bolt.
2. bolt returns a byte[] when deserializing, which limits the imagination of zero copy optimization.

How:
1. An adapter of the rpc layer
2. Based on SPI extension, the default implementation is still bolt

**Comment by SteNicholas** [comment]
Please assign this issue to me, I will discuss details of improvement with you~

**Comment by ClownfishYang** [comment]
I agreed, Especially the part used by `NodeImpl` , which makes me a beginner need to know `Bolt` before knowing the specific all process.
I  recommend refactoring the `NodeImpl` code, it code very bloated.
