### ISSUE TITLE
How does sofa jraft deploy in a virtualized environment?

### ISSUE THREAD

**Issue by wy223170** [sofastack/sofa-jraft#270]
你好，请问下sofa jraft如何在虚拟化环境下使用，比如部署三个实例，三个实例都是docker的。因为虚拟化实例可能漂移，怎么保证snapshot的迁移呢？另外怎么控制多个实例的同时漂移，导致集群不可用的问题？

**Comment by fengjiachun** [comment]
jraft 本身是有状态的，你说的实例漂移就可以理解为这个节点挂掉并新拉起了一个节点，我们内部的做法是通过一个  manager 节点监听容器上下线并执行 `CliService` removePeer 和 addPeer，利用 raft 协议本身的能力达到数据迁移的目的，但是对于半数以上节点同时漂移是无解的，可能出现丢数据的情况

这是 etcd 的一个解决类似问题的方式，供参考 https://github.com/coreos/etcd-operator

**Comment by wy223170** [comment]
感谢回答，是不是只要manager节点监听到容器变化就会立刻进行removePeer或addPeer，需不需等待容器已经达到某种状态，比如迁移完snapshot等才进行addPeer啥的，这可能就需要实例迁移后完成一个打标记的功能标志迁移完成了

**Comment by fengjiachun** [comment]
@wy223170 流程是先 addPeer 成功以后再 removePeer
其中 addPeer 在追数据成功后才会返回成功

看到你多次强调 snapshot，其实这里你不用关注 snapshot，这是 jraft 内部会考虑的 raft 层的东西，不需要额外做特殊处理

**Comment by fengjiachun** [comment]
没有更多问题就先关闭了

**Comment by wy223170** [comment]
了解，非常感谢
