### ISSUE TITLE
Snapshot improve

### ISSUE THREAD

**Issue by fengjiachun** [sofastack/sofa-jraft#276]
### Your question

The current design of snapshot is to configure the snapshot frequency. There is a case where only a few logs are written in the two snapshot intervals. Is it necessary to take another snapshot at this time?

### Your advice

Maybe we can provide an option: `distance`
Snapshot is executed when `fsm.getLastAppliedIndex - lastSnapshotId > distance`, otherwise it returns directly

### Environment

- SOFAJRaft version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by SteNicholas** [comment]
Please assign this issue to me, I will discuss details of improvement with you~

**Comment by zongtanghu** [comment]
This feature issue can assign to me if @SteNicholas  has no much more time to finish it.Thanks. @fengjiachun
