### ISSUE TITLE
Enable rocksdb force_consistency_checks

### ISSUE THREAD

**Issue by killme2008** [sofastack/sofa-jraft#283]
See

https://github.com/tikv/tikv/pull/5491

https://github.com/facebook/rocksdb/commit/a28182233109f09e23e6336b5ed860ddf2c8eece

**Comment by SteNicholas** [comment]
@killme2008 Please assigned to me,I have already worked for this option.

**Comment by fengjiachun** [comment]
@SteNicholas Waiting for rocksdb to release a new version
