### ISSUE TITLE
In election example case, listener won't run while only one node in the raft group.

### ISSUE THREAD

**Issue by ryantotti** [sofastack/sofa-jraft#284]
### Describe the bug

If there is only one node in raft group, the onLeaderStart method will run before addLeaderStateListener, and the listener is useless.

### Environment

- SOFAJRaft version: 1.2.6
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by killme2008** [comment]
Good catch! It's a bug ,we'll fix it.

**Comment by fengjiachun** [comment]
fixed
