### ISSUE TITLE
Is there a containsKey api?

### ISSUE THREAD

**Issue by zhangjun050754** [sofastack/sofa-jraft#288]
containsKey api有吗

**Comment by fengjiachun** [comment]
没有这个 api， 不用 get 是因为不想 return value？
仅仅是不想 return value 的话可以使用 [scan api](https://github.com/sofastack/sofa-jraft/blob/master/jraft-rheakv/rheakv-core/src/main/java/com/alipay/sofa/jraft/rhea/client/RheaKVStore.java#L193) 

`scan(key, BytesUtil.nextBytes(key), true, false)`

**Comment by zhangjun050754** [comment]
startKey, endKey 含义是什么？没太理解 意思是说先put的key和后put的key区间？

**Comment by zhangjun050754** [comment]
> 没有这个 api， 不用 get 是因为不想 return value？
> 仅仅是不想 return value 的话可以使用 [scan api](https://github.com/sofastack/sofa-jraft/blob/master/jraft-rheakv/rheakv-core/src/main/java/com/alipay/sofa/jraft/rhea/client/RheaKVStore.java#L193)
> 
> `scan(key, BytesUtil.nextBytes(key), true, false)`

startKey, endKey 含义是什么？没太理解 意思是说先put的key和后put的key区间？

**Comment by fengjiachun** [comment]
> > 没有这个 api， 不用 get 是因为不想 return value？
> > 仅仅是不想 return value 的话可以使用 [scan api](https://github.com/sofastack/sofa-jraft/blob/master/jraft-rheakv/rheakv-core/src/main/java/com/alipay/sofa/jraft/rhea/client/RheaKVStore.java#L193)
> > `scan(key, BytesUtil.nextBytes(key), true, false)`
> 
> startKey, endKey 含义是什么？没太理解 意思是说先put的key和后put的key区间？

scan 是扫描 startKey 和 endKey 这个区间的所有键值对，左闭右开，最后一个参数为 false 表示不返回 value，详见文档：https://www.sofastack.tech/projects/sofa-jraft/jraft-rheakv-user-guide/

**Comment by zhangjun050754** [comment]
> > > 没有这个 api， 不用 get 是因为不想 return value？
> > > 仅仅是不想 return value 的话可以使用 [scan api](https://github.com/sofastack/sofa-jraft/blob/master/jraft-rheakv/rheakv-core/src/main/java/com/alipay/sofa/jraft/rhea/client/RheaKVStore.java#L193)
> > > `scan(key, BytesUtil.nextBytes(key), true, false)`
> > 
> > 
> > startKey, endKey 含义是什么？没太理解 意思是说先put的key和后put的key区间？
> 
> scan 是扫描 startKey 和 endKey 这个区间的所有键值对，左闭右开，最后一个参数为 false 表示不返回 value，详见文档：https://www.sofastack.tech/projects/sofa-jraft/jraft-rheakv-user-guide/

可以模糊查询key吗？

**Comment by fengjiachun** [comment]
可以参考 redis 的 scan

**Comment by fengjiachun** [comment]
没其他问题先关闭了

**Comment by killme2008** [comment]
@fengjiachun  我觉的是否可以提供这么一个 api  ? containsKey 对于 kv 来说也是很常见的，比如 rocksdb 也有类似的 exists 方法

**Comment by fengjiachun** [comment]
> @fengjiachun 我觉的是否可以提供这么一个 api ? containsKey 对于 kv 来说也是很常见的，比如 rocksdb 也有类似的 exists 方法

也可以，先记一个 issue

**Comment by zhangjun050754** [comment]
> redis 的 scan

建议增加一下key的前缀查询方面的api

**Comment by fengjiachun** [comment]
> > redis 的 scan
> 
> 建议增加一下key的前缀查询方面的api

scan 就是

**Comment by zhangjun050754** [comment]
> > > redis 的 scan
> > 
> > 
> > 建议增加一下key的前缀查询方面的api
> 
> scan 就是
请教一下 如下两个key 如何得到 ‘gr10:’为前缀的所有key？
gr10:111_r0
gr10:111_r8

**Comment by fengjiachun** [comment]
> > > > redis 的 scan
> > > 
> > > 
> > > 建议增加一下key的前缀查询方面的api
> > 
> > 
> > scan 就是
> > 请教一下 如下两个key 如何得到 ‘gr10:’为前缀的所有key？
> > gr10:111_r0
> > gr10:111_r8

`

     byte[] start = "gr10".getBytes();

     byte[] end = BytesUtil.nextBytes(start);

     scan(start, end)
`

**Comment by zhangjun050754** [comment]
> > > > > redis 的 scan
> > > > 
> > > > 
> > > > 建议增加一下key的前缀查询方面的api
> > > 
> > > 
> > > scan 就是
> > > 请教一下 如下两个key 如何得到 ‘gr10:’为前缀的所有key？
> > > gr10:111_r0
> > > gr10:111_r8
> 
> `
> 
> ```
>  byte[] start = "gr10".getBytes();
> 
>  byte[] end = BytesUtil.nextBytes(start);
> 
>  scan(start, end)
> ```
> 
> `

感谢支持，还是匹配不到 不知道什么原因

**Comment by fengjiachun** [comment]
@zhangjun050754 不好意思，是我写错了
按照你的需求，应该这样构造 endKey

`

    String key = "gr10"

    String start = key + ':';

    String end = key + (char) (':' + 1);

    scan(start, end)
`

**Comment by zhangjun050754** [comment]
> @zhangjun050754 不好意思，是我写错了
> 按照你的需求，应该这样构造 endKey
> 
> `
> 
> ```
> String key = "gr10"
> 
> String start = key + ':';
> 
> String end = key + (char) (':' + 1);
> 
> scan(start, end)
> ```
> 
> `

可以了 感谢支持，我在摸索摸索。。
