### ISSUE TITLE
Does RheaKV dynamically add apis to delete nodes? Is there any api for the monitoring node?

### ISSUE THREAD

**Issue by zhangjun050754** [sofastack/sofa-jraft#292]
### Your question

Describe your question clearly

### Your scenes

Describe your use scenes (why need this feature)

### Your advice

Describe the advice or solution you'd like

### Environment

- SOFAJRaft version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by fengjiachun** [comment]
https://www.sofastack.tech/projects/sofa-jraft/jraft-user-guide/
1. 动态增删节点请参考 [3.2 CLI 服务] 章节的 CliService
2. jraft-core 与 rheakv 均有大量的指标采集，基于 dropwizard 采集，默认会输出到日志中，指标详情可以从上面的文档中了解， 但是 jraft 并不提供上报数据服务，建议可以做一个 reporter adapter 把 dropwizard 转成 prometheus 格式通过 prometheus pushgateway 推送到 prometheus server 或者是构造一个 prometheus exporter 配置 prometheus server 拉取监控数据， 最后通过 grafana + prometheus server 达到监控目的
整个流程完成下来，没有太多开发量， jraft 之所以没支持这个，是因为太重了，我们还是希望个保持 jraft 的轻量，还请谅解

dropwizard 转成 prometheus 工具库： https://www.robustperception.io/exposing-dropwizard-metrics-to-prometheus

**Comment by fengjiachun** [comment]
没其他问题先关闭了
