### ISSUE TITLE
How to ensure that the previous data is not lost after the jraft-example upgrade?

### ISSUE THREAD

**Issue by huzhihong** [sofastack/sofa-jraft#296]
jraft-example启动的时候必须指定IP吗？jraft-example在已经运行的group里如何添加新的结点？jraft-example升级之后如何保证之前的数据不丢失？

**Comment by fengjiachun** [comment]
> jraft-example启动的时候必须指定IP吗？

host 或者 ip 必须指定

> jraft-example在已经运行的group里如何添加新的结点？

参考下面链接文档中的 CliService， 提供新增节点，删除节点，替换节点的接口

> jraft-example升级之后如何保证之前的数据不丢失？

这句没看明白，升级跟丢数据没有必然联系，只要版本兼容就没问题

https://www.sofastack.tech/projects/sofa-jraft/jraft-user-guide/

**Comment by fengjiachun** [comment]
没有更多问题就先关闭了

**Comment by huzhihong** [comment]
没有啦，谢谢！

发自我的iPhone


------------------ Original ------------------
