### ISSUE TITLE
leader切换问题

### ISSUE THREAD

**Issue by hanzhihua** [sofastack/sofa-jraft#300]
### Your question

我的应用经常会因为checkDeadnode，造成重新选leader
![image](https://user-images.githubusercontent.com/1732108/67066991-402c7a80-f1a7-11e9-9a0a-a24377c222fd.png)
当时的服务器都是正常工作的，有什么方法可以避免频繁的选主

### Your scenes

Describe your use scenes (why need this feature)

### Your advice

Describe the advice or solution you'd like

### Environment

linux 4.9.0-7-amd64 #1 SMP Debian 4.9.110-3+deb9u1 (2018-08-03) x86_64 GNU/Linux
最新版本的jraft
jdk1.8

**Comment by killme2008** [comment]
你的选举超时设置成多少？ electionTimeout

这种情况肯定是有问题的，通常来说是心跳超时引起的，可能原因很多： Full gc 暂停， 网络， 或者应用负载 CPU 过高等等，需要你自行分析下。

如果应用负载相对是较高的， full gc 也较为频繁或者耗时较长，建议调大 electionTimeout

**Comment by killme2008** [comment]
心跳超时，日志里会有跟 replicator 相关的错误或者 warn 的日志，建议观察下。

也可以观察下 metric 状况， 使用 kill -s SIGUSR2 pid 可看到节点状态和性能指标统计数据，可以参考下文档： https://www.sofastack.tech/projects/sofa-jraft/jraft-user-guide/ 章节：10. 排查故障工具
