### ISSUE TITLE
apply task执行问题

### ISSUE THREAD

**Issue by hanzhihua** [sofastack/sofa-jraft#303]
### Your question

咨询一下，在应用中，我发现leader apply task，比follower执行的还要玩，这是为什么呢？

### Your scenes

多个服务器（3个节点的集群），通过ntp同步时间，通过日志，我发现follower执行状态机，比leader还要快

### Your advice

Describe the advice or solution you'd like

### Environment

jdk  1.8
linux 1 4.9.0-7-amd64 #1 SMP Debian 4.9.110-3+deb9u1 (2018-08-03) x86_64 GNU/Linux
jraft最新版本

**Comment by fengjiachun** [comment]
不会的，除非你自己的状态机是异步 apply，没成功就返回

**Comment by fengjiachun** [comment]
确实可能发生
1. leader 收到一条日志的多数派响应后即会修改自己的 lastCommittedIndex，并将 lastCommittedIndex 之前的日志应用到状态机（异步的）
2. leader 的 replicator 向 follower 发送心跳时会携带 lastCommittedIndex， follower 收到后也会将 lastCommittedIndex 之前的日志应用到状态机（异步的）
3. 如上步骤，follower 确实可能比 leader 更早将同一条日志应用到状态机

**Comment by hanzhihua** [comment]
谢谢

**Comment by fengjiachun** [comment]
补充一下，这个特性对数据一致性没有影响，也不影响线性一致读的正确性

**Comment by fengjiachun** [comment]
没更多问题就先关闭了
