### ISSUE TITLE
while running the rheakv example, cpu raise up to 100%

### ISSUE THREAD

**Issue by xiaoomai** [sofastack/sofa-jraft#306]
cpu config are i5-6600 3.3Ghz
16G memory

yaml config as

##RheaKVStoreOptions
---
# 每个store节点包含一个或多个raft-group复制组, 这个字段是所有复制组的名称前缀, 所有的raft-group name遵循
# [clusterName-regionId]的命名规则
clusterName: local_data

# PD相关选项设置
placementDriverOptions:
  # fake==true表示在无PD模式下启动, 无PD模式将失去"自管理"能力, 所有设置都基于当前这个初始的配置文件
  fake: true

# store存储节点的相关选项设置
storeEngineOptions:
  rocksDBOptions:
    # 是否同步刷盘, 默认为 true, 异步刷盘性能更好, 但是在机器掉电时有丢数据风险
    sync: false
    dbPath: rhea_db/
  # raft log存储目录
  raftDataPath: rhea_raft/
  heartbeatOptions:
    storeHeartbeatIntervalSeconds: 120
  commonNodeOptions:
    electionTimeoutMs: 5000
  useSharedRpcExecutor: true
  serverAddress:
    ip: 127.0.0.1
    # 端口, 这个是必须配置的选项, 存储层提供rpc服务的监听端口
    port: 8181
# 是否只从 leader 节点读取数据, 默认为true, 当然从follower节点读也能保证线性一致读, 但是如果一个 follower 节点在同步数据时落后较多的情况下
# 将导致读请求超时, 从而导致 rheaKV 客户端 failover 逻辑启动重新从 leader 节点上尝试读取, 最终结果就是读请求延时较长
onlyLeaderRead: true
# 集群列表中所有节点的地址列表
initialServerList: 127.0.0.1:8181,127.0.0.1:8182,127.0.0.1:8183

# 失败重试次数
failoverRetries: 2

**Comment by xiaoomai** [comment]
running with version 1.2.6

**Comment by fengjiachun** [comment]
1. top -Hp pid 找出耗 cpu 高的 thread id
2.printf '%x\n' tid （tid） 为上面获取的线程id
3. jstack -l  pid  看下对应线程id的堆栈状况
