### ISSUE TITLE
the promble in online env

### ISSUE THREAD

**Issue by hanzhihua** [sofastack/sofa-jraft#307]
### Your question

在线系统出现了下面warn
[JRaft-Closure-Executor-36]-c.a.s.jraft.storage.log.SegmentFile.read - Try to read data from segment file /mnt/storage00/raft/log/segments/0000000000000000002 out of comitted position, logIndex=278, readPos=0, wrotePos=4533, this.committedPos=0.

而且apply task需要花费很长的时间，比如几分钟

咨询一下，这个主要是什么问题呢

### Environment

jdk1.8
3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt11-1+deb8u3 (2015-08-04) x86_64 GNU/Linux
raft 1.2.6

**Comment by fengjiachun** [comment]
你改为同步刷盘了吗？ 上一个问题 #304 解决了没有？

**Comment by hanzhihua** [comment]
没有，这个是主要原因吗？我在uat环境是同样的代码，但没有出现上述的错误

**Comment by fengjiachun** [comment]
@hanzhihua 改吧，改完应该就好了

> logIndex=278, readPos=0, wrotePos=4533, this.committedPos=0.

从这行日志看 committedPos=0， 基本上可以判断你没刷盘

不过这里 jraft 本身的处理可能有一些不合理 @killme2008 可以看看， sync 选项是跟随上层的 sync，但是 read 方法却不允许读未刷盘数据，这就要求用户必须设置 sync = true，会给用户造成一些困扰

**Comment by fengjiachun** [comment]
另外 segment log 我们没发 release 你怎么用到的？直接用的 master 分支代码？线上系统的话不建议使用，下一个 release 版本才会正式加入 segment log 模块

**Comment by hanzhihua** [comment]
DefaultJRaftServiceFactory里面指定了 RocksDBSegmentLogStorage，我应该是用的raft1.2.6 snapshot版本，commit c5beea1807f1a5f58b7f41c110838dd405d78d4d

另外请问一下 RocksDBSegmentLogStorage跟RocksDBLogStorage区别是什么呢？
代替rocksdb吗？

**Comment by fengjiachun** [comment]
背景见 #39
主要目的是针对大 value 场景的优化
更多可以参考这片论文： WiscKey- Separating Keys from Values in SSD-conscious Storage

**Comment by killme2008** [comment]
@hanzhihua 我们非常不推荐使用自己打包的版本，建议都采用我们正式 release 的版本， release 版本都会经过严格的 jepsen 测试以及我们线上环境的测试，而开发分支是没有这个保证的，只是跑了单元测试。

另外这里就是sync没有设置为  true 引起的，理论上并不影响使用，只是会有一个告警日志。

**Comment by fengjiachun** [comment]
没更多问题先关闭了
