### ISSUE TITLE
while running the CounterServer example,the cpu raised up to 100%

### ISSUE THREAD

**Issue by kenro** [sofastack/sofa-jraft#309]
and the thread info from VisualVM is as follow:
HashedWheelTimer$Worker.waitForNextTick()    48%
DefaultPromise.awaitUninterruptibly()                 40%
SelectionSelectionKeySetSelector.select()            9%

- SOFAJRaft version:1.2.6
- JVM version (e.g. `java -version`):1.8
- OS version (e.g. `uname -a`): win7

**Comment by killme2008** [comment]
Have you run the client?  If you run the client, the CPU in busy is normal ,it is doing it's works.

**Comment by fengjiachun** [comment]
Visualvm does not have thread cpu occupancy ？
send a screenshot?

**Comment by fengjiachun** [comment]
![image](https://user-images.githubusercontent.com/3860496/67387705-048c1900-f5ca-11e9-8f03-50429be373ee.png)
If you are using this chart，this is cpu time, not cpu occupancy

**Comment by kenro** [comment]
I just start a CounterServer，and found it ran out of cpu。  And I send some debug info to you，which may help a lot.

**Comment by kenro** [comment]
the debug info

**Comment by fengjiachun** [comment]
#311
