### ISSUE TITLE
When saving a snapshot, the jraft-example uses an asynchronous method. Is there a thread safety issue with multiple calls?

### ISSUE THREAD

**Issue by huzhihong** [sofastack/sofa-jraft#313]
![image](https://user-images.githubusercontent.com/13905540/67467410-432ddc00-f67b-11e9-8cc0-dac44ae5d5a6.png)

**Comment by fengjiachun** [comment]
没有问题，这一句可理解为读快照 'final long currVal = this.value.get();' 是同步执行的

**Comment by huzhihong** [comment]
为什么会没有问题啊？com.alipay.sofa.jraft.example.counter.CounterStateMachine#onSnapshotSave这个方法在什么情况下回调？假如回调频率很高，比如1毫秒，回调后提交给线程池，没办法保证线程池里的线程执行顺序。

**Comment by huzhihong** [comment]
列如：第一次回调currVal = 1；第二次回调的时候currVal =2，两次都通过方法Utils.runInThread提交给了线程池，这个时候就可能会出现线程池先调度currVal = 1的情况或者currVal =2的情况，这个调度顺序是如何保证的呢？

**Comment by huzhihong** [comment]
如果我没有使用AtomicLong value，而是使用ConcurrentHashMap value，我该怎么保存快照呢？

**Comment by killme2008** [comment]
@huzhihong 关于 snapshot 使用，请仔细阅读这里的 2.6 小节

https://www.sofastack.tech/projects/sofa-jraft/jraft-user-guide/

关于你提的两个问题:

1. 每次  `onSnapshotSave` 传入的 writer 和 done 都是不同的，都记录了当时那个“时刻”整个节点的日志状态（如 log index/term 等），每次 `onSnapshotSave` 保存的目录或者文件也是不一样的。所以不会存在你说的并发保存问题。如果你仔细观察的话，会发现在 snapshot 文件目录是根据日志编号递增保存的。不过我们通常不建议将 snapshot 间隔设置太短，这会引起性能问题，因为每次 `onSnapshotSave` 都会阻塞状态机，以便用户可以”捕获“当前状态机的状态。

2. 使用 ConcurrentHashMap 也没有什么不同，需要在 `onSnapshotSave` 获取整个 map 的镜像（比如复制一个 `new HashMap<>(this.stateMap)`，然后去保存这个镜像即可。保存步骤可以异步，复制镜像这个步骤是必须同步的。

**Comment by huzhihong** [comment]
嗯嗯 好的 谢谢
