### ISSUE TITLE
should writeLock be used instead of readLock for put and delete in rawKVStore?

### ISSUE THREAD

**Issue by JerryYangSH** [sofastack/sofa-jraft#320]
### Your question
Take example of RocksRawKVStore.java

``@Override
    public void batchPutIfAbsent(final KVStateOutputList kvStates) {
        if (kvStates.isSingletonList()) {
            final KVState kvState = kvStates.getSingletonElement();
            final KVOperation op = kvState.getOp();
            putIfAbsent(op.getKey(), op.getValue(), kvState.getDone());
            return;
        }
        final Timer.Context timeCtx = getTimeContext("BATCH_PUT_IF_ABSENT");
        final Lock readLock = this.readWriteLock.readLock();
        readLock.lock();``<<<<<<<<<<<<<<<<<
why readLock is used here? I think you should have used writeLock.lock, right?
The same applies on delete.

**Comment by fengjiachun** [comment]
Read and write operations: readlock
`closedb/backupdb/restoredb...` : writelock

**Comment by killme2008** [comment]
The raw kv store is thread-safe for reading or writing. We use readWriteLock to protect the db itself when doing `closedb/backupdb/restoredb` etc.
