### ISSUE TITLE
jraft core benchmark

### ISSUE THREAD

**Issue by hanzhihua** [sofastack/sofa-jraft#328]
### Your question

请问有jraft core的benchmark数据吗？我做性能测试数据是
3台集群（jraft 版本1.2.6）
uname :4.9.0-0.bpo.6-amd64 #1 SMP Debian 4.9.88-1+deb9u1~bpo8+1 (2018-05-13) x86_64 GNU/Linux
状态机都是空方法
task data =1k 数据 qps > 3w ，没有任何Warn.

如果 taks data= 10k 数据 qps <6000
会出现大量下面这样的Warn
15:12:21.659 [jraft_test/10.69.76.19:33333-AppendEntriesThread0] WARN  com.alipay.sofa.jraft.core.NodeImpl - Node <jraft_test/10.69.76.19:33333> reject term_unmatched AppendEntriesRequest from 10.69.76.22:33333, term=1, prevLogIndex=1982062, prevLogTerm=1, localPrevLogTerm=0, lastLogIndex=1982053, entriesSize=3.
15:12:21.659 [jraft_test/10.69.76.19:33333-AppendEntriesThread0] WARN  com.alipay.sofa.jraft.core.NodeImpl - Node <jraft_test/10.69.76.19:33333> reject term_unmatched AppendEntriesRequest from 10.69.76.22:33333, term=1, prevLogIndex=1982065, prevLogTerm=1, localPrevLogTerm=0, lastLogIndex=1982053, entriesSize=3.
15:12:21.858 [jraft_test/10.69.76.19:33333-AppendEntriesThread0] WARN  com.alipay.sofa.jraft.core.NodeImpl - Node <jraft_test/10.69.76.19:33333> reject term_unmatched AppendEntriesRequest from 10.69.76.22:33333, term=1, prevLogIndex=1983252, prevLogTerm=1, localPrevLogTerm=0, lastLogIndex=1983244, entriesSize=1.
15:12:21.858 [jraft_test/10.69.76.19:33333-AppendEntriesThread0] WARN  com.alipay.sofa.jraft.core.NodeImpl - Node <jraft_test/10.69.76.19:33333> reject term_unmatched AppendEntriesRequest from 10.69.76.22:33333, term=1, prevLogIndex=1983253, prevLogTerm=1, localPrevLogTerm=0, lastLogIndex=1983244, entriesSize=1.

测试过程中，系统没有瓶颈， cpu/mem/disk/network都是低水位
请问一下，针对>10K的数据，需要做什么配置，来提升Qps吗？

**Comment by fengjiachun** [comment]
raft 是 strong leader 模式，也就是说一个 group 中只有 leader 可接受读写请求，通常为了提高吞吐需要 multi raft group，可以参考 rheakv 的 Benchmark 结果以及 Benchmark 代码都在 jraft-example 工程里，文档见这里 https://www.sofastack.tech/projects/sofa-jraft/benchmark-performance/

另外除系统指标比如 磁盘、 内存、网络、jvm 的 gc 可观测， jraft 有详细的性能指标统计，详细见这个文档第八小结 [metric 监控](https://www.sofastack.tech/projects/sofa-jraft/jraft-user-guide/)
metric 数据会打印到日志里， jraft 自带的 Benchmark 程序也会输出 metric 指标，也可以通过 `kill -s SIGUSR2 pid` 来输出监控指标以及各节点的状态信息供参考

你上面提供的信息过少，暂时看不出来具体问题

**Comment by hanzhihua** [comment]
metric我查看过，数据都是比较正常，最大耗时都是<50ms,
所以我不确定大包是不是哪里有问题，还是我的配置有问题，小包性能还是不错的>3w，也没有怎么消耗机器性能

至于mutilgroup,不太适合我的业务场景，我们同时只能有一个master对外提供工作，同时jraft我想以library方式使用

**Comment by fengjiachun** [comment]
相关信息贴出来看看

**Comment by fengjiachun** [comment]
还有机器配置，性能相关信息最好全一点

**Comment by hanzhihua** [comment]
[node_metrics.log.2019-11-02_14-48-33.txt](https://github.com/sofastack/sofa-jraft/files/3800217/node_metrics.log.2019-11-02_14-48-33.txt)
[node_describe.log.2019-11-02_14-48-33.txt](https://github.com/sofastack/sofa-jraft/files/3800218/node_describe.log.2019-11-02_14-48-33.txt)
![EE7B6293-DD96-475F-88B1-B93715FFD09E](https://user-images.githubusercontent.com/1732108/68067407-61818f00-fd81-11e9-8706-7f1710671eff.png)
![image](https://user-images.githubusercontent.com/1732108/68067445-e1a7f480-fd81-11e9-8516-43b0ff16a3da.png)

这个是压测的时候系统情况，帮忙看看，出现下面的warn是不是正常
15:12:21.659 [jraft_test/10.69.76.19:33333-AppendEntriesThread0] WARN com.alipay.sofa.jraft.core.NodeImpl - Node <jraft_test/10.69.76.19:33333> reject term_unmatched AppendEntriesRequest from 10.69.76.22:33333, term=1, prevLogIndex=1982062, prevLogTerm=1, localPrevLogTerm=0, lastLogIndex=1982053, entriesSize=3.
15:12:21.659 [jraft_test/10.69.76.19:33333-AppendEntriesThread0] WARN com.alipay.sofa.jraft.core.NodeImpl - Node <jraft_test/10.69.76.19:33333> reject term_unmatched AppendEntriesRequest from 10.69.76.22:33333, term=1, prevLogIndex=1982065, prevLogTerm=1, localPrevLogTerm=0, lastLogIndex=1982053, entriesSize=3.
15:12:21.858 [jraft_test/10.69.76.19:33333-AppendEntriesThread0] WARN com.alipay.sofa.jraft.core.NodeImpl - Node <jraft_test/10.69.76.19:33333> reject term_unmatched AppendEntriesRequest from 10.69.76.22:33333, term=1, prevLogIndex=1983252, prevLogTerm=1, localPrevLogTerm=0, lastLogIndex=1983244, entriesSize=1.
15:12:21.858 [jraft_test/10.69.76.19:33333-AppendEntriesThread0] WARN com.alipay.sofa.jraft.core.NodeImpl - Node <jraft_test/10.69.76.19:33333> reject term_unmatched AppendEntriesRequest from 10.69.76.22:33333, term=1, prevLogIndex=1983253, prevLogTerm=1, localPrevLogTerm=0, lastLogIndex=1983244, entriesSize=1.

**Comment by hanzhihua** [comment]
下面是disk,network信息
![image](https://user-images.githubusercontent.com/1732108/68067522-f0db7200-fd82-11e9-869a-1f1dcc669ecf.png)
![image](https://user-images.githubusercontent.com/1732108/68067526-fcc73400-fd82-11e9-9ee6-a591b86ee8eb.png)

**Comment by fengjiachun** [comment]
leader的 node_describe.log 没贴，你贴的是 follower 的

**Comment by fengjiachun** [comment]
你贴的metric和log不是同一时间段同一台机器，把三台都贴出来吧，贴同一时间段

**Comment by fengjiachun** [comment]
metric 是14:48的 截图是11:30的 日志貌似是昨天的 这个就不好排查了

**Comment by hanzhihua** [comment]
谢谢你辛苦的支持

同样的压力，昨天没有留下记录，今天重压了一下，是同样的warning
另外：你的benchmark是key,value都是16个字节的，没有其他报文大小的性能报告吗？
这个是leader的报告
[node_metrics.log.2019-11-02_14-40-47.txt](https://github.com/sofastack/sofa-jraft/files/3800260/node_metrics.log.2019-11-02_14-40-47.txt)
[node_describe.log.2019-11-02_14-40-47.txt](https://github.com/sofastack/sofa-jraft/files/3800261/node_describe.log.2019-11-02_14-40-47.txt)

下面是今天的Warning
![image](https://user-images.githubusercontent.com/1732108/68067988-7dd5f980-fd8a-11e9-8dbe-989dc9884107.png)

**Comment by hanzhihua** [comment]
我测试了一下小包，如果是小包的话，16字节，qps可以达到7w（iops 小包比大包高）

但大包不行，性能有点问题

另外：我发现日志量大的话，启动节点还会出现oom现象，或者在同步日志的时候也会出现oom现象

**Comment by fengjiachun** [comment]
机器配置？几core？ssd盘？ 16字节那个客户端是瓶颈一般，client要改为流式发送或者多个client

**Comment by fengjiachun** [comment]
自带benchmark程序发送字节大小是可调的，你可以调整一下

**Comment by fengjiachun** [comment]
日志 warn 的问题，比如这一条 `term=1, prevLogIndex=1982062, prevLogTerm=1, localPrevLogTerm=0, lastLogIndex=1982053, entriesSize=3`
表示这个 follower 节点的 logindex 落后了 1982062 - 1982053 = 9 条，并且当前的已经升了一个 term （从 0 -> 1），所以 follower 会拒绝日志并返回 leader 拒绝信息，leader 会将 logIndex 回退并重新发送，这里落后的不多，应该没什么问题

`RaftOptions.maxBodySize` 默认值是 512k，日志复制的最大 body size 受它控制，你测试 10k 的场景可以适当调大

10k 的我看 qps 大概不到 6000， 也问下你的 client 是怎样的？是同步发送还是异步发送或是 stream 式的？ 6000 * 10k = 60m/s ? 千兆网卡才 120m/s 左右，有没有 tsar 或者 sar 看下 tcp retran？重传率高不高？

**Comment by fengjiachun** [comment]
> 我测试了一下小包，如果是小包的话，16字节，qps可以达到7w（iops 小包比大包高）
> 
> 但大包不行，性能有点问题
> 
> 另外：我发现日志量大的话，启动节点还会出现oom现象，或者在同步日志的时候也会出现oom现象

oom 这个你要分析一下 gc 或者 dump 看看哪些对象过多导致 oom

**Comment by hanzhihua** [comment]
我的压测机的性能没有问题，我是开30个线程，同步发请求过去的，超时时间1s，报文为空，服务端收到请求，生成10k的数据日志来做同步
这个是客户端的数据：
![image](https://user-images.githubusercontent.com/1732108/68069186-b0d2ba00-fd97-11e9-8e26-cfeba7fa6814.png)

follower节点出现大量的下列日志
17:38:46.054 [archer_control_test/10.69.76.22:33333-AppendEntriesThread0] WARN  com.alipay.sofa.jraft.core.NodeImpl - Node <archer_control_test/10.69.76.22:33333> reject term_unmatched AppendEntriesRequest from 10.69.76.19:33333, term=1, prevLogIndex=760467, prevLogTerm=1, localPrevLogTerm=0, lastLogIndex=760454, entriesSize=2.
17:38:46.073 [archer_control_test/10.69.76.22:33333-AppendEntriesThread0] WARN  com.alipay.sofa.jraft.core.NodeImpl - Node <archer_control_test/10.69.76.22:33333> reject term_unmatched AppendEntriesRequest from 10.69.76.19:33333, term=1, prevLogIndex=760723, prevLogTerm=1, localPrevLogTerm=0, lastLogIndex=760721, entriesSize=2.
17:38:46.474 [archer_control_test/10.69.76.22:33333-AppendEntriesThread0] WARN  com.alipay.sofa.jraft.core.NodeImpl - Node <archer_control_test/10.69.76.22:33333> reject term_unmatched AppendEntriesRequest from 10.69.76.19:33333, term=1, prevLogIndex=764638, prevLogTerm=1, localPrevLogTerm=0, lastLogIndex=764635, entriesSize=2.
17:38:46.476 [archer_control_test/10.69.76.22:33333-AppendEntriesThread0] WARN  com.alipay.sofa.jraft.core.NodeImpl - Node <archer_control_test/10.69.76.22:33333> reject term_unmatched AppendEntriesRequest from 10.69.76.19:33333, term=1, prevLogIndex=764647, prevLogTerm=1, localPrevLogTerm=0, lastLogIndex=764643, entriesSize=8.

最好一个节点出现了oom，测试就停止了
leader/follower机器性能都正常，硬盘都是ssd，iops<2000,正常工作可以达5000

问题：如果没有leader切换，出现follower出现上面Warn原因是什么呢？
另外一个是为什么会出现节点oom,logentry里面的data什么时候释放呢？

**Comment by fengjiachun** [comment]
上面已经回答你了，我的问题也请回答一下，多少个core

**Comment by fengjiachun** [comment]
另外 client 线程继续调大吧 同步调用可能有些小 jvm heap 大小这些也都麻烦说下

**Comment by hanzhihua** [comment]
不好意思，没有看到，机器都是32core,256G的,网卡是Speed: 20000Mb/s
leader/follower我指定是4G  -Xms4G -Xmx4G  -Djraft.closure.threadpool.size.max=300

我发现好像都是follower oom

17:37:12.578 [jraft_test_control_test/10.69.76.20:33333-AppendEntriesThread0] WARN  com.alipay.sofa.jraft.core.NodeImpl - Node <jraft_test_control_test/10.69.76.20:33333> reject term_unmatched AppendEntriesRequest from 10.69.76.19:33333, term=1, prevLogIndex=166001, prevLogTerm=1, localPrevLogTerm=0, lastLogIndex=157164, entriesSize=205.
17:37:12.596 [jraft_test_control_test/10.69.76.20:33333-AppendEntriesThread0] WARN  com.alipay.sofa.jraft.core.NodeImpl - Node <jraft_test_control_test/10.69.76.20:33333> reject term_unmatched AppendEntriesRequest from 10.69.76.19:33333, term=1, prevLogIndex=166206, prevLogTerm=1, localPrevLogTerm=0, lastLogIndex=157164, entriesSize=205.
17:37:12.899 [jraft_test_control_test/10.69.76.20:33333-AppendEntriesThread0] WARN  com.alipay.sofa.jraft.core.NodeImpl - Node <jraft_test_control_test/10.69.76.20:33333> reject term_unmatched AppendEntriesRequest from 10.69.76.19:33333, term=1, prevLogIndex=166411, prevLogTerm=1, localPrevLogTerm=0, lastLogIndex=157164, entriesSize=205.
17:37:13.189 [jraft_test_control_test/10.69.76.20:33333-AppendEntriesThread0] WARN  com.alipay.sofa.jraft.core.NodeImpl - Node <jraft_test_control_test/10.69.76.20:33333> reject term_unmatched AppendEntriesRequest from 10.69.76.19:33333, term=1, prevLogIndex=166616, prevLogTerm=1, localPrevLogTerm=0, lastLogIndex=157164, entriesSize=205.
17:37:13.644 [jraft_test_control_test/10.69.76.20:33333-AppendEntriesThread0] WARN  com.alipay.sofa.jraft.core.NodeImpl - Node <jraft_test_control_test/10.69.76.20:33333> reject term_unmatched AppendEntriesRequest from 10.69.76.19:33333, term=1, prevLogIndex=166821, prevLogTerm=1, localPrevLogTerm=0, lastLogIndex=157164, entriesSize=205


Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "JRaft-LogManager-Disruptor-0"
Exception in thread "JRaft-ElectionTimer" java.lang.OutOfMemoryError: GC overhead limit exceeded

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "ReadOnlyService-PendingNotify-Scanner0"
Exception in thread "Rpc-netty-server-worker-1-thread-1" java.lang.OutOfMemoryError: GC overhead limit exceeded
Exception in thread "AsyncLoggerConfig-1" java.lang.OutOfMemoryError: GC overhead limit exceeded 

有一个疑问是，如果follower拒绝的话的，leader应该会调整prevLogIndex,应该变小，而上面的一直在变大，而follower 的lastLogIndex一直没有变化

**Comment by fengjiachun** [comment]
你这个机器配置有些过于牛逼，为什么jvm heap 给这么小？如果要在小 heap 测试的话需要让 jraft 以为系统没有那么多 core，utils 类中前几行有个system property 可以配置一下 core num（手机回复记不住具体key了），因为jraft很多线程池数量是参考 core num 的 ，你机器的 core 太多 heap又太小

**Comment by fengjiachun** [comment]
另外我还是判断你的client是发送瓶颈，调大线程数试试

**Comment by fengjiachun** [comment]
1. 启动参数加上 -Djraft.available_processors=4
2. RaftOptions.maxBodySize=1024 * 1024
3. client 线程数继续调大

再试试

**Comment by hanzhihua** [comment]
测试过了，没有oom, 但客户端大量的超时，服务大量的reject，应该是预期的
可能我原来的heap设置，和线程不匹配，出现了oom

有一个疑问：
如果follower拒绝的话的，leader应该会调整prevLogIndex,应该变小，而日志上面的一直在变大，而follower 的lastLogIndex一直没有变化

**Comment by fengjiachun** [comment]
可以先调整 1 和 2，最后再逐步调整 3（client 线程数）

> 有一个疑问：
如果follower拒绝的话的，leader应该会调整prevLogIndex,应该变小，而日志上面的一直在变大，而follower 的lastLogIndex一直没有变化

leader 会将 logIndex 回退并重新发送的，你看到上面的日志没有回退的原因大概率是因为 jraft 对日志发送实现了 pipeline 优化，没有等到每个 AppendEntries 的 response， 一系列后续的 log 就突突突全发过去了 ：），所以你才会看到的日志里没有回退 index

**Comment by killme2008** [comment]
性能相关参数除了 JVM 之外（ heap, GC etc.) ，其他参数建议看下  9.1 节

https://www.sofastack.tech/projects/sofa-jraft/jraft-user-guide/
