### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by mona-lisa-octo-cat** [sofastack/sofa-jraft#329]
### Your question

Describe your question clearly

### Your scenes

Describe your use scenes (why need this feature)

### Your advice

Describe the advice or solution you'd like

### Environment

- SOFAJRaft version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by fengjiachun** [comment]
？
