### ISSUE TITLE
logsInMemory needs a more appropriate deque

### ISSUE THREAD

**Issue by fengjiachun** [sofastack/sofa-jraft#335]
### Your question

LogManagerImpl#logsInMemory needs a more appropriate deque, now the `remove range` operation cause data movement

### Environment

- SOFAJRaft version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by masaimu** [comment]
The motivation is optimizing performance? Or it leads to bug?

**Comment by fengjiachun** [comment]
> The motivation is optimizing performance? Or it leads to bug?

for perf

**Comment by fengjiachun** [comment]
TODO:
Impl a double-ended queue implemented with a growable ring buffer, we can refer `VecDeque` in rust https://github.com/rust-lang/rust/blob/master/src/liballoc/collections/vec_deque.rs

**Comment by SteNicholas** [comment]
@fengjiachun How much performance improvement with this queue？

**Comment by fengjiachun** [comment]
> @fengjiachun How much performance improvement with this queue？

remove range will not cause data movement

**Comment by killme2008** [comment]
I am working on this feature.
