### ISSUE TITLE
[RheaKVStore] is there any API support of ceilingEntry or ceiling key search?

### ISSUE THREAD

**Issue by JerryYangSH** [sofastack/sofa-jraft#340]
### Your question
Is there any API to support ceilingEntry or ceilling key on RheaKVStore? Ceilling key means the least key greater than or equal to the given key.

Describe your question clearly

### Your scenes
I want to have an interface/API to do prefix scan.  I see there are some APIs about get/scan/iterator, 
it looks they are exact key matching, not prefix matching. 
Describe your use scenes (why need this feature)

### Your advice

Describe the advice or solution you'd like

### Environment

- SOFAJRaft version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by killme2008** [comment]
The scan/iterator can be used as prefix matching, you can try it.

I don't think we need more new APIs.

**Comment by JerryYangSH** [comment]
> The scan/iterator can be used as prefix matching, you can try it.
> 
> I don't think we need more new APIs.

yes, you're right. I figured it out later that I can wrap it by scan/iterator to implement ceilling. but how about reversed scan?

**Comment by killme2008** [comment]
@fengjiachun  It  looks that rheakv doesn't support scan in reverse order, we should support it.

**Comment by masaimu** [comment]
Maybe I can evaluate and offer it.

**Comment by fengjiachun** [comment]
> The performance of reversed iterating is usually much worse than forward iterating. There are various reasons for that: 1. delta encoding in data blocks is more friendly to Next(); 2. the skip list used in the memtable is single-direction, so Prev() is another binary search; 3. the internal key order is optimized for Next().

https://github.com/facebook/rocksdb/wiki/RocksDB-FAQ

Rocksdb 's reversed iterating is usually much worse than forward iterating, but we can still provide a reverse iterating.

@masaimu can you send a PR for this？

**Comment by masaimu** [comment]
@fengjiachun OK 👌

**Comment by fengjiachun** [comment]
any progress? @masaimu

**Comment by shibd** [comment]
##  scan in reverse example

### data
```
keys={"10", "101", "102", "111", "223", "323"} 
```

### input
`reScan(startKey="3", toKey="10")`

### output
`{"323", "223", "111"} `


上面描述的反向扫描是否正确？

**Comment by fengjiachun** [comment]
> ## scan in reverse example
> ### data
> ```
> keys={"10", "101", "102", "111", "223", "323"} 
> ```
> 
> ### input
> `reScan(startKey="3", toKey="10")`
> 
> ### output
> `{"323", "223", "111"} `
> 
> 上面描述的反向扫描是否正确？

是按照 byte order 的，参考这个 [comparator ](https://github.com/sofastack/sofa-jraft/blob/master/jraft-core/src/main/java/com/alipay/sofa/jraft/util/BytesUtil.java#L112)

**Comment by shibd** [comment]
> 是按照 byte order 的，参考这个 [comparator](https://github.com/sofastack/sofa-jraft/blob/master/jraft-core/src/main/java/com/alipay/sofa/jraft/util/BytesUtil.java#L112)

谢谢，我想先对`MemoryRawKVStore`实现 `reverseScan`方法。这个字典升序的`comparator`构建的跳表Map应该不能在`reverseScan`方法中使用。可能要实现一个字典降序的`comparator`来构建SkipMap

我想先确认清楚，reverseScan的方法的功能，比如下面描述的案例中，`output`正确吗。

## 纠正案例
### data
```
keys={"10", "101", "102", "111", "223", "323"} 
```

### input
`reScan(startKey="3", toKey="102")`

### output
`{"323", "223", "111"} `

**Comment by shibd** [comment]
> > ## scan in reverse example
> > ### data
> > ```
> > keys={"10", "101", "102", "111", "223", "323"} 
> > ```
> > 
> > 
> > ### input
> > `reScan(startKey="3", toKey="10")`
> > ### output
> > `{"323", "223", "111"} `
> > 上面描述的反向扫描是否正确？
> 
> 是按照 byte order 的，参考这个 [comparator](https://github.com/sofastack/sofa-jraft/blob/master/jraft-core/src/main/java/com/alipay/sofa/jraft/util/BytesUtil.java#L112)

收到，谢谢~

**Comment by shibd** [comment]
我在尝试支持`reverse in scan`，我在`RawKVStore`中新增了`reverseScan`接口

```
    /**
     * startKey > endKey
     */
    void reverseScan(final byte[] startKey, final byte[] endKey, final KVStoreClosure closure);
```

同时支持`线性一致读`和`多分区扫描`都需要增加`reverseScan`的逻辑。我发现这样实现不太好。

我可以在原有的 `scan`接口上实现，当 `startKey > endKey`时，就命中`reverse scan`逻辑吗？这样就不用新增接口了。

**Comment by fengjiachun** [comment]
欢迎参与 jraft，我个人还是倾向于增加新的 reverseScan 接口，职责单一更清晰

**Comment by shibd** [comment]
好的，谢谢，我按新增接口的方式先实现一版。
