### ISSUE TITLE
HashedWheelTimer中的waitForNextTick()方法导致cpu占用过高

### ISSUE THREAD

**Issue by ChengYongchao** [sofastack/sofa-jraft#344]
### Describe the bug
启动AtomicServer，后台启动了四个进程执行waitForNextTick()方法，我的windows系统电脑8g，每个进程会占用8%的cpu，调试代码发现对windows进行的特殊处理
```java
                if (Platform.isWindows()) {
                    sleepTimeMs = sleepTimeMs / 10 * 10;
                }
               try {
                    Thread.sleep(sleepTimeMs);
                } catch (InterruptedException ignored) {
                    if (workerStateUpdater.get(HashedWheelTimer.this) == WORKER_STATE_SHUTDOWN) {
                        return Long.MIN_VALUE;
                    }
                }

```
执行前 sleepTimeMs = 1 执行后 sleepTimeMs = 0。 这种行为导致thread.sleep(sleepTimeMs)没有达到睡眠的效果，死循环速度太快，cpu飙升。
在查看了https://github.com/netty/netty/issues/356 问题后 发现这是对nettybug的处理，那么为什么现在有这个问题呢？是jvm的问题吗，我用的是jdk1.8。

- SOFAJRaft version:master
- JVM version (e.g. `java -version`):1.8
- OS version (e.g. `uname -a`):window10
- Maven version:
- IDE version:idea

**Comment by masaimu** [comment]
[ISSUE 311](https://github.com/sofastack/sofa-jraft/issues/311#issuecomment-546194869) 中讨论过这个问题，不过现在代码中还没有修复

**Comment by fengjiachun** [comment]
@masaimu 贡献一个 pr 来 fix 这个问题？

**Comment by ChengYongchao** [comment]
我在参考https://github.com/sofastack/sofa-jraft/issues/311#issuecomment-546194869后，将语句改为
```java
 if (Platform.isWindows() && sleepTimeMs > 10) {
                    sleepTimeMs = sleepTimeMs / 10 * 10;
                }
```
后，可以正常使用了，那么这个问题什么时候修复呢？

**Comment by masaimu** [comment]
@ChengYongchao 我们争取在下一个版本里解决这个问题。

**Comment by ChengYongchao** [comment]
好

**Comment by fengjiachun** [comment]
@ChengYongchao 月底之前会发布一个版本，这个会 fix 掉

**Comment by ChengYongchao** [comment]
@fengjiachun  明白了
