### ISSUE TITLE
心跳机制

### ISSUE THREAD

**Issue by ChengYongchao** [sofastack/sofa-jraft#346]
### Your question
心跳是只有leader发还是follower也会发
Describe your question clearly
我在官方文档中看到的关于心跳机制是这样的：
![B10PA%(@39F0KO`7)6`{ 21](https://user-images.githubusercontent.com/42292699/69207330-594f8f00-0b8a-11ea-9142-453d2ec04478.png)
故，我产生的理解是只有leader会发送心跳保证地位，follower只会被动接收（文档的其他部分也说了一旦成为follower就只会被动接收），在代码中我看到了这样的逻辑: 在becomeLeader()中会分别添加 follower's replicators 和  learner's replicators：
```java
 // Start follower's replicators
        for (final PeerId peer : this.conf.listPeers()) {
            if (peer.equals(this.serverId)) {
                continue;
            }
            LOG.debug("Node {} add a replicator, term={}, peer={}.", getNodeId(), this.currTerm, peer);
            if (!this.replicatorGroup.addReplicator(peer)) {
                LOG.error("Fail to add a replicator, peer={}.", peer);
            }
        }

        // Start learner's replicators
        for (final PeerId peer : this.conf.listLearners()) {
            LOG.debug("Node {} add a leaarner replicator, term={}, peer={}.", getNodeId(), this.currTerm, peer);
            if (!this.replicatorGroup.addReplicator(peer, ReplicatorType.Learner)) {
                LOG.error("Fail to add a leaarner replicator, peer={}.", peer);
            }
        }
```
在addReplicator(peer)方法中会调用 Replicator.start(opts, this.raftOptions)方法，最终在start()方法中执行了 r.startHeartbeatTimer(Utils.nowMs()); 
这样的意思是为每一个follower创建一个定时心跳Timer吗？如果是这样的话，leader为什么也添加了心跳Timer？ 后面有对应的处理机制?

**Comment by masaimu** [comment]
Replicator 是 leader 用来向 follower 和 learner 发送心跳和 logEntry 用的，每个 follower 对应一个，所以是在 leader 上添加和维护。
详情可参考 《[SOFAJRaft 日志复制 - pipeline 实现剖析 | SOFAJRaft 实现原理](https://www.sofastack.tech/blog/sofa-jraft-pipeline-principle/)》

**Comment by fengjiachun** [comment]
> 这样的意思是为每一个follower创建一个定时心跳Timer吗？如果是这样的话，leader为什么也添加了心跳Timer？ 后面有对应的处理机制?

注意这段代码把  leader 跳过去了

`
if (peer.equals(this.serverId)) {
                continue;
            }
`

**Comment by ChengYongchao** [comment]
@masaimu @fengjiachun 好的，了解了，感谢！
