### ISSUE TITLE
Upgrade jackson

### ISSUE THREAD

**Issue by fengjiachun** [sofastack/sofa-jraft#347]
### Your question

https://github.com/sofastack/sofa-jraft/network/alerts

### Environment

- SOFAJRaft version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by zongtanghu** [comment]
This issue can assign to me. @fengjiachun

**Comment by fengjiachun** [comment]
@zongtanghu It's yours
