### ISSUE TITLE
What's the function of statInfo in Replicator？

### ISSUE THREAD

**Issue by devYun** [sofastack/sofa-jraft#350]
### Your question

I don‘t find where use Replicator‘s statInfo，so isn't it useless？

### Your scenes

Describe your use scenes (why need this feature)

### Your advice

Describe the advice or solution you'd like

### Environment

- SOFAJRaft version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by killme2008** [comment]
It's used in `toString` for debug or statistics.
