### ISSUE TITLE
About NullPointerException in Recycles

### ISSUE THREAD

**Issue by devYun** [sofastack/sofa-jraft#353]
### Describe the bug

in Recycles class
about this judge  `h.stack.parent != this  ` in Multiple Thread Recycle  handle's stack can be null , so it will be NullPointerException
```java
    public final boolean recycle(T o, Handle handle) {
        if (handle == NOOP_HANDLE) {
            return false;
        }

        DefaultHandle h = (DefaultHandle) handle;
        
        if (h.stack.parent != this) {
            return false;
        }
        if (o != h.value) {
            throw new IllegalArgumentException("o does not belong to handle");
        }
        h.recycle();
        return true;
    }
```

and in Recycles inner class DefaultHandle   `thread == stack.thread`  stack can be null

```java
    public void recycle() {
        Thread thread = Thread.currentThread();
        if (thread == stack.thread) {
            stack.push(this);
            return;
        }
        // we don't want to have a ref to the queue as the value in our weak map
        // so we null it out; to ensure there are no races with restoring it later
        // we impose a memory ordering here (no-op on x86)
        WeakOrderQueue queue = delayedRecycled.get(stack);
        if (queue == null) {
            delayedRecycled.put(stack, queue = new WeakOrderQueue(stack, thread));
        }
        queue.add(this);
    }

```

### Environment

- SOFAJRaft version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by fengjiachun** [comment]
'stack' is  from ThreadLocal, it can not be null


`

private final ThreadLocal<Stack<T>> threadLocal = new ThreadLocal<Stack<T>>() {

        @Override
        protected Stack<T> initialValue() {
            return new Stack<>(Recyclers.this, Thread.currentThread(), maxCapacityPerThread);
        }
    };
`

Can you add some unit test to  prove this？

**Comment by devYun** [comment]
> `stack` is from ThreadLocal, it can not be null
> 
> ```
>     private final ThreadLocal<Stack<T>> threadLocal = new ThreadLocal<Stack<T>>() {
>         @Override
>         protected Stack<T> initialValue() {
>             return new Stack<>(Recyclers.this, Thread.currentThread(), maxCapacityPerThread);
>         }
>     };
> ```
> 
> Can you add some unit test to prove this？

I mean  in WeakOrderQueue#add in this block  `handle.stack = null;` , so in  handle's  stack  can be null

**Comment by fengjiachun** [comment]
> > `stack` is from ThreadLocal, it can not be null
> > ```
> >     private final ThreadLocal<Stack<T>> threadLocal = new ThreadLocal<Stack<T>>() {
> >         @Override
> >         protected Stack<T> initialValue() {
> >             return new Stack<>(Recyclers.this, Thread.currentThread(), maxCapacityPerThread);
> >         }
> >     };
> > ```
> > 
> > 
> > Can you add some unit test to prove this？
> 
> I mean in WeakOrderQueue#add in this block `handle.stack = null;` , so in handle's stack can be null

Do you mean to `recycle` more than one time?

**Comment by devYun** [comment]
> > > `stack` is from ThreadLocal, it can not be null
> > > ```
> > >     private final ThreadLocal<Stack<T>> threadLocal = new ThreadLocal<Stack<T>>() {
> > >         @Override
> > >         protected Stack<T> initialValue() {
> > >             return new Stack<>(Recyclers.this, Thread.currentThread(), maxCapacityPerThread);
> > >         }
> > >     };
> > > ```
> > > 
> > > 
> > > Can you add some unit test to prove this？
> > 
> > 
> > I mean in WeakOrderQueue#add in this block `handle.stack = null;` , so in handle's stack can be null
> 
> Do you mean to `recycle` more than one time?

yes
for a simple example ,like this:
```java
public class RecyclersTest {

    static final class RecyclableObject {

        private final Recyclers.Handle handle;

        private RecyclableObject(Recyclers.Handle handle) {
            this.handle = handle;
        }

        public Recyclers.Handle getHandle() {
            return handle;
        }
    }

    private static Recyclers<RecyclableObject> newRecyclers(final int max) {
        return new Recyclers<RecyclableObject>(max) {

            @Override
            protected RecyclableObject newObject(final Recyclers.Handle handle) {
                return new RecyclableObject(handle);
            }
        };
    }

    @Test
    public void simpleTestMultipleRecycleAtDifferentThread() throws InterruptedException {
        final Recyclers<RecyclableObject> recyclers = newRecyclers(512);
        final RecyclableObject object = recyclers.get();
        for (int i = 0; i <= 100; i++) {
            Thread thread = new Thread(() -> recyclers.recycle(object, object.handle));
            thread.start();
        }
      
        Thread.sleep(4000);
    }
}
```

**Comment by fengjiachun** [comment]
Get once recycle multiple times is not the correct usage，but we should fix this, can you send a pr?

**Comment by devYun** [comment]
> Get once recycle multiple times is not the correct usage，but we should fix this, can you send a pr?

yes， i will， which batch I push to ?

**Comment by fengjiachun** [comment]
push to master

**Comment by fengjiachun** [comment]
tks
