### ISSUE TITLE
 Does each Node occupy one port?

### ISSUE THREAD

**Issue by Artoriasn** [sofastack/sofa-jraft#354]
### Your question

What if the number of Nodes is very large?
Describe your question clearly

### Your scenes

Describe your use scenes (why need this feature)

### Your advice

Describe the advice or solution you'd like

### Environment

- SOFAJRaft version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by fengjiachun** [comment]
The rpc port is shared, A raft node identifier is `NodeId (groupId, peerId)`

**Comment by fengjiachun** [comment]
The rpc port is shared, A raft node identifier is `NodeId (groupId, peerId)`

**Comment by fengjiachun** [comment]
The rpc port is shared, A raft node identifier is `NodeId (groupId, peerId)`

**Comment by Artoriasn** [comment]
> peerId

`Endpoint addr = new Endpoint("localhost", 8080);
  String s = addr.toString(); // 结果为 localhost:8080
  boolean success = addr.parse(s);  // 可以从字符串解析出地址，结果为 true`

那对于peerId来说，Endpoint中的端口实际并没有被占用？

**Comment by fengjiachun** [comment]
> > peerId
> 
> `Endpoint addr = new Endpoint("localhost", 8080); String s = addr.toString(); // 结果为 localhost:8080 boolean success = addr.parse(s); // 可以从字符串解析出地址，结果为 true`
> 
> 那对于peerId来说，Endpoint中的端口实际并没有被占用？

https://github.com/sofastack/sofa-jraft/blob/master/jraft-core/src/main/java/com/alipay/sofa/jraft/RaftGroupService.java#L67

关键在于， rpcServer 是共享的，一个进程启动一个 rpcServer 即可，也就是说只需要一个端口，peerId 与 node 可以是一对多的关系，不是一对一关系，
对于 multi raft group 场景，nodeId 是 groupId+peerId 决定的，可以参考 rheakv 对 multi group 是如何支持的；
对于 single raft group 场景，你不大可能单机存在 'very large nodes'，就算真的存在，PeerId 中还有一个  idx 字段用于处理这种情况

**Comment by Artoriasn** [comment]
@fengjiachun 万分感谢，是我理解错误了。
