### ISSUE TITLE
Is it safe to acknowlege user request only after leader applied the log but not majority?

### ISSUE THREAD

**Issue by JerryYangSH** [sofastack/sofa-jraft#364]
### Your question
When I look into the code of jraft-rheakv, I noticed BallotBox.commitAt(lastCommittedIndex) will be triggerred on majority responses of LogAppend. Then it's applied into FSM, FSMCallerImpl.java#doApplyTasks(iterImpl),  The question is JRAFT Leader will invoke KVStoreClosure and call it done on leader applied, not on quorum nodes. What about apply failure on follower but only success on leader, and Leader transfer happened, is it still safe here on read request?

### Your scenes
Imaging a case ：
Raft group with 3 Members: A, B and C. A is the leader now (Term 1)
1. Put Request, LogEntry 1 append req is sent to  all nodes A, B, C
2. A,B both successed on AppendEntries request, C is iresponsive.
3. Leader committed with commit index = 1 since quorum replied including A itself.
4. LogEntry 1 is applied on FSM of A (Leader) only, while B C has failed to apply
5. Put Request is acked to client. User see this update is success.
6. A stuck, and leader election triggered and B is elected as new Leader since B has the latest log between B and C.
7. Read request comes and redirects to B (New Leader, Term 2).  Now B and C is alive.
8. Even by Read Index, B can not get the latest data in StateMachine.  Although B has latest log in log store, but not in FSM. As raft paper 3.6.2, new leader can not commit entries from previous terms. in this case, it means the log always stays in log store even it's commited by previous term, but not applied until new put request comes in this term. Saying there is no update IO then. If so, read will fail and this would break the rule of Linear Read Consistency.

Please correct me if I am wrong.

Describe your use scenes (why need this feature)

### Your advice

Describe the advice or solution you'd like

### Environment

- SOFAJRaft version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by killme2008** [comment]
When a node becomes leader, it will write a configuration change log and commit previous logs,
see 

https://github.com/sofastack/sofa-jraft/blob/master/jraft-core/src/main/java/com/alipay/sofa/jraft/core/NodeImpl.java#L1208

**Comment by JerryYangSH** [comment]
> When a node becomes leader, it will write a configuration change log and commit previous logs,
> see
> 
> https://github.com/sofastack/sofa-jraft/blob/master/jraft-core/src/main/java/com/alipay/sofa/jraft/core/NodeImpl.java#L1208

Is this violating the raft paper ?
"3.6.2 Committing entries from previous terms
As described in Section 3.5, a leader knows that an entry from its current term is committed once
that entry is stored on a majority of the servers. If a leader crashes before committing an entry,
future leaders will attempt to finish replicating the entry. However, a leader cannot immediately
conclude that an entry from a previous term is committed once it is stored on a majority of servers.
Figure 3.7 illustrates a situation where an old log entry is stored on a majority of servers, yet can
still be overwritten by a future leader"

**Comment by killme2008** [comment]
First of all,  the log is applied to state machine only if it's replicated(committed) to majority. So it doesn't volatile the raft alogirithm.

`BallotBox.commitAt` will ensure that the logs is replicated to majority nodes:

```java
  for (long logIndex = startAt; logIndex <= lastLogIndex; logIndex++) {
                final Ballot bl = this.pendingMetaQueue.get((int) (logIndex - this.pendingIndex));
                hint = bl.grant(peer, hint);
                if (bl.isGranted()) {
                    lastCommittedIndex = logIndex;
                }
            }
```

**Comment by JerryYangSH** [comment]
> First of all, the log is applied to state machine only if it's replicated(committed) to majority. So it doesn't volatile the raft alogirithm.
> 
> `BallotBox.commitAt` will ensure that the log is replicated to majority nodes:
> 
> ```java
>   for (long logIndex = startAt; logIndex <= lastLogIndex; logIndex++) {
>                 final Ballot bl = this.pendingMetaQueue.get((int) (logIndex - this.pendingIndex));
>                 hint = bl.grant(peer, hint);
>                 if (bl.isGranted()) {
>                     lastCommittedIndex = logIndex;
>                 }
>             }
> ```

Thanks for reply! but I think replicated doesn't mean 'committed', follower doesn't know whether it's committed or not, only leader knows.  
My understanding for JRAFT about my above cases is just ERROR out the read index request when new leader take effect before new leader accepts new udpate request. so the read could success on old leader but error with EAGAIN for client to retry... 
`
 if (this.logManager.getTerm(lastCommittedIndex) != this.currTerm) {
            // Reject read only request when this leader has not committed any log entry at its term
            closure
                .run(new Status(
                    RaftError.EAGAIN,
                    "ReadIndex request rejected because leader has not committed any log entry at its term, logIndex=%d, currTerm=%d.",
                    lastCommittedIndex, this.currTerm));
            return;
        }
`

**Comment by fengjiachun** [comment]
> Even by Read Index, B can not get the latest data in StateMachine. Although B has latest log in log store, but not in FSM. As raft paper 3.6.2, new leader can not commit entries from previous terms. in this case, it means the log always stays in log store even it's commited by previous term, but not applied until new put request comes in this term. Saying there is no update IO then. If so, read will fail and this would break the rule of Linear Read Consistency.

When B becomes the leader, it will write a configuration change log as the first log, so the previous log will be applied.

**Comment by JerryYangSH** [comment]
Thanks! I got it now.
