### ISSUE TITLE
How to implement key lease? Like etcd, monitor whether key timeout

### ISSUE THREAD

**Issue by zhangschunfeng** [sofastack/sofa-jraft#369]

**Comment by killme2008** [comment]
in rheakv?

I think it's easy to implement this feature, you can encode the lease info(touched `timestamp + lease`) into value, and check if it's valid ( `now - timestamp < lease`) when  you retrieve it from rheakv every time. And you must updated the lease info's timestamp when getting/updatting the value.

For monitoring whether the key is expired, you can keep a timer thread in rheakv server and store the monitored keys in memory. Checking the key is expired by iterate the key collection and check it's lease info is valid, send a  message to client if not.
