### ISSUE TITLE
In the case of Lease Read, is the electionTimeoutMs of all node must set to the same value?

### ISSUE THREAD

**Issue by htner** [sofastack/sofa-jraft#372]
### Your question
如果设置ReadOnlyLeaseBased 开启了Lease Read，
在Lease Read的情况下，是不是每个节点raftOptions的electionTimeoutMs应该设置为一致 ?

### Your scenes

1. 
Lease Read 的情况下, 如果electionTimeoutMs不设置为同样的值，大家的超时时间不一致，存在一种情况，新主可能会在旧主electionTimeoutMs前，就成为新的主

jraft的文档与相关的历史issue都读过，比如下面的issue
https://github.com/sofastack/sofa-jraft/issues/15
https://github.com/sofastack/sofa-jraft/issues/25

2.进一步讨论 
如果某些raft实现使用electionTimeoutMs来做优先级的做法，这时直接使用electionTimeoutMs实现Lease Read会出错。需要增加lease timeout, 使得 lease timeout小于任意一台机器的electionTimeoutMs.

### Your advice

只希望与大家讨论一下这个问题. 希望大家能指点下

### Environment

- SOFAJRaft version: 最新的

**Comment by killme2008** [comment]
需要一致的，也没有理由不一致。 如果需要运行时修改，可以调用 `Node#resetElectionTimeoutMs` 方法

**Comment by htner** [comment]
谢谢，回复真快
