### ISSUE TITLE
The sofa-jraft introduction document says that it supports asymmetric network partition tolerance. Why is it not seen in the code?

### ISSUE THREAD

**Issue by weingithub** [sofastack/sofa-jraft#374]
### Your question
sofa-jraft介绍文档说支持非对称网络分区容忍性，为何在代码中没看到体现？
好了好几遍NodeImpl.java中对pre_vote和request_vote的处理，似乎好像没有文档说的那种。
附上文档链接：
https://www.jianshu.com/p/59d3b4f7b21e

### Your scenes

Describe your use scenes (why need this feature)

### Your advice

Describe the advice or solution you'd like

### Environment

- SOFAJRaft version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by fengjiachun** [comment]
见：

https://github.com/sofastack/sofa-jraft/blob/master/jraft-core/src/main/java/com/alipay/sofa/jraft/core/NodeImpl.java#L1613

`isCurrentLeaderValid()`
