### ISSUE TITLE
关于NodeImpl 默认的构造方法

### ISSUE THREAD

**Issue by juaby** [sofastack/sofa-jraft#379]
### Your question

NodeImpl 默认的构造方法，参数NodeId如果等于null, 后续init时，会出现空指针吗

### Your scenes

Describe your use scenes (why need this feature)

### Your advice

Describe the advice or solution you'd like

### Environment

- SOFAJRaft version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by killme2008** [comment]
通常你不会用到这个方法，我们会考虑降低下访问级别。
