### ISSUE TITLE
metric 统计接口化

### ISSUE THREAD

**Issue by killme2008** [sofastack/sofa-jraft#38]
允许可插拔的 metric 类库接入，默认是 dropwizard，用户可实现该接口提供其他实现，如 micrometer 等。

**Comment by SteNicholas** [comment]
@fengjiachun 我先认领下，在8月份完成。

**Comment by fengjiachun** [comment]
这个 issue 我觉得还是先关闭了，接口化看起来不是一个最好最合适的思路

@SteNicholas 的 PR 我看了下，接口化实现的足够好，但用户要扩展的话仍然避免不了要扩展十几个类，并且给出的 api 还不一定全部满足其他 metric 类库
在性能上，也产生了太多包装对象，这一点更是不太容易接受

我更倾向于做一个 reporter adapter 直接去转换统计报告，比如这是一个 dropwizard 转 prometheus 的工具： https://www.robustperception.io/exposing-dropwizard-metrics-to-prometheus
