### ISSUE TITLE
选举例子 注释笔误

### ISSUE THREAD

**Issue by juaby** [sofastack/sofa-jraft#383]
### Your question

启动 3 个实例选举, 注意如果实在同一台机器启动多个实例, 那么第一个参数 dataPath 不能相同

### Your scenes

Describe your use scenes (why need this feature)

### Your advice
实在 = 是在

### Environment

- SOFAJRaft version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by fengjiachun** [comment]
多谢，我改一下
