### ISSUE TITLE
Does the startup sequence of the Node RPC Server service and the election service affect the election?

### ISSUE THREAD

**Issue by juaby** [sofastack/sofa-jraft#384]
### Your question

com/alipay/sofa/jraft/RaftGroupService.java:130
```
        this.node = RaftServiceFactory.createAndInitRaftNode(this.groupId, this.serverId, this.nodeOptions);
        if (startRpcServer) {
            this.rpcServer.start();
        } else {
            LOG.warn("RPC server is not started in RaftGroupService.");
        }
```
### Your advice

Node RPC Server服务和选举服务启动先后顺序是否对选举产生影响？

### Environment

- SOFAJRaft version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by killme2008** [comment]
不会有什么影响， rpc 暂时不可用，会继续重试，理论上只是加大了选举的延迟时间。
