### ISSUE TITLE
Examples about priority-based semi-deterministic leader election for users.

### ISSUE THREAD

**Issue by zongtanghu** [sofastack/sofa-jraft#389]
### Your question

SOFAJRaft has already supportted priority-based semi-deterministic leader election in the version of 1.3.0.But it didn't updated its example codes for users.

### Your scenes

So, I think we can provide some examples for priority-based semi-deterministic leader election for users.

### Your advice

In the example module, we can provide some examples about priority-based semi-deterministic leader election.

### Environment

- SOFAJRaft version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by killme2008** [comment]
any progress?

**Comment by zongtanghu** [comment]
Sorry, this pr delayed, I will finish this pr in this week.


 原始邮件 
发件人: dennis zhuang<notifications@github.com>
收件人: sofastack/sofa-jraft<sofa-jraft@noreply.github.com>
抄送: Hu Zongtang<huzongtang@cmss.chinamobile.com>; Assign<assign@noreply.github.com>
发送时间: 2020年2月12日(周三) 16:57
主题: Re: [sofastack/sofa-jraft] Examples about priority-basedsemi-deterministic leader election for users. (#389)


any progress?
