### ISSUE TITLE
LogStorage 实现数据和索引分离

### ISSUE THREAD

**Issue by killme2008** [sofastack/sofa-jraft#39]
通常类似 rocksdb/leveldb 都只适合做小的 key/value 存储，在 key/value 较大的时候，性能不是很理想。

目前 LogStorage 的默认实现是直接基于 Rocksdb  的 `RocksdbLogStorage` 实现，虽然用户可提供自己的实现，不过默认实现也有优化的余地：

1. 将日志按照 segment 方式的 append 添加，一定大小拆分文件(1G假设）。Segment 文件名为写入的第一条日志的 `log index`。
2. rocksdb 存储的 key 保持不变为 `log index`，而 value 从直接存储日志数据，修改为存储日志在 segment 中的偏移量 `(file_index, write_position)`，value 就可以缩小到 12 个字节`(8 + 4)`实现。
3. 对于 truncate 日志的实现也较为容易，可以直接按照 segment 粒度（依据 segment 文件名来定位）来删除，同时需要删除索引数据。这里需要涉及一些 recover 处理。
4. segment 的实现可以使用 mmap 和 group commit fsync 来提升性能。

**Comment by reenWYJ** [comment]
这样修改后,反而丧失leveldb的写入优势(顺序写),所以如果要设计为数据索引分离,可以更换索引的存储数据库为读性能更好的数据库

**Comment by pifuant** [comment]
可以深度改一下leveldb， 去掉merge过程， 形成memtable->sstable1->sstable2->...->sstableN自上而下多个level， 由于logStorage特殊性， 读更多的最新log数据， 可以尽量cache上面的sstable， 同时配合bloom filter， 可以很快定位到index， truncate时把index下面的sstable delete。

**Comment by killme2008** [comment]
1. 这样改并没有丧失 LSM 的写入优势，因为索引仍然是有序的，写入仍然是 batch 的，我们仍然需要利用 key 有序的特性。整个写入流程没有变化，只是将数据单独写了一份。leveldb 或者 rocksdb 对于较大 key/value 的写入性能是较差的，因为写入放大会很严重， compaction 会带来较大的性能影响，比如这篇[分析](http://idning.github.io/leveldb-rocksdb-on-large-value.html)。这样分离能更好的发挥它的性能优势，总体上肯定是有益的。
2. 更深度的定制还不需要，优化是渐进的。

**Comment by killme2008** [comment]
3. 读放大的问题目前在 raft 这个场景并不严重，因为绝大部分场景都是读最近最新写入的日志复制到 follower 或者应用到 state machine，而 jraft 已经在 `LogManger` 这一层做了内存缓存，几乎可以 100% 命中。在 snapshot 加载的场景中，也是顺序应用日志，这个场景如果 snapshot 间隔较大，并且日志较多，才可能遇到比较严重的读瓶颈。这个优化由于整体数据规模的缩小，对于 rocksdb 的顺序读也有好处。

**Comment by scanry** [comment]
jraft的log存储基于rocksdb实现，其实只需要存储某个窗口期的数据 未确认提交+已经提交的部分窗口。
历史的已提交的log可以下沉或者转移

**Comment by fengjiachun** [comment]
@scanry 我感觉你说的是和 snapshot 机制有重复的，snapshot 做完后就会将历史 log 做裁剪
@killme2008 说的我理解更多考虑还是将 rocksdb 中的大 value 拿出来单独存储，rocksdb 不擅长处理大 value，尤其在 compaction 的时候

**Comment by oatiz** [comment]
关于大`value`的处理, `pingcap`基于`rocksdb`做了一些优化,是否可以参考?

**Comment by pifuant** [comment]
@fengjiachun compaction对于log storage这种场景， 是多余的， 无论leveldb，还是rocksdb， compaction操作都占了很大比例系统开销。与其使用不太合适的工具， 不如根据场景， 造个新轮子， 以后也方便其他人用log storage, o(∩∩)o...哈哈

**Comment by killme2008** [comment]
@oatiz 感谢分享，我们学习下。

**Comment by fengjiachun** [comment]
不过话说按照这个方案实现相当于只是利用 rocksdb 做了个索引而已，索引的话，还需要 rocksdb 吗？不如直接剥离掉 rocksdb 了

**Comment by killme2008** [comment]
@fengjiachun 可以单独再造个轮子，但是造到最后很可能是另一个  rocksdb ，我们还是需要利用他的高效存取和有序特性。 rocksdb 用来存储索引这种小数据，compaction 的影响就可控了。这也是微信 phxpaxos 对于 leveldb 的使用方式。

**Comment by GrapeBaBa** [comment]
使用mmap会导致raft的safety问题吗？

**Comment by fengjiachun** [comment]
> 使用mmap会导致raft的safety问题吗？

只要同步刷盘就行
