### ISSUE TITLE
The master node does not send a heartbeat to the restarting node, causing the restarting node to always initiate voting

### ISSUE THREAD

**Issue by lnfdxwl** [sofastack/sofa-jraft#392]
三个节点的环境， node1，node2，node3，  启动成功过后，node1成为master， 此时重启 node2， node1 会迟迟不给 node2发送心跳，导致node2一直发起投票

**Comment by killme2008** [comment]
你说的现象无法重现，只要 leader 的 replicator 存在就会不停地尝试发心跳。

请增加更多的日志说明。

同时，你可以观测下 leader 的 metric

参考用户指南里的 11 节

https://www.sofastack.tech/projects/sofa-jraft/jraft-user-guide/

**Comment by killme2008** [comment]
没有更多反馈我们先关闭了，如果有补充可以再打开
