### ISSUE TITLE
Class PeerId Cached toString result incorrect.

### ISSUE THREAD

**Issue by ClownfishYang** [sofastack/sofa-jraft#393]
### Describe the bug
My is a sofa-jraft beginner，invoking PeerId the toString method discover result incorrect.

### Expected behavior
output result is a localhost:8080::1

### Actual behavior
localhost:8080

### Steps to reproduce
See the test code。

### Minimal yet complete reproducer code (or GitHub URL to code)
This is my test code.
`Endpoint addr = new Endpoint("localhost", 8080);
        PeerId peerId1 = new PeerId(addr, 0);
        System.out.println(peerId1.toString());
        peerId1.setPriority(1);
        System.out.println(peerId1.toString());
        PeerId peerId2 = new PeerId(addr, 0, 1);
        System.out.println(peerId2);`

### Environment
- SOFAJRaft version: master
- JVM version (e.g. `java -version`): 1.8
- OS version (e.g. `uname -a`): win7
- Maven version: 3.5.3
- IDE version: 2018.1

**Comment by fengjiachun** [comment]
It's a bug, thanks for your pr @ClownfishYang
