### ISSUE TITLE
when kv cluster with pd，Client getClusterInfo api always return null....

### ISSUE THREAD

**Issue by juaby** [sofastack/sofa-jraft#396]
com.alipay.sofa.jraft.rhea.DefaultPlacementDriverService#handleGetClusterInfoRequest
```java
   @Override
    public void handleGetClusterInfoRequest(final GetClusterInfoRequest request,
                                            final RequestProcessClosure<BaseRequest, BaseResponse> closure) {
        final long clusterId = request.getClusterId();
        final GetClusterInfoResponse response = new GetClusterInfoResponse();
        response.setClusterId(clusterId);
        if (!this.isLeader) {
            response.setError(Errors.NOT_LEADER);
            closure.sendResponse(response);
            return;
        }
        try {
            final Cluster cluster = this.metadataStore.getClusterInfo(clusterId);
            response.setCluster(cluster);
            response.setValue(cluster); //Client getValue to setCluster, and null
        } catch (final Throwable t) {
            LOG.error("Failed to handle: {}, {}.", request, StackTraceUtil.stackTrace(t));
            response.setError(Errors.forException(t));
        }
        closure.sendResponse(response);
    }
```

com.alipay.sofa.jraft.rhea.client.pd.DefaultPlacementDriverRpcService#internalCallPdWithRpc

```java
private <V> void internalCallPdWithRpc(final Endpoint endpoint, final BaseRequest request,
                                           final FailoverClosure<V> closure) {
        final String address = endpoint.toString();
        final InvokeContext invokeCtx = ExtSerializerSupports.getInvokeContext();
        final InvokeCallback invokeCallback = new InvokeCallback() {

            @Override
            public void onResponse(final Object result) {
                final BaseResponse<?> response = (BaseResponse<?>) result;
                if (response.isSuccess()) {
                    closure.setData(response.getValue()); //TODO here here here
                    closure.run(Status.OK());
                } else {
                    closure.setError(response.getError());
                    closure.run(new Status(-1, "RPC failed with address: %s, response: %s", address, response));
                }
            }

            @Override
            public void onException(final Throwable t) {
                closure.failure(t);
            }

            @Override
            public Executor getExecutor() {
                return rpcCallbackExecutor;
            }
        };
        try {
            this.rpcClient.invokeWithCallback(address, request, invokeCtx, invokeCallback, this.rpcTimeoutMillis);
        } catch (final Throwable t) {
            closure.failure(t);
        }
    }

```

**Comment by fengjiachun** [comment]
After receiving the first `StoreHeartbeat`, cluster info will no longer be null

com.alipay.sofa.jraft.rhea.client.pd.HeartbeatSender

**Comment by juaby** [comment]
PD Server:
final Cluster cluster = this.metadataStore.getClusterInfo(clusterId);
**response.setCluster(cluster**);

PD Client:
closure.setData(**response.getValue()**); //TODO here here here
closure.run(Status.OK());

**Comment by fengjiachun** [comment]
Please pay attention to my last reply, which has answered your question

In addition, you can run the following two test classes


com.alipay.sofa.jraft.rhea.PdServer
com.alipay.sofa.jraft.rhea.pd.RheaHeartbeatTest

**Comment by juaby** [comment]
> 
> 
> PD Server:
> final Cluster cluster = this.metadataStore.getClusterInfo(clusterId);
> **response.setCluster(cluster**); //Client getValue to setCluster, and null
> 
> PD Client:
> response.getValue() == null
> closure.setData(**response.getValue()**); //TODO here here here
> closure.run(Status.OK());

closed?

**Comment by fengjiachun** [comment]
> > PD Server:
> > final Cluster cluster = this.metadataStore.getClusterInfo(clusterId);
> > **response.setCluster(cluster**); //Client getValue to setCluster, and null
> > PD Client:
> > response.getValue() == null !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
> > closure.setData(**response.getValue()**); //TODO here here here
> > closure.run(Status.OK());
> 
> closed?

还有其他问题？在那个新的 issue 里说吧

**Comment by fengjiachun** [comment]
> > PD Server:
> > final Cluster cluster = this.metadataStore.getClusterInfo(clusterId);
> > **response.setCluster(cluster**); //Client getValue to setCluster, and null
> > PD Client:
> > response.getValue() == null !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
> > closure.setData(**response.getValue()**); //TODO here here here
> > closure.run(Status.OK());
> 
> closed?

还有其他问题？在那个新的 issue 里说吧
