### ISSUE TITLE
How to perceive elections and how to monitor JRAFT?

### ISSUE THREAD

**Issue by xiejiashuai** [sofastack/sofa-jraft#398]
你好， 我想问下使用SOFAJRaft如何感知到选举了，我们内部想使用这个来做选举，但是需要做一些监控，比如选举的次数以及选举原因，以及集群状态等

**Comment by killme2008** [comment]
对于 leader 来说，监听 `StateMachine#onLeaderStart` 即可，在里面做统计，对于 follower 就是 `StateMachine#onStartFollowing`。
建议先阅读下用户指南和例子。
