### ISSUE TITLE
The log log is always very large, almost 20G

### ISSUE THREAD

**Issue by hanzhihua** [sofastack/sofa-jraft#400]
### Your question

我使用snapshot机制，为什么log日志一直都很大？
当系统做了snapshot后，之前的日志会不会清除

### Environment

jdk 1.8
3台集群（jraft 版本1.2.6）
uname :4.9.0-0.bpo.6-amd64 #1 SMP Debian 4.9.88-1+deb9u1~bpo8+1 (2018-05-13) x86_64 GNU/Linux

**Comment by killme2008** [comment]
snapshot 会删除之前的日志，但是rocksdb 的删除是依赖 compaction 的，如果没有触发，不会立即降下来，可以再观察一段时间。

**Comment by hanzhihua** [comment]
但是感觉一个月前的log文件存在着，这个是否正常

**Comment by killme2008** [comment]
@hanzhihua 时间不足以为依据，建议再观察下。 另外你的 snapshot 间隔设置多大

**Comment by hanzhihua** [comment]
snapshot设置了1个小时

**Comment by killme2008** [comment]
可以再观察下，后续如果持续增大，我们再跟进看下。

**Comment by fengjiachun** [comment]
问题仍然没解决吗？ @hanzhihua

**Comment by zongtanghu** [comment]
@hanzhihua  I advice you to copy the related snapshot log file contents to here, it can help us to locate the really reason.Thanks.

**Comment by hanzhihua** [comment]
@fengjiachun 
问题已经缓解了，日志大小自动下去了，谢谢
