### ISSUE TITLE
What happens when a timeout occurs after a task is applied?

### ISSUE THREAD

**Issue by hecenjie** [sofastack/sofa-jraft#401]
Hi !
When I call `Node#apply(Task)` to submit a task to raft group, if the raft group times out and the logs are not copied to the majority, will it throw an exception or call back the task related `Closure#run(Status)`?

**Comment by killme2008** [comment]
```
will it throw an exception or call back the task related Closure#run(Status)
```

Maybe or maybe not.

So you can't count on this behaviour, if the request is timed out,the result is undefined, you should check the result by checking your state machine or  other mechanisms. It's the remote invocation semantics problem.

**Comment by fengjiachun** [comment]
Hi ，there is no timeout mechanism internal and I recommend handling it in the client

**Comment by fengjiachun** [comment]
Hi， there is no timeout mechanism internal and I recommend handling it in the client

**Comment by hecenjie** [comment]
Thanks for reply! 
Futher, is jraft guaranteed to call `Closure#run` and the `Status#isOk()` must be `true` if it succeeds?

**Comment by killme2008** [comment]
> Thanks for reply!
> Futher, is jraft guaranteed to call `Closure#run` and the `Status#isOk()` must be `true` if it succeeds?

yep, this guarantee is promised.

**Comment by hecenjie** [comment]
> > Thanks for reply!
> > Futher, is jraft guaranteed to call `Closure#run` and the `Status#isOk()` must be `true` if it succeeds?
> 
> yep, this guarantee is promised.

For timeout, will jraft choose to retry all the time, or can it give an upper bound of time?

**Comment by killme2008** [comment]
> > > Thanks for reply!
> > > Futher, is jraft guaranteed to call `Closure#run` and the `Status#isOk()` must be `true` if it succeeds?
> > 
> > 
> > yep, this guarantee is promised.
> 
> For timeout, will jraft choose to retry all the time, or can it give an upper bound of time?

If the log is copied to majority(committed), it will be retried to copy to other nodes when fails,it is an internal promise by raft.
In other cases, there is no retry at all, you can retry the request by your client. The rpc has some timeout settings, you can change them through `RpcOptions`:

```java
 /**
     * Rpc connect timeout in milliseconds
     * Default: 1000(1s)
     */
    private int            rpcConnectTimeoutMs        = 1000;

    /**
     * RPC request default timeout in milliseconds
     * Default: 5000(5s)
     */
    private int            rpcDefaultTimeout          = 5000;

```
