### ISSUE TITLE
Can node. apply provide synchronization

### ISSUE THREAD

**Issue by chuntaojun** [sofastack/sofa-jraft#404]
### Your question

Can node. apply provide synchronization

### Your scenes

Nacos had some problems with the overall code moving to asynchrony for a number of reasons and wanted to provide synchronous commit capability when using Jraft for transaction commit

### Your advice

Describe the advice or solution you'd like

### Environment

- SOFAJRaft version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by fengjiachun** [comment]
See #403, use it  like this：

```
Task task = new Task(data, new JoinableClosure(closure));
node.apply(task);
task.join();
```
