### ISSUE TITLE
how to make sure leader response?

### ISSUE THREAD

**Issue by zychappy** [sofastack/sofa-jraft#405]
### Your question

how to make sure leader response?
如何确保一定是leader响应请求而不是其他follower？

### Your scenes

客户端向集群发起请求，每个节点都可能收到该请求，如果当前节点不是leader，如何处理

**Comment by killme2008** [comment]
每个节点都能感知到当前的 leader 节点是哪个（ `StateMachine#onStartFollowing` )，如果当前节点不是，做一个转发应答将当前 leader 发给客户端，客户端更新路由信息重试即可，可以看下 counter 和 rheakv 客户端的例子。文档参见 9.2.3 节，客户端建议

https://www.sofastack.tech/projects/sofa-jraft/jraft-user-guide/
