### ISSUE TITLE
After the leader node submits the index, how to notify the follower to submit it

### ISSUE THREAD

**Issue by zsh1232** [sofastack/sofa-jraft#406]
leader节点执行完状态机，把这次的index提交之后，什么时候通知的follower节点也提交呢？ 我看现象是follower也立刻跟着提交了，但是这块代码没有找到。想问下具体是怎么实现的，谢谢~

**Comment by fengjiachun** [comment]
leader 会往 follower 发送 lastCommittedIndex， 详情见 

```
com.alipay.sofa.jraft.core.NodeImpl#handleAppendEntriesRequest
com.alipay.sofa.jraft.core.BallotBox#setLastCommittedIndex
```

**Comment by zsh1232** [comment]
thank you~

**Comment by zehonghuang** [comment]
挖一下坟哈～

lastCommittedIndex是由Replicator心跳定时提交的，最后在NodeImpl.FollowerStableClosure调用BallotBox.setLastCommittedIndex()，里面会继续调用状态机的onCommitted(lastCommittedIndex);最后触发follower的onApply方法。

**Comment by killme2008** [comment]
源码阅读可以参考这里的文章

https://github.com/sofastack/sofa-jraft/issues/327
