### ISSUE TITLE
Multi jraft Group CPU usage is high

### ISSUE THREAD

**Issue by Artoriasn** [sofastack/sofa-jraft#412]
### Your question

很抱歉我的英语不是很好，很难用英语准确描述我的问题。
目前我在单台机器上启动了十个进程，并且创建了40个 raft group .
运行过程中发现cpu负载偏高
我想请问一下目前我遇到的这个现象是否正常？
### Your scenes

Describe your use scenes (why need this feature)

### Your advice

Describe the advice or solution you'd like

### Environment

- SOFAJRaft version: 1.3.0
- JVM version (e.g. `java -version`):
![image](https://user-images.githubusercontent.com/48850755/78006297-63bb3a00-736f-11ea-8e15-6bf58c3e0509.png)

- OS version (e.g. `uname -a`):
![image](https://user-images.githubusercontent.com/48850755/78006442-99f8b980-736f-11ea-9104-537e79dfcac6.png)

- Maven version:
- IDE version:

**Comment by Artoriasn** [comment]
<img width="837" alt="WX20200331-132727@2x" src="https://user-images.githubusercontent.com/48850755/77990785-d4089200-7354-11ea-8a60-8b6384e9384b.png">
<img width="823" alt="WX20200331-132205@2x" src="https://user-images.githubusercontent.com/48850755/77990791-d66aec00-7354-11ea-92f6-bfc993bc2708.png">

**Comment by Artoriasn** [comment]
[jstack.txt](https://github.com/sofastack/sofa-jraft/files/4406959/jstack.txt)
这是其中一个进程线程堆栈

**Comment by Artoriasn** [comment]
<img width="1338" alt="WX20200331-135349@2x" src="https://user-images.githubusercontent.com/48850755/77991682-1b901d80-7357-11ea-83b7-a9b44c9c590b.png">

**Comment by killme2008** [comment]
估计就是定时器和心跳引起的，这块还没有特别优化，需要采用一些合并策略。

**Comment by fengjiachun** [comment]
@Artoriasn 中文没关系的，看来还是 hash 时间轮算法的定时器的问题 #311 ，需要优化一下

**Comment by Artoriasn** [comment]
> @Artoriasn 中文没关系的，看来还是 hash 时间轮算法的定时器的问题 #311 ，需要优化一下



> 估计就是定时器和心跳引起的，这块还没有特别优化，需要采用一些合并策略。

非常感谢。我遇到的这个问题比较棘手，现在集群规模大概300台左右，我们通过jraft来实现数据分片的选举，形成主副分片的自动协调。随着数据量上涨，集群内部会达到4000+以上的raft group。按目前内部讨论的情况来看，我们可能会放弃用jraft做leader选举，而是用jraft做一个类似于etcd的组件来协调管理集群上分片。

**Comment by fengjiachun** [comment]
@Artoriasn 请问你用的 jraft 版本是？

**Comment by Artoriasn** [comment]
> @Artoriasn 请问你用的 jraft 版本是？

1.3.0

**Comment by fengjiachun** [comment]
@Artoriasn  1.3.0 感觉问题不大，机器是多少 core ？ 是不是线程数太多了？
System properties 设置 jraft.available_processors=1
System.getProperties().setProperty("available_processors", 1)

**Comment by Artoriasn** [comment]
@fengjiachun 
<img width="837" alt="WX20200331-132727@2x" src="https://user-images.githubusercontent.com/48850755/77998475-bb53a880-7363-11ea-8376-5c3cc7f784c6.png">

我试着添加了配置，
`  System.getProperties().setProperty("jraft.available_processors", "1")
  System.getProperties().setProperty("available_processors", "1")`
<img width="866" alt="WX20200331-152538@2x" src="https://user-images.githubusercontent.com/48850755/77998603-eb9b4700-7363-11ea-8da1-b57447096c9c.png">

**Comment by fengjiachun** [comment]
抱歉我写错了，应该是 jraft.available_processors ，我看你也进行了修正，不过貌似调整没生效？ 因为看起来 cpu 没有下降？ 需要再 jraft 启动之前就设置

另外还是要再问下，是一共 10 个 java 进程，每个进程 40 个 group 还是 一共 40 个 gtoup？

最后，还有一个办法，调大 `com.alipay.sofa.jraft.option.NodeOptions#electionTimeoutMs` 的值（建议先调整到尽量大，先排除问题），降低心跳频率，40 个 group 默认 electionTimeoutMs/10 ms 一个心跳有些频繁

**Comment by Artoriasn** [comment]
@fengjiachun 

1. 我移除了jraft代码测试后发现cpu使用率降了下来，排除掉是因为我本身代码存在问题导致这个现象。
2. 在进程启动时我设置了如下参数，发现问题依旧存在
![image](https://user-images.githubusercontent.com/48850755/78005941-e1cb1100-736e-11ea-854c-26c3871be9c7.png)
3. 选举超时时间electionTimeoutMs 我设置为60s，发现问题依旧存在
4.
> 是一共 10 个 java 进程，每个进程 40 个 group 还是 一共 40 个 gtoup？
一共40个group

**Comment by fengjiachun** [comment]
@Artoriasn 
1. 可不可以再 jstack 看下每个进程里的线程数量？
2. 线程消耗 cpu 的 top n 可否给一下？ 可以使用 [arthas](https://alibaba.github.io/arthas/en/thread.html)

**Comment by fengjiachun** [comment]
@Artoriasn 可以关注这个 pr #414

**Comment by Artoriasn** [comment]
@fengjiachun 抱歉因为临时有其他事情插入进来，没有及时回复
这是完整的jstack信息
[jstack.log](https://github.com/sofastack/sofa-jraft/files/4418496/jstack.log)

<img width="1346" alt="WX20200402-095719@2x" src="https://user-images.githubusercontent.com/48850755/78203171-d12eae00-74c8-11ea-9ec3-a223d178f6d1.png">

**Comment by fengjiachun** [comment]
@Artoriasn 你可以用 `thread -n 20` 来查看最耗 cpu 的 top20 线程

以下是我要做的，我先这里记录下
TODO
1. share timeManager
2.

**Comment by fengjiachun** [comment]
下面优化后我自己电脑上的测试结果，启动 com.alipay.sofa.jraft.benchmark.server.BenchmarkServer ，
开启 24 个 raft group，只启动一个节点（为了触发各种定时器）

OS version (e.g. uname -a):  Darwin ali-83454.local 18.7.0 Darwin Kernel Version 18.7.0: Tue Aug 20 16:57:14 PDT 2019; root:xnu-4903.271.2~2/RELEASE_X86_64 x86_64

1. default:
![image](https://user-images.githubusercontent.com/3860496/78321884-c004a080-759f-11ea-9529-caf248803c28.png)

2. share timer:

```
NodeOptions#timerPoolSize=-1  // -1 mean use global scheduler pool
NodeOptions#sharedElectionTimer=true
NodeOptions#sharedVoteTimer=true
NodeOptions#sharedStepDownTimer=true
NodeOptions#sharedSnapshotTimer=true
```

![image](https://user-images.githubusercontent.com/3860496/78321897-ca269f00-759f-11ea-8326-e5d6e2e5fa19.png)
