### ISSUE TITLE
When does Replicator occur (inflight.seq! = QueuedPipelinedResponse.seq) the response sequence is out of order?

### ISSUE THREAD

**Issue by zehonghuang** [sofastack/sofa-jraft#416]
如题，感谢回答。

**Comment by fengjiachun** [comment]
通信层是异步的，req1，req2 出去 resp2，resp1 回来导致顺序错乱是一个正常现象（网络传输过程中， rpc 框架异步处理线程切换都可能导致顺序错乱）
你看到的那段代码是是 jraft 流水线复制的代码实现的一部分，另外还需要开启 `com.alipay.sofa.jraft.option.RaftOptions#replicatorPipeline `
JRaft 会绑定单个线程和绑定网络连接来尽量避免这种顺序颠倒的事件发生，但是仍然无法完全避免，比如连接断掉重新建连，切换了连接可能导致顺序错乱

**Comment by zehonghuang** [comment]
哈，我知道这部分在AppendEntriesRequestProcessor，但只是Follower处理AppendEntries请求才会调用，而且跟rpc深度绑定。

这里问的是Leader的Replicator什么场景会出现以下情况，
即满足 queuedPipelinedResponse.seq == r.requiredNextSeq 为true，
又满足 inflight.seq != queuedPipelinedResponse.seq 为true

上面的seq仅出现在`com.alipay.sofa.jraft.core.Replicator#onRpcReturned`

**Comment by fengjiachun** [comment]
> 哈，我知道这部分在AppendEntriesRequestProcessor，但只是Follower处理AppendEntries请求才会调用，而且跟rpc深度绑定。
> 
> 这里问的是Leader的Replicator什么场景会出现以下情况，
> 即满足 queuedPipelinedResponse.seq == r.requiredNextSeq 为true，
> 又满足 inflight.seq != queuedPipelinedResponse.seq 为true
> 
> 上面的seq仅出现在`com.alipay.sofa.jraft.core.Replicator#onRpcReturned`

所以问题可以简化为  `inflight.seq != r.requiredNextSeq` ？可以看下 `onAppendEntriesReturned` 或 `onInstallSnapshotReturned` 方法吧，理论上出现 `resetInflights` 的时候都会导致  `inflight.seq != r.requiredNextSeq`

**Comment by zehonghuang** [comment]
好的，感谢答疑，我再看看
