### ISSUE TITLE
Repeated start will not write logs and cause an exception at the next startup

### ISSUE THREAD

**Issue by hecenjie** [sofastack/sofa-jraft#419]
### Your question

我启动了三个 Server，其中 Server1 作为 Leader，而 Server2 与 Server3 作为 Follower，并且整个实验过程中没有进行任何数据读写操作，仅仅是开启和关闭 Server。

在每个节点都成功启动后，jraft 都会首先调用到`onSnapshotLoad`方法和`onSnapshotSave`方法读取和保存快照。这时候我将 Server3 重启，发现仅仅调用了`onSnapshotLoad`方法，即使在`snapshotIntervalSecs`时间后也不会再调用`onSnapshotSave`方法保存快照，因此如果这时候我再次重启 Server3，那么就会因为上一次没有写入快照而抛出以下异常：
```
11:41:27.103 [main] WARN  com.alipay.sofa.jraft.storage.snapshot.local.LocalSnapshotStorage - No data for snapshot reader /Users/server3/raft/snapshot.
11:41:27.106 [main] ERROR com.alipay.sofa.jraft.core.NodeImpl - Node <server/127.0.0.1:8989> is initialized with inconsistent log, status=Status[EIO<1014>: Missing logs in (0, 2)].
Exception in thread "main" java.lang.IllegalStateException: Fail to init node, please see the logs to find the reason.
	at com.alipay.sofa.jraft.RaftServiceFactory.createAndInitRaftNode(RaftServiceFactory.java:48)
	at com.alipay.sofa.jraft.RaftGroupService.start(RaftGroupService.java:129)
	at com.alipay.sofa.jraft.RaftGroupService.start(RaftGroupService.java:107)
        // ...
```

我的数据一致性是由 jraft 全权管理的，也就是说每次启动时都会将状态机数据清除，而保留 jraft 相关的所有数据。加载快照的具体实现与 RheaKV 类似通过`snapshotFile.renameTo(dbFile)`完成。

我不确定这是 jraft 自身的 bug 还是我对其的使用存在什么问题？

### Environment

- SOFAJRaft version: 1.3.0
- JVM version (e.g. `java -version`): 1.8
- OS version (e.g. `uname -a`): macOS
- Maven version:
- IDE version:

**Comment by killme2008** [comment]
快照不执行，也不会报这个错误的，这个错误是因为日志被损坏了，丢了 [0, 2] 的日志，是不是意外修改了 jraft 的 log 目录里文件。

**Comment by hecenjie** [comment]
> 快照不执行，也不会报这个错误的，这个错误是因为日志被损坏了，丢了 [0, 2] 的日志，是不是意外修改了 jraft 的 log 目录里文件。

关闭快照功能后是不会有这个错误的。我认为这个错误的原因在于第一次保存快照时，[0, 2] 的日志被 jraft 合法删除了，然而在第一次重启过后将快照加载，却没有再保存快照，导致在第二次重启时既没有 [0, 2]  的快照文件，也没有 [0, 2]  的日志，也就发生了异常。所以让我疑惑的是，为什么在重启后却不会再保存快照？

**Comment by fengjiachun** [comment]
你删除快照了吗？

**Comment by hecenjie** [comment]
> 你删除快照了吗？

快照加载我与 RheaKV 一样是通过`snapshotFile.renameTo(dbFile)`实现的，所以是删除了的。

**Comment by fengjiachun** [comment]
> > 你删除快照了吗？
> 
> 快照加载我与 RheaKV 一样是通过`snapshotFile.renameTo(dbFile)`实现的，所以是删除了的。

rheakv 不删快照， rename 的是解压缩后的目录，原始文件保留着的

**Comment by hecenjie** [comment]
> > > 你删除快照了吗？
> > 
> > 
> > 快照加载我与 RheaKV 一样是通过`snapshotFile.renameTo(dbFile)`实现的，所以是删除了的。
> 
> rheakv 不删快照， rename 的是解压缩后的目录，原始文件保留着的

您是指这一段rename的是解压缩后的目录吗：
```java
// RocksRawKVStore
    void writeSnapshot(final String snapshotPath) {
        final Timer.Context timeCtx = getTimeContext("WRITE_SNAPSHOT");
        final Lock writeLock = this.readWriteLock.writeLock();
        writeLock.lock();
        try (final Checkpoint checkpoint = Checkpoint.create(this.db)) {
            final String tempPath = snapshotPath + "_temp";
            final File tempFile = new File(tempPath);
            FileUtils.deleteDirectory(tempFile);
            checkpoint.createCheckpoint(tempPath);
            final File snapshotFile = new File(snapshotPath);
            FileUtils.deleteDirectory(snapshotFile);
            if (!tempFile.renameTo(snapshotFile)) {
                throw new StorageException("Fail to rename [" + tempPath + "] to [" + snapshotPath + "].");
            }
        } catch (final StorageException e) {
            throw e;
        } catch (final Exception e) {
            throw new StorageException("Fail to write snapshot at path: " + snapshotPath, e);
        } finally {
            writeLock.unlock();
            timeCtx.stop();
        }
    }
```

**Comment by fengjiachun** [comment]
> ```java
> readSnapshot
> ```

是的，snapshotPath 是解压缩后的目录，压缩文件还留着，只有在新的 save snapshot 完成时才可以删除上一个 snapshot 文件

**Comment by fengjiachun** [comment]
load snapshot 完整逻辑你应该参考 com.alipay.sofa.jraft.rhea.storage.AbstractKVStoreSnapshotFile#load

**Comment by hecenjie** [comment]
明白了，感谢 : )
