### ISSUE TITLE
The leader encountered an invalid log problem

### ISSUE THREAD

**Issue by hanzhihua** [sofastack/sofa-jraft#426]
Your question：
**leader** 出现了这样的错误日志：
2020-04-20 16:35:44.895 WARN  leader [JRaft-NodeImpl-Disruptor-0]-c.a.s.j.storage.impl.LogManagerImpl.checkAndResolveConflict - Received entries of which the firstLog=4244932970,lastLog=0 is not greater than appliedIndex=4244932969, return immediately with nothing changed.

我以前也出现这样的错误，我修改一下代码，加上了一下异常信息，可以判断出错误入口是Node.apply(final Task task)，节点是leader.

我看到到代码是这样写的
```
private class LogEntryAndClosureHandler implements EventHandler<LogEntryAndClosure> {
        // task list for batch
        private final List<LogEntryAndClosure> tasks = new ArrayList<>(NodeImpl.this.raftOptions.getApplyBatch());

        @Override
        public void onEvent(final LogEntryAndClosure event, final long sequence, final boolean endOfBatch)
                                                                                                          throws Exception {
            if (event.shutdownLatch != null) {
                if (!this.tasks.isEmpty()) {
                    executeApplyingTasks(this.tasks);
                }
                final int num = GLOBAL_NUM_NODES.decrementAndGet();
                LOG.info("The number of active nodes decrement to {}.", num);
                event.shutdownLatch.countDown();
                return;
            }

            this.tasks.add(event);
            if (this.tasks.size() >= NodeImpl.this.raftOptions.getApplyBatch() || endOfBatch) {
                executeApplyingTasks(this.tasks);
                this.tasks.clear();
            }
        }
    }
```
**如果executeApplyingTasks(this.tasks);出错，那么后续的tasks.clear()就不会被执行，那么Task里面的logentry的index就有可能被设置了**，不知道是不是问题，请赐教

Environment
jdk 1.8
3台集群（jraft 版本1.2.6）
uname :4.9.0-0.bpo.6-amd64 #1 SMP Debian 4.9.88-1+deb9u1~bpo8+1 (2018-05-13) x86_64 GNU/Linux

**Comment by killme2008** [comment]
这里的核心是你的 apply 怎么实现，如果 apply 出现异常，整个状态机会停止，tasks 清不清都可以了，这种情况只能人工介入重启恢复的。

**Comment by hanzhihua** [comment]
目前把jraf当做library使用，如果apply失败了话，就抛到上层了处理。
我们这次出现问题主要三个节点，其中一个follower节点出现假死（系统内存被另外一个进程差不多用光，ioutil也用到80%）
理论上，jraft应该可以处理这种情况，保证集群的可用性，
但出现的现象是：leader 不停的与 那个follower同步数据，最后三个节点同步的qps降的很低，上层应用apply一直超时，最后那个假死的节点进程被kernel kill掉才恢复，同步的数据qps才上来，系统恢复

**Comment by hanzhihua** [comment]
@killme2008 我这里说的apply是nodeimple的apply,不是状态机的apply,我经常遇到的错误如下：
```
2020-04-20 16:35:44.895 ERROR leader [JRaft-NodeImpl-Disruptor-0]-c.a.s.jraft.util.LogExceptionHandler.handleEventException - Handle NodeImpl disruptor event error, event is com.alipay.sofa.jraft.core.NodeImpl$LogEntryAndClosure@785de710
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@65e8d898 rejected from com.alipay.sofa.jraft.util.MetricThreadPoolExecutor@1274fb20[Running, pool size = 200, active threads = 200, queued tasks = 0, completed tasks = 179221920]
    at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2063)
    at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:830)
    at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1379)
    at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:112)
    at com.alipay.sofa.jraft.util.Utils.runInThread(Utils.java:153)
    at com.alipay.sofa.jraft.storage.impl.LogManagerImpl.wakeupAllWaiter(LogManagerImpl.java:410)
    at com.alipay.sofa.jraft.storage.impl.LogManagerImpl.appendEntries(LogManagerImpl.java:353)
    at com.alipay.sofa.jraft.core.NodeImpl.executeApplyingTasks(NodeImpl.java:1119)
    at com.alipay.sofa.jraft.core.NodeImpl.access$200(NodeImpl.java:129)
    at com.alipay.sofa.jraft.core.NodeImpl$LogEntryAndClosureHandler.onEvent(NodeImpl.java:259)
    at com.alipay.sofa.jraft.core.NodeImpl$LogEntryAndClosureHandler.onEvent(NodeImpl.java:240)
    at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:137)
    at java.lang.Thread.run(Thread.java:748)
```
出现线程池reject的时候，就会出现我上面的那个错误。

另外提一个意见，如果发现慢节点话的，是不是节点通信的pipeline机制是不是可以停掉，不然网络流量会猛增，特殊的情况下不影响集群工作是不是可以把慢节点摘掉

**Comment by hanzhihua** [comment]
错误主要原因就是JRAFT_CLOSURE_EXECUTOR 线程池用过了，线程都用到leader跟那个假死的节点同步数据去了，它会引起Node apply出错，如果这样情况会造成状态机的不可用，最后能通知应用。
比如 StateMachine.onError

那个全局的线程池（JRAFT_CLOSURE_EXECUTOR）能不能做一下隔离呢？避免一个假死的节点把状态机搞坏了

**Comment by killme2008** [comment]
> @killme2008 我这里说的apply是nodeimple的apply,不是状态机的apply,我经常遇到的错误如下：
> 
> ```
> 2020-04-20 16:35:44.895 ERROR leader [JRaft-NodeImpl-Disruptor-0]-c.a.s.jraft.util.LogExceptionHandler.handleEventException - Handle NodeImpl disruptor event error, event is com.alipay.sofa.jraft.core.NodeImpl$LogEntryAndClosure@785de710
> java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@65e8d898 rejected from com.alipay.sofa.jraft.util.MetricThreadPoolExecutor@1274fb20[Running, pool size = 200, active threads = 200, queued tasks = 0, completed tasks = 179221920]
>     at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2063)
>     at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:830)
>     at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1379)
>     at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:112)
>     at com.alipay.sofa.jraft.util.Utils.runInThread(Utils.java:153)
>     at com.alipay.sofa.jraft.storage.impl.LogManagerImpl.wakeupAllWaiter(LogManagerImpl.java:410)
>     at com.alipay.sofa.jraft.storage.impl.LogManagerImpl.appendEntries(LogManagerImpl.java:353)
>     at com.alipay.sofa.jraft.core.NodeImpl.executeApplyingTasks(NodeImpl.java:1119)
>     at com.alipay.sofa.jraft.core.NodeImpl.access$200(NodeImpl.java:129)
>     at com.alipay.sofa.jraft.core.NodeImpl$LogEntryAndClosureHandler.onEvent(NodeImpl.java:259)
>     at com.alipay.sofa.jraft.core.NodeImpl$LogEntryAndClosureHandler.onEvent(NodeImpl.java:240)
>     at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:137)
>     at java.lang.Thread.run(Thread.java:748)
> ```
> 
> 出现线程池reject的时候，就会出现我上面的那个错误。
> 
> 另外提一个意见，如果发现慢节点话的，是不是节点通信的pipeline机制是不是可以停掉，不然网络流量会猛增，特殊的情况下不影响集群工作是不是可以把慢节点摘掉

你可以通过监控发现，自行摘除的，调用 `removePeer`，从类库角度，做自动摘除是不合适的，这是一个运维操作。

**Comment by killme2008** [comment]
> 错误主要原因就是JRAFT_CLOSURE_EXECUTOR 线程池用光了，线程都用到leader跟那个假死的节点同步数据去了，它会引起Node apply出错，如果这样情况会造成状态机的不可用，最后能通知应用。
> 比如 StateMachine.onError
> 
> 那个全局的线程池（JRAFT_CLOSURE_EXECUTOR）能不能做一下隔离呢？避免一个假死的节点把状态机搞坏了

这个可以考虑

**Comment by hanzhihua** [comment]
@killme2008 
错误主要原因就是JRAFT_CLOSURE_EXECUTOR 线程池用光了，线程都用到leader跟那个假死的节点同步数据去了，它会引起Node apply出错，如果这样情况会造成状态机的不可用，_**最后能通知应用。
比如 StateMachine.onError**_

这个你们会支持吗？

**Comment by killme2008** [comment]
@hanzhihua 会在下个版本做下

**Comment by killme2008** [comment]
1.3.2 发布，隔离了复制用的 closure thread pool
