### ISSUE TITLE
TimeoutException on execute bGet function

### ISSUE THREAD

**Issue by yuyang0423** [sofastack/sofa-jraft#434]
### Your question
we have 6 nodes for Jraft running rhea KVStore;
And we got TimeoutException on fetch result by use bGet function during two nodes panic.

java.util.concurrent.TimeoutException: null
    at java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1771) ~[?:1.8.0_60]
    at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1915) ~[?:1.8.0_60]
    at com.alipay.sofa.jraft.rhea.client.FutureHelper.get(FutureHelper.java:46) ~[jraft-rheakv-core-1.3.0.jar!/:?]
    at com.alipay.sofa.jraft.rhea.client.DefaultRheaKVStore.bGet(DefaultRheaKVStore.java:375) ~[jraft-rheakv-core-1.3.0.jar!/:?]

I was wondering how this timeout will happen.  Do you have some suggestions on this situation?

### Your scenes

Describe your use scenes (why need this feature)

### Your advice

Describe the advice or solution you'd like

### Environment

- SOFAJRaft version: v1.3.0
- JVM version (e.g. `java -version`):
java version "1.8.0_60"
Java(TM) SE Runtime Environment (build 1.8.0_60-b27)
Java HotSpot(TM) 64-Bit Server VM (build 25.60-b23, mixed mode)

- OS version (e.g. `uname -a`):
Linux 5.4.22-1.el7.x86_64 #1 SMP Wed Feb 26 10:35:01 EST 2020 x86_64 x86_64 x86_64 GNU/Linux

- Maven version:
Apache Maven 3.0.5 (Red Hat 3.0.5-17)
Maven home: /usr/share/maven
Java version: 1.8.0_212, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.212.b04-0.el7_6.x86_64/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.4.22-1.el7.x86_64", arch: "amd64", family: "unix"

- IDE version:

**Comment by fengjiachun** [comment]
Hi @yuyang0423 ，please take a look at the servers logs, and you can also view the node status through `kill -s SIGUSR2 pid` (refer to section 11 of https://www.sofastack.tech/projects/sofa-jraft/jraft-user-guide/)

**Comment by yuyang0423** [comment]
> Hi @yuyang0423 ，please take a look at the servers logs, and you can also view the node status through `kill -s SIGUSR2 pid` (refer to section 11 of https://www.sofastack.tech/projects/sofa-jraft/jraft-user-guide/)

ok, I'll do it and let you know. Further infos,  we find it's not stable performance on getValue from rheaKV during membership change in raft.

**Comment by yuyang0423** [comment]
close this temporarily, we are trying to add retry mechanisms and set longer futureTimeoutMillis.
