### ISSUE TITLE
When the leader fails, sofajraft cannot guarantee linear consistent reads, maybe dirty reads?

### ISSUE THREAD

**Issue by jiemar** [sofastack/sofa-jraft#435]
从官网读到以下描述. 是否意味着 sofajraft在leader故障的时候, 可能出现脏读, 无法保证线性一致性读?
这样还能满足金融级的场景吗?

![image](https://user-images.githubusercontent.com/1522163/80897542-586f7b80-8d2c-11ea-9f5c-be767dbcf56a.png)

**Comment by killme2008** [comment]
这句话描述不够准确，选举期间读写理论上都是不可用的，但是某些场景下，可能想继续提供读服务，可能会遇到脏读，这个选择权是交给用户的，根据场景来决策。文档我们会改下。
