### ISSUE TITLE
Question regarding RPC client/server streaming.

### ISSUE THREAD

**Issue by zhexinq** [sofastack/sofa-jraft#441]
### Your question

Is there support for com.alipay.sofa.jraft.rpcRpcClient to support a way for streaming RPC response instead of transmitting a whole object?

### Your scenes

So we are trying to build a distributed sqlite application on top sofa-jraft, but we are having issues transmitting large data from Raft rpc server to Raft rpc client. The reason is that database usually could store large amount of data in a single column or store a list items in a single table. The way to optimize query performance is to provide an OutputStream that client can read from so we don't need to load all data in memory (which is likely to crash the server), but it looks like the current RpcClient handle only supports callback to return serializable object which possibly limit the size of content an RPC server can respond?

### Your advice

Ideally, there should be support for streaming data from Raft server to Raft client.

### Environment

- SOFAJRaft version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by fengjiachun** [comment]
Hi，rpcClient (jraft) does not yet support streaming RPC. I read your description and it seems that this part does not rely on rpcClient (jraft) and you can use other frameworks that support streaming RPC

**Comment by fengjiachun** [comment]
RpcClient (jraft) is just a wrapper of the RPC implementation（for jraft-core）, and you can use the RPC implementation directly in your business layer，such as GRPC

**Comment by zhexinq** [comment]
In order to start up a Raft cluster we need to call something like this:
`this.raftGroupService = new RaftGroupService(groupId, serverId, nodeOptions, rpcServer);`
The last param is a  com.alipay.sofa.jraft.rpc.RpcServer, is there any other way to plugin gRPC implementation?

**Comment by fengjiachun** [comment]
We will release a new version in the next few days，you can use [RaftRpcFactory](https://github.com/sofastack/sofa-jraft/blob/master/jraft-core/src/main/java/com/alipay/sofa/jraft/rpc/RaftRpcFactory.java) to create [GRPC impl](https://github.com/sofastack/sofa-jraft/tree/master/jraft-extension/rpc-grpc-impl)

**Comment by fengjiachun** [comment]
Until the new version is released， you can also use bolt in jraft, use GRPC in your business layer，and use a different port
