### ISSUE TITLE
The potential security risk of jackson-databind.

### ISSUE THREAD

**Issue by zongtanghu** [sofastack/sofa-jraft#445]
### Your question

There exists some network security risk of jackson-databind.

### Your scenes

There exists some network security risk of jackson-databind.

### Your advice

I will upgrade the version of jackson-databind to solve the potential security risks.

### Environment

- SOFAJRaft version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by zongtanghu** [comment]
I will put forward a pr to upgrade the version of jackson-databind.

**Comment by fengjiachun** [comment]
@zongtanghu tks
