### ISSUE TITLE
Documentation about setting up SSL in sofa jraft's server

### ISSUE THREAD

**Issue by esther09** [sofastack/sofa-jraft#450]
Hello, I saw that there were support for ssl in sofa jraft's rpc server. We are building a replicated data storage using sofa-jraft and we would hope that the communication between nodes are secured. I would hope to get some documentation or pointer to start add SSL support to the rpcServer provided by sofa jraft

**Comment by SteNicholas** [comment]
@esther09 You could refer to [JRaft 用户指南](https://www.sofastack.tech/projects/sofa-jraft/jraft-user-guide/) and search SSL keyword, then you could find the answer about setting up SSL.
