### ISSUE TITLE
scenes to be used

### ISSUE THREAD

**Issue by songtaoying** [sofastack/sofa-jraft#457]
### Your question

您好，刚刚使用SofaJraft:  有这么一个场景：一个Raft-group 中 会有多个类型的Req输入请求；在状态机中; 需要按照type聚合MAP暂存内存中，以便与后续新入的同类型Req匹配。匹配成功将从对应type的Map中移除；
所以我想日志同步可以类照type来同步至从结点；同时SNAPShot 也可以支持按照Type 来分类储；

请问这种使用正确吗？有没有别的方式？

我目前想到的就是 每个Type 使用一个Raft-Group；但是Type种类比较多。有700多种。这样的话就得700个Raft-Group

### Environment

- SOFAJRaft version: 1.3.1

**Comment by fengjiachun** [comment]
> 所以我想日志同步可以类照type来同步至从结点；同时SNAPShot 也可以支持按照Type 来分类储；
单  raft group 也满足你的需求，当然 multi group 也可以，但不必一个 type 对应一个 group，建议 hash 之类的分片策略，另外因为 业务状态机 是用户自己实现的，所以状态机对应的 snapshot 操作也需要自己实现，你可以按照 type 来存储没有问题
