### ISSUE TITLE
An exception occurs during manual leader migration

### ISSUE THREAD

**Issue by hanzhihua** [sofastack/sofa-jraft#461]
### Your question

手动做leader迁移的时候出现异常
步骤如下：
1. node1，node2 新版本发布
2.做leader切换到把node3(老leader)迁移到node1（新leader）上面
3.重启node3时，出现了大量raft数据同步超时
4.node3重启完成，一切回复正常

我切过2次leader，步骤如上，每次都在老leader重启时，出现错误，重启完成后恢复正常（切leader时以前正常，并成功）

我看了一下代码，发现在老leader发timeout 事件给新leader,新leader发起electslef,整个过程没有发现老leader关闭与follower的连接

我还发现follower都有两个链接连着它（新，老leader）,感觉有点奇怪

至于为什么会出现数据同步超时，我看了各个节点的metric数据，没有看到有什么异常，请指教！

Environment
jdk 1.8
3台集群（jraft 版本1.2.6）
uname :4.9.0-0.bpo.6-amd64 #1 SMP Debian 4.9.88-1+deb9u1~bpo8+1 (2018-05-13) x86_64 GNU/Linux

**Comment by killme2008** [comment]
不明白问题是什么。
这里我没理解错只是关闭的问题，没有做到友好关闭。

**Comment by hanzhihua** [comment]
：），连接没有关闭是一个现象，我不知道为什么不关闭

主要问题是，老leader 一下线，就有大量的raft数据同步出现超时，直到老leader重启完成后，才恢复正常

**Comment by fengjiachun** [comment]
> 3.重启node3时，出现了大量raft数据同步超时

这句话的意思是重启期间出现超时？ 这是正常的，首先这个节点在 raft group 里，新的 leader 需要向它同步数据

**Comment by hanzhihua** [comment]
我有三个节点，我重启老leader，不应该会出现超时吧

**Comment by fengjiachun** [comment]
你说的超时是什么超时？ replicator 往对应重启节点复制日志超时？ 那不正常吗

**Comment by hanzhihua** [comment]
不好意思，没有说清楚。
我的超时，是指客户端来写Raft超时，因为有两个节点是正常，理论上客户端操作应该是正常的

同步一个信息：如果我不做手动切换leader，那么重启一个节点客户端是不会超时的，但一旦我做了切leader操作，再重启老leader的期间，客户端一定超时，直到节点重启完成

**Comment by fengjiachun** [comment]
了解了，异常信息麻烦发一下，再参考下面链接第11章节，再现一下问题然后把当时的 三个节点的 node_describe.log 和 metric 保存下来发出来看看

**Comment by killme2008** [comment]
比较怀疑是客户端的 route table 没有更新到新的 leader 信息，仍然往老的  leader 发送请求，或者你有使用 readIndex from follower

**Comment by killme2008** [comment]
有没有更多信息可以提供？ 比如当时的 raft log 之类

**Comment by hanzhihua** [comment]
现在服务器一直在工作，也没有出现这样的情况，后续在出现我把日志给你们。

以前只有主动切换leader节点，或者fullgc(做jmap导致gc)导致节点切换后，重启老的leader都会有这样的问题

而且老的leader也 一直连着follower，连接也不关闭，有点奇怪

我在想使用bolt-rpc，是不是会话expire了，连接自动关闭，所以出现leader切换了，没有关闭连接的动作

**Comment by killme2008** [comment]
好的，那先关闭了，有问题再打开，另外 1.3.3 发布了，推荐升级，有一个元信息可能丢失的 bug

**Comment by hanzhihua** [comment]
这个问题又浮现了，我看了一下代码了，我觉得里面的逻辑会不会有点问题，步骤如下（3个节点集群）
1. node1，node2 新版本发布
2.leader做切换使用transferLeadershipTo方法，把node3(老leader)随机迁移到node1（新leader）上
3.重启node3时，出现了大量raft数据同步超时
4.node3重启完成，一切回复正常

我发现做leader切换后，node3(老leader),node1（新leader）,他们会同时连接到node2，就意味着的node2同时被两个节点连接，但node2的peerid是一样的。
这个时候如果node3(老leader)重启后，会发生connect event,被node2发现并做处理
![image](https://user-images.githubusercontent.com/1732108/95682933-c0e75080-0c1a-11eb-8392-8ecef8697eeb.png)

而node1与node2在交互的时候会重新生成一个PeerRequestContext
![image](https://user-images.githubusercontent.com/1732108/95683021-3f43f280-0c1b-11eb-8685-627dfc6ace0f.png)

我今天看代码看的结果，还没有做测试，明天测一下，也请指教

**Comment by killme2008** [comment]
建议附上日志，leader 切换前后的，特别是 warn, error 等异常信息

**Comment by hanzhihua** [comment]
使用pipeline发送log的时候，如果一个Follower被多个leader链接时，他们PeerRequestContext是一个，会有这样的问题出现
老leader的断开，由io线程去造成 follower的PeerRequestContext重置，新leader发送的log，还在维持原来的seq

日志，我等下发出来

**Comment by hanzhihua** [comment]
[jraft-node01.log](https://github.com/sofastack/sofa-jraft/files/5363011/jraft-node01.log)
[jraft-node02.log](https://github.com/sofastack/sofa-jraft/files/5363012/jraft-node02.log)
[jraft-node03.log](https://github.com/sofastack/sofa-jraft/files/5363013/jraft-node03.log)

时间线 （3个节点的集群）
1. 19点 02是leader,01,03是Follower （状态正常）
2. 发布 01，03 （状态正常）
3. 2020-10-09 19:03:27 转移leader,到01 （状态正常）
4. 2020-10-09 19:07:07 发布老leader 02 （状态不正常），直到2020-10-09 19:08:07,02启动正常才恢复

**Comment by killme2008** [comment]
这个是符合预期的，老的就应该重置的，新的会从 0 重新开始，如果这段时间没有 response 出去的，就应该认为失败。

**Comment by hanzhihua** [comment]
新的leader已经正常工作，只是由于老的leader的重启，造成了follower的peercontext重置，好像有点问题吧

**Comment by killme2008** [comment]
1. 必须要重置，因为 response 可能是match不上的。
2. 不过可以改进， peer context 的映射应该加上对端的 peer id。

**Comment by hanzhihua** [comment]
transferLeadershipTo 这个功能我现在不太敢用了，如果我直接重启leader只有electiontimeout不可用的情况，如果用transferLeadershipTo目前差不多1分钟不可用（取决于老leader重启时间）

**Comment by killme2008** [comment]
这个我们尝试复现下，看看怎么更好地解决。

**Comment by hanzhihua** [comment]
好的，谢谢
感觉直接在transferLeadershipTo 成功后关闭跟follower连接是不是可以，只有老leader情况下才会出现这样的情况，不是老leader的节点跟其他follower连接的建立和关闭，对业务没有什么影响

**Comment by hanzhihua** [comment]
hi killme2008,目前针对这个问题，我简单处理了一下，就是replicator destory的时候，我加上关闭连接的操作，避免了一个follower有多个leader
![image](https://user-images.githubusercontent.com/1732108/96440169-2ac6b200-123a-11eb-892b-660f02c0c4df.png)

我现在担心的是关闭连接操作是异步，还是无法避免一个follower多个连接的问题，请指教

**Comment by killme2008** [comment]
@hanzhihua 这里感觉不大对， node2 移除的也是 remote addr ，也就是 node3 的 peer context，并不影响和 node1 的链接。

**Comment by killme2008** [comment]
@hanzhihua 了解到了，这里是个 bug，销毁错了 peer context，要销毁的是远程的，而不是本地 node 的。这个我们尽快修复下。

**Comment by killme2008** [comment]
我的第一个回复是正确的：

```
1.必须要重置，因为 response 可能是match不上的。
2. 不过可以改进， peer context 的映射应该加上对端的 peer id。
```

精确地说，是要销毁两个 peer 之间的 peer context，但是现在 peer context 是跟处理节点关联的，没有加上对端这个 key，所以导致共享的 peer context 在这个情况下被意外销毁。 这个问题比较好解决，我们尽快搞下，谢谢反馈。

**Comment by hanzhihua** [comment]
好的，谢谢

**Comment by killme2008** [comment]
@hanzhihua 可以测试下这个分支 https://github.com/sofastack/sofa-jraft/pull/528 应该解决了你提到的这个问题。

**Comment by hanzhihua** [comment]
好的，谢谢，我合到1.2.6分支

**Comment by killme2008** [comment]
@hanzhihua 合并后的版本，你那边还有出现这个问题吗？
