### ISSUE TITLE
Advanced usage issues

### ISSUE THREAD

**Issue by guotaisu** [sofastack/sofa-jraft#473]
### Your question

1.根据jraft-example, 使用“fake PD”, 怎样手动rebalance。使用PD自管理体现在哪？

2.regionEngineOptionsList配置：实例中的regionId的startKey：01000000-endKey：23000000根据什么来定义的，假设我一个store节点只部署1-3个region，可以自定义上下界是吗，依据什么来定义？ yaml配置中regionEngineOptionsList.RegionEngineOptions中的serverAddress、initialServerList等配置和外部与regionEngineOptionsList平级的serverAddress配置以及与storeEngineOptions平级的initialServerList是什么关系，谁覆盖谁？

3.jraft-example展示，Rhea-kv是客户端+服务端模式，其中benchmark使用分片集群部署模式，需要先同时使用BenchmarkClient、BenchmarkServer拉启后台服务，而后面的rheakv使用分节点配置和启动，如何区分二者的场景和使用姿势。

4.本人项目使用JRaft场景是分布式单体服务快速便捷存储业务元数据，实现一致性访问。请问后台需要拉取这么多服务如何还能保证我的应用轻量快捷？另外，这些后台jraft-kv选举和存储服务启动后，是独立进程吗，整合到自己到项目中后，可否一个进程并且其服务生命周期随同我的母体应用的生命周期。

5.参考jraft-example实例，基于rheakv部署multi group，加减learnner节点等，应该是以分组为单位操作，目前只看到NodeOptions中有groupId属性，多组时怎么配置和分别操作。

**Comment by fengjiachun** [comment]
> 1.根据jraft-example, 使用“fake PD”, 怎样手动rebalance。使用PD自管理体现在哪？

手动 api： https://github.com/sofastack/sofa-jraft/blob/master/jraft-core/src/main/java/com/alipay/sofa/jraft/CliService.java#L190

PD 目前只实现了 leader 平衡和自动分裂，支持很容易基于 SPI 扩展增加自己的逻辑(增加并实现自己的 `com.alipay.sofa.jraft.rhea.util.pipeline.Handler` 即可)，文档见：https://www.sofastack.tech/projects/sofa-jraft/jraft-rheakv-user-guide/


> 2.regionEngineOptionsList配置：实例中的regionId的startKey：01000000-endKey：23000000根据什么来定义的，假设我一个store节点只部署1-3个region，可以自定义上下界是吗，依据什么来定义？

rheakv multi group 按照 range 分片，左闭右开，可以自定义，怎么定义取决于你对自己场景 key 分布的评估

>  yaml配置中regionEngineOptionsList.RegionEngineOptions中的serverAddress、initialServerList等配置和外部与regionEngineOptionsList平级的serverAddress配置以及与storeEngineOptions平级的initialServerList是什么关系，谁覆盖谁？

store 和 region 为1：n， region 包含在 store 中，store 的参数会 copy 传递到 region

> .jraft-example展示，Rhea-kv是客户端+服务端模式，其中benchmark使用分片集群部署模式，需要先同时使用BenchmarkClient、BenchmarkServer拉启后台服务，而后面的rheakv使用分节点配置和启动，如何区分二者的场景和使用姿势。

rheakv 可以作为 client+server 部署，也可以单独作为 client 部署，通常你不想在每个节点提供服务但是还需要调用服务，那么久只 client 部署即可（配置的区别就在于是否配置了 StoreEngineOptions）

> .本人项目使用JRaft场景是分布式单体服务快速便捷存储业务元数据，实现一致性访问。请问后台需要拉取这么多服务如何还能保证我的应用轻量快捷？另外，这些后台jraft-kv选举和存储服务启动后，是独立进程吗，整合到自己到项目中后，可否一个进程并且其服务生命周期随同我的母体应用的生命周期。

jraft 是一个 jar 包，是不是独立进程完全取决于你自己的意愿，都可以

> 参考jraft-example实例，基于rheakv部署multi group，加减learnner节点等，应该是以分组为单位操作，目前只看到NodeOptions中有groupId属性，多组时怎么配置和分别操作。

这应该是两个问题
问题1（groupId 多组如何配置）：在 rheakv 里，groupId 是 clusterName + ‘-’ regionId
问题2（多组如何配置 learner）：好问题，目前没有很灵活，我们内部使用还是单独指定几台机器，上面的节点全部是 learner 节点，只要配置 `initialServerList: 127.0.0.1:8181,127.0.0.1:8182,127.0.0.1:8183/learner ` 即所有 group 的 learner 都在 127.0.0.1:8183/learner 一个节点上，你的需求收到了，下个版本会增加每个 region 单独指定 learner，需要修改 `RegionEngineOptions.initialServerList` 在不为空的时候不被 StoreEngineOptions 的值覆盖即可

**Comment by guotaisu** [comment]
我想使用PD 路由表placementDriverOptions.regionRouteTableOptionsList怎么配置，和storeEngineOptions.regionEngineOptionsList一一对应吗？可以展示一下3group 3+1(learnner)节点的配置吗？另外，我看到example中有2+1(learnner)的配置是不满足过半选主的对吧

**Comment by guotaisu** [comment]
> > 1.根据jraft-example, 使用“fake PD”, 怎样手动rebalance。使用PD自管理体现在哪？
> 
> 手动 api： https://github.com/sofastack/sofa-jraft/blob/master/jraft-core/src/main/java/com/alipay/sofa/jraft/CliService.java#L190
> 
> PD 目前只实现了 leader 平衡和自动分裂，支持很容易基于 SPI 扩展增加自己的逻辑(增加并实现自己的 `com.alipay.sofa.jraft.rhea.util.pipeline.Handler` 即可)，文档见：https://www.sofastack.tech/projects/sofa-jraft/jraft-rheakv-user-guide/
> 
> > 2.regionEngineOptionsList配置：实例中的regionId的startKey：01000000-endKey：23000000根据什么来定义的，假设我一个store节点只部署1-3个region，可以自定义上下界是吗，依据什么来定义？
> 
> rheakv multi group 按照 range 分片，左闭右开，可以自定义，怎么定义取决于你对自己场景 key 分布的评估
> 
> > yaml配置中regionEngineOptionsList.RegionEngineOptions中的serverAddress、initialServerList等配置和外部与regionEngineOptionsList平级的serverAddress配置以及与storeEngineOptions平级的initialServerList是什么关系，谁覆盖谁？
> 
> store 和 region 为1：n， region 包含在 store 中，store 的参数会 copy 传递到 region
> 
> > .jraft-example展示，Rhea-kv是客户端+服务端模式，其中benchmark使用分片集群部署模式，需要先同时使用BenchmarkClient、BenchmarkServer拉启后台服务，而后面的rheakv使用分节点配置和启动，如何区分二者的场景和使用姿势。
> 
> rheakv 可以作为 client+server 部署，也可以单独作为 client 部署，通常你不想在每个节点提供服务但是还需要调用服务，那么久只 client 部署即可（配置的区别就在于是否配置了 StoreEngineOptions）
> 
> > .本人项目使用JRaft场景是分布式单体服务快速便捷存储业务元数据，实现一致性访问。请问后台需要拉取这么多服务如何还能保证我的应用轻量快捷？另外，这些后台jraft-kv选举和存储服务启动后，是独立进程吗，整合到自己到项目中后，可否一个进程并且其服务生命周期随同我的母体应用的生命周期。
> 
> jraft 是一个 jar 包，是不是独立进程完全取决于你自己的意愿，都可以
> 
> > 参考jraft-example实例，基于rheakv部署multi group，加减learnner节点等，应该是以分组为单位操作，目前只看到NodeOptions中有groupId属性，多组时怎么配置和分别操作。
> 
> 这应该是两个问题
> 问题1（groupId 多组如何配置）：在 rheakv 里，groupId 是 clusterName + ‘-’ regionId
> 问题2（多组如何配置 learner）：好问题，目前没有很灵活，我们内部使用还是单独指定几台机器，上面的节点全部是 learner 节点，只要配置 `initialServerList: 127.0.0.1:8181,127.0.0.1:8182,127.0.0.1:8183/learner ` 即所有 group 的 learner 都在 127.0.0.1:8183/learner 一个节点上，你的需求收到了，下个版本会增加每个 region 单独指定 learner，需要修改 `RegionEngineOptions.initialServerList` 在不为空的时候不被 StoreEngineOptions 的值覆盖即可

**Comment by guotaisu** [comment]
> 1.我想使用PD 路由表placementDriverOptions.regionRouteTableOptionsList怎么配置，和storeEngineOptions.regionEngineOptionsList一一对应吗？假设我的key是任意字符串，是否需要自己生成并维护全局唯一 key和界定key的上下界。有关这两点可否举例说明并以3group 3+1(learnner)节点的配置展示一下吗？另外，我看到example中有2+1(learnner)的配置，这种是不满足过半选主的对吧。

**Comment by guotaisu** [comment]
> > 1.根据jraft-example, 使用“fake PD”, 怎样手动rebalance。使用PD自管理体现在哪？
> 
> 手动 api： https://github.com/sofastack/sofa-jraft/blob/master/jraft-core/src/main/java/com/alipay/sofa/jraft/CliService.java#L190
> 
> PD 目前只实现了 leader 平衡和自动分裂，支持很容易基于 SPI 扩展增加自己的逻辑(增加并实现自己的 `com.alipay.sofa.jraft.rhea.util.pipeline.Handler` 即可)，文档见：https://www.sofastack.tech/projects/sofa-jraft/jraft-rheakv-user-guide/
> 
> > 2.regionEngineOptionsList配置：实例中的regionId的startKey：01000000-endKey：23000000根据什么来定义的，假设我一个store节点只部署1-3个region，可以自定义上下界是吗，依据什么来定义？
> 
> rheakv multi group 按照 range 分片，左闭右开，可以自定义，怎么定义取决于你对自己场景 key 分布的评估
> 
> > yaml配置中regionEngineOptionsList.RegionEngineOptions中的serverAddress、initialServerList等配置和外部与regionEngineOptionsList平级的serverAddress配置以及与storeEngineOptions平级的initialServerList是什么关系，谁覆盖谁？
> 
> store 和 region 为1：n， region 包含在 store 中，store 的参数会 copy 传递到 region
> 
> > .jraft-example展示，Rhea-kv是客户端+服务端模式，其中benchmark使用分片集群部署模式，需要先同时使用BenchmarkClient、BenchmarkServer拉启后台服务，而后面的rheakv使用分节点配置和启动，如何区分二者的场景和使用姿势。
> 
> rheakv 可以作为 client+server 部署，也可以单独作为 client 部署，通常你不想在每个节点提供服务但是还需要调用服务，那么久只 client 部署即可（配置的区别就在于是否配置了 StoreEngineOptions）
> 
> > .本人项目使用JRaft场景是分布式单体服务快速便捷存储业务元数据，实现一致性访问。请问后台需要拉取这么多服务如何还能保证我的应用轻量快捷？另外，这些后台jraft-kv选举和存储服务启动后，是独立进程吗，整合到自己到项目中后，可否一个进程并且其服务生命周期随同我的母体应用的生命周期。
> 
> jraft 是一个 jar 包，是不是独立进程完全取决于你自己的意愿，都可以
> 
> > 参考jraft-example实例，基于rheakv部署multi group，加减learnner节点等，应该是以分组为单位操作，目前只看到NodeOptions中有groupId属性，多组时怎么配置和分别操作。
> 
> 这应该是两个问题
> 问题1（groupId 多组如何配置）：在 rheakv 里，groupId 是 clusterName + ‘-’ regionId
> 问题2（多组如何配置 learner）：好问题，目前没有很灵活，我们内部使用还是单独指定几台机器，上面的节点全部是 learner 节点，只要配置 `initialServerList: 127.0.0.1:8181,127.0.0.1:8182,127.0.0.1:8183/learner ` 即所有 group 的 learner 都在 127.0.0.1:8183/learner 一个节点上，你的需求收到了，下个版本会增加每个 region 单独指定 learner，需要修改 `RegionEngineOptions.initialServerList` 在不为空的时候不被 StoreEngineOptions 的值覆盖即可

1.我想使用PD 路由表placementDriverOptions.regionRouteTableOptionsList怎么配置，和storeEngineOptions.regionEngineOptionsList一一对应吗？假设我的key是任意字符串，是否需要自己生成并维护全局唯一 key和界定key的上下界。有关这两点可否举例说明并以3group 3+1(learnner)节点的配置展示一下吗？另外，我看到example中有2+1(learnner)的配置，这种是不满足过半选主的对吧。
