### ISSUE TITLE
Potential GPL-2.0 licence violations

### ISSUE THREAD

**Issue by dokky** [sofastack/sofa-jraft#474]
Hello,

sofa-jraft is licensed under Apache 2.0 https://github.com/sofastack/sofa-jraft/blob/master/LICENSE

But there are few c 
- https://github.com/sofastack/sofa-jraft/blob/master/jraft-core/src/main/java/com/alipay/sofa/jraft/util/Bits.java 
- https://github.com/sofastack/sofa-jraft/blob/master/jraft-core/src/main/java/com/alipay/sofa/jraft/rpc/impl/FutureImpl.java
- https://github.com/sofastack/sofa-jraft/blob/94c2ece97ca1e09a05ef19a3ee45ec3a1265a9be/jraft-core/src/main/java/com/alipay/sofa/jraft/storage/log/LibC.java

I believe that material, being part of the other projects such OpenJDK, Glassfish, RocketMQ, that are licensed under the GPL-2.0. That means any binary containing this material must be placed under the same license. This is obviously deeply problematic for anyone producing a commercial binary using this library.

**Comment by killme2008** [comment]
Thank you for your remind. 
* `Bits.java` is from [openjdk](http://hg.openjdk.java.net/jdk8u/jdk8u-dev/jdk/file/4a1e42601d61/src/share/classes/java/nio/Bits.java),it's under GPL v2 and has a special case:
```
Oracle designates this
 * particular file as subject to the "Classpath" exception as provided
 * by Oracle in the LICENSE file that accompanied this code.
```
but we should present the lisencse file under source folder, we will do it ASAP.
*  The glassfish is under GPL or CDDL license, and has the `classpath` excepiton too.
* The rocketmq is under apache2 license too, not GPL.
