### ISSUE TITLE
How MULTI-RAFT-GROUP can achieve leader balance in all nodes?

### ISSUE THREAD

**Issue by runzhiwang** [sofastack/sofa-jraft#476]
### Your question

For example, in MULTI-RAFT-GROUP, there are 3 nodes partitipate in 3 raft groups. But how we can avoid one node act as leader in 
all 3 raft groups ?  If one node act as leader in all 3 raft groups, it's pressure is very high.

**Comment by fengjiachun** [comment]
rebalance api： https://github.com/sofastack/sofa-jraft/blob/master/jraft-core/src/main/java/com/alipay/sofa/jraft/CliService.java#L190

**Comment by runzhiwang** [comment]
@fengjiachun Thanks for explanation.  One more question, rebalance api is rebalance leader when leader has been elected, so do sofa-jraft can consider the node load when leader election ? For example, if node1 has been elected as leader in group1, it will not be elected as leader in group2 again.

**Comment by fengjiachun** [comment]
Currently, there is no correlation between the different raft groups，but maybe you can try [priority-election](https://www.sofastack.tech/blog/sofa-jraft-priority-election/)

**Comment by runzhiwang** [comment]
@fengjiachun Thank you very much.

**Comment by runzhiwang** [comment]
@fengjiachun Hi, I have read the blog of priority-election, it's very interesting. One more question,  follower will decayTargetPriority if election timeout, and after some times of leader election,  all follower's targetPriority will be less than their priority, they both can trigger leader election,  then priority will be useless. How can we avoid this case ?
