### ISSUE TITLE
The snapshot and snapshot metadata are inconsistent.

### ISSUE THREAD

**Issue by juaby** [sofastack/sofa-jraft#478]
The snapshot and snapshot metadata are inconsistent.

Step 1: Synchronize and obtain snapshot metadata, at this time metadata=META-T1, state machine=FSM-T1;
Step 2: Synchronize and generate a snapshot, at this time metadata=META-T1, state machine=FSM-T2;
Step 3: Synchronize and refresh snapshot metadata, at this time metadata=META-T2, state machine=FSM-T3;

During this period, there is no guarantee that the metadata = META-T1 and the state machine = FSM-T2 are consistent;

**Comment by killme2008** [comment]
Please read the javadoc of `onSnapshotSave`

```
 /**
     * User defined snapshot generate function, this method will block StateMachine#onApply(Iterator).
     * user can make snapshot async when fsm can be cow(copy-on-write).
     * call done.run(status) when snapshot finished.
     * Default: Save nothing and returns error.
     *
     * @param writer snapshot writer
     * @param done   callback
     */
    void onSnapshotSave(final SnapshotWriter writer, final Closure done);
```

 This method will **block** StateMachine#onApply(Iterator), if your fsm can be cow(copy-on-write), you can make snapshot asynchronously.It's your duty to keep the meta and snapshot state in consistent.

**Comment by juaby** [comment]
the javadoc of onSnapshotSave 
Declaration and implementation are inconsistent

**Comment by killme2008** [comment]
The `FMSCaller` has only one thread in disruptor to execute commands for `StateMachine`, when it calls `doSnapshotSave`, it can't call `doCommitted`(for `onApply(it)`).

I am sorry i don't want to explain the source code in detail. 

If you are interested in implementation, you can read it by yourself. And if you have some questions on code, please attach the code in issue and express your worry clearly, i will try to explain it for you. Thank you.

**Comment by juaby** [comment]
Obtaining snapshot metadata occurs before calling the onSnapshotSave method

**Comment by killme2008** [comment]
The snapshot meta is built in `doSnapshotSave`, then calls `StateMachine#onSnapshotSave(writer, done)`.

```java
 private void doSnapshotSave(final SaveSnapshotClosure done) {
        Requires.requireNonNull(done, "SaveSnapshotClosure is null");
        final long lastAppliedIndex = this.lastAppliedIndex.get();
        final RaftOutter.SnapshotMeta.Builder metaBuilder = RaftOutter.SnapshotMeta.newBuilder() //
            .setLastIncludedIndex(lastAppliedIndex) //
            .setLastIncludedTerm(this.lastAppliedTerm);
        final ConfigurationEntry confEntry = this.logManager.getConfiguration(lastAppliedIndex);
        if (confEntry == null || confEntry.isEmpty()) {
            LOG.error("Empty conf entry for lastAppliedIndex={}", lastAppliedIndex);
            Utils.runClosureInThread(done, new Status(RaftError.EINVAL, "Empty conf entry for lastAppliedIndex=%s",
                lastAppliedIndex));
            return;
        }
        for (final PeerId peer : confEntry.getConf()) {
            metaBuilder.addPeers(peer.toString());
        }
        for (final PeerId peer : confEntry.getConf().getLearners()) {
            metaBuilder.addLearners(peer.toString());
        }
        if (confEntry.getOldConf() != null) {
            for (final PeerId peer : confEntry.getOldConf()) {
                metaBuilder.addOldPeers(peer.toString());
            }
            for (final PeerId peer : confEntry.getOldConf().getLearners()) {
                metaBuilder.addOldLearners(peer.toString());
            }
        }
        final SnapshotWriter writer = done.start(metaBuilder.build());
        if (writer == null) {
            done.run(new Status(RaftError.EINVAL, "snapshot_storage create SnapshotWriter failed"));
            return;
        }
        this.fsm.on
```
