### ISSUE TITLE
Where can I find the test results of Jepsen?

### ISSUE THREAD

**Issue by JoyJava** [sofastack/sofa-jraft#479]
请问 jepson 测试结果在那可以查询到？

Where can I get the Jepsen test results?

**Comment by fengjiachun** [comment]
每个 release 版本之前都需要通过 jepsen 验证，结果可以看对应的 issue，比如 #468 

下面链接为 SOFAJRaft-jepsen 项目地址：https://github.com/sofastack/sofa-jraft-jepsen
