### ISSUE TITLE
When the raft node restarts, it reloads from the snapshot and then replays the WAL to reach the reset state machine. Why?

### ISSUE THREAD

**Issue by juaby** [sofastack/sofa-jraft#483]
When the raft node restarts, it reloads from the snapshot and then replays the WAL to reach the reset state machine. What is the purpose of these? Idempotency? Or other reasons?

**Comment by killme2008** [comment]
It's the purpose of snapshot mechanism. If you don't enable snapshot, you have to replay all logs from zero to reach the last stable state.
