### ISSUE TITLE
JRheaKV进阶使用问题

### ISSUE THREAD

**Issue by guotaisu** [sofastack/sofa-jraft#485]
### Your question

1.我想使用PD 路由表placementDriverOptions.regionRouteTableOptionsList怎么配置，和storeEngineOptions.regionEngineOptionsList一一对应吗？
2.假设我的key是任意字符串，是否需要自己生成并维护全局唯一 key和界定key的上下界。
有关1、2这两点可否举例说明并以3group 3+1(learnner)节点的配置展示一下吗？另外，我看到example中有2+1(learnner)的配置，这种是不满足过半选主的对吧。
3.内嵌RocksDB未支持ttl过期时间设置和存储？

**Comment by fengjiachun** [comment]
1. 建议用 com.alipay.sofa.jraft.rhea.options.configured.PlacementDriverOptionsConfigured 取代配置，对象结构更清晰，也有助于你理解
2. 是
 2+1 的问题是为了 unit test 快一些，没有满足不满足一说
3. 不支持 ttl

**Comment by guotaisu** [comment]
> 1. 建议用 com.alipay.sofa.jraft.rhea.options.configured.PlacementDriverOptionsConfigured 取代配置，对象结构更清晰，也有助于你理解
> 2. 是
>    2+1 的问题是为了 unit test 快一些，没有满足不满足一说
> 3. 不支持 ttl

1.Client通过路由表定位key的范围，避免全局扫描，我的本意是指如果pd fake=false, 即手动维护路由表，需要配置和storeEngineOptions.regionEngineOptionsList一致吗，如果pd fake=false, 是在PD内部维护这样一张路由表吗？
本人配置如下：
##RheaKVStoreOptions
---
clusterName: raft_kv_ps

placementDriverOptions:
  fake: true
  pdGroupId: pd_default
  initialPdServerList: 127.0.0.1:8181,127.0.0.1:8182,127.0.0.1:8183
  # 路由表
  regionRouteTableOptionsList:
    - { regionId: 1 }
    - { regionId: 2 }
    - { regionId: 3 }

storeEngineOptions:
  storageType: RocksDB
  rocksDBOptions:
    fastSnapshot: true
    dbPath: rhea_db
  raftDataPath: raft_data
  raftRpcCoreThreads: 16
  serverAddress:
    ip: 127.0.0.1
    port: 18181
  leastKeysOnSplit: 10
  commonNodeOptions:
    raftOptions:
      readOnlyOptions: ReadOnlyLeaseBased
  regionEngineOptionsList:
    - { regionId:  1,                      endKey: 08000000 }
    - { regionId:  2, startKey: 08000000,  endKey: 16000000 }
    - { regionId:  3, startKey: 23000000,                   }

onlyLeaderRead: true

failoverRetries: 0
futureTimeoutMillis: 2000
useParallelKVExecutor: false

initialServerList: 127.0.0.1:18181::30,127.0.0.1:18182::30,127.0.0.1:18183::30

2.如何快速查看分片是否均匀，查看方式有哪些，以便调整key或者手动split/merge

**Comment by fengjiachun** [comment]
本地配置的路由表（storeEngineOptions.regionEngineOptionsList）用于初始化集群，不论 pd 是否 fake，都需要有一个配置，如果 pd = fake 那么一直沿用是这个配置，如果使用 pd, 在初始化集群后便不再依赖本地配置了(自动注册)

> 如何快速查看分片是否均匀，查看方式有哪些

代码侧从 `com.alipay.sofa.jraft.rhea.client.pd.StatsCollector` 获取，目前没有后台管理系统查看相关信息，不过可以从 pdServer 上查看日志，会由 `com.alipay.sofa.jraft.rhea.pipeline.handler.LogHandler` 打印 stats 信息到日志中。

另外，spilt 是自动的，默认使用 handler（基于 spi，可以定制）： `com.alipay.sofa.jraft.rhea.pipeline.handler.SplittingJudgeByApproximateKeysHandler`  基于当前 region 中 key 的数量， 默认配置在 `com.alipay.sofa.jraft.rhea.options.StoreEngineOptions#leastKeysOnSplit`

**Comment by fengjiachun** [comment]
可以运行一下 demo ：

1. 启动 `com.alipay.sofa.jraft.rhea.PdServer`
2. 启动 `com.alipay.sofa.jraft.rhea.pd.RheaHeartbeatTest`

region 分别配置 learner 见这里 #486

**Comment by guotaisu** [comment]
> 本地配置的路由表（storeEngineOptions.regionEngineOptionsList）用于初始化集群，不论 pd 是否 fake，都需要有一个配置，如果 pd = fake 那么一直沿用是这个配置，如果使用 pd, 在初始化集群后便不再依赖本地配置了(自动注册)
>
*言下之意 无论pd是否fake, 我都无需配置placementDriverOptions .regionRouteTableOptionsList*
>
> > 如何快速查看分片是否均匀，查看方式有哪些
> 
> 代码侧从 `com.alipay.sofa.jraft.rhea.client.pd.StatsCollector` 获取，目前没有后台管理系统查看相关信息，不过可以从 pdServer 上查看日志，会由 `com.alipay.sofa.jraft.rhea.pipeline.handler.LogHandler` 打印 stats 信息到日志中。
> 
*initialPdServerList: 127.0.0.1:8181,127.0.0.1:8182,127.0.0.1:8183，那就是说再启动pdServer服务就能通过此处配置地址端口查看了*
>
> 另外，spilt 是自动的，默认使用 handler（基于 spi，可以定制）： `com.alipay.sofa.jraft.rhea.pipeline.handler.SplittingJudgeByApproximateKeysHandler` 基于当前 region 中 key 的数量， 默认配置在 `com.alipay.sofa.jraft.rhea.options.StoreEngineOptions#leastKeysOnSplit`
* 既然spilt 是自动的，那storeEngineOptions.regionEngineOptionsList的key range无论配置多少个，无论数据是否均匀，就都可以自动均衡了。这样我是否可以假设我配置了包含最小下届和最大上界的region后，其它中间region的上下界就可用作区分region个数和均衡数据了。*
>
*另外本人有关上下界的盲点：Client get、put方法中的key和通过findRegionByKey()和storeEngineOptions.regionEngineOptionsList中的startKey、endKey比较时是原值比较还是计算key的hash值后进行比较。。。换句话说，startKey、endKey是hash值范围还是key原值范围？
个人理解：Client get、put经过hash计算确认所在region进行存取操作。
存在疑惑：我的get、put存储的key是根据业务形态自定义任意形式字符串，自己通过一致性哈希算法将所有的键根据哈希函数映射到 0 ~ 16383 整数槽内，相应配置regionEngineOptionsList中startKey～endKey：0 ~ 16383 。存取时用的是hash key? 明显不成立。
以上，请指教。非常感谢。

**Comment by fengjiachun** [comment]
> startKey、endKey比较时是原值比较还是计算key的hash值后进行比较。。。

按照 bytes 顺序，可以稍微看一眼代码就知道了
