### ISSUE TITLE
Would it be better to remove dependency of log4j 

### ISSUE THREAD

**Issue by scanry** [sofastack/sofa-jraft#491]
### Your question

Describe your question clearly

### Your scenes

Describe your use scenes (why need this feature)

### Your advice

Describe the advice or solution you'd like

### Environment

- SOFAJRaft version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by fengjiachun** [comment]
Only `jraft-example` module has dependency of log4j

**Comment by fengjiachun** [comment]
@scanry Tks, I will modify the scope to `test`
