### ISSUE TITLE
Does prior leader stops accepting new client requests when transfer leader ?

### ISSUE THREAD

**Issue by runzhiwang** [sofastack/sofa-jraft#498]
As the paper shows, when prior leader transfer leader ship to other server, the prior leader must stop accepting new client requests.
But I did not find the related code, can anyone help point where the code is ?

![image](https://user-images.githubusercontent.com/51938049/89622847-428ecb00-d8c6-11ea-877c-6e74b1ea5e56.png)

**Comment by zongtanghu** [comment]
Do you want to find some contents of priority leadership elections?

**Comment by runzhiwang** [comment]
@zongtanghu  Thanks for reply. As raft-paper shows, when transfer leadership,  prior leader stop accepting client requests.
But I do not find the code.
![image](https://user-images.githubusercontent.com/51938049/90122737-56d43b80-dd90-11ea-9cff-98f8153102ee.png)

**Comment by waynexia** [comment]
Hi, I think this might be something like following:

1.  When a leader is told to transfer its leadership, it will set its status to `STATE_TRANSFERRING`. [code](https://github.com/sofastack/sofa-jraft/blob/33a4a65ed968649643653ddb39da06bf3af90850/jraft-core/src/main/java/com/alipay/sofa/jraft/core/NodeImpl.java#L3168)
2.  Before a node handling its task (like `apply` a request from client), the state will be checked. And return an error if this node find it's not leader anymore. [code](https://github.com/sofastack/sofa-jraft/blob/33a4a65ed968649643653ddb39da06bf3af90850/jraft-core/src/main/java/com/alipay/sofa/jraft/core/NodeImpl.java#L1348)

Hope this is correct and can help.

**Comment by killme2008** [comment]
@waynexia yep, you are correct.
