### ISSUE TITLE
使用了官方的例子压测两个小时，日志项被删除后，空间依旧没释放

### ISSUE THREAD

**Issue by as378341313** [sofastack/sofa-jraft#501]
### Your question

我使用了官网的计数器例子，不停执行两个小时，发现存放日志项的tmp/log目录占用的空间越来越大，但是我在看源码的时候，在生成快照的时候，会把不需要使用的日志项删除，结果删除完，日志占用的空间还是那么大，只有重启jraft后才能够把占用的空间释放

### Your scenes

Describe your use scenes (why need this feature)

### Your advice

Describe the advice or solution you'd like

### Environment

- SOFAJRaft version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by killme2008** [comment]
这是因为 rocksdb 的删除是在 compaction 的时候做的，这个时间不受控，虽然可以人工触发下。你可以持续压更长时间看下。

**Comment by as378341313** [comment]
> 这是因为 rocksdb 的删除是在 compaction 的时候做的，这个时间不受控，虽然可以人工触发下。你可以持续压更长时间看下。

我尝试了一下，并不是因为rocksdb的删除时是在compaction的时候做的，deleteRange我看官网的解释是当删除量足够大的时候会直接删除，后面我在每一次执行rocksdb删除后，我都手动执行了一次compaction，发现日志量并没有明显降低，观察到占用空间大的是000x.log文件，在官网上查到这种文件对应的是wal文件，假如我们没有设置大小的话，它最大能达到2g左右，后面我在rocksOption中设置了maxTemporaryLogSize（wal最大日志量）再进行压测后，日志占用空间就变得很小了

**Comment by killme2008** [comment]
@as378341313 感谢分享， wal 确实需要占用这么多。

**Comment by as378341313** [comment]
> @as378341313 感谢分享， wal 确实需要占用这么多。

需要，我压测的时候最高能占用到3G多

**Comment by fengjiachun** [comment]
> > 这是因为 rocksdb 的删除是在 compaction 的时候做的，这个时间不受控，虽然可以人工触发下。你可以持续压更长时间看下。
> 
> 我尝试了一下，并不是因为rocksdb的删除时是在compaction的时候做的，deleteRange我看官网的解释是当删除量足够大的时候会直接删除，后面我在每一次执行rocksdb删除后，我都手动执行了一次compaction，发现日志量并没有明显降低，观察到占用空间大的是000x.log文件，在官网上查到这种文件对应的是wal文件，假如我们没有设置大小的话，它最大能达到2g左右，后面我在rocksOption中设置了maxTemporaryLogSize（wal最大日志量）再进行压测后，日志占用空间就变得很小了

请问下，有 maxTemporaryLogSize 这个 option ？ 没看到啊
