### ISSUE TITLE
关于堆外内存问题

### ISSUE THREAD

**Issue by bobbylv** [sofastack/sofa-jraft#515]
### Your question
![image](https://user-images.githubusercontent.com/69021837/94383171-dd42b200-0171-11eb-8572-40a02389583d.png)

ZIPInputStream使用Inflater申请堆外内存，Deflater释放内存，调用close()方法来主动释放。如果忘记关闭，Inflater对象的生命会延续到下一次GC。在此过程中，堆外内存会一直增长。我在做内存监控时发现堆外内存会占用较多，看了这部分代码，觉得是否应该close呢？

**Comment by killme2008** [comment]
了解下 try 语法，会自动 close 定义的局部变量。

**Comment by killme2008** [comment]
对外内存猜测是几个部分， rocksdb 的， netty 的，以及 jvm 自身的一些占用。
