### ISSUE TITLE
Provide a listener API for tracking cluster member state

### ISSUE THREAD

**Issue by alexei-osipov** [sofastack/sofa-jraft#521]
# Use case and problem

We make a system that uses SOFAJRaft for leader election and we also want to use it for cluster member management. The basic idea that we want to consider our cluster member "live" for our systems as long as it's "live" for current leader of SOFAJRaft cluster.

As for now SOFAJRaft provides a `Node#listAlivePeers()` API method that almost sufficient for our task. The missing piece is there is no simple way to track state change for a member. We want to know when a Peer changes state from "live" to "dead" and vice versa.

So as for now we have to periodically poll `Node#listAlivePeers()`. That works but such polling seems redundant because `NodeImpl#stepDownTimer` already does all necessary work (in `Node#checkDeadNodes0(...)`).

# Feature suggestion

Please add an API method to register a listener that will be executed when Peer state changes.

We understand that right now "live/dead" is a computed property so such API method will require to store "last reported state value" for listeners. However overhead of this seems to be quite low.

Sample draft of how the listener interface might look like
```java
/**
 * Invoked when current node considers that state of a follower have changed.
 * 
 * Invoked only when current node is the leader.
 *
 * @param peerId peer whose status have changed
 * @param alive true means that specified peer now considered alive
 */
void onPeerStateChange(final PeerId peerId, final boolean alive);
```

**Comment by killme2008** [comment]
I think this is an useful feature, we put it into next milestone.

**Comment by alexei-osipov** [comment]
Thank you!

**Comment by fengjiachun** [comment]
> @killme2008 is this issue moved to milestone 1.3.6?

we moved it to 1.3.6

**Comment by killme2008** [comment]
hi, the `ReplicatorStateListener` may be enough.

```java
    public interface ReplicatorStateListener {

        /**
         * Called when this replicator has been created.
         *
         * @param peer   replicator related peerId
         */
        void onCreated(final PeerId peer);

        /**
         * Called when this replicator has some errors.
         *
         * @param peer   replicator related peerId
         * @param status replicator's error detailed status
         */
        void onError(final PeerId peer, final Status status);

        /**
         * Called when this replicator has been destroyed.
         *
         * @param peer   replicator related peerId
         */
        void onDestroyed(final PeerId peer);
    }
```

You can add a listener by `Node#addReplicatorStateListener(ReplicatorStateListener)`.

**Comment by alexei-osipov** [comment]
It seems that `Node#addReplicatorStateListener(ReplicatorStateListener)` is not suitable for the task,
1. When a cluster member goes down then `void onError(final PeerId peer, final Status status)` is executed with status EINTERNAL<1004> each second (not just once).
2. When a node gets back online then there are no any notification on that interface.

It's possible to handle issue 1 with some check but there no way to workaround issue 2.

**Comment by killme2008** [comment]
@alexei-osipov Thanks for your reply. I got it. We can extend the `ReplicatorStateListener` to support this feature in next release.
