### ISSUE TITLE
StateMachine still file storage

### ISSUE THREAD

**Issue by GrapeBaBa** [sofastack/sofa-jraft#522]
### Your question

Can we reuse SegmentFile when implement a file state machine interface?

### Your scenes

We need a raft based stream storage engine

### Your advice

We would like reuse SegmentFile in state machine implementation

### Environment

- SOFAJRaft version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by killme2008** [comment]
I don't get your point clearly, but you can reuse `SegmentFile` in your implementation, SOFAJRaft is licensed under the Apache License 2.0.

**Comment by GrapeBaBa** [comment]
> I don't get your point clearly, but you can reuse `SegmentFile` in your implementation, SOFAJRaft is licensed under the Apache License 2.0.

We need a raft based log file(stream) storage system, we want to use jraft. When we use jraft, we need implement our own state machine interface. In this state machine implementation, actually it is still a log segment storage just like raft WAL, we saw jraft using SegmentFile and RocksDB to archive WAL, so that we consider also use this approach in our own state machine implementation.

**Comment by killme2008** [comment]
Of course, you can use it.
