### ISSUE TITLE
关于transferLeadershipTo方法的疑惑

### ISSUE THREAD

**Issue by Linary** [sofastack/sofa-jraft#530]
### Your question

transferLeadershipTo方法表现得是一个同步方法，传入新的leaderId，返回status，然后用status判断操作是否成功。但跟踪源码发现，transferLeadershipTo其实是给新的leader发了一个TimeoutRequest，然后并未处理请求的Future对象，就返回了Status.OK()。但是如果发送和处理TimeoutRequest时出错了，group状态就和返回出去的status不一致了。

### Your advice

让transferLeadershipTo方法签名与addPeer、removePeer保持一致，传入一个Closure。

### Environment

- SOFAJRaft version: 1.3.3

**Comment by killme2008** [comment]
transferLeadershipTo 接口的说明是
```
Try transferring leadership to |peer|
```

status 只是 try 这个操作是否成功，并不表示最终是否转移成功。不过确实可以传入一个 closure 来监听整个操作是否成功，但是**成功不意味着 transfer 本身成功了，而只是说目标节点主动发起了选举(electSelf)，但是最终是否被选为 leader 是不保证的**。也就是说转移 leadership 终究还是一个 try 的操作，这样看， closoure 似乎也没有必要了。

**Comment by Linary** [comment]
好的，明白了，感谢解答。
