### ISSUE TITLE
Node的isLeader和getLeaderId方法状态不一致

### ISSUE THREAD

**Issue by Linary** [sofastack/sofa-jraft#531]
### Your question

一个Node之前是leader，然后在transferLeader的过程中，触发了状态机的onLeaderStop，但是还没选出新的leader。按道理说onLeaderStop执行后，表示leader已经退位了，那isLeader和getLeaderId的返回值应该是：

- Node.isLeader返回false；
- Node.getLeaderId返回null；

如果说onLeaderStop只是一个中间步骤，并不表示leader已经退位，那应该是第2种情况

- Node.isLeader返回true；
- Node.getLeaderId返回原leaderId。

但是实际上的情况是：

- Node.isLeader返回false
- Node.getLeaderId返回原leaderId

这样一种矛盾的状态我不知道是不是bug。

### Environment

- SOFAJRaft version: 1.3.3

**Comment by fengjiachun** [comment]
在 transferLeader 时只修改了 state == STATE_TRANSFERRING 但是没有设置 leaderId 为 null，虽然好像没什么影响，但确实让 isLeader() 和 getLeader() 两个接口有些矛盾 @killme2008 可以看下

**Comment by Linary** [comment]
@fengjiachun 好的👌，感谢解答

**Comment by killme2008** [comment]
这种不一致是存在的，考虑到最经常用法是这样：

```java
if(node.isLeader()) {
   ...getLeaderId...
}
```

这种不一致是可以接受的。不过这种不一致也不会造成什么影响，因为最终你都需要客户端配合来做 redirect 兜底。

**Comment by Linary** [comment]
@killme2008 我感觉这个最经常用法有些奇怪。
```
if(node.isLeader()) {
   // 既然if已经判断自己是leader了，那这里不应该是直接node.getPeerId()吗？当然如果考虑到极端情况，if判断自己是leader后，在走到这一行这个很短的时间里又发生了leader切换，那确实应该这样用。
   ...getLeaderId...
}
```

另外在我们的应用场景中因为这个不一致造成了比较严重的bug，如下：

前提：我们的leader和follower对外表现的都是支持写请求的，而具体落到follower的写请求会转发到leader处理，所以我们在写请求的方法入口处有类似这样的处理逻辑：

```
// 1. 确保leader存在，如果不存在就等待选出leader，实际是用node.getLeaderId是否为null来判断的
ensureLeaderExist()
// 2. 判断自己是不是leader，用node.isLeader判断
if (!selfIfLeader()) {
    // 3. 转发到leader节点，用node.getLeaderId获取，然后通过rpc转发
    forwardToLeader();
}
```

而由于isLeader和getLeaderId不一致的情况，会导致：步骤1判断leader存在，步骤2判断自己不是leader，步骤3获取到leader节点（其实是自己），然后rpc转发给了自己。

我们没有使用client，而且follower支持写不符合raft的规范，但是我认为这都不是什么特别大的问题。关键点在于上面那两个方法的不一致，让我们用错了。

**Comment by fengjiachun** [comment]
我的建议是，在 transferLeader 期间并且已经修改 state = STATE_TRANSFERRING 的时候，是否可以同时将 leaderId 设置为 null ？
@killme2008

**Comment by killme2008** [comment]
这两个方法本来就存在竞态条件，不一致是使用上需要处理的情况。
