### ISSUE TITLE
RouteTable获取leader失败时,错误信息没有展示

### ISSUE THREAD

**Issue by shibd** [sofastack/sofa-jraft#532]
### Describe the bug

在使用Rheakv时,如果rheakv-server连接rheakv-pd,填写的pdGroupId有误. server没有抛出真实错误信息. 

### Expected behavior

![image](https://user-images.githubusercontent.com/33416836/97384366-849a3c80-190a-11eb-9616-8bf65ebd60c7.png)

### Actual behavior

![image](https://user-images.githubusercontent.com/33416836/97384441-ac89a000-190a-11eb-94c7-3ad34f12d508.png)

### Steps to reproduce

1. 启动pd
2. 启动rheakv-server,填写错误的`PdGroupId`
```
        final PlacementDriverOptions pdOpts = PlacementDriverOptionsConfigured.newConfigured()
                .withFake(false) // use a fake pd
                .withPdGroupId("pd_test")
                .withInitialPdServerList("127.0.0.1:8180,127.0.0.1:8181,127.0.0.1:8182")
                .config();
```

3. 控制台观察错误

### Minimal yet complete reproducer code (or GitHub URL to code)

实际上`RouteTable`在处理错误信息时,漏了一个错误分支. 如下图所示,虽然msg不是ErrorResponse, 但是`CliRequests.GetLeaderResponse`中依然会被下游塞到`ErrorResponse`，这种情况下，应当把下游的返回的信息带出去。

![image](https://user-images.githubusercontent.com/33416836/97384604-fa060d00-190a-11eb-9e06-0af67696b6f2.png)

### Environment

- SOFAJRaft version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by fengjiachun** [comment]
是的 ，基于 grpc 通信时有这个 bug，已经修复，见这里 #513

**Comment by shibd** [comment]
ok, 我rebase master后没有复现.
