### ISSUE TITLE
JRaft来解决存储文件

### ISSUE THREAD

**Issue by Link-Kou** [sofastack/sofa-jraft#534]
菜鸟。刚刚开始使用。

1.问题
JRaft通过Task，将文件通过Kryo序列化,传输。小文件还可以。100KB内的。大文件100Mb或以上的。日志同步就有点太大了，传输也是问题

2.问题
分片的问题，JRaft会所有节点内容一致。存储文件想同步其中一块。不知道能否实现。

**Comment by killme2008** [comment]
文件还是用专门的 dfs 更合适，用 raft 来做这个同步代价太高了，不划算
