### ISSUE TITLE
集群内有，有服务异常导致离线，如何实现获取下线服务

### ISSUE THREAD

**Issue by Link-Kou** [sofastack/sofa-jraft#542]
集群内，任何一个服务下线，我希望能知道下线的服务的IP是哪一个。

场景：负载均衡，每个follower都会承担读的职能。一个服务下线后，需要重新为客户端分配其他的服务

**Comment by killme2008** [comment]
可以使用 RouteTable

参见第 4 节 https://www.sofastack.tech/projects/sofa-jraft/jraft-user-guide/
