### ISSUE TITLE
jraft实现写多，读少的场景疑问

### ISSUE THREAD

**Issue by Link-Kou** [sofastack/sofa-jraft#543]
根据官方文档：
写服务，更改状态机数据，只能提交到 leader 写入。
目前Leader都是单点的，如果写多。leader故障，整个集群内leader选举无论为那个服务都可能是雪崩。

这样子如何优化和保证高可用？

**Comment by killme2008** [comment]
raft 系统是 CP 系统，针对可用性可能的优化手段包括：

* 使用多分组，  multi raft group，可以参照 counter 例子和 rheakv 实现，降低不可用的粒度。
* 适当设置 election timeout，降低不可用时长
* 其他设计手段，比如写入暂存区等等，牺牲一定的 C。
