### ISSUE TITLE
raft log 磁盘占用

### ISSUE THREAD

**Issue by joer1900** [sofastack/sofa-jraft#544]
### Your question
麻烦问下我现在使用rheakv三个节点，写入比较频繁，log这部分是否提供相应的配置，这部分的log随着时间越来越多，有没有相应的清理机制。

**Comment by fengjiachun** [comment]
snapshot 间隔配置的是多久？默认是一小时[com.alipay.sofa.jraft.option.NodeOptions#snapshotIntervalSecs](com.alipay.sofa.jraft.option.NodeOptions#snapshotIntervalSecs) 可以配置间隔再小一点试试， snapshot 后会清理 raft log 的，另外再确认一下是 rheakv 的 data 目录越来越大还是 raft log 目录越来越大？

**Comment by joer1900** [comment]
snapshot 间隔未自定义配置使用的是默认值，raftDataPath 配置目录下log的文件（如000003.log）会一直增长，106M重新分一个，一直累积。

配置如下：
clusterId: 1
# 每个 store 节点包含一个或多个 raft-group 复制组, 这个字段是所有复制组的名称前缀, 所有的 raft-group name 遵循
# [clusterName-regionId]的命名规则
clusterName: registry_rhea

# PD 相关选项设置
placementDriverOptions:
# fake==true 表示在无 PD 模式下启动, 无 PD 模式将失去"自管理"能力, 所有设置都基于当前这个初始的配置文件
  fake: true
# store存储节点的相关选项设置
storeEngineOptions:
  commonNodeOptions:
   electionTimeoutMs: 3000
  rocksDBOptions:
# 是否同步刷盘, 默认为 true, 异步刷盘性能更好, 但是在机器掉电时有丢数据风险
   sync: true
  # raft log存储目录
  raftDataPath: ../data/rhea_raft/
  serverAddress:
# 本机地址, 默认自动获取本机host name, 也可以自己设置
    ip: 192.168.143.89
# 端口, 这个是必须配置的选项, 存储层提供rpc服务的监听端口
    port: 10000
# 集群列表中所有节点的地址列表
initialServerList: 192.168.143.89:10000,192.168.143.90:10000,192.168.143.94:10000
# 是否只从 leader 节点读取数据, 默认为true, 当然从follower节点读也能保证线性一致读, 但是如果一个 follower 节点在同步数据时落后较多的情况下
# 将导致读请求超时, 从而导致 rheaKV 客户端 failover 逻辑启动重新从 leader 节点上尝试读取, 最终结果就是读请求延时较长
onlyLeaderRead: false

**Comment by killme2008** [comment]
应该是这个问题类似，默认 rocksdb wal 最大可以到 2g

https://github.com/sofastack/sofa-jraft/issues/501

**Comment by joer1900** [comment]
我在使用memoryDB 模式的时候依然会出现这个问题。

**Comment by fengjiachun** [comment]
> �我在使用memoryDB 模式的时候依然会出现这个问题。

是 raft log 的 rocksdb wal，即使 rheakv 使用 rocksdb 也没关系，因为 rheakv 关闭了 rocksdb 的 wal， 但是 raft log 不能关闭  wal

**Comment by joer1900** [comment]
我观察了这个raft log，每天生成105M左右分一个新的log，但是现在生成了25个了还是一直在写入，每天都会产生，产生新文件的时候会flush到sstfile，之前的 raft log并未删除。
maxTotalWalSize这个参数我看默认是0，是否可配置？

**Comment by fengjiachun** [comment]
#501 里提到的是另一个 option `maxTemporaryLogSize `, 不过我也没找到这个 option，我问问他

**Comment by killme2008** [comment]
还在持续增加吗？ 从 #501 看，最大应该会到 3g 多。

**Comment by joer1900** [comment]
一直会增加，5G多了还是持续增加的。

**Comment by zhuam** [comment]
Optimizing Space Amplification in RocksDB

**Comment by killme2008** [comment]
@joer1900 目前情况如何？ 如果没有进一步的反馈，我先关闭了。如果发现还有问题，可以再打开
