### ISSUE TITLE
How much follower supporting read can improve the read throughput ?

### ISSUE THREAD

**Issue by runzhiwang** [sofastack/sofa-jraft#547]
For example, there are 3 servers, 1 leader and 2 followers. How much read throughput improvement  if leader and followers all supporting read, compared to only leader supporting read ? Thanks a lot.

I find follower supporting read at: https://www.sofastack.tech/blog/sofa-jraft-linear-consistent-read-implementation/

**Comment by fengjiachun** [comment]
There is no benchmark result yet.
