### ISSUE TITLE
Register DownloadingSnapshot failed: an older snapshot is under installing, cancel downloading

### ISSUE THREAD

**Issue by juaby** [sofastack/sofa-jraft#548]
version 1.3.2
os centos7.x or mac

When the snapshot period is short, the simulated process (the leader) pauses the fault injection, and when the recovery process pauses, 
the new leader keeps printing this log: "A former snapshot is under installing, trying to cancel"
and the new follower keeps printing this log: "Register DownloadingSnapshot failed: an older snapshot is under installing, cancel downloading"

Caught in a loop!

**Comment by juaby** [comment]
@killme2008 
node-1 leader
node-2 fllower
node-3 fllower
kill -SIGSTOP node-1-pid 

Do a series of write operations, the snapshot period is narrowed down, during which it is best to trigger the snapshot, wait for these operations, wait for a while

kill -SIGCONT node-1-pid

**Comment by juaby** [comment]
@killme2008 
The following code, each stage is separately locked, and the installation snapshot request is received concurrently, there will be concurrent security issues, which may be the cause of the installation snapshot cycle

```
public void installSnapshot(final InstallSnapshotRequest request, final InstallSnapshotResponse.Builder response,
                                final RpcRequestClosure done) {
        final SnapshotMeta meta = request.getMeta();
        final DownloadingSnapshot ds = new DownloadingSnapshot(request, response, done);
        // DON'T access request, response, and done after this point
        // as the retry snapshot will replace this one.
        if (!registerDownloadingSnapshot(ds)) {
            LOG.warn("Fail to register downloading snapshot.");
            // This RPC will be responded by the previous session
            return;
        }
        Requires.requireNonNull(this.curCopier, "curCopier");
        try {
            this.curCopier.join();
        } catch (final InterruptedException e) {
            Thread.currentThread().interrupt();
            LOG.warn("Install snapshot copy job was canceled.");
            return;
        }

        loadDownloadingSnapshot(ds, meta);
    }
```

**Comment by killme2008** [comment]
@juaby 我们说中文？你这个我看不懂，能否再解释下

**Comment by fengjiachun** [comment]
> @killme2008
> The following code, each stage is separately locked, and the installation snapshot request is received concurrently, there will be concurrent security issues, which may be the cause of the installation snapshot cycle.
> 
> Ignore this comment if the RPC server is single-threaded
> 
> ```
> public void installSnapshot(final InstallSnapshotRequest request, final InstallSnapshotResponse.Builder response,
>                                 final RpcRequestClosure done) {
>         final SnapshotMeta meta = request.getMeta();
>         final DownloadingSnapshot ds = new DownloadingSnapshot(request, response, done);
>         // DON'T access request, response, and done after this point
>         // as the retry snapshot will replace this one.
>         if (!registerDownloadingSnapshot(ds)) {
>             LOG.warn("Fail to register downloading snapshot.");
>             // This RPC will be responded by the previous session
>             return;
>         }
>         Requires.requireNonNull(this.curCopier, "curCopier");
>         try {
>             this.curCopier.join();
>         } catch (final InterruptedException e) {
>             Thread.currentThread().interrupt();
>             LOG.warn("Install snapshot copy job was canceled.");
>             return;
>         }
> 
>         loadDownloadingSnapshot(ds, meta);
>     }
> ```

是想说 installSnapshot 不是原子操作所以有并发问题？
每一个 installSnapshot 都需要先 registerDownloadingSnapshot 成功，registerDownloadingSnapshot 失败的会直接返回，只要 registerDownloadingSnapshot 是原子操作就可以了
