### ISSUE TITLE
针对 windows 环境做系统测试

### ISSUE THREAD

**Issue by killme2008** [sofastack/sofa-jraft#55]
目前已发现的兼容问题：

1. [x] 文件路径名，部分测试用了临时目录和特殊符号的目录。
2. [x] ProtoBufFile 在文件存在的时候 save 返回 false #54

**Comment by klboke** [comment]
Windows10系统，rocksdb初始化抛如下异常：
```
org.rocksdb.RocksDBException: Compression type Snappy is not linked with the binary.
	at org.rocksdb.RocksDB.open(Native Method)
	at org.rocksdb.RocksDB.open(RocksDB.java:286)
```
解决方案：
升级到rocksdb.version到5.18.3问题解决

**Comment by fengjiachun** [comment]
> Windows10系统，rocksdb初始化抛如下异常：
> 
> ```
> org.rocksdb.RocksDBException: Compression type Snappy is not linked with the binary.
> 	at org.rocksdb.RocksDB.open(Native Method)
> 	at org.rocksdb.RocksDB.open(RocksDB.java:286)
> ```
> 
> 解决方案：
> 升级到rocksdb.version到5.18.3问题解决

当前就是 5.18.3 版本，可能你需要升级一下 jraft？
https://github.com/sofastack/sofa-jraft/blob/master/pom.xml#L76

**Comment by ted12** [comment]
system： win7
jraft : 1.2.6
rocksdb : 5.14.2
使用zulujdk 1.8.0-162/openj9 1.8.0-212 启动就会崩溃

**Comment by fengjiachun** [comment]
1.2.7.beta1 升级到了 rocksdb 5.18.3 版本，rocksdb 对 win 支持貌似不是很好

**Comment by ted12** [comment]
> 1.2.7.beta1 升级到了 rocksdb 5.18.3 版本，rocksdb 对 win 支持貌似不是很好

确实支持差，刚用oraclejdk 也会crash
