### ISSUE TITLE
关于状态机过载问题 FSMCaller is overload

### ISSUE THREAD

**Issue by Linary** [sofastack/sofa-jraft#550]
### 问题概述

follower节点的状态机繁忙时会被step down，并且设置为ERROR态，导致无法继续接收后续的raft日志，即使状态机过一会能从繁忙中恢复。

### 问题详述

`FSMCallerImpl`类中有个`enqueueTask`方法，各种事件都会触发到它这儿，我以commit日志方法说明。

```
private boolean enqueueTask(final EventTranslator<ApplyTask> tpl) {
    if (this.shutdownLatch != null) {
        // Shutting down
        LOG.warn("FSMCaller is stopped, can not apply new task.");
        return false;
    }
    if (!this.taskQueue.tryPublishEvent(tpl)) {
        setError(new RaftException(ErrorType.ERROR_TYPE_STATE_MACHINE, new Status(RaftError.EBUSY,
            "FSMCaller is overload.")));
        return false;
    }
    return true;
}
```

一种最常见的方法调用链为：

```
NodeImpl.handleAppendEntriesRequest -> this.ballotBox.setLastCommittedIndex -> 
this.waiter.onCommitted(lastCommittedIndex) -> FSMCallerImpl.onCommitted -> 
FSMCallerImpl.enqueueTask
```

这一段的逻辑是：follower节点收到心跳消息，先经过一堆状态和index之类的检查，检查通过后设置自己的committedIndex，其实也就是应用日志到状态机，然后推进自己的lastAppliedIndex。

这里是异步的方式应用状态机，具体方式为塞一个ApplyTask（包含新的committedIndex）到disruptor队列中，然后消费者会从队列中拿一个Task构造迭代器应用。

上面的`enqueueTask`就是就是塞ApplyTask到队列的过程，我的问题是：如果状态机比较繁忙，会导致队列被塞满，然后上面代码的`taskQueue.tryPublishEvent`就会false，进入到if里面，调用setError方法给状态机和Raft节点都设置Error状态，并且follower会step down。

我觉得这种方式是不是太暴力了，因为可能过一会follower的状态机就恢复过来了。

我的建议是：是否可以让follower处于一种BUSY状态，将这个BUSY状态反馈给leader，然后leader的上层通过限流，降低发送raft日志的速度，给follower一定时间的恢复期，然后使整个系统处于一个可持续运行的状态。

**Comment by killme2008** [comment]
是的，目前处理的比较粗暴，如果确定能缓过来，并且内存充足，可以适当调大 disruptorBufferSize

https://github.com/sofastack/sofa-jraft/blob/master/jraft-core/src/main/java/com/alipay/sofa/jraft/option/RaftOptions.java#L58

**Comment by Linary** [comment]
@killme2008 嗯嗯，感谢回复。
调大 disruptorBufferSize 确实能降低发生上述问题的频率，但是无法从根本上解决问题。
请问你们是否有计划解决一下该问题呢？短期没有的话我就自己先简单改改用了。

**Comment by killme2008** [comment]
不建议改，自适应限流的话， follower 长期跟不上也有可能，导致投票永远失败，整体不可用。更根本的还是看能不能解决积压的问题，如何让状态机的执行效率更优，或者使用多个 raft group。
