### ISSUE TITLE
 rheaKVStore.bGetSequence方法使用的时候发现如果服务全部重启,会出现跳号的问题,跳了大概702,154个号

### ISSUE THREAD

**Issue by gaochuanneu** [sofastack/sofa-jraft#551]
### Your question

version 1.2.5 rheaKVStore.bGetSequence方法使用的时候发现如果服务全部重启,会出现跳号的问题,跳了大概702,154个号,请问下是什么原因导致的

### Environment

- SOFAJRaft version: 1.2.5
- JVM version (e.g. `java -version`): 1.8
- OS version (e.g. `uname -a`): win10
- Maven version: 3.6.1
- IDE version: idea2020

**Comment by fengjiachun** [comment]
两个可能：
1. 你的 step 参数是多少，如果大于 1 ，那么是每次获取一个范围的
2. 不会出现跳号，应该是 raft log 已经被状态机执行，但是因为重启 client 没有获取到 server 的 response，也就是说被浪费了

要补充一下的是， getSequence 目标是提供一个递增的序列，并没有提供不跳号的保证，比如上面第二点，服务端执行了，但是你的 client 没能成功拿到结果，跳了 号是正常的，从 server 角度 看，是不存在跳号的，但你不应该利用这一点

**Comment by fengjiachun** [comment]
忘了还有第三种可能
你的com.alipay.sofa.jraft.rhea.options.RheaKVStoreOptions#failoverRetries 参数设置的是多少，默认是 2，也就是说 rpc 失败时回重试，也可能是重试导致的， getSequence 不是幂等的，从 client 角度看，是可能不连续的，还是那句话，不应该利用“连续”这个属性， getSequence 不保证连续，只保证递增

**Comment by gaochuanneu** [comment]
感谢回复,我看了failoverRetries 我没有设置这个属性下面是我的代码,我重启试了7-8次,发现这种现象不是每次都发生,而且发生的时候都是跳了700000个号左右,所有我想应该不是重试导致的
`       RheaKVStoreOptions opts = RheaKVStoreOptionsConfigured.newConfigured()
                .withClusterName(sequenceProperties.getClusterName())
                .withInitialServerList(sequenceProperties.getAllNodeAddresses())
                .withStoreEngineOptions(storeOpts)
                .withPlacementDriverOptions(pdOpts)
                .config();`,

**Comment by fengjiachun** [comment]
你使用的是什么版本

**Comment by fengjiachun** [comment]
已下几个问题麻烦回答一下
1. getSequence 的 step 参数是多少？
2. 存储用的是 rocksdb 还是 memoryDB？
3. rheakv 的版本是多少？

**Comment by fengjiachun** [comment]
看了下历史版本代码，你应该用的是 1.2.5 或者之前的版本，的确会有 sequence 跳跃情况，参考 https://github.com/sofastack/sofa-jraft/releases/tag/1.2.5.bugfix

升级一下版本吧，建议升级到最新版本

原因是，在重启是没有删除 rocksdb 的数据，raft log 回放导致 sequence 又被加了一遍，所以跳跃会这么大

**Comment by gaochuanneu** [comment]
> 升级一下版本吧，建议升级到最新版本

感谢,我更新版本试试

**Comment by gaochuanneu** [comment]
问题解决,升级1.3.5版本之后解决了此问题
