### ISSUE TITLE
Sometimes voting ping-pong in leader election

### ISSUE THREAD

**Issue by Excpt0r** [sofastack/sofa-jraft#552]
Hi,

thanks for making this nice framework available! I use it for leader election and it's much more stable and faster than my previous solutions (i.e. using ETCD transaction + watchers).
In rare cases, I observed a behaviour where I'm not sure if it is a configuration issue or might be a bug.

I have 3 stateful k8s pods (myapp-0, myapp-1, myapp-2) using jraft for leader election, and for stability tests I force-shutdown the VM where the leader runs.
In the attached logfile (from myapp-2) at time 16:27:27,790 the pods are up and running, myapp-1 being the leader that is shut down then at 16:30:40,138.
The election of leader between the remaining instances myapp-0 and myapp-2 takes pretty long in that case, and shows a ping-pong in voting, finally voting a leader at 16:30:57,719.

I'm not sure if increasing electionTimeout above 1000ms and/or setting stepDownWhenVoteTimedout=false would be a solution here?
The problem is not easy to reproduce, thanks for any help!

[election.log](https://github.com/sofastack/sofa-jraft/files/5959933/election.log)

### Environment

- SOFAJRaft version: 1.3.4
- JVM version (e.g. `java -version`): OpenJDK 64-Bit Server VM 18.9 (build 11.0.9.1+1, mixed mode)

**Comment by killme2008** [comment]
What's your configuration of raft options?

**Comment by killme2008** [comment]
Do you have log in myapp-0 ? It looks like myapp-0 processed vote request too slow, and myapp-2 steps down by `fail to get quorum vote-granted`.

**Comment by Excpt0r** [comment]
I'm using the default NodeOptions (electionTimeoutMs = 1000, electionHeartbeatFactor = 10)
Logs for myapp-0 are not there anymore unfortunately, but if the problem is reproduced, I will fetch it.

**Comment by killme2008** [comment]
@Excpt0r Ok, if you have more logs, please let us known, we will look into it.

**Comment by killme2008** [comment]
I close this issue right now, reopen it if you repeat the problem.
