### ISSUE TITLE
[Question] Why Node init need using conf in log.

### ISSUE THREAD

**Issue by haoyann** [sofastack/sofa-jraft#556]
### Your question
Why Node init need using conf in log. 
When there is a log, use conf in the log, which will cause the modified configuration to not take effect unless the log is cleaned.
https://github.com/sofastack/sofa-jraft/blob/16979b15e9d4828375875241a5ba984d450cd439/jraft-core/src/main/java/com/alipay/sofa/jraft/core/NodeImpl.java#L1024-L1031

### Your scenes

Describe your use scenes (why need this feature)

### Your advice

Describe the advice or solution you'd like

### Environment

- SOFAJRaft version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by fengjiachun** [comment]
The `conf` only works on initialization, and any conf changes should be stored in the raft log, so only the raft log is trusted.
Assuming you arbitrarily modify the conf, such as replacing 2 nodes (without passing through the raft log), this may result in data loss.

**Comment by haoyann** [comment]
Thank you, but this function can only change the cluster configuration when the raft cluster is working normally. When the cluster is abnormal or stops running, you may not get the latest configuration if you modify the configuration.

**Comment by fengjiachun** [comment]
I guess what you need is `reset peers` :

https://github.com/sofastack/sofa-jraft/blob/master/jraft-core/src/main/java/com/alipay/sofa/jraft/CliService.java#L76

https://github.com/sofastack/sofa-jraft/blob/master/jraft-core/src/main/java/com/alipay/sofa/jraft/Node.java#L217

```
     Reset the configuration of this node individually, without any replication
     to other peers before this node becomes the leader. This function is
     supposed to be invoked when the majority of the replication group are
     dead and you'd like to revive the service in the consideration of
     availability.
     Notice that neither consistency nor consensus are guaranteed in this
     case, BE CAREFULE when dealing with this method.
```

**Comment by haoyann** [comment]
Thanks for your answer.
