### ISSUE TITLE
springboot服务接入jraft的一些疑问？请大神帮忙指点一下

### ISSUE THREAD

**Issue by monkeysungit** [sofastack/sofa-jraft#557]
### Your question

浏览器-->后端单体服务-->mysql，需求是后端服务要做集群，数据存在本地缓存，有共识需求。有如下疑问？
1、需要新加一层client层做根据groupId和IP绑定server，然后更新路由表，获取leader这些动作吗?  
2、server端改造点，新加ServiceStateMachine， 凡是需要由Raft控制的服务都加上RaftService注解，还需要其他改造吗？
3、maven 引入registry-store-jraft包 ？

小白一枚，counter例子大致可以看懂，不知道怎么用到自己项目上，望大神们不吝赐教。
SOFARegistry的metaServer用到了jraft，看源码也有点晕，不知从何处下手改造。

后端服务是传统的springboot 提供rest服务给前端

**Comment by killme2008** [comment]
1. 要的，使用 RouteTable，请阅读开发指南。
2. 服务端最重要就是实现自己的状态机。
3. 不需要。

我的建议是将 raft 相关科普文章阅读下，理解 raft 解决什么问题，接下来阅读用户指南，结合 counter 例子。

**Comment by monkeysungit** [comment]
> 1. 要的，使用 RouteTable，请阅读开发指南。
> 2. 服务端最重要就是实现自己的状态机。
> 3. 不需要。
> 
> 我的建议是将 raft 相关科普文章阅读下，理解 raft 解决什么问题，接下来阅读用户指南，结合 counter 例子。

多谢
