### ISSUE TITLE
[Question]Raft learner to follower

### ISSUE THREAD

**Issue by stream2000** [sofastack/sofa-jraft#560]
### Your question

Does jraft support upgrade a learner node to a follower node? I've read the interface provided by CliService and only found interfaces for adding/removing/modifying/getting learners. 

### Your scenes

Describe your use scenes (why need this feature)

### Your advice

Describe the advice or solution you'd like

### Environment

- SOFAJRaft version: latest version
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by killme2008** [comment]
@stream2000 Sorry, the feature is not supported right now, we can implement it in new release.

**Comment by stream2000** [comment]
> @stream2000 Sorry, the feature is not supported right now, we can implement it in new release.

Thanks for your answer!

**Comment by a364176773** [comment]
please let me try

**Comment by a364176773** [comment]
设计方案：
利用现用接口，
1.移除learner，再添加一个follower，removeLearners ->addPeer
2.changePeers来实现learner转化为follower
3.resetPeer
