### ISSUE TITLE
ByteBuffer的array size为0时，会出现iterator的data对象为0

### ISSUE THREAD

**Issue by evazca** [sofastack/sofa-jraft#562]
### Describe the bug

发现在特定条件下在statemachine的onApply时iterator.getData()是null。

### Expected behavior
不应该出现该情况
### Actual behavior
空指针
### Steps to reproduce
我们的pb对象只有一个元素为repeated  xxx。我们设计的方案为repeated对象可以为空，此时会执行一些特殊逻辑。然后发现pb序列化后生成一个size为0的bytebuffer，可以正常反序列化。该proposal leader可以正常apply，follower报空指针错误。
怀疑问题在rpc处理size为0的bytebuffer这边。

### Environment

- SOFAJRaft version:    1.3.5
- JVM version (e.g. `java -version`):     不重要
- OS version (e.g. `uname -a`):            不重要
- Maven version:                                 不重要
- IDE version:                                       不重要

**Comment by killme2008** [comment]
简单来讲是不是说你们放了一个空的 ByteBuffer(size=0) 作为 data，在复制到 follower 之后变为 null 了？

**Comment by evazca** [comment]
是的

**Comment by killme2008** [comment]
应该是这行引起的

https://github.com/sofastack/sofa-jraft/blob/master/jraft-core/src/main/java/com/alipay/sofa/jraft/entity/codec/v2/V2Decoder.java#L109

你们先可以暂时兼容处理下，如果为 null 也表示 empty buffer，我们尽快修复下

**Comment by evazca** [comment]
好的，我已经做了null转zero byte的兼容处理了。
