### ISSUE TITLE
为什么SnapshotExecutorImpl初始化需要执行this.fsmCaller.onSnapshotLoad

### ISSUE THREAD

**Issue by evazca** [sofastack/sofa-jraft#565]
### Your question
为什么SnapshotExecutorImpl初始化需要执行this.fsmCaller.onSnapshotLoad

Describe your question clearly
很多场景不需要load snapshot。 一般都可以通过幂等保证数据一致性。比如我们的场景statemachine是基于rocksdb存储，proposal幂等。
### Your scenes

Describe your use scenes (why need this feature)

### Your advice
可以加config选择需不需要
Describe the advice or solution you'd like

### Environment

- SOFAJRaft version:
- JVM version (e.g. `java -version`):   不重要
- OS version (e.g. `uname -a`):           不重要
- Maven version:                                不重要
- IDE version:                                        不重要

**Comment by killme2008** [comment]
你能保证，不实现 `StateMachine#onSnapshotLoad` 即可。

**Comment by evazca** [comment]
> 你能保证，不实现 `StateMachine#onSnapshotLoad` 即可。

不行，我需要snapshot功能。或者用jraft的功能来说，我不需要FirstSnapshotLoad，需要的是installSnapshot。这两个目前均调用onSnapshotLoad

**Comment by killme2008** [comment]
你可以自己通过一个变量来确认是否是第一次加载。从类库角度，我们不能假设状态机都能做到幂等，启用 snapshot 后，会尝试加载 snapshot，之后重新回放 snapshot 起点日志到最新的日志。

**Comment by evazca** [comment]
不合适啊，statemachine并不能确切知道是第一次启动加载还是无数据加载snapshot。变量的方案是没法做到bug free的，而且也很难实现的比较优雅。类库不能假设我同意，通过加一个配置，default加载，可以自定义不初始化加载也是可以的吧。

当然具体到我这边的使用是rocksdb的实现来说。加载的成本并不会很高，没有该功能也是不影响的。只是觉得强制加载也不是必须的吧。

**Comment by killme2008** [comment]
你先理解下 snapshot 机制和 statemachine 的交互吧。每次启动都是假设 statemachine 是空白的，所以需要加载 snapshot。

**Comment by killme2008** [comment]
StateMachine 每次启动都假设是空白的：

1. 没有 snapshot，那就从第一条日志重放到现在最新。
2. 存在 snapshot，加载 snapshot，重放从 snapshot 的日志到最新。

**Comment by evazca** [comment]
我能理解你们的这个假设，但是这个假设本身很奇怪。。。
snapshot是状态机提供的，换而言之已经执行完了。就不该没有，除非故障，但是故障检查应该由statemachine自己实现。
raft实现并没有每次启动必须假设statemachien是空白的，相反，raft机制是基于statemachine执行后就不会变了。

然后举个例子。如果我的statemachine是基于remote storage实现的（比如数据库，虽然并不恰当），而每次启动后的这次load是非必要，且成本非常高的。

**Comment by killme2008** [comment]
statemachine 如果启动不清空的话，针对你的 case，是可以额外在 rocksdb 或者某个地方持久化保存 last applied index（定期保存，或者每次保存），那么在 `onSnapshotLoad` 的时候，可以判断 snapshot 的 index 是否已经存在 state machine 里，这样可以跳过,  `onApply` 的时候也可以加快。

**Comment by killme2008** [comment]
raft 本身是没有必须有这个假设，只是我们选择实现如此（或者说 braft 实现如此），我们认为 state machine **总是**可以从 log 或者 snapshot + log 的方式完整重建出来，这样是可以百分百确保数据一致性和正确性。

实际使用中，可以根据自己的情况来优化，上面提了一个办法。

**Comment by evazca** [comment]
感谢思路，也感谢回答。尊重你们的设计。

Ps：特意查了一下，etcd也是一样的。
