### ISSUE TITLE
rheakv节点启动慢

### ISSUE THREAD

**Issue by hanzhihua** [sofastack/sofa-jraft#568]
版本是1.33

我使用rheakv，kv数据量查不多100G左右，使用了snapshot功能，但每次启动节点在load snaphost都很慢，
不知道你们 有没有使用硬链接方式来实现snaphost

**Comment by fengjiachun** [comment]
1. 是 single raft group 还是 multi raft group ？
2. rheakv 有一个配置:[fastSnapshot](https://github.com/sofastack/sofa-jraft/blob/master/jraft-rheakv/rheakv-core/src/main/java/com/alipay/sofa/jraft/rhea/options/RocksDBOptions.java#L36), 默认没打开，可以改为 true 再试一下

**Comment by hanzhihua** [comment]
看到了，如果100G的数据，解压，然后load都需要几十分钟，你们现在使用参加最大的数据量有多少呢？

**Comment by fengjiachun** [comment]
> 看到了，如果100G的数据，解压，然后load都需要几十分钟，你们现在使用参加最大的数据量有多少呢？

single raft group 还是 multi raft group？ 我们没有过单 group 这么大数据量的

**Comment by fengjiachun** [comment]
通常单  group 这么大数据量也是不合理的，没人这么做，等 snapshot 需要在网络中复制的时候 100g 将导致更大的问题

**Comment by hanzhihua** [comment]
multi raft group ,kv的数据总量有100G，100G的数据量一般是多个region呢？

**Comment by hanzhihua** [comment]
另外，咨询一下，reahkv在阿里内部有线上使用吗，kv数据量规模有多大呢？集群规模有多大呢？谢谢

**Comment by fengjiachun** [comment]
1. 经验值是单个 group  100~200M 比较合适，你的解压缩慢的话请提供详细点的信息，比如单机多少个 group 导致的启动慢？单 
 group 多大数据量，这些信息都需要提供一下
2. rheakv 我们自己内部就在线上使用，内部也还有很多其他用户，集群规模的话不方便透露了

**Comment by killme2008** [comment]
zip 压缩这块可能可以采用并行压缩

https://commons.apache.org/proper/commons-compress/apidocs/org/apache/commons/compress/archivers/zip/ParallelScatterZipCreator.html

**Comment by fengjiachun** [comment]
> zip 压缩这块可能可以采用并行压缩
> 
> https://commons.apache.org/proper/commons-compress/apidocs/org/apache/commons/compress/archivers/zip/ParallelScatterZipCreator.html

如果他是单台机器上需要解压缩 100g， 并行压缩应该也解不了他的问题，核心应该是把单  group 的 size 缩小，然后每个机器上分布少数个 group

**Comment by hanzhihua** [comment]
嗯，单节点可能数据量有几十G左右，主要是load snapshot会比较慢，有什么解决方案。另外raft snaphost是否可以使用rocksdb sst文件的硬链接方式吗？而不是压缩 rocksdb checkpoint

**Comment by fengjiachun** [comment]
> 主要是load snapshot会比较慢，有什么解决方案?
缩小单个 raft group 的 size，然后每台机器（进程）分布少量的 raft group，一个 raft group 是数据搬迁的最小单位，通常分布式数据库一个 region 也是只有几百兆，比如 TiDB 一个 region 好像是 200m 左右

> 另外raft snaphost是否可以使用rocksdb sst文件的硬链接方式吗？
rocksdb 侧 checkpoint 机制并没有直接去拷贝文件，就是对 sst 文件的硬链接，你现在应该是慢在解压缩，不是慢在 checkpoint

**Comment by hanzhihua** [comment]
谢谢，等下我试试
另外关于split，一般是多大分裂呢？有配置吗？

**Comment by fengjiachun** [comment]
> 另外关于split，一般是多大分裂呢？有配置吗？

rheakv 里的 split 还比较简单并且没有在生产上正式使用过，另外只提供了按照 key 的数量来进行 split，建议提前分配好 region，这样就不需要使用 pd 角色了
如果不能做到提前分配好 region 的话，那么需要引入 pd，并且最好自行扩展一个 split 的策略（按照 data size 来 split），扩展是基于 SPI 的，不难做到

**Comment by hanzhihua** [comment]
收到，谢谢

**Comment by killme2008** [comment]
> > zip 压缩这块可能可以采用并行压缩
> > https://commons.apache.org/proper/commons-compress/apidocs/org/apache/commons/compress/archivers/zip/ParallelScatterZipCreator.html
> 
> 如果他是单台机器上需要解压缩 100g， 并行压缩应该也解不了他的问题，核心应该是把单 group 的 size 缩小，然后每个机器上分布少数个 group

嗯，我不是说这个能解决他的问题，他的问题还是要拆分 multi group，我的意思这里是可以优化的一个点，后面我们可以搞下。

**Comment by fengjiachun** [comment]
> > > zip 压缩这块可能可以采用并行压缩
> > > https://commons.apache.org/proper/commons-compress/apidocs/org/apache/commons/compress/archivers/zip/ParallelScatterZipCreator.html
> > 
> > 
> > 如果他是单台机器上需要解压缩 100g， 并行压缩应该也解不了他的问题，核心应该是把单 group 的 size 缩小，然后每个机器上分布少数个 group
> 
> 嗯，我不是说这个能解决他的问题，他的问题还是要拆分 multi group，我的意思这里是可以优化的一个点，后面我们可以搞下。

恩，是的，可以优化的点

**Comment by fengjiachun** [comment]
先关闭了，后续还有问题可以再打开
