### ISSUE TITLE
关于rheakv region的几个问题

### ISSUE THREAD

**Issue by Mervey0324** [sofastack/sofa-jraft#572]
1. 不启用PD Server时，Region还会自动split吗？
2. 如何控制每个region的副本数，即每个raft group的peer数？
3. 如何对整个KV集群进行扩/缩容？对每个region进行add/remove replica操作还是有其他接口？

**Comment by fengjiachun** [comment]
1. 不会自动 split
2. 每个 raft group 的副本，通过 CliService 管理
3. 同 2，参考 CliService

建议先看文档： https://www.sofastack.tech/projects/sofa-jraft/overview/
