### ISSUE TITLE
Adding a new node in a cluster

### ISSUE THREAD

**Issue by Tanveerbaba** [sofastack/sofa-jraft#575]
### Your question

I've **3** initial server nodes with **16** regions and the replication factor is **3**.  I want to add a new node (Let's assume 4th node) in a cluster using remote PD but when I try to add a Node, it seems the region engine is not being refreshed(or copied) to a newer node. Is there any different way for that?. 

For more Information, NodeManager not having all the 16 regions mapped for the new Node. So, when I try to call **pdClient.addReplica()**, it fails as **Node-4** doesn't have information of the region engine. In our case, the regionEngineOptions list will be empty so the StoreEngine will add the **DEFAULT_REGION_ID**. There must be a way to update or refresh regionEngineOptions for a new Node?

Hope I'm Clear...

### Your scenes

I simply want to add or remove new nodes on-demand using Remote PD.

### Your advice

Describe the advice or solution you'd like

### Environment

- SOFAJRaft version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by fengjiachun** [comment]
>  In our case, the regionEngineOptions list will be empty so the StoreEngine will add the DEFAULT_REGION_ID

If you want multi regions, every region must have a regionId, so the regionEngineOptionsList can not be empty.


Also, a few test-cases would help me understand...
