### ISSUE TITLE
Add Segment Log Storage Index module, remove dependency on rocksdb

### ISSUE THREAD

**Issue by fengjiachun** [sofastack/sofa-jraft#577]
## Introduction
  SOFAJRaft is a production-level, high-performance Java implementation based on the RAFT consistency algorithm that supports MULTI-RAFT-GROUP for high-load, low-latency scenarios. With SOFAJRaft you can focus on your business area. SOFAJRaft handles all RAFT-related technical challenges. SOFAJRaft is very user-friendly, which provides several examples, making it easy to understand and use

## Target
  The current implementation of LogStorage adopts the design of separate index and data. We write the offset and key as the index into rocksdb, and write the log entry (data) into Segment Log Files,  because users who use SOFAJRaft often also use different versions of rocksdb , Which requires users to have to replace their own rocksdb version to adapt to SOFAJRaft, so we hope to make an improvement: remove the dependency on rocksdb and build a java implementation index module.

## 简介
  SOFAJRaft 是一个基于 RAFT 一致性算法的生产级高性能 Java 实现，支持 MULTI-RAFT-GROUP，适用于高负载低延迟的场景。 使用 SOFAJRaft 你可以专注于自己的业务领域，由 SOFAJRaft 负责处理所有与 RAFT 相关的技术难题，并且 SOFAJRaft 非常易于使用，你可以通过几个示例在很短的时间内掌握它。

## 目标
  当前 LogStorage 的实现，采用 index 与 data 分离的设计，我们将 key 和 value 的 offset 作为索引写入 rocksdb，同时日志条目（data）写入 Segment Log，因为使用 SOFAJRaft 的用户经常也使用了不同版本的 rocksdb，这就要求用户不得不更换自己的 rocksdb 版本来适应 SOFAJRaft， 所以我们希望做一个改进：移除对 rocksdb 的依赖，构建出一个纯 java 实现的索引模块。

**Comment by hzh0425** [comment]
@fengjiachun 您好

您好,对于这个任务,我是这样考虑的:

每一块的segmentFile,都赋予一块偏移量索引offsetIndex,索引项的格式:

<Offset,PhysicalPosition>,其中,Offset代表相对于当前SegmentFile的startLogIndex的偏移量,PhysicalPosition代表该日志在文件中的物理地址

同时,我想利用以下的方式进行搜索优化:

- 每块OffsetIndex保存的是稀疏索引,而不是全量索引,搜索时可利用二分进行搜索小于等于当前targetIndex中最大的LogIndex

- 多块的segmentFile维护在跳表中,搜索日志时(假设要搜索targetIndex):
  先通过跳表查询该targetIndex所在的SegmentFile
  接着在SegmentFile对应的OffsetIndex中利用二分搜索,查询离该targetIndex最近的索引项
  最后根据索引项中的物理地址,从PhysicalPosition开始,往后依次对比,读取日志
  此外.OffsetIndex文件和SegmentFile文件都通过Mmap 内存映射文件技术进行加速读写
![image](https://user-images.githubusercontent.com/58988019/120308344-97dd1280-c306-11eb-8403-32dd4c20ce45.png)

- 在上面的方法中,搜索LogEntry时,似乎仍需要多次的遍历磁盘,我想,是否可以通过BloomFilter进行进一步的加速.也即,每一块的SegmentFile,还多了一个BloomFilter过滤器,在SegmentFile中搜索LogEntry时,先通过BloomFilter进行过滤,如果判断不在该SegmentFile中,则无需搜索,直接返回即可.当然,BloomFilter也可以通过Mmap技术进行加速读写

以上的思路是我的初步想法,如有不对的地方,请指正,谢谢!

**Comment by fengjiachun** [comment]
@hzh0425 谢谢，我们会尽快看一下
