### ISSUE TITLE
Some tune reference etcd 

### ISSUE THREAD

**Issue by horizonzy** [sofastack/sofa-jraft#588]
### Your advice
Hi, I notice the doc at https://etcd.io/docs/v3.4/tuning/#disk and https://etcd.io/docs/v3.4/tuning/#network.

It's intersting, I think jraft also can use it to optimize, maybe we can append it in jraft docs.

**Comment by fengjiachun** [comment]
Good! Can you send a PR for this? @horizonzy 
repo: https://github.com/sofastack/sofastack.tech

**Comment by horizonzy** [comment]
Ok, I will append it at night.
