### ISSUE TITLE
USe leader election along with RheaKV

### ISSUE THREAD

**Issue by amit2103** [sofastack/sofa-jraft#589]
Hey , thanks for the awesome project. I have an usecase where I need to use the RheaKV and also need leader election along with it.
Is there a way to do it without instantiating two raft clusters ?  What I want is kind of support for multi-raft which will allow me to do consensus in parallel for different sets of keys

Regards

**Comment by fengjiachun** [comment]
Maybe this is what you need： `com.alipay.sofa.jraft.rhea.LeaderStateListener` 
See [RheaKVStore#addLeaderStateListener](https://github.com/sofastack/sofa-jraft/blob/master/jraft-rheakv/rheakv-core/src/main/java/com/alipay/sofa/jraft/rhea/client/RheaKVStore.java#L734)
