### ISSUE TITLE
如何判断状态机处在日志回放或者load snapshot阶段

### ISSUE THREAD

**Issue by Mervey0324** [sofastack/sofa-jraft#594]
当节点重启或者新节点加入，节点的数据会通过load snapshot和日志回放来追赶，那如何判断节点/状态机处在日志回放或者load snapshot阶段呢？

**Comment by fengjiachun** [comment]
没有这个状态

**Comment by Mervey0324** [comment]
好的，了解。后来想了一下，从raft理论上来说一直是apply日志，所以可以说一直是日志回放，只不过是index有快有慢～
