### ISSUE TITLE
是否需要在Snapshot安装时引入多线程断点续传机制

### ISSUE THREAD

**Issue by hzh0425** [sofastack/sofa-jraft#597]
### Your question
在learder snapShot非常大的情况下,需要通过超长时间的RPC将snapShot复制到follower,
为此,是否需要引入多线程断点续传的机制,以加速复制的速度呢?

### Environment

- SOFAJRaft version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by fengjiachun** [comment]
见 #503
