### ISSUE TITLE
若InstallSnapshot执行期间再次接收到新的InstallSnapshot请求，loadSnapshot将不会再被执行

### ISSUE THREAD

**Issue by 312223105** [sofastack/sofa-jraft#605]
### Describe the bug

目前在SnapshotExecutor里有判断是否为重试请求的逻辑(见引用1)，但是正是这一部分逻辑导致一个问题就是：假设第一次`InstallSnapshot`请求的响应消息丢失，发生重试，则第一次未完成的`InstallSnapshot`会回复被中断(见引用3)，并因为参数`ds`和`downloadSnapshot`不同，不会执行后续的`registerDownloadingSnapshot`(见引用2)；而对于第二次`InstallSnapshot`，因`registerDownloadingSnapshot`方法就返回了失败，也不会执行后续的`registerDownloadingSnapshot`，这次请求也不会得到响应。

代码引用：
1. https://github.com/sofastack/sofa-jraft/blob/971648170860a521f821442375c85e54b8787c4b/jraft-core/src/main/java/com/alipay/sofa/jraft/storage/snapshot/SnapshotExecutorImpl.java#L608
2. https://github.com/sofastack/sofa-jraft/blob/971648170860a521f821442375c85e54b8787c4b/jraft-core/src/main/java/com/alipay/sofa/jraft/storage/snapshot/SnapshotExecutorImpl.java#L504
3. https://github.com/sofastack/sofa-jraft/blob/971648170860a521f821442375c85e54b8787c4b/jraft-core/src/main/java/com/alipay/sofa/jraft/storage/snapshot/SnapshotExecutorImpl.java#L652

### Expected behavior

第一次InstallSnapshot请求在第二次请求到来之后提前回复RaftError.EINTR。第二次InstallSnapshot请求在registerDownloadingSnapshot调用失败后提前退出，并在第一次InstallSnapshot请求的函数调用中回复执行结果。

### Actual behavior

见描述。

### Steps to reproduce

在client执行InstallSnapshot期间，server再次发送InstallSnapshot请求。

### Minimal yet complete reproducer code (or GitHub URL to code)

我写了一个单元测试，复现该问题( https://github.com/312223105/sofa-jraft/blob/8114fc41b3e154e225e2788aaa9a143db1bf4ebd/jraft-core/src/test/java/com/alipay/sofa/jraft/storage/SnapshotExecutorTest.java#L145).

### Environment

- SOFAJRaft version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by killme2008** [comment]
这是预期内的行为，不允许并发 install snapshot。

**Comment by 312223105** [comment]
如果第一次rpc响应超时，server重新发送install snapshot，应该不能算并发吧？

**Comment by killme2008** [comment]
@312223105 确实是一个 bug，替换后应该让 registerDownloadingSnapshot 返回 true 往下走，欢迎提个 PR

**Comment by lilei0527** [comment]
![image](https://user-images.githubusercontent.com/55618021/121327428-042ec600-c946-11eb-9339-7a471d9af22a.png)

这一段逻辑一定会被执行，不需要判断if(saved!=null) 吧

**Comment by lilei0527** [comment]
![image](https://user-images.githubusercontent.com/55618021/121329458-d0ed3680-c947-11eb-8df7-e267c96c4ca2.png)

@killme2008  @312223105  这句代码去掉能不能解决上述问题

**Comment by 312223105** [comment]
@lilei0527 只需要修改成 `result = true` 即可，见 #606
