### ISSUE TITLE
如果发现要install的快照文件和最后一次备份的快照文件相同,未添加最后一次备份文件到目前的安装文件目录

### ISSUE THREAD

**Issue by lilei0527** [sofastack/sofa-jraft#610]
### Your question

![image](https://user-images.githubusercontent.com/55618021/121766070-05e4cd80-cb82-11eb-9bc2-aa91a44e6332.png)

如上图所示，如果发现要install的快照文件和最后一次备份的快照文件相同时，仅仅只是将localMeta添加到了write，我翻阅了源

码未发现将上一次备份的文件拷贝到目前安装目录的代码，烦请大佬解释这个疑惑。

**Comment by killme2008** [comment]
上面不是做了一个软链接？

**Comment by lilei0527** [comment]
> 上面不是做了一个软链接？

我口述一下位置吧：LocalSnapshotCopie.javar 314行

**Comment by killme2008** [comment]
@lilei0527 我的意思就是这行的上面这段，就是在做文件软链接。

**Comment by lilei0527** [comment]
> @lilei0527 我的意思就是这行的上面这段，就是在做文件软链接。

 如果被链接的文件（lastSnapshot目录的file） 被删除，这个软链接还能定位到文件吗

**Comment by killme2008** [comment]
那肯定不能，默认 snapshot 都不删除的，人工删除的话需要注意下。一般来说，你也不会删除最近的几个 snapshot。

**Comment by lilei0527** [comment]
> 那肯定不能，默认 snapshot 都不删除的，人工删除的话需要注意下。一般来说，你也不会删除最近的几个 snapshot。

![image](https://user-images.githubusercontent.com/55618021/121990619-a3354100-cdd0-11eb-9539-550751dc2546.png)

![image](https://user-images.githubusercontent.com/55618021/121991044-7170aa00-cdd1-11eb-8854-19122bb502b7.png)


在LocalSnapshotStorage初始化的时候会首先删除除了lastSnapshot以外的备份，并且lastSnapshot也可能在LocalSnapshotWriter

关闭的时候调用unref(lastSnapshotIndex)导致被删除

**Comment by killme2008** [comment]
嗯， snapshot 的逻辑我记错了，不过那个创建的是硬链接，原始文件不会删除直到所有引用也被删除。

你是在阅读源码，还是实际遇到这个问题？

**Comment by lilei0527** [comment]
![image](https://user-images.githubusercontent.com/55618021/121993201-9e26c080-cdd5-11eb-9045-bfe0f758a6ef.png)

我在学习源码，这个是硬链接吧，这样好像就没有问题，即使删除了原文件，也可以通过这个硬链接访问

**Comment by lilei0527** [comment]
@killme2008  请教一下大佬，目前项目中用于给.proto文件生成代码的protoc是那个版本

**Comment by fengjiachun** [comment]
> @killme2008 请教一下大佬，目前项目中用于给.proto文件生成代码的protoc是那个版本

3.5.1
