### ISSUE TITLE
ThroughputSnapshotThrottle may have a bug

### ISSUE THREAD

**Issue by xiaoheng1** [sofastack/sofa-jraft#612]
version：master

Code copied from the master branch：

```
public ThroughputSnapshotThrottle(final long throttleThroughputBytes, final long checkCycleSecs) {
        this.throttleThroughputBytes = throttleThroughputBytes;
        this.checkCycleSecs = checkCycleSecs;
        this.currThroughputBytes = 0L;
        this.baseAligningTimeUs = 1000 * 1000 / checkCycleSecs;
        this.lastThroughputCheckTimeUs = this.calculateCheckTimeUs(Utils.monotonicUs());
    }
```

My personal opinion is that baseAligningTimeUs should be 1000 * 1000 * checkCycleSecs, which converts seconds into milliseconds

and also

```
public long throttledByThroughput(final long bytes) {
        long availableSize;
        final long nowUs = Utils.monotonicUs();
        final long limitPerCycle = this.throttleThroughputBytes / this.checkCycleSecs;
        this.lock.lock();
        try {
            if (this.currThroughputBytes + bytes > limitPerCycle) {
                // reading another |bytes| exceeds the limit
                if (nowUs - this.lastThroughputCheckTimeUs <= 1000 * 1000 / this.checkCycleSecs) {
                    // if time interval is less than or equal to a cycle, read more data
                    // to make full use of the throughput of current cycle.
                    availableSize = limitPerCycle - this.currThroughputBytes;
                    this.currThroughputBytes = limitPerCycle;
                } else {
                    // otherwise, read the data in the next cycle.
                    availableSize = bytes > limitPerCycle ? limitPerCycle : bytes;
                    this.currThroughputBytes = availableSize;
                    this.lastThroughputCheckTimeUs = calculateCheckTimeUs(nowUs);
                }
            } else {
                // reading another |bytes| doesn't exceed limit(less than or equal to),
                // put it in current cycle
                availableSize = bytes;
                this.currThroughputBytes += availableSize;
            }
        } finally {
            this.lock.unlock();
        }
        return availableSize;
    }
```

1000 * 1000 / this.checkCycleSecs Should be modified to 1000 * 1000.

**Comment by killme2008** [comment]
The comment describes the logic here:

```
  // if time interval is less than or equal to a cycle, read more data
                    // to make full use of the throughput of current cycle.
```

`nowUs - this.lastThroughputCheckTimeUs <= 1000 * 1000 / this.checkCycleSecs` is equals to `(nowUs - this.lastThroughputCheckTimeUs )*1000*1000 <= checkCycleSecs`.

**Comment by xiaoheng1** [comment]
> nowUs - this.lastThroughputCheckTimeUs <= 1000 * 1000 / this.checkCycleSecs is equals to (nowUs - this.lastThroughputCheckTimeUs )*1000*1000 <= checkCycleSecs.

nowUs - this.lastThroughputCheckTimeUs <= 1000 * 1000 / this.checkCycleSecs is  not equals to (nowUs - this.lastThroughputCheckTimeUs )*1000*1000 <= checkCycleSecs.

set a = nowUs - this.lastThroughputCheckTimeUs
a <= 1000 * 1000 / this.checkCycleSecs

a * this.checkCycleSecs <= 1000 * 1000

There should be a problem with this logic

**Comment by killme2008** [comment]
My mistake,  `nowUs - this.lastThroughputCheckTimeUs <= 1000 * 1000 / this.checkCycleSecs` is equals to ` (nowUs - this.lastThroughputCheckTimeUs )/(1000*1000) < 1/ this.checkCycleSecs` .

`1/this.checkCycleSecs` is a cycle in seconds, `(nowUs - this.lastThroughputCheckTimeUs )/(1000*1000) ` cast the value in microsecond  to second unit.

**Comment by xiaoheng1** [comment]
@killme2008 
In my opinion, if this place is to calculate the number of bytes allowed to pass in 1 second, it should not be 1/ this.checkCycleSecs, but it should be 1.

The meaning of checkCycleSecs is how many seconds to check once. Assuming checkCycleSecs = 2, the meaning of 1/2 is difficult to understand

**Comment by killme2008** [comment]
I don't think it's difficult to understand. If you check something every 2 seconds, then the cycle(or interval) between two checking action is 0.5 second.

**Comment by xiaoheng1** [comment]
But I understand that nowUs-this.lastThroughputCheckTimeUs calculates the total elapsed time from the beginning to the present, and then converts this time into seconds. Would it be more reasonable to directly compare with the checkCycleSecs time? Or directly use nowUs-this.lastThroughputCheckTimeUs to convert to seconds and compare with 1.

```
availableSize = limitPerCycle-this.currThroughputBytes;
this.currThroughputBytes = limitPerCycle;
```

What I understand is that the meaning of this code is that when the number of bytes transmitted in 1 second exceeds limitPerCycle, if it is still in a detection cycle, then the maximum limitPerCycle should be allowed to be transmitted as far as possible.

So, my idea is to modify nowUs-this.lastThroughputCheckTimeUs <= 1000 * 1000 / this.checkCycleSecs to nowUs-this.lastThroughputCheckTimeUs <= 1000 * 1000

**Comment by killme2008** [comment]
```
What I understand is that the meaning of this code is that when the number of bytes transmitted in 1 second exceeds limitPerCycle, if it is still in a detection cycle, then the maximum limitPerCycle should be allowed to be transmitted as far as possible.
```

If you change the `1 second` to one cycle, then the code is logical.

**Comment by xiaoheng1** [comment]
Yes, if checkCycleSecs=1, there is no problem. But if checkCycleSecs=2, then testing in 0.5s will result in 2048 bytes being transmitted within 2s, which is inconsistent with our original assumption.

test case：

```
@Before
    public void setup() {
        //1K every seconds
        this.snapshotThrottle = new ThroughputSnapshotThrottle(1024, 2);
    }


    @Test
    public void testThrottledByThroughput1() throws Exception {
        assertEquals(512L, this.snapshotThrottle.throttledByThroughput(512));
        Thread.sleep(502);
        assertEquals(512L, this.snapshotThrottle.throttledByThroughput(512));
        Thread.sleep(502);
        assertEquals(512, this.snapshotThrottle.throttledByThroughput(512));
        Thread.sleep(502);
        assertEquals(512, this.snapshotThrottle.throttledByThroughput(512));
        assertEquals(0, this.snapshotThrottle.throttledByThroughput(512));
    }
```

**Comment by killme2008** [comment]
I am sorry i don't want to explain more, thank you.

**Comment by xiaoheng1** [comment]
ok，thanks
