### ISSUE TITLE
More than one leader in the same term

### ISSUE THREAD

**Issue by changyuchun** [sofastack/sofa-jraft#613]
https://github.com/sofastack/sofa-jraft/blob/5f6938f40253384e5f593ff846f0d98ec5fa0981/jraft-core/src/main/java/com/alipay/sofa/jraft/core/NodeImpl.java#L1918
raft pager里明确同一个任期只能有一个leader 什么特殊情况下会出现同一个任期 两个不同的leader呢？

**Comment by fengjiachun** [comment]
> raft pager里明确同一个任期只能有一个leader 

只能有一个 `有效`  leader

只要是分布式集群，就可能存在某些节点消息、状态滞后

**Comment by changyuchun** [comment]
能描述下具体的场景吗？

**Comment by changyuchun** [comment]
> > raft pager里明确同一个任期只能有一个leader
> 
> 只能有一个 `有效` leader
> 
> 只要是分布式集群，就可能存在某些节点消息、状态滞后

能描述下具体场景吗

**Comment by killme2008** [comment]
> > > raft pager里明确同一个任期只能有一个leader
> > 
> > 
> > 只能有一个 `有效` leader
> > 只要是分布式集群，就可能存在某些节点消息、状态滞后
> 
> 能描述下具体场景吗

出现网络分区的情况。

**Comment by changyuchun** [comment]
> > > > raft pager里明确同一个任期只能有一个leader
> > > 
> > > 
> > > 只能有一个 `有效` leader
> > > 只要是分布式集群，就可能存在某些节点消息、状态滞后
> > 
> > 
> > 能描述下具体场景吗
> 
> 出现网络分区的情况。

这种情况集群的节点数一定是偶数个吧？
