### ISSUE TITLE
jraft内存复制优化咨询

### ISSUE THREAD

**Issue by tsgmq** [sofastack/sofa-jraft#617]
### Your question
为了满足高频计算，将全量1G左右的数据全部放入内存，直接对内存做增删改查操作，为了做高可用，使用了sofa-jraft3个节点做内存复制，数据存入内存，每个节点做本地文件持久化，使用leader做写入，目前耗时如下，请教是否还有优化空间
5, 使用raft后耗时=1920865纳秒
5, 使用raft后耗时=1287288纳秒
5, 使用raft后耗时=1631582纳秒
5, 使用raft后耗时=1791344纳秒
5, 使用raft后耗时=1740492纳秒
5, 使用raft后耗时=1589167纳秒
5, 使用raft后耗时=1357484纳秒
5, 使用raft后耗时=1893818纳秒
5, 使用raft后耗时=2073515纳秒
5, 使用raft后耗时=1355719纳秒
5, 使用raft后耗时=1474409纳秒
5, 使用raft后耗时=1774893纳秒
5, 使用raft后耗时=1971443纳秒
5, 使用raft后耗时=1438487纳秒
5, 使用raft后耗时=1703041纳秒
Describe your question clearly

关键代码如下：
@Log4j2
@ToString
@RequiredArgsConstructor
@Component
public class RaftConfig {

    @Value("${jraft.dataPath}")
    private String dataPath;

    @Value("${jraft.serverList}")
    private String serverList;

    @Getter
    private RheaKVStore rheaKVStore;

    @PostConstruct
    public void startup() throws Exception {
        // 1.初始化kv store集群
        startSeqDbCluster();
    }

    //////////////////////////////////////////////////////////////////////////

    //启动KV Store
    private void startSeqDbCluster() {
        final PlacementDriverOptions pdOpts = PlacementDriverOptionsConfigured.newConfigured()
                .withFake(true)
                .config();

        // 127.0.0.1:8891
        String  ip ="";
        try {
            InetAddress addr = InetAddress.getLocalHost();
            ip = addr.getHostAddress();
        } catch (Exception e) {
            e.printStackTrace();
        }
        final StoreEngineOptions storeOpts = StoreEngineOptionsConfigured.newConfigured()
                .withStorageType(StorageType.Memory)
                .withMemoryDBOptions(MemoryDBOptionsConfigured.newConfigured().config())
                .withRaftDataPath(dataPath)
                .withServerAddress(new Endpoint(ip, 8891))
                .config();

        final RheaKVStoreOptions opts = RheaKVStoreOptionsConfigured.newConfigured()
                .withInitialServerList(serverList)
                .withStoreEngineOptions(storeOpts)
                .withPlacementDriverOptions(pdOpts)
                .config();

//        node = new RaftStorageNode(opts);
//        node.start();
        start(opts);
        Runtime.getRuntime().addShutdownHook(new Thread(this::stop));
        log.info("start seq node success on port : {}", 8891);

    }

    private final AtomicLong leaderTerm = new AtomicLong(-1);

    /**
     * 是否leader节点
     * @return
     */
    public boolean isLeader(){
        return leaderTerm.get() > 0;
    }

    /**
     * 停止Node
     */
    public void stop(){
        rheaKVStore.shutdown();
    }

    /**
     * 启动Node
     */
    public void start(RheaKVStoreOptions opts){
        //初始化kvstore
        rheaKVStore = new DefaultRheaKVStore();
        rheaKVStore.init(opts);
        //监听节点状态
        rheaKVStore.addLeaderStateListener(-1, new LeaderStateListener() {
            @Override
            public void onLeaderStart(long newTerm) {
                String ip = "";
                try {
                    InetAddress addr = InetAddress.getLocalHost();
                    ip = addr.getHostAddress();
                } catch (Exception e ) {
                    e.printStackTrace();
                }

                log.info(ip+" node become leader");
                leaderTerm.set(newTerm);
            }

            @Override
            public void onLeaderStop(long oldTerm) {
                leaderTerm.set(-1);
            }
        });

    }

    public void add(String key,String value) {
        rheaKVStore.bPut(key,value.getBytes());
        log.info("数据写入raft成功");
    }

    public String get(String key) {
        return new String(rheaKVStore.bGet(key));
    }

}
### Your scenes

Describe your use scenes (why need this feature)

### Your advice

Describe the advice or solution you'd like

### Environment

- SOFAJRaft version:1.3.7
- JVM version (e.g. `java -version`):java version "16.0.1" 2021-04-20
Java(TM) SE Runtime Environment (build 16.0.1+9-24)
Java HotSpot(TM) 64-Bit Server VM (build 16.0.1+9-24, mixed mode, sharing)
- OS version (e.g. `uname -a`):2021 x86_64 x86_64 x86_64 GNU/Linux
- Maven version:Apache Maven 3.8.1 (05c21c65bdfed0f71a2f2ada8b84da59348c4c5d)
- IDE version:2021.1

**Comment by fengjiachun** [comment]
把 bPut 换成 put，rheakv 会在客户端自动进行写合并， 不仅仅合并 rpc 请求，还会合并 raft log，最高能将吞吐提升一个数量级

**Comment by fengjiachun** [comment]
> 把 bPut 换成 put，rheakv 会在客户端自动进行写合并， 不仅仅合并 rpc 请求，还会合并 raft log，最高能将吞吐提升一个数量级

吞吐提升一个数量级是指在你写的很快、很连续的情况下，bGet 同理，可改成 get

**Comment by tsgmq** [comment]
16  Intel(R) Xeon(R) Platinum 8124M CPU @ 3.00GHz
MemTotal:       31889560 kB
Linux version 4.14.232-176.381.amzn2.x86_64 (mockbuild@ip-10-0-1-103) (gcc version 7.3.1 20180712 (Red Hat 7.3.1-12) (GCC)) #1 SMP Wed May 19 00:31:54 UTC 2021

**Comment by tsgmq** [comment]
> > 把 bPut 换成 put，rheakv 会在客户端自动进行写合并， 不仅仅合并 rpc 请求，还会合并 raft log，最高能将吞吐提升一个数量级
> 
> 吞吐提升一个数量级是指在你写的很快、很连续的情况下，bGet 同理，可改成 get
感谢指点，果然牛

![image](https://user-images.githubusercontent.com/7135396/123100671-e3965e00-d465-11eb-892f-d1a233fa0743.png)

**Comment by tsgmq** [comment]
> > 把 bPut 换成 put，rheakv 会在客户端自动进行写合并， 不仅仅合并 rpc 请求，还会合并 raft log，最高能将吞吐提升一个数量级
> 
> 吞吐提升一个数量级是指在你写的很快、很连续的情况下，bGet 同理，可改成 get

请教下，目前是1G的数据量，得使用kv这个模式把，案例中的counter状态机的是不是不合适，每次修改是uid维度的全量数据，持久化后硬盘上大概4K左右

**Comment by fengjiachun** [comment]
kv 的话，不需要自己实现状态机啊，直接用 rheakv 不就好了么？

**Comment by tsgmq** [comment]
![image](https://user-images.githubusercontent.com/7135396/123189689-db273d00-d4d0-11eb-86bb-fbb9a91a6ac3.png)
内存中需要保存用户的全量信息，每个用户按照uid作为key存储，从dump下来的文件来看，4k-24k之间，平均值10k，有如下问题请教
1，每秒钟1万个用户的信息需要读出来，修改一些信息后保存回去，如果使用jvm缓存都是引用类型，之间修改字段就可以，使用kv后，是不是需要将每个用户对象信息序列化为二进制put，然后get的时候反序列化，这样可能产生大量的垃圾，对cpu也有影响，因为数据节点是应用程序在同一个node，如果明确知道leader节点了。对于leader节点操作能否直接去应用jvm中的缓存呢？
2， 高可靠方面如何做的，像redis有aof和rdb，jraft的机制如何呢？是否也有镜像，如果随着业务的发展内存中有1G数据量了，系统宕机重启时，内存恢复时间大概多少呢？

**Comment by killme2008** [comment]
1. 可以自己在 rheakv 基础上加一层内存缓存，通过线性一致读，可以直接读内存，也不用关注是否是 leader
2. jraft 的可靠性和可用性就是 raft 算法的实现，具体请参考 raft 算法论文或者一些资料。数据的恢复可以基于 snapshot 加快。

**Comment by tsgmq** [comment]
> * 可以自己在 rheakv 基础上加一层内存缓存，通过线性一致读，可以直接读内存，也不用关注是否是 leader

可以自己在 rheakv 基础上加一层内存缓存，通过线性一致读，可以直接读内存，也不用关注是否是 leader
这个是否有demo之类的可以参考，或者有相关文档，我学习下
