### ISSUE TITLE
【内存泄露】使用ReadIndex读操作OOM

### ISSUE THREAD

**Issue by horizonzy** [sofastack/sofa-jraft#618]
## 场景：
使用ReadIndex读取数据，读取的数据大小大概4M左右。

## 大概代码：
![image](https://user-images.githubusercontent.com/22524871/123103377-83ed8200-d468-11eb-94c9-d02ff2cb5543.png)

## 堆使用情况：
![image](https://user-images.githubusercontent.com/22524871/123101348-89e26380-d466-11eb-971d-4e2431bbbc18.png)

## 大对象所持有的对象依赖情况：
![image](https://user-images.githubusercontent.com/22524871/123101508-b9916b80-d466-11eb-9635-8335b8d6f681.png)

## 大对象被持有情况：
![image](https://user-images.githubusercontent.com/22524871/123101573-c9a94b00-d466-11eb-8371-36b3462c7ca1.png)

## 内存占用相关代码
![image](https://user-images.githubusercontent.com/22524871/123104159-4d643700-d469-11eb-9a9b-7f1a27bbf84a.png)

![image](https://user-images.githubusercontent.com/22524871/123104115-40dfde80-d469-11eb-9858-f709366074bc.png)

可以看出来 com.alipay.sofa.jraft.core.ReadOnlyServiceImpl#readIndexQueue这个RingBuffer是元凶。由于RingBuffer的机制，导致内存占用高。

## 问题原因：
ReadIndexClosure是抽象类，使用时用了匿名类去进行实例化。实例化时会将方法内部使用的引用持有在匿名类内部。
在我的这种场景下，匿名内部类将future引用了。future调用了complete后，将4M的res设置在了result中，因此ReadIndexClosure的匿名对象会占4M。
由于ReadIndex用了disruptorj进行解耦，将ReadIndexClosure传递到了ReadIndexEvent内部，而ReadIndexEvent保存在RingBuffer中，导致readIndexQueue的内存占用很高。

**Comment by killme2008** [comment]
本质上是使用上的问题，我不认为是内存泄漏，不过可以做个提前的清理释放。

**Comment by fengjiachun** [comment]
可以就按照我们线下讨论时的建议，对 disruptor 的 event 使用后进行 reset/clear

**Comment by horizonzy** [comment]
嗯。对使用过后的event进行reset。提前释放内存，不用等到ringbuffer的下一个轮次。
