### ISSUE TITLE
com.alipay.sofa.jraft.storage.impl.RocksDBLogStorage#firstLogIndex 可能读取的不准

### ISSUE THREAD

**Issue by xiaoheng1** [sofastack/sofa-jraft#623]
### Environment

- SOFAJRaft version:
- JVM version 1.8
- OS version macos

我查看了下 master 分支的代码。firstLogIndex 是取的 RocksDB 中的第一条 LogEntry.

但是数据在存储的时候，配置类型的数据会向 defaultHandle、confHandle 写入。数据类型的数据会向 defaultHandle 写入。
但是再取 firstLogIndex 的时候，我理解的是应该要去数据类型的索引。

因此，再取 firstLogIndex 是有要过滤掉配置类型的数据？

**Comment by killme2008** [comment]
配置类型仅仅是特殊的日志，加入 conf column 是为了加速查询，没有别的目的。

**Comment by xiaoheng1** [comment]
但是如果存储结构是这样的：
在 defaultHandle 列簇的话：
LogEntry(config) LogEntry(data) LogEntry(config)
那么在读取 firstLogIndex 的时候，会读取到 LogEntry 的 logIndex. 而 LogEntry(config) 的 logIndex 往往是 0，这样的话，会对 firstLogIndex 造成影响。不知道我的理解是否正确。

**Comment by killme2008** [comment]
不会是 0，日志 index 按序递增。 conf log 还是一条 log。

**Comment by xiaoheng1** [comment]
明白了，感谢。
