### ISSUE TITLE
com.alipay.sofa.jraft.util.RepeatedTimer#restart 是否应该增加本身是启动状态的判断

### ISSUE THREAD

**Issue by xiaoheng1** [sofastack/sofa-jraft#626]
### Environment

- SOFAJRaft version: master
- JVM version 1.8
- OS version macos

摘抄自 master 分支：

我看到 restart 方法在 stepDown 中会被调用到，但是 stepDown 方法在极短的时间内被调用多次，比如在 com.alipay.sofa.jraft.core.NodeImpl#handleRequestVoteRequest 方法中.

我们是否有必要增加对 running 状态的判断，如果本身定时任务处于运行状态，则直接返回.

restart 方法我理解这里的设计是为了将不是运行状态的任务变为运行状态，那么本身处于运行状态的任务是否要重新再被创建？

```
public void restart() {
        this.lock.lock();
        try {
            if (this.destroyed) {
                return;
            }
            this.stopped = false;
            this.running = true;
            schedule();
        } finally {
            this.lock.unlock();
        }
    }
```

**Comment by killme2008** [comment]
核心是为了 schedule，重新调度定时器，状态倒是其次。

**Comment by xiaoheng1** [comment]
明白了，感谢
