### ISSUE TITLE
关于 com.alipay.sofa.jraft.core.Replicator#appendEntriesCounter 属性的统计优化问题

### ISSUE THREAD

**Issue by xiaoheng1** [sofastack/sofa-jraft#630]
### Environment

- SOFAJRaft version: master
- JVM version 1.8
- OS version macos

摘抄自 master 分支：

com.alipay.sofa.jraft.core.Replicator#appendEntriesCounter

master 分支上的 appendEntriesCounter 属性，其实是统计的探针请求的数量，并不是日志复制请求的数量。我的建议是把 appendEntriesCounter 调整为统计日志复制请求的数量，然后新增加一个专门用于统计探针请求的变量。

**Comment by fengjiachun** [comment]
@xiaoheng1 还真的是啊，帮忙提个 PR ？

**Comment by xiaoheng1** [comment]
好的，我来修复这个问题。
