### ISSUE TITLE
[Question] How did you generate the beatiful flow?

### ISSUE THREAD

**Issue by JerryYangSH** [sofastack/sofa-jraft#640]
### Your question

I noticed there is a very cool fancy diagram from (https://github.com/sofastack/sofa-jraft/blob/master/jraft-rheakv/rheakv-core/src/main/java/com/alipay/sofa/jraft/rhea/client/RheaKVStore.java#L40-L77).  I am curious. is this drawn by hand or generated by some assistant tool? If it is done by a tool, can you share the tool name?

**Comment by fengjiachun** [comment]
@JerryYangSH It is monodraw: https://monodraw.helftone.com/
