### ISSUE TITLE
请教如何高效实现snapshot

### ISSUE THREAD

**Issue by tsgmq** [sofastack/sofa-jraft#644]
### Your question
如果为了保证snapshot跟当时的内存完全一致，则需要加lock，暂停内存的修改。通过验证1G的数据量在2 GHz 四核Intel Core i5的环境下，使用protostuff序列化后保存到磁盘需要10s左右，如果加上Zip压缩，耗时15s,压缩后140M左右，但是由于有10-15s暂停交易，因此肯定不可取，是否有高效的snapshot方式，不影响业务的写入，同时做了snapshot的保存呢？
看MemoryRawKVStore的代码时按照key的范围分段保存的，如果ConcurrentSkipListMap里面的数量很大，for循环处理的时间比较长的话，处理的过程对ConcurrentSkipListMap造成的修改是否会影响snapshot的值和开始做snapshot时内存中的状态不一致呢？

Describe your question clearly

### Your scenes

Describe your use scenes (why need this feature)

### Your advice

Describe the advice or solution you'd like

### Environment

- SOFAJRaft version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by killme2008** [comment]
lock 后，获取当前状态机的“镜像”拷贝就可以释放锁了，序列化、压缩和文件存储都可以异步做，最后调用 `onSnapshotSave(final SnapshotWriter writer, final Closure done)` 传入的 `done` 回调即可。

**Comment by tsgmq** [comment]
当前状态机4G大小的数据，那么获取当前状态机的“镜像”是不是也快不了？目前还没有找到向redis那样fork进程，copyOnWrite的方式

**Comment by fengjiachun** [comment]
> 当前状态机4G大小的数据，那么获取当前状态机的“镜像”是不是也快不了？目前还没有找到向redis那样fork进程，copyOnWrite的方式

不一定快不了，举个例子，假设你的状态机有版本号机制，那么获取镜像只是拿到当前版本号而已，读取的时候只读取小于等于这个版本号的数据即可

**Comment by tsgmq** [comment]
有没有上面说的有版本号的例子学习下

**Comment by tsgmq** [comment]
以下是测试的数据验证情况，clone耗时也挺高的，1.4G数据量
![image](https://user-images.githubusercontent.com/7135396/125789742-12ea67f3-dd3d-4943-9f6c-df4be3a6c708.png)

**Comment by killme2008** [comment]
高效镜像的实现，无外乎就是那么几个方法：

1. 增量镜像，基于版本化和无锁化的方式，尽量减少拷贝
2. 拆分多 raft group，缩小单个 group 的镜像规模

**Comment by tsgmq** [comment]
目前已经在网关层面按照uid做水平分片了。这样每个单独的raft集群只是整体中很小的一部分数据了，相当于自己实现了个MULT_RAFT_GROUP，上面提到的2应该是一个意思

看了下源码，snapshot也是往taskQueue的ringBuffer中提交了Task,由于状态机中的Task是顺序onApply的，这样的话如果是单线程执行，就不会出现snapshot的过程中有其他logEntry处理，就不会改变状态机中的其他对象的值了吧，因此我在处理onSnapshotSave的时候不需要对自定义状态机加锁吧，只需要把状态机对象copy一份，然后异步去保存序列化后的文件就可以吧

@override
public boolean onSnapshotSave(final SaveSnapshotClosure done) {
return enqueueTask((task, sequence) -> {
task.type = TaskType.SNAPSHOT_SAVE;
task.done = done;
});
}

**Comment by killme2008** [comment]
@tsgmq ，是可以的，但是如果你的状态机允许并发读的话，可能还是需要适当同步。
