### ISSUE TITLE
如何初始化一个18位的sequence？

### ISSUE THREAD

**Issue by hieastz** [sofastack/sofa-jraft#645]
bGetSequence入参是int。怎么办？

**Comment by fengjiachun** [comment]
不支持， step 入参的意义是 ”步长“，无法支持你这么使用

**Comment by hieastz** [comment]
> 不支持， step 入参的意义是 ”步长“，无法支持你这么使用

我自己改成long型了，可以支持

**Comment by fengjiachun** [comment]
功能是没问题，只不过这不是设计的初衷

**Comment by hieastz** [comment]
> 功能是没问题，只不过这不是设计的初衷

后续可以考虑下初始化的问题，步长正常情况下确实不会需要long型，但是想初始化一个16位序列是很正常的业务需求。
