### ISSUE TITLE
raft日志保存为什么选择rockdbs,而不是使用本地文件

### ISSUE THREAD

**Issue by hanzhihua** [sofastack/sofa-jraft#646]
### Your question

raft日志保存为什么选择rockdbs,而不是使用本地文件，比如zookeeper，请指教？

引入Rocksdb的话，我们发现Sst文件一直在增多，相关的deleterange也做了

Describe the advice or solution you'd like

Environment
jdk 1.8
3台集群（jraft 版本1.2.6）
uname :4.9.0-0.bpo.6-amd64 #1 SMP Debian 4.9.88-1+deb9u1~bpo8+1 (2018-05-13) x86_64 GNU/Linux

**Comment by fengjiachun** [comment]
也没有为啥，可理解为当时懒了，可关注 #577 ，已经在去 rocksdb 了
