### ISSUE TITLE
设计问题： log storage 为什么 选择使用rocksdb，而不是本地的磁盘文件

### ISSUE THREAD

**Issue by whdwsl** [sofastack/sofa-jraft#654]
log存储后，确实有查询需求， 一般会根据index查询具体的log内容，用于同步follower或状态机更新。
如果使用类似消息中间件保存message的方式，由两个文件组成，一个是log内容，一个是索引文件，查询性能上也不会比rocksdb差。使用rocksdb相当于又引入一个第三方系统， 增加运维难度。请问使用rocksdb是有什么其它的考虑吗？

**Comment by killme2008** [comment]
没有为什么，就是方便，当时不想造轮子。也没有什么运维难度吧，就是嵌入式在用，跟自己实现一个 storage 引擎一样。
