### ISSUE TITLE
关于 com.alipay.sofa.jraft.rhea.pipeline.handler.PlacementDriverTailHandler#handleInbound 的疑问

### ISSUE THREAD

**Issue by xiaoheng1** [sofastack/sofa-jraft#655]
分支：master

摘抄自 master 分支：

有一个疑问， ctx.fireOutbound(new PongEvent(ping.getInvokeId(), Lists.newArrayList(ping.getInstructions())));

这段代码修改为

ctx.pipeline().fireOutbound(new PongEvent(ping.getInvokeId(), Lists.newArrayList(ping.getInstructions())));

是否会更加合理一点？

因为如果直接使用 ctx.fireOutbound 方法的话，就会和该 handler 的位置相关，可能会导致某些 outboundHandler 不会执行，如果使用 pipeline.fireOutbound 方法的话，能够保证一定是从 tail -> head 这个方法进行传播，同时这个链上的 outboundHandler 都会被执行。

```
public class PlacementDriverTailHandler extends InboundHandlerAdapter<PingEvent<?>> {

    @Override
    public void handleInbound(final HandlerContext ctx, final InboundMessageEvent<?> event) throws Exception {
        if (isAcceptable(event)) {
            // to outbound
            PingEvent<?> ping = (PingEvent<?>) event;
            ctx.fireOutbound(new PongEvent(ping.getInvokeId(), Lists.newArrayList(ping.getInstructions())));
        }
    }

    @Override
    public void readMessage(final HandlerContext ctx, final PingEvent<?> event) throws Exception {
        // no-op
    }
}
```

**Comment by fengjiachun** [comment]
代码看的好仔细，可以改成 ctx.pipeline() ，不过其实 PlacementDriverTailHandler 能确定就是最后一个 handler
如果方便的话，可以提一个 PR 吗？

**Comment by xiaoheng1** [comment]
好的，我来提交一个 pr
