### ISSUE TITLE
请教关于 rheakv 中有办法保证插入的一批数据要么都成功，要么都失败吗

### ISSUE THREAD

**Issue by xiaoheng1** [sofastack/sofa-jraft#657]
请教关于 rheakv 中有办法保证插入的一批数据要么都成功，要么都失败吗？

**Comment by fengjiachun** [comment]
是指 put(list) 接口吗？如果是同时写入多个 region 无法保证（这个 api 注释有说明），如果是这一批数据都是一个 region 那么可以保证要么都成功，要么都失败

**Comment by xiaoheng1** [comment]
嗯，api 上确实注释了，在写入多 region 的时候无法保证。rheakv 后续会考虑支持分布式事务不？

**Comment by fengjiachun** [comment]
应该不会考虑去支持分布式事务 @xiaoheng1

**Comment by xiaoheng1** [comment]
好的，了解了，感谢。
