### ISSUE TITLE
Mac OS X 10.13运行Jraft失败

### ISSUE THREAD

**Issue by Mervey0324** [sofastack/sofa-jraft#663]
一直以来都是在Mac OS X10.15上运行jraft，今天在Mac OS X 10.13运行了一次，出现了一个启动失败的问题。报错信息如下：
```
dyld: lazy symbol binding failed: Symbol not found: ____chkstk_darwin
 Referenced from: /private/var/folders/09/hftbpn9122j1r8xg013lsn5c0000gn/T/librocksdbjni6606734763678809306.jnilib (which was built for Mac OS X 10.15)
 Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: ____chkstk_darwin
 Referenced from: /private/var/folders/09/hftbpn9122j1r8xg013lsn5c0000gn/T/librocksdbjni6606734763678809306.jnilib (which was built for Mac OS X 10.15)
 Expected in: /usr/lib/libSystem.B.dylib
```

- SOFAJRaft version: 1.3.6
- JVM version (e.g. `java -version`): java8
- OS version (e.g. `uname -a`):  Mac OS X 10.13
- Maven version: 3.6.3
- IDE version: ideaj

**Comment by fengjiachun** [comment]
可能需要降级 rocksdb 到 5.18.3，试下看看，没有你那么老版本的 mac os 了，辛苦你自己试一下

**Comment by Mervey0324** [comment]
> 可能需要降级 rocksdb 到 5.18.3，试下看看，没有你那么老版本的 mac os 了，辛苦你自己试一下

好的 我先试一下

**Comment by Mervey0324** [comment]
> 可能需要降级 rocksdb 到 5.18.3，试下看看，没有你那么老版本的 mac os 了，辛苦你自己试一下

可以了，把rocksdb降级到5.18.3之后，就可以在10.13上运行了～
