### ISSUE TITLE
关于 leader 增加检查租约的定时任务

### ISSUE THREAD

**Issue by xiaoheng1** [sofastack/sofa-jraft#684]
当发生网络分区的时候，可能存在多个 leader。此时对于客户端而言，应该是没办法判定那个 leader 是多数派接受的 leader，那么是少数派接受的 leader。

有一个想法是，开启一个定时任务，每隔一段时间 leader 检查下自己是否能和多数节点通讯。如果不能，则将自身状态退回到 follower。

**Comment by fengjiachun** [comment]
> 当发生网络分区的时候，可能存在多个 leader。此时对于客户端而言，应该是没办法判定那个 leader 是多数派接受的 leader，那么是少数派接受的 leader。

实际上不存在你说的少数派的 leader，可以认为只是这个节点自以为他是 leader，实际它不是，而且它无法成功应用任何 raft log

> 有一个想法是，开启一个定时任务，每隔一段时间 leader 检查下自己是否能和多数节点通讯。如果不能，则将自身状态退回到 follower。

可以看下 NodeImpl 里面定时 checkstepdown 的逻辑，这个自以为自己是 leader 的节点是会自己 stepdown 的

**Comment by xiaoheng1** [comment]
@fengjiachun 好的，感谢，我看看这块的逻辑

**Comment by xiaoheng1** [comment]
@fengjiachun  刚看了下，checkStepDown 现在在两个地方用到 handleAppendEntriesRequest 和 handleInstallSnapshot。
这两个方法我理解都是非 leader 接收新 leader 的请求时会导致自身退回到 follower 的逻辑.

下面是我的想法，不知道是否正确，还望指点下。

如果存在这么一种场景：

![11CCAC7D-3F3C-4000-95DF-FB65CD9A1917](https://user-images.githubusercontent.com/12539730/132834653-6519c41b-6d4e-4557-8d87-4e8a9d2d2472.png)

最初 B 是 leader，现在由于网络分区，导致 B A 这两个节点和 C、D、E 这三个节点完全隔离：

![5E38137F-51E9-4D2F-B23F-FD16F4E20503](https://user-images.githubusercontent.com/12539730/132834824-07fb0551-e3d3-47e6-831d-d6d44adb460d.png)

那么此时假设在 C、D、E 三个节点中 C 最终当选。对于 B、A 这个小的集群中，由于没有造反派的存在，B 将会一直维护其 leader 的地位。

对于客户端而言，在调用 getLeader 方法的时候，假设获取到 B 这个 leader，其实它并不知道这个 B 已经不被多数派接受了，虽然它发送给 B 的消息无法 commit. 针对这个问题，我的想法是 B 在消除分区之前，使其自动的降为 follower(方法就是定时和集群间的其他节点通讯)，这样对于客户端而言，它在后面就只会获取到一个 leader，这样避免将数据发送到少数派的 leader 上，这样它的数据就能被正确 commit 了。

**Comment by fengjiachun** [comment]
@xiaoheng1 抱歉，没看代码就直接回复你了，不严谨了， `checkDeadNodes` 看这个方法，以及被定时器调度的 `handleStepDownTimeout`

**Comment by xiaoheng1** [comment]
@fengjiachun 看到啦，这个方法做了检查，非常感谢指点。
