### ISSUE TITLE
IPv6 Support ?

### ISSUE THREAD

**Issue by NanerLee** [sofastack/sofa-jraft#685]
当前 JRaft 支持 IPv6 地址吗?

我们生产用的 JRaft, 在 IPv6 环境中测试时, 在 Raft Node 进行 preVote 时会报错, 看报错信息是其依赖的 Bolt 无法解析 IPv6 形式的 address, 我已经向 Bolt 提了个 issue [IPv6 Support ? · Issue #263 · sofastack/sofa-bolt](https://github.com/sofastack/sofa-bolt/issues/263).

之前看到 1.35 的 release 中提到过对 IPv6 支持的特性, 但目前看来仅仅是自己支持对地址的解析. 

所以我目前疑惑的是: 当前 JRaft 对 IPv6 提供完整的支持吗? 有通过相关环境的测试吗? 

- SOFAJRaft version: 1.3.5

**Comment by fengjiachun** [comment]
可以将 rpc 层由 bolt 替换为 [grpc-impl] (https://github.com/sofastack/sofa-jraft/tree/master/jraft-extension/rpc-grpc-impl),基于 SPI 扩展的，只要 pom 引入依赖即可

对于 bolt ，当它支持 ipv6 后我们也会进行 bolt 升级

**Comment by NanerLee** [comment]
嗯, 谢谢, 昨天替换了 grpc-impl 之后测试下没问题
