### ISSUE TITLE
Can provide node status metrics?

### ISSUE THREAD

**Issue by haoyann** [sofastack/sofa-jraft#687]
### Your question
The [document](https://www.sofastack.tech/projects/sofa-jraft/jraft-user-guide/) does not describe the metrics related to the node status. Can provide node status metrics? Like `have_leader`,`node_status` ,can better observe the state machine.
![image](https://user-images.githubusercontent.com/43994656/134611474-8dd286bd-b425-4b20-b7be-f8b63dd54d93.png)

**Comment by fengjiachun** [comment]
执行 `kill -s SIGUSR2 pid` 后会生成 node_describe.log 文件

见你发的文档的第十一小节

**Comment by haoyann** [comment]
> 执行 `kill -s SIGUSR2 pid` 后会生成 node_describe.log 文件
> 
> 见你发的文档的第十一小节

嗯，这种形式是可以观察到节点的状态，但是我想的是通过指标的形式输出节点状态，这样可以通过时序数据库采集、观察。

**Comment by fengjiachun** [comment]
本身 node state 不是指标，比较难指标化

**Comment by fengjiachun** [comment]
不过，如果你需要采集状态信息的话，是不是可以直接调用 node#describe() 获取相应的 status ？

**Comment by haoyann** [comment]
> 不过，如果你需要采集状态信息的话，是不是可以直接调用 node#describe() 获取相应的 status ？

谢谢你的回复，这种方式可以拿到节点的状态但是比较麻烦，也可以通过`com.alipay.sofa.jraft.Node#getNodeState` 获取节点状态和`com.alipay.sofa.jraft.Node#getLeaderId` 判断 leader 是否存在。其实我想要一个能够快速反应节点是否工作的指标比如`have_leader`，现在看来也可以通过上诉方式获取。
