### ISSUE TITLE
DistributedLock中getFencingToken如何使用？

### ISSUE THREAD

**Issue by baojie5642** [sofastack/sofa-jraft#695]
![image](https://user-images.githubusercontent.com/9031343/137057166-e5d6f317-1eb7-43c5-a57b-327f81e15d42.png)

这样使用正确吗？

**Comment by fengjiachun** [comment]
不太对， fencing token 的作用可以见这里 
https://martin.kleppmann.com/2016/02/08/how-to-do-distributed-locking.html
和
https://hazelcast.com/blog/long-live-distributed-locks/

简单说，你需要在你执行有副作用的外部服务时将 fencing token 传递给外部服务，让外部服务始终持有最新的 fencing token，外部服务还需要能拒绝任何小于当前 fencing token 的任何请求

**Comment by fengjiachun** [comment]
没其他疑问就先关闭了
