### ISSUE TITLE
选举领导者不成功

### ISSUE THREAD

**Issue by Xugcs** [sofastack/sofa-jraft#698]
客户端启动就卡在这里了
2021-10-18 20:48:59 [main] INFO  log:30 - Sofa-Middleware-Log SLF4J : Actual binding is of type [ com.alipay.remoting Log4j2 ]
2021-10-18 20:49:02 [main] ERROR AbstractClientService:157 - Fail to connect 127.0.0.1:8081, remoting exception: com.alipay.remoting.rpc.exception.InvokeTimeoutException: Rpc invocation timeout[responseCommand TIMEOUT]! the address is 127.0.0.1:8081.
2021-10-18 20:49:02 [main] ERROR AbstractClientService:157 - Fail to connect 127.0.0.1:8082, remoting exception: com.alipay.remoting.rpc.exception.InvokeTimeoutException: Rpc invocation timeout[responseCommand TIMEOUT]! the address is 127.0.0.1:8082.
2021-10-18 20:49:02 [main] ERROR AbstractClientService:157 - Fail to connect 127.0.0.1:8083, remoting exception: com.alipay.remoting.rpc.exception.InvokeTimeoutException: Rpc invocation timeout[responseCommand TIMEOUT]! the address is 127.0.0.1:8083.
Exception in thread "main" java.lang.IllegalStateException: Refresh leader failed
	at com.alipay.sofa.jraft.example.counter.CounterClient.main(CounterClient.java:54)
2021-10-18 20:49:17 [Finalizer] INFO  LogThreadPoolExecutor:97 - ThreadPool is terminated: JRaft-RPC-Processor, com.alipay.sofa.jraft.util.MetricThreadPoolExecutor@39f294cb[Shutting down, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0].

**Comment by Xugcs** [comment]
看了一下是连接不上rpc
cliClientService.connect(peer.getEndpoint()) 这里返回的是flase   peer是没问题的

**Comment by Xugcs** [comment]
都启动了 
![image](https://user-images.githubusercontent.com/71803018/137829813-9704330c-18ff-4649-9cf8-62c7f901c00d.png)

**Comment by Xugcs** [comment]
> 127.0.0.1:8081， 127.0.0.1:8082，127.0.0.1:8083 这三个节点你都启动了吗
启动了
![image](https://user-images.githubusercontent.com/71803018/137829855-d0d477ef-053d-43aa-be2b-fde035f0984a.png)

**Comment by Xugcs** [comment]
都启动了&nbsp;
client启动不了&nbsp; 选举不成功
看了一下是连接不上rpc
cliClientService.connect(peer.getEndpoint()) 这里返回的是flase peer是没问题的


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "sofastack/sofa-jraft"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月19日(星期二) 上午9:40
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [sofastack/sofa-jraft] 选举领导者不成功 (Issue #698)





 
127.0.0.1:8081， 127.0.0.1:8082，127.0.0.1:8083
 这三个节点你都启动了吗
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by fengjiachun** [comment]
把三个 server 节点的 log 发上来看看

**Comment by killme2008** [comment]
这个日志没啥问题，已经选举成功了：

```
onStartFollowing: LeaderChangeContext [leaderId=127.0.0.1:8083, term=1, status=Status[ENEWLEADER<10011&gt;: Follower receives message from new leader with the same term.]].
```

```
2021-10-19 10:19:54 [JRaft-FSMCaller-Disruptor-0] INFO&nbsp; StateMachineAdapter:62 - onLeaderStart: term=1.
```

8083 已经是 leader 了，你启动客户端应该是没有选举成功的时候跑的，等集群产生 leader 后再跑客户端例子。

**Comment by killme2008** [comment]
集群全部节点启动后，要等待产生 leader， leader 日志会有 `onLeaderStart` 字样的日志，产生 leader 后才可以正常提供服务。

**Comment by Xugcs** [comment]
同一台机器 telnet通&nbsp; 也没有开代理翻墙&nbsp; 不过这是学校网络




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "sofastack/sofa-jraft"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月19日(星期二) 上午10:49
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [sofastack/sofa-jraft] 选举领导者不成功 (Issue #698)





 
客户端在同一台机器吗？ 确认 telnet 可以链接？
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Xugcs** [comment]
关闭了一切安全软件，没有翻墙




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "sofastack/sofa-jraft"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月19日(星期二) 上午10:52
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [sofastack/sofa-jraft] 选举领导者不成功 (Issue #698)





 
是否在本地开了一些代理软件，网络工具之类的？我之间在 windows 遇到过 netty 端口监听ok，tcp 握手能够建立连接，但是收不到 io 事件的问题。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Xugcs** [comment]
只有一次连接他会走这段代码





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "sofastack/sofa-jraft"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月19日(星期二) 中午11:15
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [sofastack/sofa-jraft] 选举领导者不成功 (Issue #698)





  
你启动客户端应该是没有选举成功的时候跑的，等集群产生 leader 后再跑客户端例子。
   
设置了两次连接同一个peer&nbsp; 第二次就成功了并获取到 leader
  
不是 @killme2008 说的原因吗？
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by killme2008** [comment]
抱歉，我们的开发环境是 mac 和 linux，目前没有 windows 机器可以测试，如果有其他反馈，我们再跟进。

**Comment by chenshengli** [comment]
我也遇到了这个问题，一样是windows系统，然后尝试了一下，这个可以将代码中的rpc连接超时时间调长一点，我这边就成功了，具体代码为：
`CliOptions cliOptions = new CliOptions();
        cliOptions.setRpcConnectTimeoutMs(10000);
        cliClientService.init(cliOptions);`

**Comment by chenshengli** [comment]
@killme2008  @Xugcs @fengjiachun @horizonzy @marks-yag  我也遇到了这个问题，一样是windows系统，然后尝试了一下，这个可以将代码中的rpc连接超时时间调长一点，我这边就成功了，具体代码为：
`CliOptions cliOptions = new CliOptions(); 
cliOptions.setRpcConnectTimeoutMs(10000); 
cliClientService.init(cliOptions);`

**Comment by fengjiachun** [comment]
问题应该已经解决，详见 #810 ，这个 issue 先关闭了
