### ISSUE TITLE
关于SegmentList#removeFromFirst(int)没有回收Segment异常

### ISSUE THREAD

**Issue by huangjianqin** [sofastack/sofa-jraft#709]
### Describe the bug
https://github.com/sofastack/sofa-jraft/blob/1.3.8/jraft-core/src/main/java/com/alipay/sofa/jraft/util/SegmentList.java#L333
如果SegmentList支持复用Segment, 则上面该行代码没有回收被移除的Segment.

**Comment by killme2008** [comment]
回收只是个对象池优化，并不强求，并且如果使用不在同一个线程，回收也没有效果（因为基于 thread local）。目前用到 `removeFromFirst` 方法的仅在 ballobox 里，刚好是没有启用回收选项的 `recycleSegment=false`。
