### ISSUE TITLE
Client put will throw exception, when  Region Split.

### ISSUE THREAD

**Issue by huzx0608** [sofastack/sofa-jraft#721]
### Your question

部署逻辑：
1： 部署三个PD，PD-1 PD-2 PD-3 Using  Class: com.alipay.sofa.jraft.rhea.PlacementDriverStartup, start on different port
2:   部署三个RheaKVStore： KV-1 KV-2 KV-3 Using Class: DefaultRheaKVStore
![image](https://user-images.githubusercontent.com/6895821/142795844-4a7a062c-56ce-4109-9b55-08e8eb97ac32.png)

3: 基于jraft-example中的example，使用Client Using PD to connect KV, and do Put to trigger region split
![image](https://user-images.githubusercontent.com/6895821/142795984-d7447e20-70c8-4f21-b569-a4a40579bb04.png)

在Region进行分裂的时候，发现所有的client的写请求会全部被拒绝，对应的堆栈如下：
![image](https://user-images.githubusercontent.com/6895821/142796066-adde280c-bb58-4a9e-8f32-8d86df479cf2.png)

### Environment

- SOFAJRaft version: 1.3.8
- JVM version (e.g. `java -version`): 1.8
- OS version (e.g. `uname -a`): ubuntu 
- Maven version: 
- IDE version:

**Comment by fengjiachun** [comment]
你的 client 用的 fake pd，无法感知 split 后的路由信息，配置一下 PlacementDriverOptions

**Comment by huzx0608** [comment]
Client是有配置路由表的。
![image](https://user-images.githubusercontent.com/6895821/142796706-039abb31-a9aa-4fb2-8514-9caafbbea94b.png)


这是静态配置的。

**Comment by fengjiachun** [comment]
但是你使用的 example 不从这里读配置啊

**Comment by huzx0608** [comment]
![Uploading image.png…]()
我改了代码，直接走的配置加载

**Comment by huzx0608** [comment]
![image](https://user-images.githubusercontent.com/6895821/142796987-d80c3a87-aa2c-4498-b2ea-52eb2c100279.png)

**Comment by fengjiachun** [comment]
看不到你改的代码的逻辑，或者你直接运行 RheaHeartbeatTest 试试（现成  example）

**Comment by fengjiachun** [comment]
可以先试运行一下 RheaHeartbeatTest，或者把你修改的代码发出来看下

关于 pd 的设计，下面这个连接是设计文档
https://www.sofastack.tech/projects/sofa-jraft/jraft-rheakv-user-guide/

**Comment by fengjiachun** [comment]
先关闭了，还有后续问题可以再打开

**Comment by wg1993** [comment]
这个问题解决了吗@huzx0608

**Comment by wg1993** [comment]
> 但是你使用的 example 不从这里读配置啊

这个问题解决了吗@huzx0608
