### ISSUE TITLE
ringBuffer内存泄露分析

### ISSUE THREAD

**Issue by tsgmq** [sofastack/sofa-jraft#723]
### Your question
看源码，在onEevent处理后，是有reset释放资源的，但是dump下来发现占了3个多G内存没有清理
// 这个是清理的源码
private static class LogEntryAndClosure {
        LogEntry       entry;
        Closure        done;
        long           expectedTerm;
        CountDownLatch shutdownLatch;

        public void reset() {
            this.entry = null;
            this.done = null;
            this.expectedTerm = 0;
            this.shutdownLatch = null;
        }
    }
下面是内存mat分析结果
![image](https://user-images.githubusercontent.com/7135396/142957864-ca4207c3-2fa0-472e-9c76-ff33c7247c92.png)

另外32C 64G的机器，disruptorBufferSize设置多少合适呢？一个5节点的集群，一次raft apply耗时大概0.7ms左右，帮忙指点下，下面的raftOptions设置是否合理

RaftOptions raftOptions = new RaftOptions();
        raftOptions.setDisruptorBufferSize(16384 * 8);
        raftOptions.setMaxByteCountPerRpc(128 * 1024 * 8);
        // 从 leader 往 follower 发送的最大日志个数，默认 1024
        raftOptions.setMaxEntriesSize(1024 * 8);
        // 从 leader 往 follower 发送日志的最大 body 大小，默认 512K
        raftOptions.setMaxBodySize(512 * 1024 * 8);
        // 日志存储缓冲区最大大小，默认256K
        raftOptions.setMaxAppendBufferSize(256 * 1024 * 8);
        // 向 leader 提交的任务累积一个批次刷入日志存储的最大批次大小，默认 32 个任务
        raftOptions.setApplyBatch(32 * 8);
        raftOptions.setSync(false);
        // 读写都在leader,因此采用LeaseBased减少heartbeat耗时
        raftOptions.setReadOnlyOptions(ReadOnlyOption.ReadOnlyLeaseBased);

Describe your question clearly

### Your scenes

Describe your use scenes (why need this feature)

### Your advice

Describe the advice or solution you'd like

### Environment

- SOFAJRaft version: 1.3.8
- JVM version (e.g. `java -version`): 17
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by killme2008** [comment]
disruptor 会对 event 做复用，这里并不是内存泄漏吧，因为你的 disruptorBufferSize 设置的比较大，我理解这里是复用的对象池也比较大。 具体 disruptorBufferSize 设置多少，其实还是看你要吞吐还是延迟，如果追求吞吐量，肯定是 disruptorBufferSize 较大比较好，反之希望延迟较小，则应该较小。包括 applyBatchSize 也是类似。

**Comment by wulianliang22** [comment]
https://github.com/sofastack/sofa-jraft/issues/720

disruptorBufferSize设置的过下的话，现在会有这个死锁的问题么？

**Comment by fengjiachun** [comment]
> 一次raft apply耗时大概0.7ms左右

参考下面连接 11 小节，把性能指标发上来看看，关于 ringBuffer 3G 应该是你 apply 慢了，ringbuf 里都是你没有 commit 的 raft log 而已，看你是 64G 的内存，不知道具体场景和情况，猜测你的 jvm heap 本身就很大

https://www.sofastack.tech/projects/sofa-jraft/jraft-user-guide/

**Comment by fengjiachun** [comment]
> #720
> 
> disruptorBufferSize设置的过小的话，现在会有这个死锁的问题么？ @killme2008 ，这个值设置的范围区间，建议是多少合适？

默认值就是经验值，如果出现过载，通常是 apply 慢了（用户状态机写入数据慢），如果用户状态机无法进一步优化，可以适当往上调整（这就没有建议了，需要看你具体场景）

**Comment by killme2008** [comment]
> > #720
> > disruptorBufferSize设置的过小的话，现在会有这个死锁的问题么？ @killme2008 ，这个值设置的范围区间，建议是多少合适？
> 
> 默认值就是经验值，如果出现过载，通常是 apply 慢了（用户状态机写入数据慢），如果用户状态机无法进一步优化，可以适当往上调整（这就没有建议了，需要看你具体场景）

嗯嗯。应该是堆积的 buffer 占用的，我误解了。

具体怎么调整，还是要看 metric ，根据指标你是可以推算出来整个 raft group 的吞吐量的，在吞吐量达标的情况下，再适当调整参数去获得最佳 latency。

**Comment by tsgmq** [comment]
重启一下已经好了，已经不能恢复现场，等下次有问题再一起看看
