### ISSUE TITLE
如何关闭jraft的日志生成，日志量实在太大

### ISSUE THREAD

**Issue by SpringLin97** [sofastack/sofa-jraft#724]
十几秒的时间生成几M的日志
![image](https://user-images.githubusercontent.com/63085858/143548021-96faf9d0-9229-4f82-94c4-920cc8ae8ea1.png)

**Comment by fengjiachun** [comment]
目前的日志级别是什么？ debug ？ info？ ，调整一下看看
这是 jraft 默认依赖的 rpc 框架 bolt 打印的日志，如果完全不想要这些日志，改用 grpc 也行，把  gprc-impl 模块引入到你的 pom 中即可

**Comment by SpringLin97** [comment]
>不能直接关闭 rpc 框架 bolt日志打印吗，日志级别是error

**Comment by SpringLin97** [comment]
> 目前的日志级别是什么？ debug ？ info？ ，调整一下看看 这是 jraft 默认依赖的 rpc 框架 bolt 打印的日志，如果完全不想要这些日志，改用 grpc 也行，把 gprc-impl 模块引入到你的 pom

**Comment by SpringLin97** [comment]
> 目前的日志级别是什么？ debug ？ info？ ，调整一下看看 这是 jraft 默认依赖的 rpc 框架 bolt 打印的日志，如果完全不想要这些日志，改用 grpc 也行，把 gprc-impl 模块引入到你的 pom 中即可

日志级别是error，控制台没有输出了，但是还生成日志文件，如何关闭rpc 框架 bolt 生成的日志文件，

**Comment by fengjiachun** [comment]
@SpringLin97 前两个日志文件你要么发上来，我看看什么内容

**Comment by fengjiachun** [comment]
前四个都上传上来？

**Comment by killme2008** [comment]
关闭应该很容易吧， slf4j 做个bolt包名的配置就可以了，主要还是看下为啥这么多日志，正常来讲不会是个问题才对

**Comment by SpringLin97** [comment]
> @SpringLin97 前两个日志文件你要么发上来，我看看什么内容

![image](https://user-images.githubusercontent.com/63085858/143795415-1095afbc-55d6-488b-989b-d72f54bcada0.png)
![image](https://user-images.githubusercontent.com/63085858/143795444-35e31b37-5358-49ac-8761-c33734c7bfd9.png)
![image](https://user-images.githubusercontent.com/63085858/143795464-9386c2ed-b983-4ec6-bd12-f41ea442bee4.png)

**Comment by SpringLin97** [comment]
> 关闭应该很容易吧， slf4j 做个bolt包名的配置就可以了，主要还是看下为啥这么多日志，正常来讲不会是个问题才对

屏蔽了包也没有用呀
![image](https://user-images.githubusercontent.com/63085858/143796679-2bc32454-4042-44e7-9710-7eca246a87b3.png)

**Comment by fengjiachun** [comment]
System.setProperty("com.alipay.remoting.client.log.level", "off");

**Comment by SpringLin97** [comment]
> System.setProperty("com.alipay.remoting.client.log.level", "off");

加了，也没有效果，还是生成日志
![image](https://user-images.githubusercontent.com/63085858/143815912-27ed30ac-e4ae-43cb-aaeb-bfe3b00bd922.png)

**Comment by SpringLin97** [comment]
> System.setProperty("com.alipay.remoting.client.log.level", "off");

根本就没有这个包，没用这个 类，你们怎么读取的
![image](https://user-images.githubusercontent.com/63085858/143816656-9d22f7ef-54d2-40b2-af70-99a24e955b74.png)

**Comment by fengjiachun** [comment]
System.setProperty("com.alipay.remoting.client.log.level", "off");

是关掉日志打印，不是关掉文件创建，你把日志文件删掉，再启动进程看下是否有新增日志，我是测过了才发上来的

**Comment by fengjiachun** [comment]
另外，要在你的进程启动最初就加上这段代码，或者使用 -D 确定参数，不是运行时随便调用一下就行了

**Comment by SpringLin97** [comment]
> 另外，要在你的进程启动最初就加上这段代码，或者使用 -D 启动参数，不是运行时随便调用一下就行了

我的问题是，日志追加在文件中，导致日志文件过大，如何屏蔽日志追加在文件中？控制台是没有打印的。

**Comment by fengjiachun** [comment]
> > 另外，要在你的进程启动最初就加上这段代码，或者使用 -D 启动参数，不是运行时随便调用一下就行了
> 
> 我的问题是，日志追加在文件中，导致日志文件过大，如何屏蔽日志追加在文件中？控制台是没有打印的。

我回答你的不就是这个问题吗

**Comment by fengjiachun** [comment]
> 另外，要在你的进程启动最初就加上这段代码，或者使用 -D 启动参数，不是运行时随便调用一下就行了

再确认一下方法

**Comment by SpringLin97** [comment]
> 动最



> > 另外，要在你的进程启动最初就加上这段代码，或者使用 -D 启动参数，不是运行时随便调用一下就行了
> 
> 再确认一下方法
解决了，在启动日志模块前，加上了屏蔽
![image](https://user-images.githubusercontent.com/63085858/143818097-8d416da4-8323-4bae-bcaf-fb8108509f21.png)
