### ISSUE TITLE
在组建集群或者启动的的时候，如何追加自己的身份验证方式？比如版本，密码等参数，除了jraft内部groupId识别身份。

### ISSUE THREAD

**Issue by SpringLin97** [sofastack/sofa-jraft#725]
![image](https://user-images.githubusercontent.com/63085858/143797351-6aee139c-4d93-41d9-a7c4-0c31dc40ff88.png)

**Comment by killme2008** [comment]
目前没有设计鉴权方式， 可以尝试用 ssl，比如 bolt ssl https://github.com/sofastack/sofa-bolt/pull/197
