### ISSUE TITLE
Aggressive snapshot cast causing exception with custom snapshot impl

### ISSUE THREAD

**Issue by colinrgodsey** [sofastack/sofa-jraft#728]
### Describe the bug

ClassCastException is thrown when using a custom Snapshot impl that does not extend `LocalSnapshotStorage`:

https://github.com/sofastack/sofa-jraft/blob/a1fa8c30a895fc45f39c9661eb383a890ba4b6d8/jraft-core/src/main/java/com/alipay/sofa/jraft/storage/snapshot/SnapshotExecutorImpl.java#L245-L248

### Expected behavior

Type check should be performed before casting.

### Actual behavior

ClassCastException is thrown when using a custom Snapshot impl that does not extend `LocalSnapshotStorage`.

### Steps to reproduce

Implement a custom Snapshot (using a custom `JRaftServiceFactory` in the `NodeOptions`) and wait until a snapshot is triggered.

### Minimal yet complete reproducer code (or GitHub URL to code)

None yet, but I'll probably submit a PR at some point with a test.

### Environment

- SOFAJRaft version: 1.3.8
- JVM version (e.g. `java -version`): n/a
- OS version (e.g. `uname -a`): n/a
- Maven version: n/a
- IDE version: n/a

**Comment by killme2008** [comment]
Yep, it's a bug here, welcome a PR, thank you.
