### ISSUE TITLE
New developers should be familiar with the code based on that branch？

### ISSUE THREAD

**Issue by kuaile-zc** [sofastack/sofa-jraft#731]
### Your question
New developers should be familiar with the code based on that branch？

**Comment by killme2008** [comment]
What do you mean? sorry ,i don't get it.

**Comment by kuaile-zc** [comment]
> What do you mean? sorry ,i don't get it.

我之前是想问，新手可以在那个分支上面调试。现在知道了。应该是在master是吧。

I was just asking, which branch can a novice debug on.  Now we know.  I think it's at Master.

**Comment by killme2008** [comment]
Yep, the master branch is the development branch.
