### ISSUE TITLE
Fail to unlock with Replicator

### ISSUE THREAD

**Issue by dengjunw** [sofastack/sofa-jraft#732]
### Your question
3个实例组成的raft集群，运行一段时间后，leader有大量WARN级别日志：Fail to unlock with Replicator。日志如下：
Fail to unlock with Replicator [state=Probe, statInfo=<running=IDLE, firstLogIndex=9914, lastLogIncluded=0, lastLogIndex=9914, lastTermIncluded=0>, peerId= 172.18.130.93:8081, type=Follower], the lock is held by null and current thread is Thread[JRaft-Rpc-Closure-Executor-19,5,main].

Fail to unlock with Replicator [state=Probe, statInfo=<running=IDLE, firstLogIndex=9914, lastLogIncluded=0, lastLogIndex=9914, lastTermIncluded=0>, peerId= 172.18.130.93:8081, type=Follower], the lock is held by Thread[JRaft-Rpc-Closure-Executor-33,5,main] and current thread is Thread[JRaft-Rpc-Closure-Executor-19,5,main].

Fail to unlock with Replicator [state=Probe, statInfo=<running=IDLE, firstLogIndex=9914, lastLogIncluded=0, lastLogIndex=9914, lastTermIncluded=0>, peerId= 172.18.130.93:8081, type=Follower], the lock is held by Thread[JRaft-Rpc-Closure-Executor-31,5,main] and current thread is Thread[JRaft-Rpc-Closure-Executor-19,5,main].

Fail to unlock with Replicator [state=Probe, statInfo=<running=IDLE, firstLogIndex=9914, lastLogIncluded=0, lastLogIndex=9914, lastTermIncluded=0>, peerId= 172.18.130.93:8081, type=Follower], the lock is held by null and current thread is Thread[JRaft-Rpc-Closure-Executor-19,5,main].

### Your scenes
3个实例组成的raft集群，主要模拟了账户的增删改查操作，业务数据通过rocksdb进行存储。

### Environment

- SOFAJRaft version: 1.3.8
- JVM version (e.g. `java -version`):  java8
- OS version (e.g. `uname -a`): Ubuntu
- Maven version:  3.6.3
- IDE version:

**Comment by killme2008** [comment]
有什么实际影响吗？ 这个应该只是一个 warn 日志， replicator 被销毁了，但是 rpc 是异步返回应答，尝试去寻找 replicator，就会打印这个告警信息，理论上无影响

**Comment by killme2008** [comment]
应该是这个问题 https://github.com/sofastack/sofa-jraft/issues/668

**Comment by dengjunw** [comment]
目前看没有影响，复制是正常的，只是leader这个日志量比较大。并且长时间以后会发生重新选举

**Comment by killme2008** [comment]
@dengjunw 理论上不应该经常出现，除非网络层经常出问题。

**Comment by killme2008** [comment]
1.3.10 发布，这个问题应该解决了
