### ISSUE TITLE
SOFAJRAFT是如何解决未提交日志冲突？

### ISSUE THREAD

**Issue by LinHuiG** [sofastack/sofa-jraft#733]
### Your question

举例：
某SOFAJRAFT集群有五个节点：A,B,C,D,E，此时A节点为领导者，当前日志序号为x并全部已提交。
若A节点提交一条日志，日志序号为x+1，并且发送到B节点，这时网络故障，CDE与AB分区并触发选举。
此时C被选为新领导者，并新增了另一条x+1的日志并提交。
请问当网络正常时候，A和B节点中的x+1日志是如何处理的，我没看到回滚机制。

### Your scenes

Describe your use scenes (why need this feature)

### Your advice

Describe the advice or solution you'd like

### Environment

- SOFAJRaft version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by killme2008** [comment]
参见 LogMangerImpl 的 `checkAndResolveConflict`方法

https://github.com/sofastack/sofa-jraft/blob/master/jraft-core/src/main/java/com/alipay/sofa/jraft/storage/impl/LogManagerImpl.java#L994

**Comment by LinHuiG** [comment]
非常感谢，我现在的理解是：日志在提交后才会应用到状态机，若领导者最新日志为x，则将该x+1日志加到领导者日志末尾，若发生日志冲突则以领导者为准。若新领导者提交了新的x+1日志，即使新跟随者未收到提交推送，若再次发生分区，下一代领导者依然会持有新领导者提交的日志（此代领导者上任时不知此日志是否提交，但一定是准确的）。
举例（新）：
某SOFAJRAFT集群有五个节点：A,B,C,D,E，此时A节点为领导者，当前日志序号为x并全部已提交。
若A节点提交一条日志，日志序号为x+1，并且发送到B节点，这时网络故障，CDE与AB分区并触发选举。
此时C被选为新领导者，并新增了另一条x+1的日志，DE正常接收日志但未收到提交推送（C已发出提交推送）。
此时网络分区变化，ABD在一个分区，此时ABD都持有一条未提交x+1日志（D的已提交但D不知道）。
我理解此时选举必然选出D，因为在日志比对中D的日志最大（因为任期大，我注意到你们的LogId类的compareTo方法优先比对了term）。

请问我的理解有什么问题吗。

**Comment by killme2008** [comment]
你的理解存在一些问题，或者说描述不是那么准确的地方， issue 不是讨论论文或者实现细节的地方。建议仔细阅读下论文的 5.4.2 节， 这块的讨论和资料也非常多，中英文都有，我也不在这里赘述。

**Comment by LinHuiG** [comment]
好的，谢谢

**Comment by fengjiachun** [comment]
没其他问题关闭了
