### ISSUE TITLE
快照安装过程中报错 重复响应rpc问题

### ISSUE THREAD

**Issue by yaowenfeng998** [sofastack/sofa-jraft#735]
场景：四个节点三副本，副本默认启动region -1，存储端是rocksdb,加载数据后 region -1开始分裂，分裂完成后分区开始保存快照
           在快照写成功的前提下，调用cli服务的changePeer方法变更该分区所在的ratf group，新加入的节点收到leader的安装快照请求
           加载快照。
问题：当快照中的数据较少时，新加入的节点可以成功安装加载快照，
           当快照中的数据较多时（8亿kv对），新加入的节点报错重复发送rpc响应？
          
![image](https://user-images.githubusercontent.com/79828715/145328304-dcd33ede-d635-4e80-96dd-8524f517e2c7.png)

**Comment by killme2008** [comment]
当快照过大的时候，目前的实现是有这个问题，这个 PR 就就是想通过分片和断点续传解决这个问题

https://github.com/sofastack/sofa-jraft/pull/639

我们目前推荐的做法是建议人工拷贝 snapshot （例如 scp）到新节点，然后再加入，避免走 RPC 安装。

**Comment by fengjiachun** [comment]
一般来讲，要控制数据搬迁的最小单位，比如采用 multi raft group，一个 group 中的数据量（snapshot） 最大几十 M 以内，这样会比较合理

当然单 group 也可以，SCP 人工拷贝确实会更快

**Comment by killme2008** [comment]
嗯，更合理还是应该控制单个 group 大小
