### ISSUE TITLE
提交延时问题

### ISSUE THREAD

**Issue by LinHuiG** [sofastack/sofa-jraft#737]
### Your question

我在同一台机器上启动了三个节点，任务从apply到onApply平均需要20ms，请问这性能是正常表现吗？

### Environment

- SOFAJRaft version:1.3.2
- JVM version (e.g. `java -version`):1.8
- OS version (e.g. `uname -a`):win10
- Maven version:3.8.1
- IDE version:

**Comment by fengjiachun** [comment]
https://www.sofastack.tech/projects/sofa-jraft/jraft-user-guide/

11小节，看下 metric

**Comment by LinHuiG** [comment]
你好，这是我的Metric信息，我想先问一下在正常情况下从apply到onApply的延迟大概是什么量级呢。
[Metric.txt](https://github.com/sofastack/sofa-jraft/files/7683832/Metric.txt)

**Comment by fengjiachun** [comment]
你给的是啥没看懂，给下原始的吧，不要你转过一层的

> 我想先问一下在正常情况下从apply到onApply的延迟大概是什么量级呢

正常肯定不会到 20ms，可参考 benchmark 情况下的平均耗时（包含用户状态机执行万 apply 以及 rpc 通信时间）： https://www.sofastack.tech/projects/sofa-jraft/benchmark-performance/

**Comment by LinHuiG** [comment]
你好，我刚刚将代码部署到centos7上运行，kill -s SIGUSR2 27538 后并没有输出Metric文件，只有这个文件生成
[node_describe.2021-12-09_18-26-36.log](https://github.com/sofastack/sofa-jraft/files/7684251/node_describe.2021-12-09_18-26-36.log)
。

**Comment by fengjiachun** [comment]
不会的，多个文件是由同一个信号触发，看看 jraft 自身的日志，是否输出文件是出错了

**Comment by fengjiachun** [comment]
你个的是 follower 节点的信息，给下 leader 节点的

**Comment by LinHuiG** [comment]
[node_describe.2021-12-09_19-09-44.log](https://github.com/sofastack/sofa-jraft/files/7684555/node_describe.2021-12-09_19-09-44.log)
你好，这是leader节点的文件

**Comment by fengjiachun** [comment]
metric呢？

**Comment by LinHuiG** [comment]
这个信号量没有触发metic文件的生成==

**Comment by fengjiachun** [comment]
可不可以排查一下为什么？ 否则我没什么可以作为参考的，猜不出来原因

**Comment by LinHuiG** [comment]
我改了一下代码，同步写入每条数据大约是5ms，将同步写入改为了异步，当所有数据commit的时候性能提高了几十倍，（一万条数据使用了156ms），是不是有什么配置是关于批量调用延时等待的...

**Comment by killme2008** [comment]
他要启用 metric 吧？ 

```
NodeOptions nodeOpts =  ...
nodeOpts.setEnableMetrics(true);
```

**Comment by LinHuiG** [comment]
这个有的，我启用了

**Comment by LinHuiG** [comment]
Node.getNodeMetrics().getMetricRegistry()这个接口可以获取到metric数据，但是要打印下来只能Json格式化...

**Comment by fengjiachun** [comment]
> 我改了一下代码，同步写入每条数据大约是5ms，将同步写入改为了异步，当所有数据commit的时候性能提高了几十倍，（一万条数据使用了156ms），是不是有什么配置是关于批量调用延时等待的...

整个链路上没有延时等待这种行为，攒批全部是异步非延时攒批

**Comment by LinHuiG** [comment]
我排查一下为什么无法生成metric文件吧

**Comment by fengjiachun** [comment]
> 我排查一下为什么无法生成metric文件吧

好像知道了，你是不是 windows ？

**Comment by LinHuiG** [comment]
我部署到centos7上去生成文件了..
但是没生成出来

**Comment by fengjiachun** [comment]
> 我部署到centos7上去生成文件了.. 但是没生成出来

哦哦，对，我忘记了你提到过， win 下的话不能使用 sigusr2 信号，一个文件也不会产生，linux 应该产生多个文件的，这个还是要你帮忙查一下

**Comment by LinHuiG** [comment]
我今晚查一下吧，找到了再来问您。

**Comment by fengjiachun** [comment]
https://github.com/sofastack/sofa-jraft/blob/master/jraft-core/src/main/java/com/alipay/sofa/jraft/core/NodeImpl.java#L151

signal handler 加载逻辑在这里，如果你没修改代码默认是会基于 SPI 加载到 3 个 signal handler 的，所以一共会输出三个文件：
https://github.com/sofastack/sofa-jraft/blob/master/jraft-core/src/main/resources/META-INF/services/com.alipay.sofa.jraft.util.JRaftSignalHandler

**Comment by LinHuiG** [comment]
谢谢，我看一下

**Comment by LinHuiG** [comment]
您好，通过排查发现信号量触发成功但是执行过程中报错：日志信息
2021-12-09 19:58:58  com.alipay.sofa.jraft.util.SignalHelper [SIGUSR2 handler]-[ERROR] Fail to handle signal: SIGUSR2.
java.lang.NullPointerException: null
        at com.alipay.sofa.jraft.core.NodeImpl.describe(NodeImpl.java:3377) ~[jraft-core-1.3.2.jar:?]
        at com.alipay.sofa.jraft.NodeDescribeSignalHandler.handle(NodeDescribeSignalHandler.java:61) ~[jraft-core-1.3.2.jar:?]
        at com.alipay.sofa.jraft.util.SignalHelper$SignalHandlerAdapter.handle(SignalHelper.java:107) [jraft-core-1.3.2.jar:?]
        at sun.misc.Signal$1.run(Signal.java:212) [?:1.8.0_201]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]

**Comment by LinHuiG** [comment]
[node_metrics.2021-12-09_20-07-28.log](https://github.com/sofastack/sofa-jraft/files/7684896/node_metrics.2021-12-09_20-07-28.log)
我修改了他们的输出顺序，拿到metric了

**Comment by LinHuiG** [comment]
这是leader的三个文件，麻烦您了
[thread_pool_metrics.log.2021-12-09_20-10-15.log](https://github.com/sofastack/sofa-jraft/files/7684916/thread_pool_metrics.log.2021-12-09_20-10-15.log)
[node_describe.log.2021-12-09_20-10-15.log](https://github.com/sofastack/sofa-jraft/files/7684917/node_describe.log.2021-12-09_20-10-15.log)
[node_metrics.log.2021-12-09_20-10-15.log](https://github.com/sofastack/sofa-jraft/files/7684918/node_metrics.log.2021-12-09_20-10-15.log)

**Comment by fengjiachun** [comment]
貌似你自己实现的状态机在 onApply 执行的最大耗时 8 秒了，所以耗时应该在你自己状态机里面
```
fsm-apply-tasks
             count = 9
         mean rate = 0.26 calls/second
     1-minute rate = 0.35 calls/second
     5-minute rate = 0.39 calls/second
    15-minute rate = 0.40 calls/second
               min = 0.00 milliseconds
               max = 8021.00 milliseconds
              mean = 1396.65 milliseconds
            stddev = 2546.05 milliseconds
            median = 30.00 milliseconds
              75% <= 920.00 milliseconds
              95% <= 8021.00 milliseconds
              98% <= 8021.00 milliseconds
              99% <= 8021.00 milliseconds
            99.9% <= 8021.00 milliseconds
```

**Comment by LinHuiG** [comment]
目前状态机里只进行了数据的接收（一个string的反序列化，大约十个字符），并且每次执行一条，同步等待的话延时稳定是5到10毫秒。

**Comment by fengjiachun** [comment]
> 目前状态机里只进行了数据的接收（一个string的反序列化，大约十个字符），并且每次执行一条，同步等待的话延时稳定是5到10毫秒。

一次 onApply ，反序列化了 40w 个字符串，能快吗？

PS：你 60w 条 raft log，没有 snapshot，刚启动是在回放 raft log 呢，把数据删了再测下看看

**Comment by LinHuiG** [comment]
嗷，我把序列化和日志删了再试试

**Comment by fengjiachun** [comment]
https://www.sofastack.tech/projects/sofa-jraft/jraft-user-guide/

文档第八小节，各个 metric 的作用请看一下，也可以结合代码很容易明白每个 metric 的作用，结合 metirc 一般你自己就可以查出大概问题，这个 issue 我就先关闭了

**Comment by fengjiachun** [comment]
建议先读一遍文档

**Comment by LinHuiG** [comment]
状态机现在不做任何处理，日志也清空了，提交延时还是5ms左右=
[node_describe.log.2021-12-10_09-26-31.log](https://github.com/sofastack/sofa-jraft/files/7689448/node_describe.log.2021-12-10_09-26-31.log)
[node_metrics.log.2021-12-10_09-26-31.log](https://github.com/sofastack/sofa-jraft/files/7689450/node_metrics.log.2021-12-10_09-26-31.log)
[thread_pool_metrics.log.2021-12-10_09-26-31.log](https://github.com/sofastack/sofa-jraft/files/7689451/thread_pool_metrics.log.2021-12-10_09-26-31.log)
=

**Comment by LinHuiG** [comment]
好吧，我自己先排查一下吧，不过能告诉我从发起apply到开始执行onApply的延时（不算状态机执行）正常情况下应该是多少吗。

**Comment by fengjiachun** [comment]
> 好吧，我自己先排查一下吧，不过能告诉我从发起apply到开始执行onApply的延时（不算状态机执行）正常情况下应该是多少吗。

可以先查一下你自己的状态机为什么执行了 26ms

```
fsm-apply-tasks
             count = 8
         mean rate = 0.16 calls/second
     1-minute rate = 0.17 calls/second
     5-minute rate = 0.19 calls/second
    15-minute rate = 0.20 calls/second
               min = 0.00 milliseconds
               max = 26.00 milliseconds
              mean = 2.88 milliseconds
            stddev = 7.54 milliseconds
            median = 0.00 milliseconds
              75% <= 1.00 milliseconds
              95% <= 26.00 milliseconds
              98% <= 26.00 milliseconds
              99% <= 26.00 milliseconds
            99.9% <= 26.00 milliseconds
```

**Comment by fengjiachun** [comment]
> 好吧，我自己先排查一下吧，不过能告诉我从发起apply到开始执行onApply的延时（不算状态机执行）正常情况下应该是多少吗。

这个不是给你了么，上面给了你 benchmark 连接，里面不是有延时数据么

**Comment by LinHuiG** [comment]
好的
