### ISSUE TITLE
SOFA-Jraft优化咨询

### ISSUE THREAD

**Issue by LinHuiG** [sofastack/sofa-jraft#744]
### Your question

您好，我在使用SOFA-JRAFT的时候遇到了一点问题，就是在轻负载的情况下apply提交任务到onApply这段时间延迟会超过5ms。
场景是单机三节点，状态机内只进行future的complete。
我在各个场景下进行了测试，无论是重负载（一次提交一万个task）还是轻负载（一次提交一个task），对于每个task从apply到onApply的延迟都超过了5ms，状态机内只进行future的complete。

我上周曾经咨询过相关问题，得到的优化方向没有解决掉问题，很抱歉再次打扰您，非常感谢您的解惑。

### Your scenes

Describe your use scenes (why need this feature)

### Your advice

Describe the advice or solution you'd like

### Environment

- SOFAJRaft version:1.3.9
- JVM version (e.g. `java -version`):1.8
- OS version (e.g. `uname -a`):centos7
- Maven version:3.8.1
- IDE version:

**Comment by fengjiachun** [comment]
最新的 metric 数据给下，之前看你的业务状态机执行时间大概就是 5ms，最大 26ms

```
fsm-apply-tasks
             count = 8
         mean rate = 0.16 calls/second
     1-minute rate = 0.17 calls/second
     5-minute rate = 0.19 calls/second
    15-minute rate = 0.20 calls/second
               min = 0.00 milliseconds
               max = 26.00 milliseconds
              mean = 2.88 milliseconds
            stddev = 7.54 milliseconds
            median = 0.00 milliseconds
              75% <= 1.00 milliseconds
              95% <= 26.00 milliseconds
              98% <= 26.00 milliseconds
              99% <= 26.00 milliseconds
            99.9% <= 26.00 milliseconds
```

**Comment by LinHuiG** [comment]
好的，请稍等

**Comment by LinHuiG** [comment]
[node_metrics.log.2021-12-15_14-58-25.log](https://github.com/sofastack/sofa-jraft/files/7717082/node_metrics.log.2021-12-15_14-58-25.log)
您好，这是我刚刚测试的metric文件

**Comment by LinHuiG** [comment]
fsm-apply-tasks
             count = 21
         mean rate = 0.40 calls/second
     1-minute rate = 0.36 calls/second
     5-minute rate = 0.40 calls/second
    15-minute rate = 0.40 calls/second
               min = 0.00 milliseconds
               max = 1.00 milliseconds
              mean = 0.09 milliseconds
            stddev = 0.29 milliseconds
            median = 0.00 milliseconds
              75% <= 0.00 milliseconds
              95% <= 1.00 milliseconds
              98% <= 1.00 milliseconds
              99% <= 1.00 milliseconds
            99.9% <= 1.00 milliseconds

**Comment by LinHuiG** [comment]
状态机内操作是将两个字符串放入哈希表中，并将future进行complete

**Comment by fengjiachun** [comment]
现在应该没有 5ms 延时了啊

**Comment by fengjiachun** [comment]
你的 5ms 延时怎么统计的？

**Comment by LinHuiG** [comment]
CompletableFuture<TaskReturn> future = new CompletableFuture();
        Task task = new Task();
        SyncTaskClosure closure = new SyncTaskClosure(future, raftTask);
        task.setDone(closure);
        ByteBuffer buffer = ByteUtil.getByteBuffer(raftTask);
        task.setData(buffer);
        task.setExpectedTerm(this.stateMachine.leaderTerm.get());
        long start = System.nanoTime();
        future.whenComplete((a, e) -> {
            long spendTime = System.nanoTime() - start;
            a.setSpendTime(spendTime);
        });
        this.currentNode.apply(task);

**Comment by fengjiachun** [comment]
统计的具体指标数据看一下

**Comment by LinHuiG** [comment]
具体的指标数据是指什么呢

**Comment by LinHuiG** [comment]
目前我是手动一个一个触发测试延迟的，统计数据大概是5ms左右浮动（最新的几条（单位纳秒）：5411978，5713915，5117072，4197633，5047649）

**Comment by LinHuiG** [comment]
如果批量提交的话速度好一些，一次性提交一万条到这一万条都被执行大概花600ms左右，但是单条提交总是很慢..

**Comment by fengjiachun** [comment]
> 目前我是手动一个一个触发测试延迟的，统计数据大概是5ms左右浮动（最新的几条（单位纳秒）：5411978，5713915，5117072，4197633，5047649）

你手动触发只 run 了几次？ 写个循环多 run 一会吧，用 metric.timer 记录一下耗时，jraft 就提供的 KVMetrics.timer

**Comment by LinHuiG** [comment]
您好，我使用metric计时了一下重复跑多次的结果，这是metric对象打印成json的数据

**Comment by LinHuiG** [comment]
{
  "key": "k1",
  "val": "v1",
  "n": 10,
  "ret": {
    "status": 0,
    "val": "v1",
    "spendTime": 36619547
  },
  "spendTime2": 41.612660999999996,
  "metrics": {
    "metrics": {
      "执行次序：7": {
        "fifteenMinuteRate": 0.0,
        "fiveMinuteRate": 0.0,
        "meanRate": 70.09283726202517,
        "oneMinuteRate": 0.0,
        "count": 1,
        "snapshot": {
          "values": [
            7905910
          ],
          "mean": 7905910.0,
          "min": 7905910,
          "stdDev": 0.0,
          "max": 7905910,
          "median": 7905910.0,
          "75thPercentile": 7905910.0,
          "95thPercentile": 7905910.0,
          "98thPercentile": 7905910.0,
          "99thPercentile": 7905910.0,
          "999thPercentile": 7905910.0
        }
      },
      "执行次序：8": {
        "fifteenMinuteRate": 0.0,
        "fiveMinuteRate": 0.0,
        "meanRate": 70.26924433930292,
        "oneMinuteRate": 0.0,
        "count": 1,
        "snapshot": {
          "values": [
            7473872
          ],
          "mean": 7473872.0,
          "min": 7473872,
          "stdDev": 0.0,
          "max": 7473872,
          "median": 7473872.0,
          "75thPercentile": 7473872.0,
          "95thPercentile": 7473872.0,
          "98thPercentile": 7473872.0,
          "99thPercentile": 7473872.0,
          "999thPercentile": 7473872.0
        }
      },
      "执行次序：9": {
        "fifteenMinuteRate": 0.0,
        "fiveMinuteRate": 0.0,
        "meanRate": 65.32892197610059,
        "oneMinuteRate": 0.0,
        "count": 1,
        "snapshot": {
          "values": [
            7108619
          ],
          "mean": 7108619.0,
          "min": 7108619,
          "stdDev": 0.0,
          "max": 7108619,
          "median": 7108619.0,
          "75thPercentile": 7108619.0,
          "95thPercentile": 7108619.0,
          "98thPercentile": 7108619.0,
          "99thPercentile": 7108619.0,
          "999thPercentile": 7108619.0
        }
      },
      "执行次序：0": {
        "fifteenMinuteRate": 0.0,
        "fiveMinuteRate": 0.0,
        "meanRate": 20.033345503590727,
        "oneMinuteRate": 0.0,
        "count": 1,
        "snapshot": {
          "values": [
            37159840
          ],
          "mean": 3.715984E7,
          "min": 37159840,
          "stdDev": 0.0,
          "max": 37159840,
          "median": 3.715984E7,
          "75thPercentile": 3.715984E7,
          "95thPercentile": 3.715984E7,
          "98thPercentile": 3.715984E7,
          "99thPercentile": 3.715984E7,
          "999thPercentile": 3.715984E7
        }
      },
      "执行次序：1": {
        "fifteenMinuteRate": 0.0,
        "fiveMinuteRate": 0.0,
        "meanRate": 20.23876889997434,
        "oneMinuteRate": 0.0,
        "count": 1,
        "snapshot": {
          "values": [
            36544020
          ],
          "mean": 3.654402E7,
          "min": 36544020,
          "stdDev": 0.0,
          "max": 36544020,
          "median": 3.654402E7,
          "75thPercentile": 3.654402E7,
          "95thPercentile": 3.654402E7,
          "98thPercentile": 3.654402E7,
          "99thPercentile": 3.654402E7,
          "999thPercentile": 3.654402E7
        }
      },
      "执行次序：2": {
        "fifteenMinuteRate": 0.0,
        "fiveMinuteRate": 0.0,
        "meanRate": 20.263622022334197,
        "oneMinuteRate": 0.0,
        "count": 1,
        "snapshot": {
          "values": [
            36274301
          ],
          "mean": 3.6274301E7,
          "min": 36274301,
          "stdDev": 0.0,
          "max": 36274301,
          "median": 3.6274301E7,
          "75thPercentile": 3.6274301E7,
          "95thPercentile": 3.6274301E7,
          "98thPercentile": 3.6274301E7,
          "99thPercentile": 3.6274301E7,
          "999thPercentile": 3.6274301E7
        }
      },
      "执行次序：3": {
        "fifteenMinuteRate": 0.0,
        "fiveMinuteRate": 0.0,
        "meanRate": 20.28571455232653,
        "oneMinuteRate": 0.0,
        "count": 1,
        "snapshot": {
          "values": [
            39944494
          ],
          "mean": 3.9944494E7,
          "min": 39944494,
          "stdDev": 0.0,
          "max": 39944494,
          "median": 3.9944494E7,
          "75thPercentile": 3.9944494E7,
          "95thPercentile": 3.9944494E7,
          "98thPercentile": 3.9944494E7,
          "99thPercentile": 3.9944494E7,
          "999thPercentile": 3.9944494E7
        }
      },
      "执行次序：4": {
        "fifteenMinuteRate": 0.0,
        "fiveMinuteRate": 0.0,
        "meanRate": 47.44086425109804,
        "oneMinuteRate": 0.0,
        "count": 1,
        "snapshot": {
          "values": [
            11487621
          ],
          "mean": 1.1487621E7,
          "min": 11487621,
          "stdDev": 0.0,
          "max": 11487621,
          "median": 1.1487621E7,
          "75thPercentile": 1.1487621E7,
          "95thPercentile": 1.1487621E7,
          "98thPercentile": 1.1487621E7,
          "99thPercentile": 1.1487621E7,
          "999thPercentile": 1.1487621E7
        }
      },
      "执行次序：5": {
        "fifteenMinuteRate": 0.0,
        "fiveMinuteRate": 0.0,
        "meanRate": 47.73267867009884,
        "oneMinuteRate": 0.0,
        "count": 1,
        "snapshot": {
          "values": [
            11094082
          ],
          "mean": 1.1094082E7,
          "min": 11094082,
          "stdDev": 0.0,
          "max": 11094082,
          "median": 1.1094082E7,
          "75thPercentile": 1.1094082E7,
          "95thPercentile": 1.1094082E7,
          "98thPercentile": 1.1094082E7,
          "99thPercentile": 1.1094082E7,
          "999thPercentile": 1.1094082E7
        }
      },
      "执行次序：6": {
        "fifteenMinuteRate": 0.0,
        "fiveMinuteRate": 0.0,
        "meanRate": 51.145806721530775,
        "oneMinuteRate": 0.0,
        "count": 1,
        "snapshot": {
          "values": [
            9310798
          ],
          "mean": 9310798.0,
          "min": 9310798,
          "stdDev": 0.0,
          "max": 9310798,
          "median": 9310798.0,
          "75thPercentile": 9310798.0,
          "95thPercentile": 9310798.0,
          "98thPercentile": 9310798.0,
          "99thPercentile": 9310798.0,
          "999thPercentile": 9310798.0
        }
      }
    },
    "names": [
      "执行次序：0",
      "执行次序：1",
      "执行次序：2",
      "执行次序：3",
      "执行次序：4",
      "执行次序：5",
      "执行次序：6",
      "执行次序：7",
      "执行次序：8",
      "执行次序：9"
    ],
    "gauges": {},
    "counters": {},
    "histograms": {},
    "meters": {},
    "timers": {
      "执行次序：0": {
        "fifteenMinuteRate": 0.0,
        "fiveMinuteRate": 0.0,
        "meanRate": 19.15137976402781,
        "oneMinuteRate": 0.0,
        "count": 1,
        "snapshot": {
          "values": [
            37159840
          ],
          "mean": 3.715984E7,
          "min": 37159840,
          "stdDev": 0.0,
          "max": 37159840,
          "median": 3.715984E7,
          "75thPercentile": 3.715984E7,
          "95thPercentile": 3.715984E7,
          "98thPercentile": 3.715984E7,
          "99thPercentile": 3.715984E7,
          "999thPercentile": 3.715984E7
        }
      },
      "执行次序：1": {
        "fifteenMinuteRate": 0.0,
        "fiveMinuteRate": 0.0,
        "meanRate": 19.28903100704019,
        "oneMinuteRate": 0.0,
        "count": 1,
        "snapshot": {
          "values": [
            36544020
          ],
          "mean": 3.654402E7,
          "min": 36544020,
          "stdDev": 0.0,
          "max": 36544020,
          "median": 3.654402E7,
          "75thPercentile": 3.654402E7,
          "95thPercentile": 3.654402E7,
          "98thPercentile": 3.654402E7,
          "99thPercentile": 3.654402E7,
          "999thPercentile": 3.654402E7
        }
      },
      "执行次序：2": {
        "fifteenMinuteRate": 0.0,
        "fiveMinuteRate": 0.0,
        "meanRate": 19.323786880196057,
        "oneMinuteRate": 0.0,
        "count": 1,
        "snapshot": {
          "values": [
            36274301
          ],
          "mean": 3.6274301E7,
          "min": 36274301,
          "stdDev": 0.0,
          "max": 36274301,
          "median": 3.6274301E7,
          "75thPercentile": 3.6274301E7,
          "95thPercentile": 3.6274301E7,
          "98thPercentile": 3.6274301E7,
          "99thPercentile": 3.6274301E7,
          "999thPercentile": 3.6274301E7
        }
      },
      "执行次序：3": {
        "fifteenMinuteRate": 0.0,
        "fiveMinuteRate": 0.0,
        "meanRate": 18.579549931583593,
        "oneMinuteRate": 0.0,
        "count": 1,
        "snapshot": {
          "values": [
            39944494
          ],
          "mean": 3.9944494E7,
          "min": 39944494,
          "stdDev": 0.0,
          "max": 39944494,
          "median": 3.9944494E7,
          "75thPercentile": 3.9944494E7,
          "95thPercentile": 3.9944494E7,
          "98thPercentile": 3.9944494E7,
          "99thPercentile": 3.9944494E7,
          "999thPercentile": 3.9944494E7
        }
      },
      "执行次序：4": {
        "fifteenMinuteRate": 0.0,
        "fiveMinuteRate": 0.0,
        "meanRate": 32.51354018252516,
        "oneMinuteRate": 0.0,
        "count": 1,
        "snapshot": {
          "values": [
            11487621
          ],
          "mean": 1.1487621E7,
          "min": 11487621,
          "stdDev": 0.0,
          "max": 11487621,
          "median": 1.1487621E7,
          "75thPercentile": 1.1487621E7,
          "95thPercentile": 1.1487621E7,
          "98thPercentile": 1.1487621E7,
          "99thPercentile": 1.1487621E7,
          "999thPercentile": 1.1487621E7
        }
      },
      "执行次序：5": {
        "fifteenMinuteRate": 0.0,
        "fiveMinuteRate": 0.0,
        "meanRate": 32.48650965200191,
        "oneMinuteRate": 0.0,
        "count": 1,
        "snapshot": {
          "values": [
            11094082
          ],
          "mean": 1.1094082E7,
          "min": 11094082,
          "stdDev": 0.0,
          "max": 11094082,
          "median": 1.1094082E7,
          "75thPercentile": 1.1094082E7,
          "95thPercentile": 1.1094082E7,
          "98thPercentile": 1.1094082E7,
          "99thPercentile": 1.1094082E7,
          "999thPercentile": 1.1094082E7
        }
      },
      "执行次序：6": {
        "fifteenMinuteRate": 0.0,
        "fiveMinuteRate": 0.0,
        "meanRate": 34.21781128781265,
        "oneMinuteRate": 0.0,
        "count": 1,
        "snapshot": {
          "values": [
            9310798
          ],
          "mean": 9310798.0,
          "min": 9310798,
          "stdDev": 0.0,
          "max": 9310798,
          "median": 9310798.0,
          "75thPercentile": 9310798.0,
          "95thPercentile": 9310798.0,
          "98thPercentile": 9310798.0,
          "99thPercentile": 9310798.0,
          "999thPercentile": 9310798.0
        }
      },
      "执行次序：7": {
        "fifteenMinuteRate": 0.0,
        "fiveMinuteRate": 0.0,
        "meanRate": 35.707313861254306,
        "oneMinuteRate": 0.0,
        "count": 1,
        "snapshot": {
          "values": [
            7905910
          ],
          "mean": 7905910.0,
          "min": 7905910,
          "stdDev": 0.0,
          "max": 7905910,
          "median": 7905910.0,
          "75thPercentile": 7905910.0,
          "95thPercentile": 7905910.0,
          "98thPercentile": 7905910.0,
          "99thPercentile": 7905910.0,
          "999thPercentile": 7905910.0
        }
      },
      "执行次序：8": {
        "fifteenMinuteRate": 0.0,
        "fiveMinuteRate": 0.0,
        "meanRate": 35.99065409090829,
        "oneMinuteRate": 0.0,
        "count": 1,
        "snapshot": {
          "values": [
            7473872
          ],
          "mean": 7473872.0,
          "min": 7473872,
          "stdDev": 0.0,
          "max": 7473872,
          "median": 7473872.0,
          "75thPercentile": 7473872.0,
          "95thPercentile": 7473872.0,
          "98thPercentile": 7473872.0,
          "99thPercentile": 7473872.0,
          "999thPercentile": 7473872.0
        }
      },
      "执行次序：9": {
        "fifteenMinuteRate": 0.0,
        "fiveMinuteRate": 0.0,
        "meanRate": 36.17213319838233,
        "oneMinuteRate": 0.0,
        "count": 1,
        "snapshot": {
          "values": [
            7108619
          ],
          "mean": 7108619.0,
          "min": 7108619,
          "stdDev": 0.0,
          "max": 7108619,
          "median": 7108619.0,
          "75thPercentile": 7108619.0,
          "95thPercentile": 7108619.0,
          "98thPercentile": 7108619.0,
          "99thPercentile": 7108619.0,
          "999thPercentile": 7108619.0
        }
      }
    }
  }
}

**Comment by fengjiachun** [comment]
看不懂

**Comment by LinHuiG** [comment]
这是我的测试代码

**Comment by fengjiachun** [comment]
你用 KVMetrics.timer ， kill -s SIGUSR2 也会输出结果的

**Comment by LinHuiG** [comment]
好的，我试试

**Comment by fengjiachun** [comment]
> 这是我的测试代码，返回的map转成json就是上面的数据
> 
> ```
> @RequestMapping("/submitTask")
> public Map<Object,Object> submitTask(@RequestBody Map<Object, Object> params) throws Exception {
>     Object k=params.get("key");
>     Object v=params.get("val");
>     RaftTask task=new RaftTask();
>     task.Data.add(k);
>     task.Data.add(v);
>     task.type="13";
>     int n= (int) params.get("n");
> 
> 
>     MetricRegistry metrics = new MetricRegistry();
> 
>     long start = System.nanoTime();
>     CountDownLatch latch=new CountDownLatch(n);
>     for (int i=0;i<n;i++){
>         Timer.Context mTimern = metrics.timer("执行次序："+i).time();//--------mTimer1开始计时
> 
>         CompletableFuture<TaskReturn> future= JraftManege.raftServerManage.submitTask(task);
>         future.whenComplete((a,b)->{
>             mTimern.stop();
>             if (b!=null)
>                 params.put("error",b.getMessage());
>             params.putIfAbsent("ret",a);
>             latch.countDown();
>         });
>     }
>     latch.await();
>     params.put("spendTime2",(System.nanoTime() - start) * 0.000001);
>     params.put("metrics",metrics);
>     return params;
> }
> ```

唉，我的意思是，你写一个循环，不断的 apply task，然后再看耗时统计，用 com.alipay.sofa.jraft.core.NodeMetrics#recordLatency 这个吧，KVMetrics 是 rheakv 的，看起来你只用了 jraft-core

**Comment by LinHuiG** [comment]
是的，我只用了jraft-core，写一个循环不断apply我测试过，apply一万条大概在600ms左右，看上去没什么问题，不过单条比较慢...

**Comment by fengjiachun** [comment]
> 是的，我只用了jraft-core，写一个循环不断apply我测试过，apply一万条大概在600ms左右，看上去没什么问题，不过单条比较慢...

我意思是你不断的 apply 单条，然后看耗时，现在怀疑 5ms 包含了一些预热时间等

**Comment by LinHuiG** [comment]
就是apply一条，同步等它返回然后再下一条，不断循环吗，这个我也测试过的，平均也是5ms左右。

**Comment by fengjiachun** [comment]
异步，攒一批在同步等一下

**Comment by LinHuiG** [comment]
提交一批，同步等这一批返回，然后再提交一批这样吗，我测试过每批提交一千条，等这一千条都返回再提交下一千条，总吞吐量最高达到过4w/s，但是针对单条的计时都在5ms以上。

**Comment by LinHuiG** [comment]
冯老师您看看测试代码这么写可以吗

        NodeMetrics metrics = new NodeMetrics(true);
        long start = System.nanoTime();
        CountDownLatch latch=new CountDownLatch(n);
        for (int i=0;i<n;i++){
            CompletableFuture<TaskReturn> future= JraftManege.raftServerManage.submitTask(task);
            long startApply = System.nanoTime();
            int finalI = i;
            future.whenComplete((a, b)->{
                if (b!=null)
                    params.put("error",b.getMessage());
                params.putIfAbsent("ret",a);
                metrics.recordTimes("i:"+finalI,System.nanoTime()-startApply);
                latch.countDown();
            });
        }

**Comment by fengjiachun** [comment]
不是老师哈，我也是个小菜鸟

1. node.getNodeMetrics, 不要再创建
2. recordLatency 第二个参数仔细看下，单位是毫秒哈
3. 外层再套一个循环， m*n， n不要取太大

**Comment by LinHuiG** [comment]
哈哈，达者为先，大哥看看这样可以吗

        NodeMetrics metrics = JraftManege.raftServerManage.getCurrentNode().getNodeMetrics();
        long start = System.nanoTime();
        for (int i=0;i<m;i++){
            CountDownLatch latch=new CountDownLatch(n);
            for (int j=0;j<n;j++){
                CompletableFuture<TaskReturn> future= JraftManege.raftServerManage.submitTask(task);
                long startApply = System.currentTimeMillis();
                int finalI = i;
                future.whenComplete((a, b)->{
                    if (b!=null)
                        params.put("error",b.getMessage());
                    params.putIfAbsent("ret",a);
                    metrics.recordTimes("i:"+finalI,System.currentTimeMillis()-startApply);
                    latch.countDown();
                });
            }
            latch.await();
        }
        params.put("spendTimeSum",(System.nanoTime() - start) * 0.000001);

**Comment by fengjiachun** [comment]
recordLatency 啊

**Comment by LinHuiG** [comment]
这样可以吗

        NodeMetrics metrics = JraftManege.raftServerManage.getCurrentNode().getNodeMetrics();
        long start = System.nanoTime();
        for (int i=0;i<m;i++){
            CountDownLatch latch=new CountDownLatch(n);
            for (int j=0;j<n;j++){
                CompletableFuture<TaskReturn> future= JraftManege.raftServerManage.submitTask(task);
                long startApply = System.currentTimeMillis();
                int finalI = i;
                int finalJ = j;
                future.whenComplete((a, b)->{
                    if (b!=null)
                        params.put("error",b.getMessage());
                    params.putIfAbsent("ret",a);
                    metrics.recordLatency ("i:"+finalI+"j:"+ finalJ,System.currentTimeMillis()-startApply);
                    latch.countDown();
                });
            }
            latch.await();
        }
        params.put("spendTimeSum",(System.nanoTime() - start) * 0.000001);

**Comment by LinHuiG** [comment]
这样可以吗
        NodeMetrics metrics = JraftManege.raftServerManage.getCurrentNode().getNodeMetrics();
        long start = System.nanoTime();
        for (int i=0;i<m;i++){
            CountDownLatch latch=new CountDownLatch(n);
            for (int j=0;j<n;j++){
                CompletableFuture<TaskReturn> future= JraftManege.raftServerManage.submitTask(task);
                long startApply = System.currentTimeMillis();
                future.whenComplete((a, b)->{
                    if (b!=null)
                        params.put("error",b.getMessage());
                    params.putIfAbsent("ret",a);
                    long spendTime=System.currentTimeMillis()-startApply;
                    String key="raftTestSpeed";
                    metrics.recordLatency (key,spendTime);
                    latch.countDown();
                });
            }
            latch.await();
        }
        params.put("spendTimeSum",(System.nanoTime() - start) * 0.000001);

**Comment by fengjiachun** [comment]
亲，我不想说话了，你直接给数据吧

**Comment by LinHuiG** [comment]
外层m取100，内层n取10 这是测试数据（前面用1*1点了四次）
[node_metrics.log.2021-12-15_17-01-02.log](https://github.com/sofastack/sofa-jraft/files/7717806/node_metrics.log.2021-12-15_17-01-02.log)

**Comment by fengjiachun** [comment]
```
append-logs
             count = 205
         mean rate = 1.76 calls/second
     1-minute rate = 1.83 calls/second
     5-minute rate = 0.74 calls/second
    15-minute rate = 0.39 calls/second
               min = 0.00 milliseconds
               max = 13.00 milliseconds
              mean = 1.87 milliseconds
            stddev = 1.58 milliseconds
            median = 1.00 milliseconds
              75% <= 2.00 milliseconds
              95% <= 4.00 milliseconds
              98% <= 8.00 milliseconds
              99% <= 10.00 milliseconds
            99.9% <= 13.00 milliseconds
```

好像写盘比较慢，你这样，让你的代码一种执行两次，你copy 一份（m=100），先执行一遍作为预热（记得把 recordLatency 去掉），紧接着再执行一次 m=1000 （这次要带着 recordLatency ，我要看这次的数据 ），明白了吗？

**Comment by LinHuiG** [comment]
懂了，是这样吗


        for (int i = 0; i < m; i++) {
            CountDownLatch latch = new CountDownLatch(n);
            for (int j = 0; j < n; j++) {
                CompletableFuture<TaskReturn> future = JraftManege.raftServerManage.submitTask(task);
                long startApply = System.currentTimeMillis();
                future.whenComplete((a, b) -> {
                    if (b != null)
                        params.put("error", b.getMessage());
                    params.putIfAbsent("ret", a);
                    long spendTime = System.currentTimeMillis() - startApply;
                    latch.countDown();
                });
            }
            latch.await();
        }
        m *= 10;
        NodeMetrics metrics = JraftManege.raftServerManage.getCurrentNode().getNodeMetrics();
        long start = System.nanoTime();
        for (int i = 0; i < m; i++) {
            CountDownLatch latch = new CountDownLatch(n);
            for (int j = 0; j < n; j++) {
                CompletableFuture<TaskReturn> future = JraftManege.raftServerManage.submitTask(task);
                long startApply = System.currentTimeMillis();
                future.whenComplete((a, b) -> {
                    if (b != null)
                        params.put("error", b.getMessage());
                    params.putIfAbsent("ret", a);
                    long spendTime = System.currentTimeMillis() - startApply;
                    String key = "raftTestSpeed";
                    metrics.recordLatency(key, spendTime);
                    latch.countDown();
                });
            }
            latch.await();
        }
        params.put("spendTimeSum", (System.nanoTime() - start) * 0.000001);

**Comment by fengjiachun** [comment]
对，是这意思

**Comment by LinHuiG** [comment]
[node_metrics.log.2021-12-15_17-16-51.log](https://github.com/sofastack/sofa-jraft/files/7717940/node_metrics.log.2021-12-15_17-16-51.log)
冯老师再看看

**Comment by fengjiachun** [comment]
你统计的指标 75% 小于 3ms
```
raftTestSpeed
             count = 10000
         mean rate = 438.14 calls/second
     1-minute rate = 1557.60 calls/second
     5-minute rate = 1902.46 calls/second
    15-minute rate = 1966.94 calls/second
               min = 1.00 milliseconds
               max = 35.00 milliseconds
              mean = 3.16 milliseconds
            stddev = 2.10 milliseconds
            median = 3.00 milliseconds
              75% <= 3.00 milliseconds
              95% <= 6.00 milliseconds
              98% <= 10.00 milliseconds
              99% <= 12.00 milliseconds
            99.9% <= 25.00 milliseconds
```

然后大部分时间，花在了刷盘上

```
append-logs
             count = 1629
         mean rate = 27.06 calls/second
     1-minute rate = 19.31 calls/second
     5-minute rate = 5.23 calls/second
    15-minute rate = 1.96 calls/second
               min = 0.00 milliseconds
               max = 20.00 milliseconds
              mean = 1.58 milliseconds
            stddev = 1.73 milliseconds
            median = 1.00 milliseconds
              75% <= 2.00 milliseconds
              95% <= 3.00 milliseconds
              98% <= 6.00 milliseconds
              99% <= 10.00 milliseconds
            99.9% <= 18.00 milliseconds
```

**Comment by LinHuiG** [comment]
count好像没对上，是有一部分没提交成功吗...

**Comment by fengjiachun** [comment]
count 对不上是正常的，刷盘是 group commit，异步无延时的攒批，举个例子 1，2，3，4，5  的请求可能只刷盘一次，但是这次刷盘被阻塞 2ms，那么 1，2，3，4，5 几个请求的延时都会大于 2ms

**Comment by LinHuiG** [comment]
懂了，谢谢冯老师，这就找公司要硬盘

**Comment by fengjiachun** [comment]
不客气，我是菜鸡，不用叫老师，那这个 issue 先关闭了啊，试试 SSD 盘

**Comment by LinHuiG** [comment]
还是谢谢您了，不过关于预热机制有没有什么办法关掉让它一直热着呢，我想在这块也优化一下。

**Comment by fengjiachun** [comment]
> 还是谢谢您了，不过关于预热机制有没有什么办法关掉让它一直热着呢，我想在这块也优化一下。

我只是解决你进程刚启动时期的预热，进程启动后就不需要了
