### ISSUE TITLE
在RheaKV中支持动态的addpeer和removepeer 节点

### ISSUE THREAD

**Issue by softdzx** [sofastack/sofa-jraft#747]
### Your question

在基于RheaKV做一个 嵌入式的 客户端分布式存储（边缘存储），容许通过API来控制 客户端的上下线（addpeer和removepeer）

### Your scenes

1 有客户端节点连接后，将该节点加入到集群，将数据分裂到该节点上
2 当客户端“长时间”离线后，可以通过api 主动的将该节点t掉，并将该节点上的数据分裂到其它节点上

### Your advice

- SOFAJRaft version: 1.3.9

**Comment by fengjiachun** [comment]
add_peer

https://github.com/sofastack/sofa-jraft/blob/master/jraft-rheakv/rheakv-core/src/main/java/com/alipay/sofa/jraft/rhea/client/pd/PlacementDriverClient.java#L117

remove_peer
https://github.com/sofastack/sofa-jraft/blob/master/jraft-rheakv/rheakv-core/src/main/java/com/alipay/sofa/jraft/rhea/client/pd/PlacementDriverClient.java#L122

split
https://github.com/sofastack/sofa-jraft/blob/master/jraft-rheakv/rheakv-core/src/main/java/com/alipay/sofa/jraft/rhea/client/RheaKVCliService.java#L40

要注意的是，split 要立刻触发 snapshot，目前没有自动化这个操作

**Comment by softdzx** [comment]
boolean addReplica(final long regionId, final Peer peer, final boolean refreshConf);
boolean removeReplica(final long regionId, final Peer peer, final boolean refreshConf);

用那个api 可以获取到指定Peer 上的 regionId list

**Comment by fengjiachun** [comment]
注意 split 的 regionId 是你填进去的
