### ISSUE TITLE
Peer IP 变成空的

### ISSUE THREAD

**Issue by qiujiayu** [sofastack/sofa-jraft#750]
### Describe the bug

以下是日志信息
```
logger_name: com.alipay.sofa.jraft.core.NodeImpl
message: Node <xxx:2021> channel init failed, address=:2021.
thread_name:  JRaft-ElectionTimer-xxx
```

通过上面日志，发现 Peer 的IP变成空的，但端口号是正确的。

### Environment

- SOFAJRaft version: 1.3.9
- JVM version (e.g. `java -version`): 17
- OS version (e.g. `uname -a`):  `4.15.0-70-generic #79~16.04.1-Ubuntu SMP Tue Nov 12 14:01:10 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by fengjiachun** [comment]
conf 中有空的 ip 吧？可以 kill -s USR2 看下（参考11小节 https://www.sofastack.tech/projects/sofa-jraft/jraft-user-guide/）

**Comment by killme2008** [comment]
说明在什么情况下出现吧，jraft 不会主动去改 node 的 peer id 的

**Comment by qiujiayu** [comment]
找到原因了，是我配置的问题。
