### ISSUE TITLE
数据一致性核对方案探索

### ISSUE THREAD

**Issue by tsgmq** [sofastack/sofa-jraft#751]
### Your question
目前raft使用的5节点组成的集群，由于业务是持续不断在运行，5节点内存状态一致性很难核对。snapshot又是定时任务驱动，不同启动时间点snapshot时刻也不一样，对比snapshot大概率也是不一致的
1，请教下基于raft的应用，如何来做leader和follower内存数据一致性核对的

2，snapshot的时机能否由定时任务修改为基于iter.getIndex()值，比如每10万的时候做一次snapshot，这样leader和follower 前后到了相同的logIndex理论上snapshot是完全一致的，这样可以基于snapshot做核对

Describe your question clearly

### Your scenes

Describe your use scenes (why need this feature)

### Your advice

Describe the advice or solution you'd like

### Environment

- SOFAJRaft version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by fengjiachun** [comment]
> 1，请教下基于raft的应用，如何来做leader和follower内存数据一致性核对的

为什么要核对？ 如果一定要核对，核对可以 snapshot + raft log 即可，这两者相加，在指定 log index 内，所有节点一定是相同的

> 2，snapshot的时机能否由定时任务修改为基于iter.getIndex()值，比如每10万的时候做一次snapshot，这样leader和follower 前后到了相同的logIndex理论上snapshot是完全一致的，这样可以基于snapshot做核对

snapshot 分散开执行是好事，因为 snapshot 执行时某个环节或阶段是需要阻塞同步执行的，另外根据对问题 1 的回答，你这个问题也不存在了哈
