### ISSUE TITLE
高并发高吞吐性能优化咨询

### ISSUE THREAD

**Issue by tsgmq** [sofastack/sofa-jraft#753]
### Your question
业务6w tps时，raft耗时明显上升，确认下是否业务onApply处理慢了拖累导致的，另外在这个吞吐下，参数是否有哪些需要优化调整
以下是一些metric信息，详细信息参加附件（如果不使用raft，单独跑业务，当前这个量级也是非常快的，都是5ms以内完成100笔的一个批次）
[thread_pool_metrics.log.2022-01-12_01-46-55.txt](https://github.com/sofastack/sofa-jraft/files/7852047/thread_pool_metrics.log.2022-01-12_01-46-55.txt)
[rheakv_metrics.log.2022-01-12_01-46-55.txt](https://github.com/sofastack/sofa-jraft/files/7852048/rheakv_metrics.log.2022-01-12_01-46-55.txt)
[node_metrics.log.2022-01-12_01-46-55.txt](https://github.com/sofastack/sofa-jraft/files/7852049/node_metrics.log.2022-01-12_01-46-55.txt)
[node_describe.log.2022-01-12_01-46-55.txt](https://github.com/sofastack/sofa-jraft/files/7852050/node_describe.log.2022-01-12_01-46-55.txt)

append-logs
             count = 9070956
         mean rate = 4774.87 calls/second
     1-minute rate = 5038.06 calls/second
     5-minute rate = 4473.30 calls/second
    15-minute rate = 4093.76 calls/second
               min = 0.00 milliseconds
               max = 1.00 milliseconds
              mean = 0.02 milliseconds
            stddev = 0.12 milliseconds
            median = 0.00 milliseconds
              75% <= 0.00 milliseconds
              95% <= 0.00 milliseconds
              98% <= 0.00 milliseconds
              99% <= 1.00 milliseconds
            99.9% <= 1.00 milliseconds
fsm-apply-tasks
             count = 877
         mean rate = 0.46 calls/second
     1-minute rate = 0.48 calls/second
     5-minute rate = 0.45 calls/second
    15-minute rate = 0.57 calls/second
               min = 0.00 milliseconds
               max = 5625.00 milliseconds
              mean = 2062.04 milliseconds
            stddev = 202.98 milliseconds
            median = 2058.00 milliseconds
              75% <= 2079.00 milliseconds
              95% <= 2174.00 milliseconds
              98% <= 2264.00 milliseconds
              99% <= 2738.00 milliseconds
            99.9% <= 4183.00 milliseconds
fsm-commit
             count = 878
         mean rate = 0.46 calls/second
     1-minute rate = 0.48 calls/second
     5-minute rate = 0.45 calls/second
    15-minute rate = 0.59 calls/second
               min = 0.00 milliseconds
               max = 5632.00 milliseconds
              mean = 2066.29 milliseconds
            stddev = 203.22 milliseconds
            median = 2061.00 milliseconds
              75% <= 2084.00 milliseconds
              95% <= 2180.00 milliseconds
              98% <= 2268.00 milliseconds
              99% <= 2742.00 milliseconds
            99.9% <= 4190.00 milliseconds
fsm-snapshot-save
             count = 8
         mean rate = 0.00 calls/second
     1-minute rate = 0.00 calls/second
     5-minute rate = 0.01 calls/second
    15-minute rate = 0.03 calls/second
               min = 0.00 milliseconds
               max = 5.00 milliseconds
              mean = 0.10 milliseconds
            stddev = 0.30 milliseconds
            median = 0.00 milliseconds
              75% <= 0.00 milliseconds
              95% <= 1.00 milliseconds
              98% <= 1.00 milliseconds
              99% <= 1.00 milliseconds
            99.9% <= 1.00 milliseconds
pre-vote
             count = 5
         mean rate = 0.00 calls/second
     1-minute rate = 0.00 calls/second
     5-minute rate = 0.00 calls/second
    15-minute rate = 0.05 calls/second
               min = 1.00 milliseconds
               max = 19.00 milliseconds
              mean = 4.87 milliseconds
            stddev = 6.68 milliseconds
            median = 2.00 milliseconds
              75% <= 3.00 milliseconds
              95% <= 19.00 milliseconds
              98% <= 19.00 milliseconds
              99% <= 19.00 milliseconds
            99.9% <= 19.00 milliseconds
replicate-entries
             count = 32483266
         mean rate = 17099.00 calls/second
     1-minute rate = 18011.43 calls/second
     5-minute rate = 16077.33 calls/second
    15-minute rate = 14518.12 calls/second
               min = 0.00 milliseconds
               max = 2.00 milliseconds
              mean = 0.55 milliseconds
            stddev = 0.50 milliseconds
            median = 1.00 milliseconds
              75% <= 1.00 milliseconds
              95% <= 1.00 milliseconds
              98% <= 1.00 milliseconds
              99% <= 1.00 milliseconds
            99.9% <= 2.00 milliseconds
request-vote
             count = 2
         mean rate = 0.00 calls/second
     1-minute rate = 0.00 calls/second
     5-minute rate = 0.00 calls/second
    15-minute rate = 0.05 calls/second
               min = 5.00 milliseconds
               max = 16.00 milliseconds
              mean = 10.50 milliseconds
            stddev = 5.50 milliseconds
            median = 16.00 milliseconds
              75% <= 16.00 milliseconds
              95% <= 16.00 milliseconds
              98% <= 16.00 milliseconds
              99% <= 16.00 milliseconds
            99.9% <= 16.00 milliseconds
save-raft-meta
             count = 1
         mean rate = 0.00 calls/second
     1-minute rate = 0.00 calls/second
     5-minute rate = 0.00 calls/second
    15-minute rate = 0.02 calls/second
               min = 4.00 milliseconds
               max = 4.00 milliseconds
              mean = 4.00 milliseconds
            stddev = 0.00 milliseconds
            median = 4.00 milliseconds
              75% <= 4.00 milliseconds
              95% <= 4.00 milliseconds
              98% <= 4.00 milliseconds
              99% <= 4.00 milliseconds
            99.9% <= 4.00 milliseconds
truncate-log-prefix
             count = 7
         mean rate = 0.01 calls/second
     1-minute rate = 0.00 calls/second
     5-minute rate = 0.01 calls/second
    15-minute rate = 0.05 calls/second
               min = 0.00 milliseconds
               max = 87.00 milliseconds
              mean = 0.00 milliseconds
            stddev = 0.01 milliseconds
            median = 0.00 milliseconds
              75% <= 0.00 milliseconds
              95% <= 0.00 milliseconds
              98% <= 0.00 milliseconds
              99% <= 0.00 milliseconds
            99.9% <= 0.00 milliseconds

Describe your question clearly

### Your scenes

Describe your use scenes (why need this feature)

### Your advice

Describe the advice or solution you'd like

### Environment

- SOFAJRaft version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by killme2008** [comment]
apply 相当慢啊，你可能看下你的 state machine 的这块实现，看看有没有办法优化

```
fsm-apply-tasks
count = 877
mean rate = 0.46 calls/second
1-minute rate = 0.48 calls/second
5-minute rate = 0.45 calls/second
15-minute rate = 0.57 calls/second
min = 0.00 milliseconds
max = 5625.00 milliseconds
mean = 2062.04 milliseconds
stddev = 202.98 milliseconds
median = 2058.00 milliseconds
75% <= 2079.00 milliseconds
95% <= 2174.00 milliseconds
98% <= 2264.00 milliseconds
99% <= 2738.00 milliseconds
99.9% <= 4183.00 milliseconds
```

**Comment by fengjiachun** [comment]
```
fsm-apply-tasks-count
             count = 877
               min = 1
               max = 15535
              mean = 11405.35
            stddev = 885.42
            median = 11462.00
              75% <= 11775.00
              95% <= 12104.00
              98% <= 12529.00
              99% <= 12827.00
            99.9% <= 14618.00
```
如  @killme2008  所说，apply 慢了，进一步看，慢的原因可能是一次 apply 大量的 task（mean 114.05），这其实是好事，猜测你的状态机串行处理了这些 task，所以比较慢，可以做的一个优化是将没有前后依赖的 task 做 batch 处理，类似 rheakv；进一步的优化还可以进行 task 之间的依赖的分析，没有依赖的并行处理

**Comment by killme2008** [comment]
> ```
> fsm-apply-tasks-count
>              count = 877
>                min = 1
>                max = 15535
>               mean = 11405.35
>             stddev = 885.42
>             median = 11462.00
>               75% <= 11775.00
>               95% <= 12104.00
>               98% <= 12529.00
>               99% <= 12827.00
>             99.9% <= 14618.00
> ```
> 
> 如 @killme2008 所说，apply 慢了，进一步看，慢的原因可能是一次 apply 大量的 task（mean 11462），这其实是好事，猜测你的状态机串行处理了这些 task，所以比较慢，可以做的一个优化是将没有前后依赖的 task 做 batch 处理，类似 rheakv；进一步的优化还可以进行 task 之间的依赖的分析，没有依赖的并行处理

平均 2 秒，100 个 task 一批，单个也要 20 毫秒了，这块看看有没有优化空间了。

**Comment by fengjiachun** [comment]
举个例子，可以把多个 put 操作集到一起，一次完成，一般这样做会有一些效果，前提是你的状态机支持高效的 batchPut

**Comment by tsgmq** [comment]
嗯呢，基本学习了rheakv的好多优化点，流转批。onApply的时候之前1w tps的时候是能够稳定在0.8ms，现在量大了感觉跑不动了，业务上有要求，有的是有前后依赖的，所以我设计了个带shardingKey的线程池，同一个key的提交到同一个线程中排队，可能是业务量上来了。打印的日志太多了。拖累了。我把日志降级了再看看。
onApply的时候是使用下面的线程池来并行执行的,线程池长度为1，这样保证相同的key能够串行执行
/**
     * 获取可用处理器数量
     * 由于业务系统都是需要多个线程池并行处理
     */
    public static int PARALLELISM =
            SystemPropertyUtil.getInt("jraft.options.parallelism.max", Runtime.getRuntime().availableProcessors());

    /**
     * 初始化线程池
     */
    private ExecutorService[] executors;

    private String threadPoolName;

    /**
     * 分片数量
     **/
    private int poolSize;

    public ShardThreadPoolExecutor(String threadPoolName) {
        executors = new ExecutorService[PARALLELISM];
        this.threadPoolName = threadPoolName;
        this.poolSize = PARALLELISM;
    }

    public ShardThreadPoolExecutor(String threadPoolName, int size) {
        executors = new ExecutorService[size];
        this.threadPoolName = threadPoolName;
        this.poolSize = size;
    }

    /**
     * 初始化线程池
     */
    public void init() {
        for (int i = 0; i < PARALLELISM; i++) {
            executors[i] =
                    new ThreadPoolExecutor(1, 1, 60L, TimeUnit.MILLISECONDS, new LinkedBlockingQueue<Runnable>(),
                            new NamedThreadFactory(threadPoolName));
        }
    }



    public <V> Future<V> submitByShardingKey(Long shardingKey, Callable<V> callable) {
        return executors[getIndexByShardingKey(shardingKey)].submit(callable);
    }

**Comment by killme2008** [comment]
提醒下，线程池长度为1，不一定能保证串行的，你要考虑任务失败导致 worker exit 的场景

**Comment by fengjiachun** [comment]
> 提醒下，线程池长度为1，不一定能保证串行的，你要考虑任务失败导致 worker exit 的场景

可以使用 jraft 里的 MpscSingleThreadExecutor 来代替 ThreadPoolExecutor

**Comment by tsgmq** [comment]
fsm-apply-tasks
             count = 2356675
         mean rate = 2484.22 calls/second
     1-minute rate = 5209.12 calls/second
     5-minute rate = 3978.72 calls/second
    15-minute rate = 2027.92 calls/second
               min = 0.00 milliseconds
               max = 1.00 milliseconds
              mean = 0.03 milliseconds
            stddev = 0.17 milliseconds
            median = 0.00 milliseconds
              75% <= 0.00 milliseconds
              95% <= 0.00 milliseconds
              98% <= 1.00 milliseconds
              99% <= 1.00 milliseconds
            99.9% <= 1.00 milliseconds
fsm-commit
             count = 2356683
         mean rate = 2484.22 calls/second
     1-minute rate = 5209.18 calls/second
     5-minute rate = 3978.74 calls/second
    15-minute rate = 2027.93 calls/second
               min = 0.00 milliseconds
               max = 1.00 milliseconds
              mean = 0.04 milliseconds
            stddev = 0.21 milliseconds
            median = 0.00 milliseconds
              75% <= 0.00 milliseconds
              95% <= 0.00 milliseconds
              98% <= 1.00 milliseconds
              99% <= 1.00 milliseconds
            99.9% <= 1.00 milliseconds

**Comment by tsgmq** [comment]
压力小的时候，性能非常棒

**Comment by killme2008** [comment]
你可以观察下 GC 情况吧，可能也是个因素，单个 raft group 也有上限，可以考虑 multi raft group

**Comment by fengjiachun** [comment]
> > 提醒下，线程池长度为1，不一定能保证串行的，你要考虑任务失败导致 worker exit 的场景
> 
> 可以使用 jraft 里的 MpscSingleThreadExecutor 来代替 ThreadPoolExecutor

这是 bench 结果(见代码 SingleThreadExecutorBenchmark)：

```
    /*
     * Benchmark                                                                         Mode  Cnt  Score   Error  Units
     * SingleThreadExecutorBenchmark.defaultSingleThreadPollExecutor                    thrpt    3  1.266 ± 2.822  ops/s
     * SingleThreadExecutorBenchmark.mpscSingleThreadExecutor                           thrpt    3  4.066 ± 4.990  ops/s
     * SingleThreadExecutorBenchmark.mpscSingleThreadExecutorWithConcurrentLinkedQueue  thrpt    3  3.470 ± 0.845  ops/s
     * SingleThreadExecutorBenchmark.mpscSingleThreadExecutorWithLinkedBlockingQueue    thrpt    3  2.643 ± 1.222  ops/s
     * SingleThreadExecutorBenchmark.mpscSingleThreadExecutorWithLinkedTransferQueue    thrpt    3  3.266 ± 1.613  ops/s
     * SingleThreadExecutorBenchmark.nettyDefaultEventExecutor                          thrpt    3  2.290 ± 0.446  ops/s
     *
     * Benchmark                                                                         Mode  Cnt  Score   Error  Units
     * SingleThreadExecutorBenchmark.defaultSingleThreadPollExecutor                    thrpt   10  1.389 ± 0.130  ops/s
     * SingleThreadExecutorBenchmark.mpscSingleThreadExecutor                           thrpt   10  3.646 ± 0.323  ops/s
     * SingleThreadExecutorBenchmark.mpscSingleThreadExecutorWithConcurrentLinkedQueue  thrpt   10  3.386 ± 0.247  ops/s
     * SingleThreadExecutorBenchmark.mpscSingleThreadExecutorWithLinkedBlockingQueue    thrpt   10  2.535 ± 0.153  ops/s
     * SingleThreadExecutorBenchmark.mpscSingleThreadExecutorWithLinkedTransferQueue    thrpt   10  3.184 ± 0.299  ops/s
     * SingleThreadExecutorBenchmark.nettyDefaultEventExecutor                          thrpt   10  2.097 ± 0.075  ops/s
     */
```

**Comment by tsgmq** [comment]
> > > 提醒下，线程池长度为1，不一定能保证串行的，你要考虑任务失败导致 worker exit 的场景
> > 
> > 
> > 可以使用 jraft 里的 MpscSingleThreadExecutor 来代替 ThreadPoolExecutor
> 
> 这是 bench 结果(见代码 SingleThreadExecutorBenchmark)：
> 
> ```
>     /*
>      * Benchmark                                                                         Mode  Cnt  Score   Error  Units
>      * SingleThreadExecutorBenchmark.defaultSingleThreadPollExecutor                    thrpt    3  1.266 ± 2.822  ops/s
>      * SingleThreadExecutorBenchmark.mpscSingleThreadExecutor                           thrpt    3  4.066 ± 4.990  ops/s
>      * SingleThreadExecutorBenchmark.mpscSingleThreadExecutorWithConcurrentLinkedQueue  thrpt    3  3.470 ± 0.845  ops/s
>      * SingleThreadExecutorBenchmark.mpscSingleThreadExecutorWithLinkedBlockingQueue    thrpt    3  2.643 ± 1.222  ops/s
>      * SingleThreadExecutorBenchmark.mpscSingleThreadExecutorWithLinkedTransferQueue    thrpt    3  3.266 ± 1.613  ops/s
>      * SingleThreadExecutorBenchmark.nettyDefaultEventExecutor                          thrpt    3  2.290 ± 0.446  ops/s
>      *
>      * Benchmark                                                                         Mode  Cnt  Score   Error  Units
>      * SingleThreadExecutorBenchmark.defaultSingleThreadPollExecutor                    thrpt   10  1.389 ± 0.130  ops/s
>      * SingleThreadExecutorBenchmark.mpscSingleThreadExecutor                           thrpt   10  3.646 ± 0.323  ops/s
>      * SingleThreadExecutorBenchmark.mpscSingleThreadExecutorWithConcurrentLinkedQueue  thrpt   10  3.386 ± 0.247  ops/s
>      * SingleThreadExecutorBenchmark.mpscSingleThreadExecutorWithLinkedBlockingQueue    thrpt   10  2.535 ± 0.153  ops/s
>      * SingleThreadExecutorBenchmark.mpscSingleThreadExecutorWithLinkedTransferQueue    thrpt   10  3.184 ± 0.299  ops/s
>      * SingleThreadExecutorBenchmark.nettyDefaultEventExecutor                          thrpt   10  2.097 ± 0.075  ops/s
>      */
> ```

好的，之前没有找到这个，就自己写了个
另外我已经使用了分片的思想，各个分片是完全隔离的。我初期设置了10个分片。每个分片如果支持6w,理论上全局是60w能抗住的。现在我要把一个分片的raft搞到极致

**Comment by fengjiachun** [comment]
建议你在自己状态机里面进行一些必要的指标统计，看看慢在哪里，现在基本是锁定慢在状态机里，但是具体哪里还不知道
