### ISSUE TITLE
LogEntry 中的 data 设计问题。

### ISSUE THREAD

**Issue by qiujiayu** [sofastack/sofa-jraft#755]
LogEntry 中的 data 是个静态数据，建议将其类型由 ByteBuffer 改为 byte[] 。

因为现在这个 data 在下面代码中使用：

com.alipay.sofa.jraft.core.IteratorWrapper#getData

```
    public ByteBuffer getData() {
        final LogEntry entry = this.impl.entry();
        return entry != null ? entry.getData() : null;
    }
```

使用者一不小心，就会直接从这个ByteBuffer 获取数据，从而修改其内部的 pos值。从而造成其它地方调用remaining() 方法时，得到错误的值。

**Comment by killme2008** [comment]
这个我们可以加个注释，建议用 slice 获取一个 view 去修改数据，或者我们增加一个类似的方法。

用 byte buffer 的原因在于 byte buffer 更适合做编解码处理，其次是可以做池化。
