### ISSUE TITLE
Support of hostnames for cluster member addresses

### ISSUE THREAD

**Issue by alexei-osipov** [sofastack/sofa-jraft#756]
Examples for cluster node configuration use hostnames for node addresses. Example:
```java
Endpoint addr = JRaftUtils.getEndpoint("localhost:8080");
PeerId peer = JRaftUtils.getPeerId("localhost:8080");
// A Raft group that consists of three nodes. Separate the nodes with commas (,).
Configuration conf = JRaftUtils.getConfiguration("localhost:8081,localhost:8082,localhost:8083");
```
(form here https://www.sofastack.tech/en/projects/sofa-jraft/jraft-user-guide/ )

However JavaDoc for Endpoint class explicitly says that it represents an IP address and port (see 
https://github.com/sofastack/sofa-jraft/blob/master/jraft-core/src/main/java/com/alipay/sofa/jraft/util/Endpoint.java ).

So are hostnames (like `node1.mycluster.mycompany.com`, not just IP addresses) are supposed to be supported for `Endpoint` and `PeerId` or not?

**Comment by killme2008** [comment]
Hostnames are supported, we will correct the javadoc.
