### ISSUE TITLE
SST句柄泄漏问题

### ISSUE THREAD

**Issue by huzx0608** [sofastack/sofa-jraft#758]
### Your question

集群结构：
1、PD1、PD2、PD3
2、KV1、KV2、KV3

持续的进行数据写入，在发生Snapshot时，会进行DeleteRange操作，此时发现对应raft-region下对应文件已经标记删除，但对应的JVM仍然占用句柄，如下图。

![image](https://user-images.githubusercontent.com/6895821/150780410-ef14cf94-6c73-40a4-ad78-e7361161c16e.png)

造成raft对应的磁盘空间无法释放，Snapshot时，耗时较大。

### Your scenes

Describe your use scenes (why need this feature)

### Your advice

Describe the advice or solution you'd like

### Environment

- SOFAJRaft version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by killme2008** [comment]
最终应该会物理删除的，另外 1.3.9 版本也增加了 wal 大小控制，建议升级设置下

https://github.com/sofastack/sofa-jraft/releases/tag/1.3.9
