### ISSUE TITLE
Snapshot的目录多线程压缩生成zip文件bug

### ISSUE THREAD

**Issue by zhangjie0303** [sofastack/sofa-jraft#759]
添加相关对的配置项：
\#### snapshot compress or decompress parallelly
useParallelCompress: true
compressThreads: 4
deCompressThreads: 5
后，发现仍然没有走ParallelZipStrategy的compress方法，定们到以下逻辑代码判断处有BUG：
```java
 public static void init(final RheaKVStoreOptions opts) {
        // add parallel zip strategy
        if (opts.isUseParallelCompress()) {
            if (zipStrategies[PARALLEL_STRATEGY] != null) {
                final ZipStrategy zipStrategy = new ParallelZipStrategy(opts.getCompressThreads(),
                    opts.getDeCompressThreads());
                ZipStrategyManager.addZipStrategy(ZipStrategyManager.PARALLEL_STRATEGY, zipStrategy);
                DEFAULT_STRATEGY = PARALLEL_STRATEGY;
            }
        }
    }
```
将 **zipStrategies[PARALLEL_STRATEGY] != null** 改成 **zipStrategies[PARALLEL_STRATEGY] == null** 后功能通了。

**Comment by hzh0425** [comment]
@zhangjie0303 sorry, 这确实是个 Bug, 您是否方便提个 issue?

**Comment by MartianQiu** [comment]
非常感谢您发现了此Bug，我已经修复了它，并提交了一个pr

**Comment by zhangjie0303** [comment]
才看到不好意思，收到邮件说已经修复了，新年快乐!

在 2022-01-27 18:52:21，hzh ***@***.***> 写道：


@zhangjie0303 sorry, 这确实是个 Bug, 您是否方便提个 issue?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zhangjie0303** [comment]
> 非常感谢您发现了此Bug，我已经修复了它，并提交了一个pr

还有个BUG，ParallelZipStrategy类的compress方法，每次执行时都会newFixedPool，这样真正创建了配置中的压缩线程个数，但实际这个线程池只用了一次，而且用完后未关闭创建的线程或线程池，会造成每次compress时都会有线程泄露，但是deCompress没有此问题，因为用完后，已经释放掉了线程池资源（具体代码：ExecutorServiceHelper.shutdownAndAwaitTermination(deCompressExecutor);）

**Comment by MartianQiu** [comment]
> 还有个BUG，ParallelZipStrategy类的compress方法，每次执行时都会newFixedPool，这样真正创建了配置中的压缩线程个数，但实际这个线程池只用了一次，而且用完后未关闭创建的线程或线程池，会造成每次compress时都会有线程泄露，但是deCompress没有此问题，因为用完后，已经释放掉了线程池资源（具体代码：ExecutorServiceHelper.shutdownAndAwaitTermination(deCompressExecutor);）

好的，收到，感谢老哥！我会修复此问题并提交rp。

**Comment by MartianQiu** [comment]
> 还有个BUG，ParallelZipStrategy类的compress方法，每次执行时都会newFixedPool，这样真正创建了配置中的压缩线程个数，但实际这个线程池只用了一次，而且用完后未关闭创建的线程或线程池，会造成每次compress时都会有线程泄露，但是deCompress没有此问题，因为用完后，已经释放掉了线程池资源（具体代码：ExecutorServiceHelper.shutdownAndAwaitTermination(deCompressExecutor);）

好的，收到，感谢老哥！我会修复此问题并提交pr。

**Comment by hzh0425** [comment]
@zhangjie0303 thanks!
