### ISSUE TITLE
关于multi-raft-group使用多个rocksdb实例的问题

### ISSUE THREAD

**Issue by yufan022** [sofastack/sofa-jraft#765]
### Your question

Hi，想要向各位请教一个问题：
我注意到kv项目在实现multi-raft-group中，似乎为每组region都分别初始化了一个rocksdb实例作为log-storage，而状态机是共享同一个rocksdb实例。这样如果在海量region的场景下，例如有十万组region，可能每个节点会初始化大量的log-storage rocksdb实例。

这样对raft-log这块盘而言，整体就由顺序写变成了随机写，还有就是这样单节点存在大量rocksdb实例会不会开销比较大，存在性能问题？
所以咨询下这块儿这么设计是基于怎样考虑的？感谢

### Your scenes

Describe your use scenes (why need this feature)

### Your advice

Describe the advice or solution you'd like

### Environment

- SOFAJRaft version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by fengjiachun** [comment]
你好，以下的回答仅仅是我自己的看法，可供参考

raftlog 基于 rocksdb 的 logstorage 目前是一个 raft group 一个 rocksdb 实例，之所以这么设计也是因为毕竟我们目标不是做一个存储海量数据的数据库，目标 region 数量没有这么大量级，几十个上百个 region 是我们最初的设计目标

当然，也不是说 jraft 就无法支持更大量级的 region ， 在 jraft 中 log storage 是组件式并可插拔的，只要再实现一个共享 log storage 即可解决这个问题，不过目前暂时还没有制定相关 feature 的计划

对于 kv 项目之所以共享 rocksdb 实例，因为实现成本不高，这样设计也更合理

另外，这个问题应该讨论的是单节点 region 数量，如果你单节点十万组 region，那么也应该重新考虑下分 region 是否有意义了，单节点这么多 region 好像是没什么必要的

**Comment by yufan022** [comment]
> 你好，以下的回答仅仅是我自己的看法，可供参考
> 
> raftlog 基于 rocksdb 的 logstorage 目前是一个 raft group 一个 rocksdb 实例，之所以这么设计也是因为毕竟我们目标不是做一个存储海量数据的数据库，目标 region 数量没有这么大量级，几十个上百个 region 是我们最初的设计目标
> 
> 当然，也不是说 jraft 就无法支持更大量级的 region ， 在 jraft 中 log storage 是组件式并可插拔的，只要再实现一个共享 log storage 即可解决这个问题，不过目前暂时还没有制定相关 feature 的计划
> 
> 对于 kv 项目之所以共享 rocksdb 实例，因为实现成本不高，这样设计也更合理
> 
> 另外，这个问题应该讨论的是单节点 region 数量，如果你单节点十万组 region，那么也应该重新考虑下分 region 是否有意义了，单节点这么多 region 好像是没什么必要的

感谢您的回复，这个问题的出现，是因为对比了一下[tikv](https://docs.pingcap.com/zh/tidb/stable/massive-regions-best-practices
)的场景，在作为kv数据库使用的场景，region按MB级容量做分裂和调度，这样可能出现海量region的场景。

如果没理解错的话，记得tikv的实现应该是log-storage是共享一台rocksdb实例的，所以有了如上的问题。

我想jraft目前的设计应该也是每组raft-group使用不同的rocksdb，在`new RaftGroupService`没看有传入rocksdb对象的选项，所以想要确认下。
