### ISSUE TITLE
k8s 环境下无法动态设置serverAddress ，initialServerAddressList可咋整？

### ISSUE THREAD

**Issue by qingtianbuyu** [sofastack/sofa-jraft#767]
### Your question

k8s 环境下无法动态设置serverAddress ，initialServerAddressList

### Your scenes

麻烦咨询下，如果像公司中使用的k8s，现在需要使用jraft-core做选主进行Leader 节点写操作，参考 jraft-example  中ElectionBootstrap 现在但是需要设置serverAddress ，initialServerAddressList，这个没法固定写死，有啥好的方案不？

### Your advice

是否可以支持注册中心(zk/nacos 等)？

### Environment

- SOFAJRaft version: 1.3.9.fix-log4j2
- JVM version (e.g. `java -version`): JDK8
- OS version (e.g. `uname -a`): 
- Maven version:  3.6.3 
- IDE version: IntelliJ IDEA 2021.3.2 (Ultimate Edition)

**Comment by fengjiachun** [comment]
initialServerAddressList 填自己的 IP 或 host，其他节点动态走 raft 协议加进来（利用 CLI  add peer，参考连接 4.2 小节）
https://www.sofastack.tech/projects/sofa-jraft/jraft-user-guide/

**Comment by fengjiachun** [comment]
没有更多问题就先关闭了
