### ISSUE TITLE
Use deleteFilesInRanges instead of deleteRange in RocksDBLogStorage

### ISSUE THREAD

**Issue by killme2008** [sofastack/sofa-jraft#768]
According to https://github.com/facebook/rocksdb/wiki/Delete-A-Range-Of-Keys

The command will remove all SST files only containing keys in the range to delete. For a large chunk, it will immediately reclaim most space, so it is a good solution to  release disk pressure under writing heavy load.

**Comment by killme2008** [comment]
It' also noted by TIKV https://tikv.github.io/deep-dive-tikv/key-value-engine/rocksdb.html

```
DeleteRange turns out to be unstable and can not release disk space fast enough.

A faster way to release disk space is to delete some files directly, which leads us to the DeleteFilesInRange feature. But this feature is not perfect, it is quite dangerous because it breaks the snapshot consistency. If you acquire a snapshot from RocksDB, use DeleteFilesInRange to delete some files, then try to read that data you will find that some of it is missing. So we should use this feature carefully.
```

**Comment by 18013631263** [comment]
升级到1.3.10后，deleteFilesInRanges 之后再 compactRange 并没有立即释放磁盘，rockdb空间磁盘占用还是居高不下

**Comment by killme2008** [comment]
看看你的 rocksdb 占用是什么吧，这个只会在启用 snapshot，加快 raft log 的回收，对状态机的数据没有帮助的

**Comment by cassvin** [comment]
在某些场景下可能会有数据残留：
1. deleteFilesInRanges不会删除L0文件；
2. 如果文件里面只有部分key ranges。比如触发snapshot时index是1000，等到实际调用删除接口时最新的sst文件里面包含900 - 1100范围的key，那么这个sst也不会被选中删除，下一轮也删不了。
