### ISSUE TITLE
关于快照期间，异步任务使用的读写锁问题

### ISSUE THREAD

**Issue by yufan022** [sofastack/sofa-jraft#773]
### Your question

Hi，各位，我在走读代码过程中发现基于multiRaftGroup的快照是使用rocksdb snapshot特性异步实现的。

首先同步获取rocksdb snapshot
https://github.com/sofastack/sofa-jraft/blob/e9ae4e477576fd98d9dd539faf7470b6b938e98b/jraft-rheakv/rheakv-core/src/main/java/com/alipay/sofa/jraft/rhea/storage/RocksRawKVStore.java#L1316

然后异步基于该snapshot读取所有key，并且创建sst文件完成快照操作
https://github.com/sofastack/sofa-jraft/blob/e9ae4e477576fd98d9dd539faf7470b6b938e98b/jraft-rheakv/rheakv-core/src/main/java/com/alipay/sofa/jraft/rhea/storage/RocksRawKVStore.java#L1326

但此处有个疑问，为什么`doCreateSstFiles`函数内部要加读写锁？已经拿到了snapshot，这里是不是不需要考虑并发修改的问题了？
https://github.com/sofastack/sofa-jraft/blob/e9ae4e477576fd98d9dd539faf7470b6b938e98b/jraft-rheakv/rheakv-core/src/main/java/com/alipay/sofa/jraft/rhea/storage/RocksRawKVStore.java#L1334
这个方法内部逻辑似乎只是通过`readOptions.setSnapshot(snapshot);`来读取之前snapshot时间点的所有key value，然后写入SST文件，最后`releaseSnapshot`。
但是`doCreateSstFiles`内部加了读写锁，不知道这里是出于什么原因？这样一来虽然`doCreateSstFiles`是异步的，但似乎同样会导致状态机阻塞，因为加了读锁会导致写阻塞。

这里可以去掉`doCreateSstFiles`函数内部的读写锁么？从而实现只有在getSnapshot时是同步并且加锁阻塞状态机，后续根据snapshot扫描rocksdb以及创建sst文件时都是异步并且无锁不阻塞状态机么？这样可以将快照时对状态机的阻塞时间降到最低，只有getSnapshot时会影响到状态机执行。

**Comment by fengjiachun** [comment]
> 但此处有个疑问，为什么doCreateSstFiles函数内部要加读写锁？已经拿到了snapshot，这里是不是不需要考虑并发修改的问题了？

RocksRawKVStore 中的读写锁用于处理对 rocksdb 的正常操作（获取读锁）以及对 rocksdb 的打开和关闭（获取写锁），所以在读 snapshot 的时候也要获取读锁避免此时 rocksdb 实例被打开或者关闭

**Comment by yufan022** [comment]
多谢，是我这里阅读代码不仔细 原以为set等也是写锁，实际是只有在restore、backup、shutdown等操作才会获取写锁，正常操作时都是读锁不会互斥导致阻塞，只有打开关闭等重要操作时才会互斥。

**Comment by fengjiachun** [comment]
不客气，如果没有更多问题，这个 issue 就先关闭了
