### ISSUE TITLE
按照固定间隔index 进行snapshot

### ISSUE THREAD

**Issue by 18013631263** [sofastack/sofa-jraft#774]
目前都是按照定时周期snapshot ,由于任务执行有时差，每台机器的snapshot时的index各不相同，我们现在期望比对leader和follower 同一snapshotIndex时的 数据是否一致，后面版本能否加入 按照固定index间隔进行snapshot 的配置项

**Comment by killme2008** [comment]
`Node` 有 `snapshot(closure)` 方法可以手动触发 snapshot 的，所以这个需求目前是可以自行实现的。

不过这个需求也是合理的，我们会放入后续迭代考虑。

**Comment by 18013631263** [comment]
> `Node`有`snapshot(closure)`办法可以手动触发快照的，所以这个需求目前是可以自己实现的。
> 
> 这也是需要考虑的问题。
Node.snapshot() 调用的之后会封装一个task 丢到disruptor 排队执行，等真正执行snasphot的时候, 已经不是当初设定的index了,无法保证实时性与顺序性。

**Comment by killme2008** [comment]
是有这个问题，欢迎来贡献

**Comment by tsgmq** [comment]
> `Node` 有 `snapshot(closure)` 方法可以手动触发 snapshot 的，所以这个需求目前是可以自行实现的。
> 
> 不过这个需求也是合理的，我们会放入后续迭代考虑。

非常期待这个功能，虽然logEntry层面能够保证各个节点顺序执行，但是针对每个logEntry业务的处理逻辑会很很大的差异，一些业务场景的业务很复杂，需要在onApply的时候去执行。不像KV，计数器那么简单，所以需要验证leader，follower相同的输入下，是否最终执行的结果一致，我这边的场景是基于sofaJraft搞的存数据管理，内存中的数据是复杂的业务对象(为了减少序列化，反序列化造成的耗时问题，直接使用jvm对象)。非常期待有个统一的按照index来做snapshot的能力，这样可以对各个节点的snapshot前面增加针对全量内存对象MD5值，相同的logIndex被apply，理论上MD5值需要一样，这样就可以说明各节点数据完全一致

**Comment by horizonzy** [comment]
嗯，这个需求非常 nice，这样各个节点的 snapshot 和 raft-log 也能保持一致。

**Comment by MartianQiu** [comment]
老板们，这个issue我试试看哇，争取尽快提个pr

**Comment by fengjiachun** [comment]
@MartianQiu 欢迎，这个 PR 比较复杂，建议先提个 [RFC](https://github.com/sofastack/sofa-jraft/tree/master/rfcs) 讨论清楚了，然后再着手写代码

**Comment by MartianQiu** [comment]
> @MartianQiu 欢迎，这个 PR 比较复杂，建议先提个 [RFC](https://github.com/sofastack/sofa-jraft/tree/master/rfcs) 讨论清楚了，然后再着手写代码

okkkk

**Comment by tsgmq** [comment]
感谢各位老板，我们一起将sofaJraft发扬光大，我相信sofaJraft如果在我们的业务场景中能够使用的很好，那么没有sofaJraft搞不定的更复杂的场景了

**Comment by killme2008** [comment]
@MartianQiu hi，你开始这个工作了吗

**Comment by killme2008** [comment]
@MartianQiu 客气，那我 assign 给你

**Comment by MartianQiu** [comment]
FRC is as follows:

Feature Name: A snapshot saving would be triggered when the lastAppliedIndex value minus lastSnapshotId value greater than or equal to 'snapshotAppliedIndexMargin'.

Date:2022-03-08

Summary
provide a configuration which name 'snapshotAppliedIndexMargin' for nodeOptions, a snapshot saving would be triggered when the lastAppliedIndex value minus lastSnapshotId value is greater than 'snapshotAppliedIndexMargin'.

Motivation
This feature is necessary, user couldn't save a snapshot at fixed 'appliedIndex' interval without this feature. Therefore, I'd like to implement this feature, then user can manage the generation of snapshots by setting property.

Detailed Design
provide a configuration item which name is 'snapshotAppliedIndexMargin' for nodeOptions, the default value of this property is zero. It only takes effect when 'snapshotAppliedIndexMargin' > 0 && 'snapshotAppliedIndexMargin' <= Integer.MAX_VALUE. 

In the "notifyLastAppliedIndexUpdated" method, add a listener. When the index changes, the listener will handle this event. Calculate whether lastAppliedIndex value minus lastSnapshotId value is greater than or equal to 'snapshotAppliedIndexMargin'. if true, trigger snapshot save.

FYR.

**Comment by MartianQiu** [comment]
> 这里应该还需要有个优先级的考虑，新的配置项和老的配置项生效的问题，应该是二选一的，这个也可以在 RFC 中体现一下。

okkk, 我的倾向是当'snapshotAppliedIndexMargin'与'snapshotIntervalSecs'同时配置，且'snapshotAppliedIndexMargin'配置的值有效时，'snapshotIntervalSecs'的配置失效，这样各节点生成的快照内容达成一致的概率会更高。
倘若二者同时生效，大概率会使得生成快照的频率增加。高频率交替生成快照的意义并不大，造成不必要的性能损耗。

**Comment by horizonzy** [comment]
> > 这里应该还需要有个优先级的考虑，新的配置项和老的配置项生效的问题，应该是二选一的，这个也可以在 RFC 中体现一下。
> 
> okkk, 我的倾向是当'snapshotAppliedIndexMargin'与'snapshotIntervalSecs'同时配置，且'snapshotAppliedIndexMargin'配置的值有效时，'snapshotIntervalSecs'的配置失效，这样各节点生成的快照内容达成一致的概率会更高。 倘若二者同时生效，大概率会使得生成快照的频率增加。高频率交替生成快照的意义并不大，造成不必要的性能损耗。

ok，在代码注释中标明优先级吧。

**Comment by 18013631263** [comment]
谢谢各位老板，我们对这个需求功能非常迫切，请问有个大概完成时间节点吗

**Comment by MartianQiu** [comment]
> 谢谢各位老板，我们对这个需求功能非常迫切，请问有个大概完成时间节点吗

预计一两周哇，老哥。最近工作上事儿比较多，我尽量抽时间来搞哇。

**Comment by horizonzy** [comment]
> 我有个建议是引入一个枚举类型 `SnapshotMode`，包括： ByTimeInterval, ByIndexMargin, MixMode, None，默认就是 None，就是什么都不启用，然后在四类模式下，这两个参数可以分别起作用。
> 
> 另外 `lastSnapshotId` 建议改成 `lastSnapshotIndex`， 并且需要处理 onSnapshotLoad 情况去主动修改，有一些细节需要注意。

这个有待商榷。默认为 None 的话，用户升级完之后，按照之前的配置方式，snapshot 就不生效了，这个不太合理。

**Comment by MartianQiu** [comment]
> > 我有个建议是引入一个枚举类型 `SnapshotMode`，包括： ByTimeInterval, ByIndexMargin, MixMode, None，默认就是 None，就是什么都不启用，然后在四类模式下，这两个参数可以分别起作用。
> > 另外 `lastSnapshotId` 建议改成 `lastSnapshotIndex`， 并且需要处理 onSnapshotLoad 情况去主动修改，有一些细节需要注意。
> 
> 这个有待商榷。默认为 None 的话，用户升级完之后，按照之前的配置方式，snapshot 就不生效了，这个不太合理。

更倾向默认为ByTimeInterval

**Comment by killme2008** [comment]
> > 我有个建议是引入一个枚举类型 `SnapshotMode`，包括： ByTimeInterval, ByIndexMargin, MixMode, None，默认就是 None，就是什么都不启用，然后在四类模式下，这两个参数可以分别起作用。
> > 另外 `lastSnapshotId` 建议改成 `lastSnapshotIndex`， 并且需要处理 onSnapshotLoad 情况去主动修改，有一些细节需要注意。
> 
> 这个有待商榷。默认为 None 的话，用户升级完之后，按照之前的配置方式，snapshot 就不生效了，这个不太合理。 MixMode 有必要需要吗，我认为2选一就能满足用户的需求了。

有道理，主要我是觉的参数之间的隐藏关系，是很不符合直觉的，需要文档来说明。

这块可以再讨论下。

**Comment by yufan022** [comment]
> > > 我有个建议是引入一个枚举类型 `SnapshotMode`，包括： ByTimeInterval, ByIndexMargin, MixMode, None，默认就是 None，就是什么都不启用，然后在四类模式下，这两个参数可以分别起作用。
> > > 另外 `lastSnapshotId` 建议改成 `lastSnapshotIndex`， 并且需要处理 onSnapshotLoad 情况去主动修改，有一些细节需要注意。
> > 
> > 
> > 这个有待商榷。默认为 None 的话，用户升级完之后，按照之前的配置方式，snapshot 就不生效了，这个不太合理。
> 
> 更倾向默认为ByTimeInterval

Hi，这里想提个需求，希望能支持MixMode。也就是在达到时间间隔或index间隔两种条件均触发快照模，这样index快照可以用来校验一致性，基于时间快照间隔还是正常触发，两种规则同时生效。
