### ISSUE TITLE
FSMCallerImpl#ApplyTaskHandler的疑问

### ISSUE THREAD

**Issue by zrlw** [sofastack/sofa-jraft#777]
### Your question
FSMCallerImpl#init方法创建了ApplyTaskHandler对象：
```
this.disruptor.handleEventsWith(new ApplyTaskHandler());
```
从代码上看，调用FSMCallerImpl#init方法可以一直追溯到RaftGroupService的start方法：
```
   public synchronized Node start(final boolean startRpcServer) { // 同步方法
        if (this.started) { 
            return this.node;
        }
        // 代码省略
        this.started = true;
        LOG.info("Start the RaftGroupService successfully.");
        return this.node;
```
从上述代码看每个rpcServer只会创建一个ApplyTaskHandler对象。
FSMCallerImpl的init方法创建的disruptor只有一个ApplyTaskHandler：
```
this.disruptor.handleEventsWith(new ApplyTaskHandler());
```
handleEventsWith方法会创建BatchEventProcessor，而BatchEventProcessor的run方法是循环调用eventHandler.onEvent。
所以发生多个ApplyTask事件，ApplyTaskHandler的onEvent方法应该是按照sequence的顺序串行处理每个事件的吧？

我们做nacos性能测试(目标是确定相关资源配置条件下nacos集群可以支撑的最大临时实例数量），发现FSMCallerImpl#doApplyTasks方法调用nacos状态机的onApply方法时出现了iterImpl.done()返回null的情况，iterImpl的currentIndex比firstClosureIndex小。从代码看firstClosureIndex是closureQueue的firstIndex，currentIndex是lastAppliedIndex（上次doCommitted执行的最后一个任务的index+1），什么情况会导致创建IterImpl对象时closureQueue队列的firstIndex比FSMCallerImpl的lastAppliedIndex还要大呢？
是不是doCommitted执行this.closureQueue.popClosureUntil方法时，先将closureQueue的firstIndex数值加到了committedIndex+1，但是执行后续的doApplyTasks调用时出了异常，iterImpl的index没有同步增加相应的数量，导致设置的lastAppliedIndex数值比closureQueue的firstIndex小了？

压测环境：
- SOFAJRaft version: 1.3.9
- JVM version (e.g. `java -version`): 1.8
- OS version (e.g. `uname -a`): centos7
- Nacos: 1.4.2 （改了sofa-jraft版本）

**Comment by fengjiachun** [comment]
> 请问发生多个TaskType.COMMITTED类型的事件时，ApplyTaskHandler的onEvent方法是串行执行（一个线程循环调用onEvent处理）还是并行执行（多个线程同时执行onEvent方法）？

串行，可以了解一下 Disruptor 的配置，如果你使用 ` #handleEventsWith` 的话那么就是单消费者； 在 jraft-core 中所有使用 Disruptor 的地方都是 MPSC 模型（多生产者单消费者），这么做是为了异步无延时攒批来达到组提交/执行的效果

> iterImpl.done()返回null的情况

follower 节点的 it.done 就是 null，需要 it.getData() 出来返序列化一下，可以找下 jraft 代码里的任意一个状态机的 example 参考一下

**Comment by killme2008** [comment]
具体代码分析，有兴趣可以自行分析了， 具体看 popClosureUntil，并且需要理解整个 raft 算法的逻辑。这里就不解释了。
可以保证的是 follower 的closure 是 null，因为拿不到，只有 leader 才有，这也是一个用于优化的手段，比如将  data 附加在 closure，避免了从 data 反序列化。

**Comment by zrlw** [comment]
原因应该是follower的closures条目内容都为null，复制日志到follower节点时没有复制task的closure

**Comment by fengjiachun** [comment]
关闭了，已经回答的比较清楚了
