### ISSUE TITLE
[Document] counter-example Snapshot onSnapshotSave 异步备份是否合理

### ISSUE THREAD

**Issue by inkinworld** [sofastack/sofa-jraft#778]
### Your question

看了 counter-example： https://www.sofastack.tech/projects/sofa-jraft/counter-example/
感觉示例里的 Snapshot 实现有些问题，onSnapshotSave 内部通过异步任务保存快照文件，这样做无法保障业务状态机与 raft log 状态机状态一致。希望能讨论下。
![image](https://user-images.githubusercontent.com/12553724/156523899-94a6adc1-99b6-456c-9e9d-4174689c5a58.png)

### Your scenes

示例里的实现会导致状态不一致

**Comment by horizonzy** [comment]
这里的 demo 是 ok的，获取数据的这个时间点是同步的，只是把数据的存储给异步了。只需要保证获取数据是同步就ok。

**Comment by inkinworld** [comment]
明白了，谢谢。很巧妙～
