### ISSUE TITLE
AddNewLearners log info tweak.

### ISSUE THREAD

**Issue by horizonzy** [sofastack/sofa-jraft#779]
### Describe the bug

https://github.com/sofastack/sofa-jraft/blob/bc4cfb3397bd5a610879d9b070ec158060d363b5/jraft-core/src/main/java/com/alipay/sofa/jraft/core/NodeImpl.java#L414-L424
line_417.   It should be addingLearners.

**Comment by xh1202** [comment]
I want to fix it
