### ISSUE TITLE
leader stop send heartbeat to follower

### ISSUE THREAD

**Issue by david-ealge-han** [sofastack/sofa-jraft#781]
### Expected behavior
leader send heartbeat to follower periodically

### Actual behavior
leader stop send heartbeat to follower

### Minimal yet complete reproducer code (or GitHub URL to code)
![image](https://user-images.githubusercontent.com/49236628/156556794-fd597c6f-39b1-4d77-9ef6-f99a9052fec4.png)
![image](https://user-images.githubusercontent.com/49236628/156556854-203c1cb8-4c48-4dcb-92cd-e0ccc6308fca.png)

when try-lock failed, heartbeat error put into the list, may need next unlock to run the heartbeat, so the heartbeat cann't send periodically as expected. this may cause leader vote.

### Environment

- SOFAJRaft version: jraft-core-1.2.7.beta1.jar
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by killme2008** [comment]
Yep, there is a race condition between 

```
  this.pendingErrors.add(errorCode);
```

and `ThreadId#unlock`,  so the error signal may be delayed  and cause an unnecessary election. 

We wil fix it, thank your for your report.
