### ISSUE TITLE
运行测试用例com.alipay.sofa.jraft.rhea.pd.RheaHeartbeatTest报No nodes in group pd_test--1, Fail to init channel的问题

### ISSUE THREAD

**Issue by LianxinGao** [sofastack/sofa-jraft#782]
应该怎样运行这个测试呢？

**Comment by fengjiachun** [comment]
先启动 https://github.com/sofastack/sofa-jraft/blob/master/jraft-rheakv/rheakv-pd/src/test/java/com/alipay/sofa/jraft/rhea/PdServer.java
