### ISSUE TITLE
Region副本数能否设置

### ISSUE THREAD

**Issue by zhangjie0303** [sofastack/sofa-jraft#784]
我搭了一个5个PD，5个store的集群，经验证默认region的副本数就是5了，1个leader，4个follower，如果我期望region的副本数为3（这样扩容store节点就能扩容整个集群的存储容量了），在配置上是否支持了呢，要如何配置？
看jraft的设计文档说是支持的，链接地址：https://www.sofastack.tech/blog/sofa-jraft-rheakv-multi-raft-group/，相关图片：
[
![image](https://user-images.githubusercontent.com/15648099/156906622-3ec6ea0d-8c82-4e16-96fa-667805631014.png)
](url)

**Comment by fengjiachun** [comment]
> 如果我期望region的副本数为3（这样扩容store节点就能扩容整个集群的存储容量了），在配置上是否支持了呢，要如何配置？

支持的，不需要每个 store 节点包含所有 region，每个节点包含的 region ，你可以自己配置，参考： https://github.com/sofastack/sofa-jraft/blob/master/jraft-rheakv/rheakv-core/src/test/resources/pd_conf/rhea_pd_test_1.yaml


> 我搭了一个5个PD，5个store的集群，

应该是一个 PD吧？
