### ISSUE TITLE
sofa-jraft-rheaKV产生的日志文件是否会自动清理

### ISSUE THREAD

**Issue by Transi-ent** [sofastack/sofa-jraft#786]
在使用默认配置时（使用RocksDB模式），rheaKV会在raft_data目录下创建3个目录——log、meta、snapshot，这3个目录分别用于存放相应的raft配置，请问下这些文件在使用完成后会被自动删除吗？

**Comment by killme2008** [comment]
snapshot 要自己清理，因为是你自己生成的文件，所以需要自己来维护，包括 snapshot 目录下的元信息。 meta/log 目录下的文件， jraft 会自行维护。

**Comment by Transi-ent** [comment]
那请问下哪些是需要保留的，那些是可以删除调的呢？还是可以全部删除呢，盼复，肥肠感谢！

**Comment by fengjiachun** [comment]
> 那请问下哪些是需要保留的，那些是可以删除调的呢？还是可以全部删除呢，盼复，肥肠感谢！

@killme2008 其实已经回答你了，只有 snapshot 可以自己清理，其他文件 jraft 自行维护

**Comment by killme2008** [comment]
snapshot 需要看下你的保存方式，如果是增量的方式，肯定也是不能无脑删的，如果每次都全量，保存最近几次的就可以了，可以按照时间或者 snapshot index 大小来判断。

**Comment by Transi-ent** [comment]
@killme2008 @fengjiachun 肥肠感谢二位的解答，这下清楚了。
