### ISSUE TITLE
1.4.0啥时候发布呢？

### ISSUE THREAD

**Issue by tsgmq** [sofastack/sofa-jraft#788]
https://github.com/sofastack/sofa-jraft/milestone/7

1.4中已经close的几个issues是我们很迫切需要的，系统稳定性有很大的挑战。能否基于现有的master先发个小版本tag。等1.4全部内容完成再发个版本。
昨天又出现个问题，sst文件没有清理，高到32G，导致raftGroup启动时寻找lastIndex耗时20分钟，如果合并都有的话，sst文件少了，这些问题应该就都能解决了

**Comment by fengjiachun** [comment]
预计在下周一二左右发布 1.3.10， 最快的话本周五也有可能

**Comment by fengjiachun** [comment]
@tsgmq 今天发 1.3.10
