### ISSUE TITLE
文献引用的问题

### ISSUE THREAD

**Issue by jasonclown** [sofastack/sofa-jraft#801]
### Your question

请问除了SOFAJRaft的网址https://www.sofastack. tech/projects/sofa-jraft/overview/.
是否有针对SOFAJRaft的论文或者专利呢？我想引用一下。

### Your advice

希望能得到回复

**Comment by killme2008** [comment]
jraft 没有申请专利和论文，你要引用这个项目的话，可以直接引用此项目 github 链接

**Comment by jasonclown** [comment]
已收到您的邮件！
