### ISSUE TITLE
是否可以限制状态机单次apply的数量

### ISSUE THREAD

**Issue by cassvin** [sofastack/sofa-jraft#809]
现有实现是将committed index和last apply index之间的log entry封装到IteratorImpl，送到doApplyTasks中做apply。考虑以下场景：
在某一段时间内有一些log entry的处理耗时比平常的要多一些，假设从时间点A开始。由于处理耗时增加，导致处理期间积压了比较多的请求（committed index - last apply index），可能会造成恶性循环，后续积压的越来越多，最后“雪崩”overload。如果能够限制单次apply的数量，那么disruptor队列的消息有机会被及时“收割”走，积压的情况能够得到缓和，等到状态机扛过这一波，服务就能够恢复正常，队列也能够被清空。虽然最终整体处理耗时可能是增加的，但是减缓了积压的情况，一定程度上降低了overload的概率。

我们在自己的环境中发现follower集体出现状态机overload的情况，最后定位到是从某段时间开始log entry的反序列化时间加长，导致整个apply耗时增大，apply disruptor队列消息开始积压，很快就overload了。看代码发现apply的逻辑是拿committed index和last apply index之间的数据做处理的，想探讨下这块的做法 :)

**Comment by fengjiachun** [comment]
> 导致处理期间积压了比较多的请求（committed index - last apply index）

这里更多的考虑了攒批，也可以说组提交，也有利于用户状态机做进一步的优化，比如 rheakv 中的状态机 batch 写入优化，甚至也可以进行依赖分析后对无依赖操作并行处理等

对于 overload，如 @killme2008 所说，建议试用一下最新版本试试？
