### ISSUE TITLE
`RouteTable#refreshConfiguration` lost learner list.

### ISSUE THREAD

**Issue by haoyann** [sofastack/sofa-jraft#815]
### Your question

`RouteTable#refreshConfiguration` lost learner list,.So get learner list from RouteTable is empty, there will be some confusion.
https://github.com/sofastack/sofa-jraft/blob/092913645ffc4795e7e52f82e9d595bf86ba3ab9/jraft-core/src/main/java/com/alipay/sofa/jraft/RouteTable.java#L317-L323

### Your scenes

Describe your use scenes (why need this feature)

### Your advice

`RouteTable#refreshConfiguration` also refresh learner list.

### Environment

- SOFAJRaft version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by haoyann** [comment]
I want to contribute this issue.

**Comment by fengjiachun** [comment]
Thank you and send a PR please. @haoyann

**Comment by haoyann** [comment]
PR merged close.
