### ISSUE TITLE
是否支持集群节点IP或者端口的变动？

### ISSUE THREAD

**Issue by JavaCoderCff** [sofastack/sofa-jraft#819]
### Your question
这样一个场景，有三台节点A、B、C组成的raft集群，某些原因需要将集群迁移至 D、E、F三个节点上，且节点IP无法与之前的集群对应，两个集群的网路无法通信。

如果可以支持ip的变动，那么就可以通过磁盘的挂载或者拷贝整个目录，然后修改配置文件，来解决以上问题

不过有点像业务上的需求了 ~~~

如果可以对PeerId接口抽象，提供SPI，由用户去实现具体的IP 、PORT？？？猜想哈，，没有仔细思考~~

**Comment by fengjiachun** [comment]
想了下，好像可以这么做，把 snapshot 拷贝到新集群，并设置新的 groupConf 以 bootstrap 方式启动，然后再正常启动这个节点，最后再把另外两个节点用 addpeer 加进来，参考:

1. [testBootStrapWithSnapshot](https://github.com/sofastack/sofa-jraft/blob/master/jraft-core/src/test/java/com/alipay/sofa/jraft/core/NodeTest.java#L2966)
2. 以及这里的回答：https://github.com/sofastack/sofa-jraft/issues/95

不确定一定可行，愿意动手的话可以试一下

**Comment by killme2008** [comment]
bootstrap 就是干这事的，将原有集群的数据用新集群的方式启动。

**Comment by JavaCoderCff** [comment]
ok~~~  我试试， 感谢~~
