### ISSUE TITLE
使用rocketmq的存储替换jraft的存储实现

### ISSUE THREAD

**Issue by Cczzzz** [sofastack/sofa-jraft#821]
这似乎是可行的。
这是rocketmq存储层的接口：

    public abstract DLedgerEntry appendAsLeader(DLedgerEntry entry);

    public abstract DLedgerEntry appendAsFollower(DLedgerEntry entry, long leaderTerm, String leaderId);

    public abstract DLedgerEntry get(Long index);

    public abstract long getCommittedIndex();

    public void updateCommittedIndex(long term, long committedIndex) {

    }

    public abstract long getLedgerEndTerm();

    public abstract long getLedgerEndIndex();

    public abstract long getLedgerBeginIndex();

    protected void updateLedgerEndIndexAndTerm() {
        if (getMemberState() != null) {
            getMemberState().updateLedgerIndexAndTerm(getLedgerEndIndex(), getLedgerEndTerm());
        }
    }

    public void flush() {

    }

    public long truncate(DLedgerEntry entry, long leaderTerm, String leaderId) {
        return -1;
    }

    public void startup() {

    }

    public void shutdown() {

    }

**Comment by killme2008** [comment]
We don't consider it right now, thank you.
