### ISSUE TITLE
sub module(ark biz) is web project, the dynamic-stock-mng-1.0.0-ark-executable.jar cannot run

### ISSUE THREAD

**Issue by Code-Coding** [sofastack/sofa-jraft#824]
### Your question

Describe your question clearly

### Your scenes
![image](https://user-images.githubusercontent.com/23294005/165007846-eecefa38-c9f8-4f28-b12b-6dded67b7769.png)
![image](https://user-images.githubusercontent.com/23294005/165007635-9d2bf162-9708-4782-9377-0e608aaefcd1.png)
![image](https://user-images.githubusercontent.com/23294005/165007647-407ce0a8-9e04-4301-82d6-f64525e49d73.png)

### Your advice

Describe the advice or solution you'd like

### Environment

- SOFAJRaft version: 3.2.2
- JVM version (e.g. `java -version`):JDK1.8
- OS version (e.g. `uname -a`):
- Maven version:3.6.3
- IDE version:2020.3

**Comment by killme2008** [comment]
sofa-ark is at https://github.com/sofastack/sofa-ark
