### ISSUE TITLE
关于replicator pipeline复制的乱序处理疑问

### ISSUE THREAD

**Issue by zzzyyf** [sofastack/sofa-jraft#829]
### Your question

目前Replicator如果开启pipeline，会把follower的AppendEntries RPC响应暂存在holdingQueue中，并且检查队首的响应是否是当前正在等待的响应，如果不是则不会处理。那么，一旦复制过程中某个AppendEntries RPC发生丢失、乱序等导致延迟的问题（高并发下可能更常见），可能Replicator能收到follower对后续RPC的拒绝响应，但不能收到该问题RPC的响应，此时就算Replicator和follower可以正常通信，最终也无法更新lastRpcSendTimestamp，从而会导致重新选举？

我的问题是，follower对乱序RPC的拒绝响应是否应该更新lastRpcSendTimestamp？上述的重新选举过程可以避免吗？

### Your scenes

Describe your use scenes (why need this feature)

### Your advice

Describe the advice or solution you'd like

### Environment

- SOFAJRaft version: 1.3.10.bugfix2
- JVM version (e.g. `java -version`): 8.0.312.7
- OS version (e.g. `uname -a`): Linux 3.10.0
- Maven version:
- IDE version:

**Comment by killme2008** [comment]
你是遇到了这个问题，还是分析觉的会有这个问题？心跳并没有走这个 pipeline 队列的，所以你说的问题理论上不存在。

**Comment by zzzyyf** [comment]
> 你是遇到了这个问题，还是分析觉的会有这个问题？

我现在遇到了这方面的问题，但是还在定位，看到了这一块的代码所以感觉好像会有这个问题。

> 心跳并没有走这个 pipeline 队列的，所以你说的问题理论上不存在。

我指的是leader的stepDownTimer，当其超时后leader会检查与各follower上次成功rpc的发送时间，以判断该节点是否“dead”，若存活节点不过半就会主动step down。

**Comment by zzzyyf** [comment]
> 你是遇到了这个问题，还是分析觉的会有这个问题？心跳并没有走这个 pipeline 队列的，所以你说的问题理论上不存在。

最近又看了代码，你说的确实没错，超时的问题主要在于心跳，这个issue我就先关闭了
