### ISSUE TITLE
Import Error Class?

### ISSUE THREAD

**Issue by NanerLee** [sofastack/sofa-jraft#831]
最近线上发现了一个报错, 关于 Netty 的相关 class 找不到, 看了下 jraft-core 中的 netty 实际是由 bolt 引入的. 但由于我们使用的是 grpc 的实现, 所以是把 bolt exclude 掉了.

看了下具体报错的地方, 是 leader 处理 follower 节点的 install snapshot 请求, 在创建 FileService 时抛出的, 相关引入如下:

https://github.com/sofastack/sofa-jraft/blob/5a2030ffcf361b918a6f8bddb896485a27d28ba9/jraft-core/src/main/java/com/alipay/sofa/jraft/storage/FileService.java#L25

https://github.com/sofastack/sofa-jraft/blob/5a2030ffcf361b918a6f8bddb896485a27d28ba9/jraft-core/src/main/java/com/alipay/sofa/jraft/storage/FileService.java#L76

由于 java 也有一个同名的类 `java.util.concurrent.ThreadLocalRandom`, 所以我怀疑是当时写代码的时候写错了?

---------------------------------------------

然后延伸到宽泛一些的问题上, **jraft 本身是否依赖 netty** ? 因为目前 rpc 的实现本身是可插拔:
- 如果依赖的话, 不应该以 bolt 依赖的形式来间接引入? 
- 如果不依赖的话, 上面提到的 case 实际是一个 bug ?

**Comment by fengjiachun** [comment]
是 import 错了，我来改一下 @NanerLee
