### ISSUE TITLE
jraft如何关闭所有资源，调用哪些方法

### ISSUE THREAD

**Issue by SpringLin97** [sofastack/sofa-jraft#836]
调用这两个方法，能够关闭jraft
![image](https://user-images.githubusercontent.com/63085858/170660000-d0356001-ca16-404f-81d6-0df923df4a8c.png)
但是，线程还有很多占用
![image](https://user-images.githubusercontent.com/63085858/170660115-217745e4-2dd3-4edc-8b36-a88ee9a8bb3d.png)
![image](https://user-images.githubusercontent.com/63085858/170660145-ae2ed360-aaf1-4262-9888-3d1881bc93f0.png)
![image](https://user-images.githubusercontent.com/63085858/170660154-9986ce0a-82c9-4b76-a6cb-77cd2df82075.png)
![image](https://user-images.githubusercontent.com/63085858/170660172-ee60686a-4662-4237-90e5-eb4af2cae270.png)

**Comment by killme2008** [comment]
这些大部分是全局的 daemon 线程池，无需关闭，在进程退出后会自动退出。

后续这些全局线程池，我们也会提供配置选项给用户，交给用户设置。
