### ISSUE TITLE
SnapshotSave 是否可以暂停

### ISSUE THREAD

**Issue by xiumliang** [sofastack/sofa-jraft#839]
### Your question

观察到状态机启动时就会启动SnapShotExecutorImpl。之后就会按照指定的时间间隔执行状态机的onSnapshotSave。我的代码会在特定时间有IO密集操作，这时，需要尽可能减少IO相关的此操作。目前优化到Snapshot这里。想请教一下是否有办法暂停snapshot save或者把snapshot save 的时间间隔暂时延长？

### Your scenes

Describe your use scenes (why need this feature)

### Your advice

Describe the advice or solution you'd like

### Environment

- SOFAJRaft version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by killme2008** [comment]
参考 NodeOptions 的相关选项

https://github.com/sofastack/sofa-jraft/blob/master/jraft-core/src/main/java/com/alipay/sofa/jraft/option/NodeOptions.java#L68

**Comment by xiumliang** [comment]
> 参考 NodeOptions 的相关选项
> 
> https://github.com/sofastack/sofa-jraft/blob/master/jraft-core/src/main/java/com/alipay/sofa/jraft/option/NodeOptions.java#L68
多谢回复。我的情况有些复杂，需要在启动raft group的时候snapshot 是启用状态。中间有一段时间应用需要把snapshot暂停，这段时间应用要做大量的磁盘操作。等这些操作完成后，再重新把snapshot 启用。暂停的时间和时长不确定，要看磁盘操作什么时候完成。

您上面给的 NodePotions -> snapshotIntervalSecs。这个值我只看到在 RaftServiceFactory#createAndInitRaftNode 时候才会使用。这时候NodeImple会保存nodeOption, 同时根据snapshotIntervalSecs来启动snapshot相关的服务。但是启动后，我没看到有动态修改snapshotIntervalSecs的地方。
有没有办法在raft group 启动后动态的修改snapshotIntervalSecs 为 -1，在需要的时候再动态的把snapshotIntervalSecs改为3000 或者其他我需要的值？同时还能让raft node使用动态修改后的snapshotIntervalSecs?

**Comment by killme2008** [comment]
@xiumliang 没法修改，如果需要更灵活的策略，那就关闭定时器（snapshotIntervalSecs 设置为 <=0），然后自己按照需求触发，调用 `Node#snapshot(closure)` 方法。
