### ISSUE TITLE
Iterator里回滚方法setErrorAndRollback的ntail参数有没有实际的作用？

### ISSUE THREAD

**Issue by jackjoesh** [sofastack/sofa-jraft#850]
setErrorAndRollback的ntail参数从功能上看是回滚lastappliedindex
但是一旦setErrorAndRollback后，整个服务也是stop掉的。
当修复节点代码重启后有两种恢复方式：
1 如果有snapshot,加载snapshot，然后从snapshot的index+1开始apply log
2 如果没有snapshot，从index=0开始apply log
这两种方式本质都是数据重放，那setErrorAndRollback在内存里回滚的ntail是不是没有什么意义。无论如何，节点重启后，也不会重复apply的？
我很想理解ntail参数的实际作用，这个对服务使用混沌测试非常有意义，麻烦能解释下缘由，谢谢！

**Comment by killme2008** [comment]
主要意义在于告诉客户端，这个请求的结果处于“未决”状态，需要业务上去确认。

https://github.com/sofastack/sofa-jraft/blob/master/jraft-core/src/main/java/com/alipay/sofa/jraft/core/FSMCallerImpl.java#L546

**Comment by jackjoesh** [comment]
> 主要意义在于告诉客户端，这个请求的结果处于“未决”状态，需要业务上去确认。
> 
> https://github.com/sofastack/sofa-jraft/blob/master/jraft-core/src/main/java/com/alipay/sofa/jraft/core/FSMCallerImpl.java#L546

谢谢答复，这里的客户端是指网络请求端吗？但是一旦执行setErrorAndRollback后，我理解整个服务都会stepdown吧。另外如果抛出错误，客户端也能知道这次请求是失败的吧，不一定需要回滚内存里的lastappliedindex。
抱歉，我不是为了挑刺，是希望理解setErrorAndRollback的ntail参数我们该如何测试，谢谢！

**Comment by killme2008** [comment]
stepdown 是要在 `setErrorAndRollback` 之后，但是 state machine 正在 apply 的这一批是否认为成功或者 unknown ，取决于你的决定，这就是 `ntail ` 意义。

**Comment by jackjoesh** [comment]
> stepdown 是要在 `setErrorAndRollback` 之后，但是 state machine 正在 apply 的这一批是否认为成功或者 unknown ，取决于你的决定，这就是 `ntail ` 意义。

如果说回滚的时候我不设置ntail，服务器也会stepdown， 当我修复代码再次重启后有两种恢复方式：
1 如果有snapshot,加载snapshot，然后从snapshot的index+1开始apply log
2 如果没有snapshot，从index=0开始apply log
所以并不会对状态机重复提交，并没有实质的影响？
我其实最大的困惑就是ntail就算不设置，我下次重启，貌似状态机提交也是可以正常的，并不会多提交？所以感觉ntail对数据准确性一致性并没有实质的影响。

**Comment by killme2008** [comment]
对数据的准确性和一致性没有影响，但是对客户端看到的一致性有影响，如果反馈给客户端结果是成功，但是却没有应用到状态机，那么客户端看到的结果就不是一致的，虽然最终一致。
