### ISSUE TITLE
线性一致读的一致问题

### ISSUE THREAD

**Issue by LinHuiG** [sofastack/sofa-jraft#862]
### Your question

线性一致读的描述是“所谓线性一致性，一个简单的例子就是在 t1 的时间我们写入了一个值，那么在 t1 之后，我们的读一定能读到这个值，不可能读到 t1 之前的值。”
设状态机在t0时间的状态为A0
那么我们在t1时间发起一次写入操作，状态机在t3时间将该状态应用为A1。
如果我们在t2时间发起一次读取操作，我们读取的值应该为A0还是A1？
我的理解是我们应该读取到A1状态，但是当前我读取到的却是A0状态。

### Your scenes

Describe your use scenes (why need this feature)

### Your advice

Describe the advice or solution you'd like

### Environment

- SOFAJRaft version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by killme2008** [comment]
需要线性一致读就使用 readIndex 或者 apply log 的方式，具体见文档。

**Comment by LinHuiG** [comment]
我使用的就是readIndex方式，apply log方式是正常，readIndex方式会读到A0状态

**Comment by farawayliu** [comment]
我的一些理解：线性一致读不是指读写串行化，线性一致性读应是：任何一个读请求获得最新的值后，后续所有的读请求，不能返回比它更旧的值。

这种情况类似于图中的δ，读到0/1都是可以接受的。
![xxx](https://user-images.githubusercontent.com/20223723/179449578-aab21363-32ab-4d95-8be2-6fb1ad7c2e30.png)

**Comment by LinHuiG** [comment]
> 
懂了，也就是说readIndex保证读操作的线性一致，但是不保证写读操作的线性一致。
如果需要线性读写还是得走log append

**Comment by LinHuiG** [comment]
> 我的一些理解：线性一致读不是指读写串行化，线性一致性读应是：任何一个读请求获得最新的值后，后续所有的读请求，不能返回比它更旧的值。
> 
> 这种情况类似于图中的δ，读到0/1都是可以接受的。 ![xxx](https://user-images.githubusercontent.com/20223723/179449578-aab21363-32ab-4d95-8be2-6fb1ad7c2e30.png)

懂了，也就是说readIndex保证读操作的线性一致，但是不保证写读操作的线性一致。
如果需要线性读写还是得走log append

**Comment by fengjiachun** [comment]
https://www.sofastack.tech/projects/sofa-jraft/consistency-raft-jraft/

参考 `JRaft 实现细节解析之高效的线性一致读` 小节

> 那么我们在t1时间发起一次写入操作，状态机在t3时间将该状态应用为A1。

t1 时刻的描述不是发起写入操作，而是写入成功的时刻


这样的话你的整个描述就是可以正确达成的

@LinHuiG
