### ISSUE TITLE
ReadOnlyOption 支持请求级别

### ISSUE THREAD

**Issue by qiujiayu** [sofastack/sofa-jraft#863]
### Your question

现在对于线性一致性读是通过 RaftOptions.readOnlyOptions 配置进行全局控制的。 不能针对业务请求来区分，不够灵活。

### Your advice

建议 ReadIndexClosure 增加 ReadOnlyOption 来控制当前请求线性一致性的类型。

**Comment by farawayliu** [comment]
@killme2008 I want to have a try，can you assign me？

**Comment by killme2008** [comment]
@farawayliu Ok, feel free to try

**Comment by farawayliu** [comment]
https://github.com/sofastack/sofa-jraft/pull/867
