### ISSUE TITLE
关于snapshotSync在apply iterator中currentIndex的问题

### ISSUE THREAD

**Issue by yufan022** [sofastack/sofa-jraft#864]
### Your question
我们在项目中使用了1.3.11中的feature snapshotSync，从而实现通过状态机在多个节点的同一进度触发snapshotSync，最后校验各节点快照来验证数据一致性。

遇到了一个问题：
触发后发现快照是准确的，但是加载快照后根据index重放的log有重复的情况。

比如当前a=1 a=2 a=3 a=4 a=5，5个操作，在a=3时触发snapshotSync，在基于snapshotSync快照重启节点时应该读区快照a=3 然后重放a=4 a=5的操作，但在我们实际使用中发现加载a=3 然后在a=1开始重放。

### Your scenes
阅读源码后发现我们当前是在状态机的apply回调函数中触发[NodeImpl.snapshotSync](https://github.com/sofastack/sofa-jraft/blob/c849d19cd060f9935d28d4739861efd0750ba796/jraft-core/src/main/java/com/alipay/sofa/jraft/core/NodeImpl.java#L3137)，这里使用的[lastAppliedIndex](https://github.com/sofastack/sofa-jraft/blob/c849d19cd060f9935d28d4739861efd0750ba796/jraft-core/src/main/java/com/alipay/sofa/jraft/core/FSMCallerImpl.java#L591)是历史的，可能不包含本次apply中iterator可能已经迭代过的currentIndex，所以重启加载快照后可能会重复回放LOG。
https://github.com/sofastack/sofa-jraft/blob/c849d19cd060f9935d28d4739861efd0750ba796/jraft-core/src/main/java/com/alipay/sofa/jraft/core/FSMCallerImpl.java#L591

我们又在IteratorImpl中发现了[commitAndSnapshotSync](https://github.com/sofastack/sofa-jraft/blob/a3ed1f7ebe52e3c4e0c9572e58cb1858f548ba4b/jraft-core/src/main/java/com/alipay/sofa/jraft/core/IteratorImpl.java#L152)函数，该函数会调用commit更新lastApplied为currentIndex，然后在内部再调用snapshotSync。
https://github.com/sofastack/sofa-jraft/blob/a3ed1f7ebe52e3c4e0c9572e58cb1858f548ba4b/jraft-core/src/main/java/com/alipay/sofa/jraft/core/IteratorImpl.java#L153

有以下3个问题：
1: 该功能是需要业务方在状态机直接调用Iterator的commitAndSnapshotSync函数么，而不能直接调用NodeImpl.snapshotSync？

2: 如果是调用IteratorImpl.commitAndSnapshotSync的话，在同一批次迭代中途更新currentIndex为lastApplied这种行为，会对状态机遇到关键错误需要终止时，使用`it.setErrorAndRollback`方法产生不可预期的影响么？

3: [这里](https://github.com/sofastack/sofa-jraft/blob/c849d19cd060f9935d28d4739861efd0750ba796/jraft-core/src/main/java/com/alipay/sofa/jraft/core/FSMCallerImpl.java#L591)可以直接使用包含本次迭代器更新点位的currentIndex，而不是用lastAppliedIndex么？

**Comment by yufan022** [comment]
Hi @killme2008 打扰，有时间的话希望帮忙解答下这几个问题，十分感谢

**Comment by killme2008** [comment]
1. 都建议通过 iterator 的 `commitAndSnapshotSync` 来使用这个功能，除非你并不需要控制间距。`commitAndSnapshotSync` 最终调用的也是 `NodeImpl #snapshotSync`。
2. 都是可预期的， commit 的含义就是后续你无法 rollback 到 commit 之前的日志，也就是 state machine 承诺 commit 之前的日志都已经应用到状态机，这个业务上完全可以保证。
3. 不能，snapshot 是对当前状态做镜像，所以需要你 commit 承诺，否则可能破坏一致性承诺。
