### ISSUE TITLE
打快照功能失效

### ISSUE THREAD

**Issue by qiujiayu** [sofastack/sofa-jraft#868]
### Describe the bug

发现快照功能有问题，从快照文件来看，已经打了一个快照了，但接下来就一直没有打快照。

通过接口手动打快照，报如下错误：

```
{
    "ok": false,
    "code": 1009,
    "raft-error": "EBUSY",
    "error-msg": "Is saving another snapshot."
  }
```

具体原因还在定位中。

### Environment

- SOFAJRaft version:   1.3.11 版本
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by fengjiachun** [comment]
可以尝试找一下最近一次打快照那个时间点附件的异常日志看看有什么可疑的
