### ISSUE TITLE
Suggest RheaKVStore add key fuzzy matching

### ISSUE THREAD

**Issue by zhuxt2015** [sofastack/sofa-jraft#869]
### Your scenes
Some keys have the same prefix in RheaKVStore, and I want to get all keys prefixed with same characters

Similar to Zookeeper getChildren(path, false)

### Your advice
```
RheaKVStore.put("abc/a", "a")
RheaKVStore.put("abc/b", "b")
RheaKVStore.put("abc/c", "c")

RheaKVStore.getKeys("abc/"), then return "abc/a", "abc/b", "abc/c"
```

### Environment

- SOFAJRaft version: 1.3.11
- JVM version (e.g. `java -version`): 1.8
- OS version (e.g. `uname -a`):
- Maven version: 3.6.3
- IDE version:

**Comment by fengjiachun** [comment]
Hi， maybe you can use [scan](https://github.com/sofastack/sofa-jraft/blob/master/jraft-rheakv/rheakv-core/src/main/java/com/alipay/sofa/jraft/rhea/client/RheaKVStore.java#L183)

**Comment by fengjiachun** [comment]
Hi， maybe you can use [scan](https://github.com/sofastack/sofa-jraft/blob/master/jraft-rheakv/rheakv-core/src/main/java/com/alipay/sofa/jraft/rhea/client/RheaKVStore.java#L183) .

**Comment by zhuxt2015** [comment]
> Hi， maybe you can use [scan](https://github.com/sofastack/sofa-jraft/blob/master/jraft-rheakv/rheakv-core/src/main/java/com/alipay/sofa/jraft/rhea/client/RheaKVStore.java#L183) .

Thank you very much. The scan is able to meet my needs.
