### ISSUE TITLE
sofa-jrat能否用到分布式事务

### ISSUE THREAD

**Issue by lzhenglin** [sofastack/sofa-jraft#870]
jraft有没有提供一些类似spi的抽象扩展接口,可以让我们自己去实现多个节点一致性验证,或者存储,比如可以根据jraft的抽象实现类似分布式事务

**Comment by lzhenglin** [comment]
目前有看过CountServer累加器这个demo, 发现数累加是请求到主节点,主节点处理完会写日志并直接返回 然后follwer会定期的同步主节点的数据 ,  这块与其他分布式操作有些许差异, 一般会二阶段大于半数节点写成功才会 返回给客户端,        目前的实现会不会导致  follwer追不上leader ，leader挂掉后 数据会丢失, 如果我表达的有问题 请指正我

**Comment by killme2008** [comment]
raft 是解决一致性问题的算法，具体可以见 raft 的论文，他跟事务不是一个事情。至于第二个问题，也在论文中有描述，中文资料也汗牛充栋。
