### ISSUE TITLE
增加压缩级别

### ISSUE THREAD

**Issue by qiujiayu** [sofastack/sofa-jraft#874]
### Your question

快照在99%的情况是用于本地重启，而用于网络传输的机会比较少。

所以为了降低 CPU 使用率，建议可以调整压缩级别。

### Your scenes

Describe your use scenes (why need this feature)

### Your advice

Describe the advice or solution you'd like

### Environment

- SOFAJRaft version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by fengjiachun** [comment]
Thanks for your PR @qiujiayu
