### ISSUE TITLE
Backwards compatibility with rocksdb

### ISSUE THREAD

**Issue by asad-awadia** [sofastack/sofa-jraft#877]
What is sofa jraft doing inside rocksdb? Is it doing something more unique and unexpected?

I ask because once rocksdb has been upgraded it cannot be downgraded back without sofa jraft throwing exceptions - even though rocksdb by itself is compatible

Some exceptions I am seeing are

```
java.util.IllegalFormatConversionException: d != java.lang.String
at com.alipay.sofa.jraft.storage.impl.LogManagerImpl.checkConsistency(LogManagerImpl.java:1180)
```

and

```
Fail to save first log index 63. - [] []
org.rocksdb.RocksDBException: Unknown Footer version. Maybe this file was created with newer version of RocksDB?
at org.rocksdb.RocksDB.put(Native Method)
```

**Comment by asad-awadia** [comment]
@killme2008 @shihuili1218 @qiujiayu

**Comment by killme2008** [comment]
JRaft doesn't do any modifications in rocksdb , i think it's the compatibility of rocksdb.
