### ISSUE TITLE
如何获取当前节点的最大日志序号、已提交日志序号

### ISSUE THREAD

**Issue by LinHuiG** [sofastack/sofa-jraft#879]
### Your question

如何获取当前节点的最大日志序号、已提交日志序号，已应用到状态机的日志序号。
如何在当前节点上获取其他节点的最大日志序号、已提交日志序号，已应用到状态机的日志序号。

### Your scenes

Describe your use scenes (why need this feature)

### Your advice

Describe the advice or solution you'd like

### Environment

- SOFAJRaft version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by killme2008** [comment]
这些信息在 `FSMCallerImpl` 中都有，不过目前没有在 `Node` 开放获取的 API，可以考虑加下，有兴趣可以提个 PR

**Comment by LinHuiG** [comment]
> 这些信息在`FSMCallerImpl`里面有，不过目前没有在`Node`开放获取的 API，可以考虑加下，有兴趣可以提个 PR
前两天比较忙，准备闲了回家做（用公司电脑怕有版权问题），今天看到你们都已经做完了，非常感谢~~
