### ISSUE TITLE
创建RheaKVStore时配置InitialServerList列表时，配置多个节点IP验证无效

### ISSUE THREAD

**Issue by xtr1993** [sofastack/sofa-jraft#881]
### Your question

按照官网的案列，配置InitialServerList都是本地一台节点的三个端口，这个是没问题的，当我想把服务做成分布式的，配置了三台节点的IP，发现不起作用

### Environment

- SOFAJRaft version: 1.3.10
- JVM version (jdk1.8):
- OS version (e.g. `uname -a`):
- Maven version: 3.6
- IDE version:

**Comment by fengjiachun** [comment]
需要详细一点的信息，比如具体错误等， 是本地三个端口还是分布式三个节点，理论上对 rheakv 都不感知，所以需要你给出比如错误是什么？ 否则我也没法猜

**Comment by xtr1993** [comment]
> 需要详细一点的信息，比如具体错误等， 是本地三个端口还是分布式三个节点，理论上对 rheakv 都不感知，所以需要你给出比如错误是什么？ 否则我也没法猜

具体代码如下：
`public RaftRegistry() {
        try {
            final PlacementDriverOptions pdOpts = PlacementDriverOptionsConfigured.newConfigured()
                    .withFake(true) // use a fake pd
                    .config();
            //TODO set ha store engine: default rocksdb
            final StoreEngineOptions storeOpts = StoreEngineOptionsConfigured.newConfigured() //
                    .withStorageType(StorageType.RocksDB)
                    .withRocksDBOptions(RocksDBOptionsConfigured.newConfigured().withDbPath(DB_PATH).config())
                    .withRaftDataPath(RAFT_DATA_PATH)
                    .withServerAddress(new Endpoint("127.0.0.1", HA_LISTENER_PORT))
                    .config();
            final RheaKVStoreOptions opts = RheaKVStoreOptionsConfigured.newConfigured() //
                    .withClusterName(HA_CLUSTER_NAME)
                    .withUseParallelCompress(true)
                    .withInitialServerList(HA_ALL_NODES)
                    .withStoreEngineOptions(storeOpts)
                    .withPlacementDriverOptions(pdOpts)
                    .config();

            rheaKVStore = new DefaultRheaKVStore();
            rheaKVStore.init(opts);
            subscribeListenerManager = new SubscribeListenerManager(rheaKVStore);
            subscribeListenerManager.refreshSubscribe();
            logger.info("JRaft Server start OK");
        } catch (Exception e) {
            logger.error("JRaft Server start Failed");
        }
    }`
我在三台节点上部署了这个服务，把三台节点的心态信息通过线程定时发送到这个服务中。
当我把 HA_ALL_NODES 这个配成 三个节点的IP+端口号时，发现只有第一次的心跳发送过去了，后面就没有发送心跳的日志输出；
但是当我把HA_ALL_NODES 换成本地的三个IP+端口号时又立马没问题了；

日志输出情况：图一是异常情况，图二是正常状态
![1663664536215](https://user-images.githubusercontent.com/38655011/191216187-bfea5f44-dfbf-4c2e-abb2-30eee9ec394a.png)

![1663664654385](https://user-images.githubusercontent.com/38655011/191216491-a4c1ffee-e82f-477a-a564-1411d089bbf3.png)

**Comment by xtr1993** [comment]
> 需要详细一点的信息，比如具体错误等， 是本地三个端口还是分布式三个节点，理论上对 rheakv 都不感知，所以需要你给出比如错误是什么？ 否则我也没法猜

目前没发现报错，希望给一点排查经验或者建议，我们想要在生产组件上使用sofa技术栈

**Comment by killme2008** [comment]
去 `~/logs` 目录下看看，看下所有的日志，有没有错误信息等。

**Comment by fengjiachun** [comment]
`.withServerAddress(new Endpoint("127.0.0.1", HA_LISTENER_PORT))`

这里要填你在 InitialServerList 配置的那个地址，如果你 InitialServerList 配置的是 host，那么直接去掉这行代码也可以

猜测问题应该是你填的这个 server_address 导致该节点认为它不在 group 里，所以没启动

**Comment by killme2008** [comment]
InitialServerList 一次性配置后，是不能乱改的，后面增删节点需要通过 api 增删，如果要重新配置，记得删除你配置的 `RAFT_DATA_PATH` 目录，否则不会生效。

使用raft先阅读下论文和 jraft 的用户指南吧 https://www.sofastack.tech/projects/sofa-jraft/overview/

**Comment by fengjiachun** [comment]
@xtr1993 如问题解决辛苦回来反馈一下

**Comment by fengjiachun** [comment]
先关闭了，仍未解决可以再打开

**Comment by xtr1993** [comment]
> @xtr1993 如问题解决辛苦回来反馈一下

问题已解决，如果分布式部署的话，new Endpoint("127.0.0.1", HA_LISTENER_PORT) 这块要写IP，不能用127.0.0.1
