### ISSUE TITLE
遇到一个braft覆盖已committed日志的bug，jraft是不是也有？

### ISSUE THREAD

**Issue by Yriuns** [sofastack/sofa-jraft#882]
1. A B C 3节点, A是`term=29`的leader, 3个节点的`term`都是29, `lastLogId`都是`(term=29, index=6608)`
2. AB之间网络中断, B触发election_timeout开始走选举流程时网络又恢复了
3. B发起`preVote`, A同意
4. B发起`requestVote`, A在`handleRequestVoteRequest`中放锁读`lastLogId`, 读到`(term=29, index=6608)`
5. A收到新的用户请求`(term=29, index=6609)`, 发给了C, 达成一致并`onApply`
6. A在`handleRequestVoteRequest`中重新加锁, 校验`logIsOk `通过, 向B回复`granted=true`
7. B成为`term=30`的leader, 写下空日志`(term=30, index=6609)`. 与已经apply的`(term=29, index=6609)`冲突!

**Comment by killme2008** [comment]
有几个问题： 

首先，在 A 还是 leader 的情况下，第 3 步 prevVote 就会忽略，不会同意，所以选举也不可能发生。见 
https://github.com/sofastack/sofa-jraft/blob/master/jraft-core/src/main/java/com/alipay/sofa/jraft/core/NodeImpl.java#L1685-L1689

```java
if (this.leaderId != null && !this.leaderId.isEmpty() && isCurrentLeaderValid()) {
                    LOG.info(
                        "Node {} ignore PreVoteRequest from {}, term={}, currTerm={}, because the leader {}'s lease is still valid.",
                        getNodeId(), request.getServerId(), request.getTerm(), this.currTerm, this.leaderId);
                    break;
                }
```
其次，第 4 步，当 B 发起 requestVote 的时候， A 就会从 leader 退位 `stepDown`，不可能再去接受 C 的请求，见 https://github.com/sofastack/sofa-jraft/blob/master/jraft-core/src/main/java/com/alipay/sofa/jraft/core/NodeImpl.java#L1782-L1789

```java
        if (request.getTerm() >= this.currTerm) {
                    LOG.info("Node {} received RequestVoteRequest from {}, term={}, currTerm={}.", getNodeId(),
                        request.getServerId(), request.getTerm(), this.currTerm);
                    // increase current term, change state to follower
                    if (request.getTerm() > this.currTerm) {
                        stepDown(request.getTerm(), false, new Status(RaftError.EHIGHERTERMRESPONSE,
                            "Raft node receives higher term RequestVoteRequest."));
                    }
                }
```

所以你描述这个场景，如果我没有误解的话，应该是不可能发生。从我对 braft 的代码了解程度来看，他们也是处理了这种情况。

**Comment by Yriuns** [comment]
> 有几个问题：
> 
> 首先，在 A 还是 leader 的情况下，第 3 步 prevVote 就会忽略，不会同意，所以选举也不可能发生。见 https://github.com/sofastack/sofa-jraft/blob/master/jraft-core/src/main/java/com/alipay/sofa/jraft/core/NodeImpl.java#L1685-L1689
> 
> ```java
> if (this.leaderId != null && !this.leaderId.isEmpty() && isCurrentLeaderValid()) {
>                     LOG.info(
>                         "Node {} ignore PreVoteRequest from {}, term={}, currTerm={}, because the leader {}'s lease is still valid.",
>                         getNodeId(), request.getServerId(), request.getTerm(), this.currTerm, this.leaderId);
>                     break;
>                 }
> ```
> 
> 其次，第 4 步，当 B 发起 requestVote 的时候， A 就会从 leader 退位 `stepDown`，不可能再去接受新的请求，见 https://github.com/sofastack/sofa-jraft/blob/master/jraft-core/src/main/java/com/alipay/sofa/jraft/core/NodeImpl.java#L1782-L1789
> 
> ```java
>         if (request.getTerm() >= this.currTerm) {
>                     LOG.info("Node {} received RequestVoteRequest from {}, term={}, currTerm={}.", getNodeId(),
>                         request.getServerId(), request.getTerm(), this.currTerm);
>                     // increase current term, change state to follower
>                     if (request.getTerm() > this.currTerm) {
>                         stepDown(request.getTerm(), false, new Status(RaftError.EHIGHERTERMRESPONSE,
>                             "Raft node receives higher term RequestVoteRequest."));
>                     }
>                 }
> ```
> 
> 所以你描述这个场景，如果我没有误解的话，应该是不可能发生。从我对 braft 的代码了解程度来看，他们也是处理了这种情况。

感谢回复。看起来jraft和braft的实现是有区别的，确实避免了这种情况
1. step 3在braft上不会忽略，因为braft的判断条件`follower_lease`是否还有效，而leader是没有`follower_lease`的
2. step 4在braft上是先取`last_log_id`然后再校验term触发stepdown

我研究一下提交历史看看jraft是不是有过fix

**Comment by killme2008** [comment]
看情况 braft 是这个 commit 改了这块逻辑 https://github.com/baidu/braft/commit/3cfb1f110682d30f75dc1c750033575b36ef7801

**Comment by Yriuns** [comment]
> 看情况 braft 是这个 commit 改了这块逻辑 [baidu/braft@3cfb1f1](https://github.com/baidu/braft/commit/3cfb1f110682d30f75dc1c750033575b36ef7801)

是的，这个commit是为了修复N>3的raft group切主不成功的问题，没想到引入了正确性问题。。

**Comment by Yriuns** [comment]
> 看情况 braft 是这个 commit 改了这块逻辑 [baidu/braft@3cfb1f1](https://github.com/baidu/braft/commit/3cfb1f110682d30f75dc1c750033575b36ef7801)

是的，这个commit是为了修复N>3的raft group切主不成功的问题，没想到引入了正确性问题。。
