### ISSUE TITLE
如何应对节点IP变动、节点迁移的问题？？

### ISSUE THREAD

**Issue by JavaCoderCff** [sofastack/sofa-jraft#883]
bootstrap(BootstrapOptions) 好像满足不了需求。如果存在操作日志的话会报错吧。。
可以描述下bootstrap的应用场景吗？

**Comment by killme2008** [comment]
成员变更用 `addPeer`, `removePeer` 等，参照指南 4.2 节 CLI 服务 https://www.sofastack.tech/projects/sofa-jraft/jraft-user-guide/

bootstrap 是让你停机迁移集群，或者当紧急情况下，优先为了可用性恢复集群用的。
