### ISSUE TITLE
RFC: I'm working on #854 "multi-generation log cache"

### ISSUE THREAD

**Issue by RockRockWhite** [sofastack/sofa-jraft#886]
@RockRockWhite You can submit a RFC first

_Originally posted by @hzh0425 in https://github.com/sofastack/sofa-jraft/issues/854#issuecomment-1250519954_
     As discussion in #854, I was assigned the issue, on which I'm working.   
I submit this RFC for farther discussion and report the progress of my work.

**Comment by hzh0425** [comment]
'Submit RFC' means you should submit a pr like that https://github.com/sofastack/sofa-jraft/pull/710
