### ISSUE TITLE
主从进行日志一致性判断后，将从指定位置后的日志删除

### ISSUE THREAD

**Issue by wangweiai** [sofastack/sofa-jraft#894]
主从进行日志一致性判断后，将从节点指定位置后的日志删除，但是从已经将日志应用到状态机，此时从与主的内存数据不一致，此时是不是只能通过Install主的Snapshot文件进行修复？

**Comment by LinHuiG** [comment]
根据我的理解，从的日志应用到状态机是在从节点日志提交之后。从节点收到日志提交信息并校验通过后才会在本节点将日志提交，之后再应用到状态机，被提交的日志是不可能被删除的，你说的情况是不存在的。
详细可以看一下raft论文的5.4.8，里面有比较详细的描述https://github.com/maemual/raft-zh_cn/blob/master/raft-zh_cn.md#5-raft-%E4%B8%80%E8%87%B4%E6%80%A7%E7%AE%97%E6%B3%95
