### ISSUE TITLE
关于低延迟的优化配置项的疑问

### ISSUE THREAD

**Issue by LinHuiG** [sofastack/sofa-jraft#895]
### Your question

我正在开发一个低延迟的系统，我尝试了非常多的配置项，包括把磁盘的fsync配置为false，调整线程池等方式，以及在同一台机器上部署三个节点以降低网络延迟，但最后测试出来的提交延迟（从任务提交到任务被apply到状态机）总是不低于250微秒。
我想了解一下你们是否有针对低延迟场景的配置方案。
以及，我不太清楚为什么内部需要开启那么多线程池，根据我的测试，线程池的提交延迟（从任务被submit到任务开始执行）是超过5微秒的。据我所知netty的一根连接会被绑定到同一个work线程里处理，raft的状态机也应该是单线程处理，其他的心跳选举等操作也不需要太多线程。
以上，不知是否是我的理解有误

### Environment

- SOFAJRaft version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by LinHuiG** [comment]
Environment
SOFAJRaft version:1.3.11
JVM version (e.g. java -version):1.8_201
OS version (e.g. uname -a):windows10
Maven version:3.8.1
IDE version:Idea2021.3

**Comment by LinHuiG** [comment]
据我测试，程序启动了上百个线程，线程之间的竞争或许也会导致高延迟

**Comment by LinHuiG** [comment]
这是我配置的nodeOptions
            nodeOptions.setEnableMetrics(false);
            nodeOptions.setEnableRpcChecksum(true);
            nodeOptions.setElectionTimeoutMs(3000);
            nodeOptions.getRaftOptions().setSync(fsync);
            nodeOptions.getRaftOptions().setEnableLogEntryChecksum(true);
            nodeOptions.getRaftOptions().setDisruptorBufferSize(32 * 1024);
            nodeOptions.getRaftOptions().setMaxAppendBufferSize(1024 * 1024);
            nodeOptions.getRaftOptions().setMaxEntriesSize(2 * 1024);
            nodeOptions.getRaftOptions().setMaxBodySize(512 * 2048);
            nodeOptions.getRaftOptions().setApplyBatch(4);
            nodeOptions.setApplyTaskMode(ApplyTaskMode.Blocking);
            nodeOptions.setRaftRpcThreadPoolSize(1);
            nodeOptions.setTimerPoolSize(1);
            nodeOptions.setCliRpcThreadPoolSize(1);
            nodeOptions.setRpcProcessorThreadPoolSize(1);

**Comment by fengjiachun** [comment]
相比较单个请求延时，jraft 更追求的是整体的吞吐
从 raft 的机制上分析，对于单个提交请求来讲，写 raft log（需要同步刷盘），复制 log 到 followers，达成多数派后提交到状态机，这三个步骤有多个涉及到磁盘 IO 甚至网络 IO 的操作，有可预见的延时，所以 jraft 进行了比较多了攒批（异步 batch，理论上是无延时的攒批，代价是一个队列做中转，还需要线程切换），这对单个请求的延时理论上会稍微有一些影响。

综合看，追求单个请求的超低延时不擅长，如果可转为整体吞吐的目标，可尝试调大各种 disruptor buffer size，以及 apply batch 的size 

虽然 250 微秒看起来很难再进行优化，不过如果你能给出一个代码 example 的话，我也可以再分析一下

**Comment by LinHuiG** [comment]
当前我还在做验证性测试，我的应用场景不考虑三个节点同时挂掉两台的情况，所以文件写盘是可以异步的，因此我关掉了fsync，不知道是否还有其他的配置可以降低文件写盘的可靠性以降低延迟
我的状态机内除了data.setTime(System.nanoTime() - data.getTime());外没有做任何事情，

**Comment by LinHuiG** [comment]
对了，我尝试过测试攒批的无延迟，实际上是有延迟的，当我一次提交一条日志并sleep 1ms，平均延迟比一次提交batchNum条日志再sleep 1ms的平均延迟要高出许多
当我设置batchNum=32，一次提交4条日志，延迟超过1ms
当我设置batchNum=4，一次提交4条日志，延迟0.25ms左右

**Comment by LinHuiG** [comment]
我的使用场景：应用会使用低延迟网卡，网络延迟应该会在1微秒级别，不考虑同时挂两台机器的情况，所以磁盘IO也可以忽略（异步落盘即可，异步落盘失败进行特殊处理）

**Comment by fengjiachun** [comment]
先缩小排查范围，你不要使用3副本，直接使用一个节点呢看看延时，jraft 也可以只启动一个节点

**Comment by LinHuiG** [comment]
经过测试，单节点的平均提交延迟在120微秒左右，大约是三节点的一半

**Comment by LinHuiG** [comment]
单节点启动，将applyBatch设置为32，一次提交4条日志，十万条日志的平均提交延迟为200微秒左右
单节点启动，将applyBatch设置为32，一次提交32条日志，十万条日志的平均提交延迟为140微秒左右
单节点启动，将applyBatch设置为1，一次提交1条日志，一万条日志的平均提交延迟为135微秒左右
单节点启动，将applyBatch设置为8，一次提交8条日志，一万条日志的平均提交延迟为139微秒左右

**Comment by LinHuiG** [comment]
单节点启动，将applyBatch设置为1，一次提交32条日志，十万条日志的平均提交延迟为120微秒左右
单节点启动，将applyBatch设置为8，一次提交32条日志，十万条日志的平均提交延迟为150微秒左右

**Comment by LinHuiG** [comment]
单节点启动，将applyBatch设置为8，直接提交十万条日志，花费125ms全部提交

**Comment by LinHuiG** [comment]
单节点启动，将applyBatch设置为1，直接提交十万条日志，花费148ms全部提交
单节点启动，将applyBatch设置为8，直接提交十万条日志，花费125ms全部提交
单节点启动，将applyBatch设置为32，直接提交十万条日志，花费127ms全部提交

测试方法：启动节点后先写入十万条预热，然后执行多次测试方案，计算出来的平均延迟去掉最高和最低，取平均值

**Comment by LinHuiG** [comment]
> nodeOptions.getRaftOptions().setEnableLogEntryChecksum(false);
> nodeOptions.setEnableRpcChecksum(false);

单节点启动，将applyBatch设置为4，一次提交4条日志，十万条日志的平均提交延迟为152微秒左右

**Comment by fengjiachun** [comment]
差不多就这个延迟水平了，你期望的延迟是多少？

**Comment by LinHuiG** [comment]
> 差不多就这个延迟水平了，你期望的延迟是多少？
我期望部署在4台机器上的3个普通节点+1个学习者节点，提交延迟可以达到10微秒量级的延迟 ( ’ ’ )

**Comment by fengjiachun** [comment]
距离目标还差1个数量级，预计是很难的，有没有试过其他 raft 实现？有数据吗

**Comment by killme2008** [comment]
将 setDisruptorBufferSize 缩小，设置成最极端的 5 以内试试。

**Comment by LinHuiG** [comment]
> 距离目标还差1个数量级，预计是很难的，有没有试过其他 raft 实现？有数据吗

目前还没测试过别的raft实现

**Comment by LinHuiG** [comment]
> 将 setDisruptorBufferSize 缩小，设置成最极端的 5 以内试试。

我尝试一下，不过我理解disruptor队列的长度应该不太会对延迟造成负面影响..

**Comment by LinHuiG** [comment]
> > 将 setDisruptorBufferSize 缩小，设置成最极端的 5 以内试试。
> 
> 我尝试一下，不过我理解disruptor队列的长度应该不太会对延迟造成负面影响..

单节点启动，将applyBatch设置为1，一次提交1条日志，一万条日志的平均提交延迟为154微秒左右

**Comment by killme2008** [comment]
似乎修改的不是 setDisruptorBufferSize ?

**Comment by fengjiachun** [comment]
暂时先关闭，有更新可以再打开
