### ISSUE TITLE
集群重启，节点在状态机回放未完成时当选leader

### ISSUE THREAD

**Issue by LinHuiG** [sofastack/sofa-jraft#897]
### Your question

整个集群重启，有节点状态机日志回放未完成便当选leader，请问有什么配置可以让节点把日志回放完成后再启动选举

### Your scenes

Describe your use scenes (why need this feature)

### Your advice

Describe the advice or solution you'd like

### Environment

- SOFAJRaft version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by killme2008** [comment]
当选 leader 并不需要等待 commit 日志回放到 state machine 完成，不知道是什么需求要求这样？
