### ISSUE TITLE
Snapshot file meta 能否同步文件夹

### ISSUE THREAD

**Issue by andesmountain** [sofastack/sofa-jraft#899]
### Your question
snapshot file meta 同步文件夹
Describe your question clearly
阅读了Counter的例子，知道可以设置data文件作为file meta，这样在follower启动时会收到installSnapshot请求，copy file meta中的文件。现在我有个场景，想在snapshot里存一个文件夹a，该文件夹a里的内容是rocksdb相关文件，这种情况下我该如何在onSnapshotSave时处理 writer.addFile，可以直接写成writer.addFile("a") 添加文件夹么。还是说不建议把rocksDb数据库放在snapshot里传递？
### Your scenes

Describe your use scenes (why need this feature)

### Your advice

Describe the advice or solution you'd like

### Environment

- SOFAJRaft version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by killme2008** [comment]
建议压缩成一个文件包。

**Comment by andesmountain** [comment]
那我同步压缩包过去了后，还得解压么？感觉不是很方便

**Comment by killme2008** [comment]
没有更好的建议。一个一个文件通过 `addFile` 添加也是办法，但是传输效率较低，可以参考 rheakv 的处理方式。
