### ISSUE TITLE
当在onLeaderStart中执行node.appy 提交task将阻塞leader 状态机

### ISSUE THREAD

**Issue by a364176773** [sofastack/sofa-jraft#900]
### Describe the bug
当在onLeaderStart中执行node.appy 提交task将阻塞leader 状态机
follower状态机正常执行,leader状态机被阻塞,且leader还不会被重选举替换导致集群无法正常工作,目前还没定位具体代码,怀疑这块onstartleader和状态机的线程池为同一个,单线程下阻塞了leader状态机的任务
我不清楚这样的设计算不算bug,需要官方人员帮忙评估一下,我简单说下我的场景
seata在使用jraft的时候,将数据存储在内存中,在分布式事务下某些处于begin状态的事务在发生leader重选举后由于2秒选举时间的不可用,大部分begin的事务需要转换状态为rollback进行事务的回滚,这个时候利用了onleaderstart去创建task将各个follower中的事务状态进行修改,从而触发了这个类似死锁了一样的bug

### Environment

- SOFAJRaft version: 1.3.11
- JVM version (e.g. `java -version`): jdk 8 331
- OS version (e.g. `uname -a`): windows 11
- Maven version: 
- IDE version:

**Comment by fengjiachun** [comment]
jraft 里的回调，一般不会新开线程，这主要有几个原因：
1. 异步回调将可能导致一些顺序问题，比如可能让 onStartLeader 成为过去式
2. 是否可以在回调接口里做一些异步的处理，一般只有用户可以判断
3. 线程资源问题

像你这种情况，是不是可以考虑异步执行业务逻辑？

**Comment by a364176773** [comment]
> 

1,2两点理解,3的话我觉得可以用CompletableFuture来跑onstartleader吧? 我目前就是采用当成为leader的时候创建一个新的线程去执行业务处理来解决,谢谢

**Comment by killme2008** [comment]
尽量不要在 state machine 的任何回调方法里进行阻塞操作，除非是为了保证顺序类似 `onApply` 这样。

**Comment by a364176773** [comment]
> 尽量不要在 state machine 的任何回调方法里进行阻塞操作，除非是为了保证顺序类似 `onApply` 这样。

ok,明白了谢谢
