### ISSUE TITLE
support  arm like mac m1

### ISSUE THREAD

**Issue by vividfish** [sofastack/sofa-jraft#901]
RocksDB 6.29.4.1/7.0.3 has been released to Maven Central which should now work on M1 macs.
when jraft support ?

**Comment by killme2008** [comment]
The master branch already upgraded rocksdb to 7.7.3, you can package it by yourself if you are in a hurry.

https://github.com/sofastack/sofa-jraft/pull/896

The next release may not soon.

**Comment by a364176773** [comment]
I'm also having this problem, please tell me when a new version will be released

**Comment by fengjiachun** [comment]
SOFAJRaft[ v1.3.12 ](https://github.com/sofastack/sofa-jraft/releases/tag/1.3.12) is released.

**Comment by fengjiachun** [comment]
@vividfish @a364176773

**Comment by a364176773** [comment]
> SOFAJRaft[ v1.3.12 ](https://github.com/sofastack/sofa-jraft/releases/tag/1.3.12) is released.

https://mvnrepository.com/artifact/com.alipay.sofa/jraft-core
目前还没被同步到中央仓库吗？
