### ISSUE TITLE
RocksDB 参数差异化

### ISSUE THREAD

**Issue by qiujiayu** [sofastack/sofa-jraft#903]
### Describe the bug

使用多个 RaftGoup 时，RocksDB 的配置一样的话，那可能在同一时间触发 Compaction，那么会给系统带来比较大的抖动。

### Expected behavior

希望能对不同的 RaftGoup 设置不同的参数，来尽可能避免同一时间触发 Compaction。

**Comment by killme2008** [comment]
这个似乎不是 rocksdb 参数，而是说希望首次 snapshot 增加随机因子。 这个还比较容易，欢迎提个 PR。

**Comment by qiujiayu** [comment]
> 这个似乎不是 rocksdb 参数，而是说希望首次 snapshot 增加随机因子。 这个还比较容易，欢迎提个 PR。

  没太理解，Raft Log 的RocksDB Compaction，和首次 snapshot有什么关系。

**Comment by killme2008** [comment]
sorry，我理解错了，以为是 snapshot。 这个可以有，本质上是对 StorageOptions 多加一层 group id 的映射。https://github.com/sofastack/sofa-jraft/blob/master/jraft-core/src/main/java/com/alipay/sofa/jraft/util/StorageOptionsFactory.java
