### ISSUE TITLE
节点连接本地 ip 时，连接失败

### ISSUE THREAD

**Issue by ReDChicagOTypewriteR** [sofastack/sofa-jraft#908]
### 我通过创建一个类似排队机的 demo 时，出现了一些问题。

![image](https://user-images.githubusercontent.com/52368721/204116495-def0d75c-357a-43b9-935f-d35355f95227.png)

**Comment by ReDChicagOTypewriteR** [comment]
问题似乎已经解决了，是版本的问题，我在使用
`        <dependency>
            <groupId>com.alipay.sofa</groupId>
            <artifactId>jraft-rheakv-core</artifactId>
            <version>1.3.4</version>
        </dependency>`
时出现了上述问题，但是我将版本切换为 1.3.0 时，问题似乎解决了。

**Comment by killme2008** [comment]
优先使用当前稳定版本。
