### ISSUE TITLE
多个  sofa-jraft 客户端冲突问题

### ISSUE THREAD

**Issue by qiujiayu** [sofastack/sofa-jraft#911]
### Describe the bug

多个系统的 sofa-jraft 客户端一起使用时，有以下几个问题：

1.  SPI 机制冲突。如果各个系统个性化定制 com.alipay.sofa.jraft.rpc.impl.BoltRaftRpcFactory 等组件时，会相互冲突，只能加载其中之一；
2. RouteTable 是单例的，如果raft group id 名称相同的话，会有冲突；

### Environment

- SOFAJRaft version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by fengjiachun** [comment]
没有理解这个场景，可以再详细描述下？ 比如多个系统是在单个进程内？

**Comment by qiujiayu** [comment]
> 没有理解这个场景，可以再详细描述下？ 比如多个系统是在单个进程内？

A, B 两个应用都是基于 sofa-jraft 开发的， C应用要调用 A, B 两个应用。 

如果 A、B 两个应用都个性化定制 com.alipay.sofa.jraft.rpc.impl.BoltRaftRpcFactory 等组件时，就会有冲突。

**Comment by fengjiachun** [comment]
那需要定制 BoltRaftRpcFactory 是真实场景还是仅限于举例？ C 调用 A 和 B 需要不同的通信方式？

**Comment by qiujiayu** [comment]
是真实环境

**Comment by fengjiachun** [comment]
> 是真实环境。因为引入了注册中心，需要定制 AddressParser。
> 
> 现在解决方案是不使用 BoltRaftRpcFactory 创建 RpcClient

定制 AddressParser 可不可以根据端口判断？

**Comment by qiujiayu** [comment]
> > 是真实环境。因为引入了注册中心，需要定制 AddressParser。
> > 现在解决方案是不使用 BoltRaftRpcFactory 创建 RpcClient
> 
> 定制 AddressParser 可不可以根据端口判断？

不可以。

**Comment by fengjiachun** [comment]
那就用不同的 rpcclient 吧
