### ISSUE TITLE
咨询一个multi-raft的使用问题

### ISSUE THREAD

**Issue by a364176773** [sofastack/sofa-jraft#913]
### Your question
假设我有3个节点，我想在3个节点上搭3个group是否可以？
如果可以，jraft上是否可以避免已经是某个group的leader再次在另一个group选举中当选leader？尽量保证leader均衡，因为leader是需要做计算的，follower大部分只需要将leader计算逻辑后的结果同步存储下来即可，压力会小很多

### Your scenes

Describe your operational scenes (why do you need this function)

### Your advice

Describe the advice or solution you would like to receive

### Environment

- SOFAJRaft version: - JVM version (e.g. `java -version`): - OS Version (e.g. `uname -a`): - Maven Version: - IDE Version:

**Comment by fengjiachun** [comment]
首先，你可以这么做
然后，各个 group 是互相不感知切隔离的，如果你要保证 leader 均衡，你需要从外部（全局视角）来调度，使用 CliService#rebalance 来平衡 leader

**Comment by a364176773** [comment]
> 

那就是在jraft上没有做干扰机制了对吧，只能通过api方式，有没有可能在选举的时候让多个集群选举串行化
假设3个节点是3个group
group1的选举选举完了，才是2，然后是3，根据顺序1选举完了就知道leader是谁，是否可以在选举定时器间隔器中做下手脚，假设300ms是这次倒计时的时间，发现我是leader后，我随机个干扰时长（可由用户配置，搭载个默认值），尽量把已是leader的节点的倒计时时长加大（不可超过maxElectionDelayMs）来避免其再次成为leader的概率

**Comment by a364176773** [comment]
> 没看懂
> 
> 在我的经验里，leader 的平衡比较好的方式是根据运行时条件动态的 transfer leader， 而不是在选举那一刻就干扰它 （当然你也确实可以依靠选举优先级来巧妙的实现，这个 jraft 也支持，具体请翻阅一些文档，但要说明的是优先级对选举的影响是持续的）
> 
> 另外 RheaKV 的 PD 实现了 leader 平衡，可以供参考，如果你要实现一个的话，主要逻辑在： RegionLeaderBalanceHandler

选举的优先级来实现好像不够动态吧，因为集群的leader可能会在运行过程中进行变化，靠首次启动的优先级不能很好的动态负载均衡。
我的想法就是在选举过程中去破坏这个选举的间隔时间，已经是leader的时间如果大概率比follower慢，先发起选举的follower肯定会成为leader，如果能在选举的过程中延迟已经是leader的节点的其他group的选举倒计时时间，感觉也是一个办法

**Comment by a364176773** [comment]
我阅读了https://www.sofastack.tech/blog/sofa-jraft-priority-election/ 基本上明白该怎么做了谢谢。还有一个问题就是我希望我的集群是可以让用户自定义创建group的，就是启动的时候，多个group下我是不是就得让用户提供多个带有不同优先级策略的连接串，而不能只用同一串。我本来是想着在选举过程中干扰选举而不是选举过程前干扰的方案。

**Comment by a364176773** [comment]
@fengjiachun @killme2008 我还是觉得好像有点问题，我的multi-raft集群已经搭起来了，有没有什么办法尽量不让2个group的leader都是同一个节点呢？想权重那块是全局的，这就有点尴尬，由于leader存在计算开销，可能cpu是30%，而follower是5%，如果2个group都在一个节点上，那么可能cpu就飙到60%了
