### ISSUE TITLE
通过 Github Action 自动发布新版本 jar 到 maven 仓库

### ISSUE THREAD

**Issue by fengjiachun** [sofastack/sofa-jraft#915]

**Comment by qiujiayu** [comment]
https://github.com/sofastack/sofa-jraft/blob/master/pom.xml#L506 把 autoReleaseAfterClose 设置为true，可以非常方便。

**Comment by 1294566108** [comment]
您好，请问是修改pom文件属性配置吗，我可以试试吗

**Comment by fengjiachun** [comment]
@1294566108 我也还没调研怎么弄，有兴趣可以试试

**Comment by shihuili1218** [comment]
可以通过github发布release时触发action，提交到maven仓库

**Comment by fengjiachun** [comment]
> 可以通过github发布release时触发action，提交到maven仓库

来吧，弄弄看
