### ISSUE TITLE
从clickhouse keeper中看到特性是否可以考虑

### ISSUE THREAD

**Issue by a364176773** [sofastack/sofa-jraft#916]
### Your question
https://clickhouse.com/docs/en/operations/clickhouse-keeper/
![image](https://user-images.githubusercontent.com/19943636/209073701-e24b48a5-bc0b-4a96-b40f-b4a924c3c355.png)
我的理解是其它几个节点真的无法再拉起来时，为了保证集群的可用性，可以使1个节点直接成为leader并提交相关任务到状态机执行，这样可能可以减少故障的时间，并为运维人员的扩容争取时间，让1一个节点持续运行，后续的节点扩容进来后成为follower，直接跳过选举

### Your scenes

Describe your use scenes (why need this feature)

### Your advice

Describe the advice or solution you'd like

### Environment

- SOFAJRaft version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by killme2008** [comment]
`resetPeers(Configuration newPeers)` 就是用来处理你说的紧急情况
参见 https://www.sofastack.tech/projects/sofa-jraft/jraft-user-guide/ 的 7.3 节。

**Comment by a364176773** [comment]
> `resetPeers(Configuration newPeers)` 就是用来处理你说的紧急情况 参见 https://www.sofastack.tech/projects/sofa-jraft/jraft-user-guide/ 的 7.3 节。

谢谢,之前看到了,以为这个还是必须大于一定节点数,因为描述上并没有说1个节点也可以强制选主,现在明白了
