### ISSUE TITLE
程序包com.codahale.metrics不存在

### ISSUE THREAD

**Issue by a364176773** [sofastack/sofa-jraft#917]
### Describe the bug

现在是要自行引包吗?
1.3.11
mvn dependency:tree  存在
![image](https://user-images.githubusercontent.com/19943636/209349728-458447a5-9569-429e-be1d-e830e6e8c3d4.png)
1.3.12时

        <dependency>
            <groupId>io.dropwizard.metrics</groupId>
            <artifactId>metrics-core</artifactId>
        </dependency>
就打不进来

### Environment

- SOFAJRaft version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by fengjiachun** [comment]
https://github.com/sofastack/sofa-jraft/blame/master/pom.xml#L240

这不都在呢么

**Comment by fengjiachun** [comment]
看看是不是你自己排除了 jar，先关闭了

**Comment by a364176773** [comment]
可能是这个原因  is missing, no dependency information available ,没真正拉下来

**Comment by a364176773** [comment]
> https://github.com/sofastack/sofa-jraft/blame/master/pom.xml#L240
> 
> 这不都在呢么

我也觉得自己问题,后面排查到了谢谢
