### ISSUE TITLE
get_entry 耗时高，如何优化

### ISSUE THREAD

**Issue by Cczzzz** [sofastack/sofa-jraft#919]
在主从复制和应用状态机时，都需要根据index 读取raft_log 。
读取raft_log  有两个指标：
- get_entry
- get_entry_from_memory

get_entry_from_memory 直接从logsInMemory 读取，这个性能是很好的 在 50us 左右。
但是 get_entry 从rocket DB 读取的性能不太行，可能会到5ms 以上。（磁盘是 aws gp3 10000 io/s 128MB/s ，很显然磁盘不是性能瓶颈）
我该如何优化以减少get_entry 的耗时。
或者调整参数尽可能让所有请求都从logsInMemory 读取

**Comment by fengjiachun** [comment]
https://www.sofastack.tech/projects/sofa-jraft/jraft-user-guide/

参考11小节，把相应的指标发出来看看

**Comment by Cczzzz** [comment]
指标是我后加的：  
public LogEntry getEntry(final long index) {
        this.readLock.lock();
        long time = System.nanoTime();
        try {
            if (index > this.lastLogIndex || index < this.firstLogIndex) {
                return null;
            }
            final LogEntry entry = getEntryFromMemory(index);
            if (entry != null) {
                this.nodeMetrics.recordLatency("get_entry_from_memory", System.nanoTime() - time);
                return entry;
            }
        } finally {
            this.readLock.unlock();
        }
        final LogEntry entry = this.logStorage.getEntry(index);
        if (entry == null) {
            reportError(RaftError.EIO.getNumber(), "Corrupted entry at index=%d, not found", index);
        }
        // Validate checksum
        if (entry != null && this.raftOptions.isEnableLogEntryChecksum() && entry.isCorrupted()) {
            String msg = String.format("Corrupted entry at index=%d, term=%d, expectedChecksum=%d, realChecksum=%d",
                index, entry.getId().getTerm(), entry.getChecksum(), entry.checksum());
            // Report error to node and throw exception.
            reportError(RaftError.EIO.getNumber(), msg);
            throw new LogEntryCorruptedException(msg);
        }
        this.nodeMetrics.recordLatency("get_entry", System.nanoTime() - time);

        return entry;
    }

**Comment by fengjiachun** [comment]
请参考上边的链接第11小节，里面有说明如何输出性能指标，然后把指标数据贴上来看看

**Comment by fengjiachun** [comment]
<img width="896" alt="image" src="https://user-images.githubusercontent.com/3860496/209919550-957ec35e-6fdd-4faf-abab-caad37acf1a8.png">

**Comment by fengjiachun** [comment]
先关闭了，有了更多信息可以重新打开
