### ISSUE TITLE
请问添加或删除节点是否有listener通知？

### ISSUE THREAD

**Issue by a364176773** [sofastack/sofa-jraft#920]
### Your question

目前查看文档 https://www.sofastack.tech/projects/sofa-jraft/jraft-user-guide/ 和 状态机StateMachine的api，貌似没有看到添加leaner和follower会有相关的通知接口
假设我使用jraft做raft集群后，我添加和删除节点时触发广播给我的client一些通知就比较难，好像只能做轮询。目前是leader可以触发onLeaderStart，可以发出相关的通知，而普通的成员不行

### Your scenes

Describe your use scenes (why need this feature)

### Your advice

Describe the advice or solution you'd like

### Environment

- SOFAJRaft version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by fengjiachun** [comment]
com.alipay.sofa.jraft.StateMachine#onConfigurationCommitted

**Comment by a364176773** [comment]
> com.alipay.sofa.jraft.StateMachine#onConfigurationCommitted

看这个名字和方法上注释没理解到是可以有成员变更时的通知，还有个问题LeaderChangeContext里貌似没有携带group信息，当一个multi-raft下某个leader变动后，如何知道是哪个group的leader发生变动了呢（不使用ClientService）

**Comment by fengjiachun** [comment]
multi group 本身是在 jraft-core 再上一层实现的，#onConfigurationCommitted 这个方法属于你的业务状态机，既然已经拿到所在 group 的状态机实例了， groupid 本身应该就不是问题了

**Comment by a364176773** [comment]
> multi group 本身是在 jraft-core 再上一层实现的，#onConfigurationCommitted 这个方法属于你的业务状态机，既然已经拿到所在 group 的状态机实例了， groupid 本身应该就不是问题了

我的疑问是为何LeaderChangeContext中不带有group？集群不增删成员的情况下，好像onConfigurationCommitted不会被调用吧？毕竟没有调用changePeers之类的接口，所以如果不带有group信息，每次都得再查一下，好像不太方便

**Comment by fengjiachun** [comment]
上面不是说了么，multi group 跟 jraft-core 没有关系，自然就没有所谓 groupId

**Comment by fengjiachun** [comment]
`RaftGroupService` 是业务层构建的，需要传入 groupId，fsm 也是业务侧构建的，把两个关联一下 （jraft-core 不感知所谓的 group）

**Comment by a364176773** [comment]
> `RaftGroupService` 是业务层构建的，需要传入 groupId，fsm 也是业务侧构建的，把两个关联一下 （jraft-core 不感知所谓的 group）

明白了，那看来还是要自己编码处理下这个情况，谢谢
