### ISSUE TITLE
multi-raft集群怎么在group级别上设置每个节点选举的权重？

### ISSUE THREAD

**Issue by a364176773** [sofastack/sofa-jraft#924]
### Your question

@fengjiachun @killme2008 我的multi-raft集群已经搭起来了，有没有什么办法尽量不让2个group的leader都是同一个节点呢？想权重那块是全局的，这就有点尴尬，由于leader存在计算开销，可能cpu是30%，而follower是5%，如果2个group都在一个节点上，那么可能cpu就飙到60%了
192.168.31.182:9091::100,192.168.31.181:9092::10,192.168.31.183:9093::10
比如上面的初始连接串只有全局的权重配置，我希望是可以在已经是leader的节点上加一个扰动，假设182这个节点已经是某个group的leader了，那么将他的定时器（选举用的，如果没有leader心跳过来就会触发选举）比如定时器已经到了要重选举的行为了，在此行为前进行随机的sleep，让其他节点的拉票先发出，这样就因为扰动降低了自己当leader的概率了，不知道我这个设想合不合理，如果可以的话，我可以提个pr，具体的代码我还没去看，大概设计上我是这样设计的加个扰动

### Your scenes

Describe your use scenes (why need this feature)

### Your advice

Describe the advice or solution you'd like

### Environment

- SOFAJRaft version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by fengjiachun** [comment]
对于 jraft-core 来说权重不是全局的，每个 raft group 独立的，rheakv 中这个权重确实被设计为全局的，但你参考并稍作修改一下就可以解决

**Comment by a364176773** [comment]
> 对于 jraft-core 来说权重不是全局的，每个 raft group 独立的，rheakv 中这个权重确实被设计为全局的，但你参考并稍作修改一下就可以解决

好的谢谢，其实我想的是如果能动态扰动就好了，但是jraft-core来说对于有多少个group应该是无感知的，是比较位于底层的，看来这种情况只能业务上尝试进行干扰了
