### ISSUE TITLE
时间轮算法可能出现低效率多循环问题

### ISSUE THREAD

**Issue by 1294566108** [sofastack/sofa-jraft#926]
### Your question
时间轮算法中可能出现低效率多循环问题
Describe your question clearly
在HashedWheelTimer#normalizeTicksPerWheel方法中，当ticksPerWheel的值较大时，该方法会循环很多次，方法执行时间不稳定，效率可能会偏低。
![image](https://user-images.githubusercontent.com/91858554/215148733-1f89af7f-7b11-47b9-be61-65ca2f189cde.png)

### Your scenes
使用java8 HashMap的相关实现来完善改算法
Describe your use scenes (why need this feature)
HashedWheelTimer#normalizeTicksPerWheel方法和java8 HashMap中的达到的目的相同，都可以得到一个大于或等于ticksPerWheel的2的幂并返回。
### Your advice
完善修改原算法
Describe the advice or solution you'd like
可以使用如下算法，
    int n = ticksPerWheel - 1;
    n |= n >>> 1;
    n |= n >>> 2;
    n |= n >>> 4;
    n |= n >>> 8;
    n |= n >>> 16;
    // 此处1073741824 = 2^30,防止溢出
    return (n < 0) ? 1 : (n >= 1073741824) ? 1073741824 : n + 1;
由于HashedWheelTimer#normalizeTicksPerWheel方法传入的参数ticksPerWheel类型是【int】,一共运算了2的31次方的数。由于int型最大值是2的31次方，所以输入的int型参数都可以移动的到，不存在由于移位次数不够导致的转换失败的问题。
### Environment

- SOFAJRaft version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by killme2008** [comment]
不错的改进，欢迎提个 PR。这个实现应该是来自 netty 的，也可以同时给 netty 。

**Comment by fengjiachun** [comment]
很好的建议，欢迎 PR
