### ISSUE TITLE
时序图

### ISSUE THREAD

**Issue by gumandy** [sofastack/sofa-jraft#93]
能不能提供一下counter-incrementAndGet的时序图

**Comment by killme2008** [comment]
sorry，暂时没有提供，有兴趣可以来分析贡献一份。

Counter 例子是一个典型的 client-server 结构，通过 bolt 提供的 RPC 协议交互，请求提交到状态机执行，并通过 callback(Closure) 返回应答。

**Comment by Jackie2079** [comment]
Finally, I find somewhere I can talk.. test if I can comment

**Comment by slick2109** [comment]
I greatly appreciate it but I can’t pull anything up. I’m not familiar with any of this

**Comment by killme2008** [comment]
奇葩了，突然多了好多机器人的节奏

**Comment by Prisoner87126** [comment]
大家好，只想问如果想学习coding，请问有什么可以介绍的吗？我只有很基础的知识而已
