### ISSUE TITLE
Closure threadpool 使用SynchronousQueue原因

### ISSUE THREAD

**Issue by hanzhihua** [sofastack/sofa-jraft#934]
### Your question
咨询一个问题，Closure threadpool 使用SynchronousQueue而不使用其他的有缓存的Queue，是怎么考虑的呢？

另外我看到了，到网络调用(this.rpcService.appendEntries) 如果出现在发送端错误如编码出错、iobuf溢出是，还是会调用onRpcReturned，并触发 (Replicator) id.lock()，是否有必要，请指教，谢谢

### Environment

- SOFAJRaft version: 1.3.2
- JVM version (e.g. `java -version`): 1.8
- OS version (e.g. `uname -a`): 4.9
- Maven version:
- IDE version:

**Comment by fengjiachun** [comment]
抱歉回复的有一点晚

> 咨询一个问题，Closure threadpool 使用SynchronousQueue而不使用其他的有缓存的Queue，是怎么考虑的呢？

主要是原因是希望在任务量大 core thread 饱和的时候尽快新增线程来更快的处理任务，中间加一个 queue 会影响到，java threadpool 的策略你懂的，需要 queue 满了后 maximumThreads 参数的值才发挥作用


> 另外我看到了，到网络调用(this.rpcService.appendEntries) 如果出现在发送端错误如编码出错、iobuf溢出是，还是会调用onRpcReturned，并触发 (Replicator) id.lock()，是否有必要，请指教，谢谢

没有太理解，为什么不必要可以说说看
