### ISSUE TITLE
jraft-rheakv 似乎没有只返回keys的方法

### ISSUE THREAD

**Issue by lfygh** [sofastack/sofa-jraft#942]
需求是根据一个前缀范围扫描kv,只获取扫描到的key，业务上不需要value的数据，现在的方法似乎返回的都是KVEntry，只能就全部数据拿到后过滤得到key。所以希望减少value的数据来加快传输。

这种需求有什么好的实现方式吗？

**Comment by fengjiachun** [comment]
https://github.com/sofastack/sofa-jraft/blob/master/jraft-rheakv/rheakv-core/src/main/java/com/alipay/sofa/jraft/rhea/client/RheaKVStore.java#L217

**Comment by fengjiachun** [comment]
最后一个参数： returnValue = false
