### ISSUE TITLE
Rocksdb data rollback

### ISSUE THREAD

**Issue by eye-gu** [sofastack/sofa-jraft#943]
### Your question

RheadKV If two nodes fail to put and one node succeeds in putting, how does the successful node roll back the data from Rocksdb?

RheadKV如果有两个节点put失败, 一个节点put成功, 成功的那个节点是怎么回滚rocksdb的数据的?

**Comment by fengjiachun** [comment]
成功的为什么要回滚？ 

三个节点的都处理了 put，分布式一致性的保障到这里已经完成了，rheakv 如果遇到不可抗力比如写磁盘失败，那么这个节点只能报错并退出，接下来需要人工介入处理，比如替换掉失败的节点（注意 raft log 已经形成多数派，数据并不会丢失）

**Comment by eye-gu** [comment]
> 成功的为什么要回滚？
> 
> 三个节点的都处理了 put，分布式一致性的保障到这里已经完成了，rheakv 如果遇到不可抗力比如写磁盘失败，那么这个节点只能报错并退出，接下来需要人工介入处理，比如替换掉失败的节点（注意 raft log 已经形成多数派，数据并不会丢失）

是我理解有误
