### ISSUE TITLE
关于jraft主节点设置优先级的需求

### ISSUE THREAD

**Issue by SpringLin97** [sofastack/sofa-jraft#946]
有这样一个需求，用jraft多机热备，并且可以设置机器的主节点优先级，目前的主节点是随机的，这样不利于业务的切换。
希望你们可以加入一个主节点优先级的概念。

**Comment by killme2008** [comment]
支持选举优先级啊 https://github.com/sofastack/sofa-jraft/blob/master/jraft-example/src/main/java/com/alipay/sofa/jraft/example/priorityelection/PriorityElectionBootstrap.java

**Comment by SpringLin97** [comment]
![image](https://user-images.githubusercontent.com/63085858/226793215-97d574fb-9347-4272-94d1-d841235b0632.png)
希望你们的文档更新一下，上面没有搜到相关的文档，包括你们最新的特性
