### ISSUE TITLE
提交任务Task为什么要让使用方去获取Leader Node?

### ISSUE THREAD

**Issue by googlefan** [sofastack/sofa-jraft#949]
### Your question
提交任务的Node不能自动获取leader Node 进行任务提交么?
Describe your question clearly
在集成Jraft 来实现我的分布式文件系统的时候,在写node.apply(task) 功能时, 参考文档与代码,发现必须要实现获取leader node的逻辑,或者使用redirect重定向leader 的逻辑 后,才能提交任务,为什么要这么设计呢?
### Your scenes
目前从框架提供的各种工具类中,并没有 提供友好的 获取leader node 的方法,我想使用nodeManage获取leader,发现nodeManager也只能存储自身的Node信息(不知道是不是bug),如果非leader Node 进行提交任务提示失败
Describe your use scenes (why need this feature)

### Your advice
能否将提交任务的功能处理设计人性化一些, 自动获取leader node 进行任务提交,不要让调用方去实现这个逻辑了.
Describe the advice or solution you'd like

### Environment

- SOFAJRaft version:1.3.12
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by fengjiachun** [comment]
Already answered in #939, this issue will be closed for now.
