### ISSUE TITLE
关于jraft主节点设置优先级问题

### ISSUE THREAD

**Issue by SpringLin97** [sofastack/sofa-jraft#951]
A机器：100
B机器：80
C机器：60
第一步先开启B机器和C机器的jraft服务，会在B机器产生主节点。
第二步开启A机器，主节点并不会在A机器，一直保留在B机器，
这个主节点设置优先级选举功能怎么让主节点生效在A机器？？
或者如何让这jraft集群重新选举的方法？？

**Comment by killme2008** [comment]
优先级仅在触发重新选举的时候生效， 为了保证服务的稳定性，会尽量不去触发重新选举。

如果你需要明确指定 leader，请使用 `Node#transferLeadershipTo` 方法。

**Comment by a364176773** [comment]
> 优先级仅在触发重新选举的时候生效， 为了保证服务的稳定性，会尽量不去触发重新选举。
> 
> 如果你需要明确指定 leader，请使用 `Node#transferLeadershipTo` 方法。

我想接着这个issue请问下，目前有没有禅让机制，比如我让某个leader优雅下线的时候，他可以禅让给指定节点或者立即触发其他节点的选举（而不用等待选举定时器达到超时时间触发选举）
