### ISSUE TITLE
readCommittedUserLog 可能获得不到刚写入的数据

### ISSUE THREAD

**Issue by hanzhihua** [sofastack/sofa-jraft#956]
### Describe the bug

我在做NodeTest测试过程中，在测试readCommittedUserLog方法中，出现了错误
![image](https://user-images.githubusercontent.com/1732108/230054947-c0a754f9-8075-48e1-9cc8-4004a4826c86.png)

我发现主要是日志写入后，但lastAppliedIndex 没有原子级别更新，造成了读取不到错误
![image](https://user-images.githubusercontent.com/1732108/230056997-b98358a1-8fe1-4cbb-ac61-0064fd77dd92.png)

### Environment

- SOFAJRaft version: 1.2.6
- JVM version (e.g. `java -version`): 1.8
- OS version (e.g. `uname -a`): 4.9
- Maven version:
- IDE version:

**Comment by killme2008** [comment]
因为 `onApply` 中是可以回滚的，所以没法去实时更新 lastAppliedIndex，只有确认这一批次没有回滚或者回滚的正确 log index，才能去更新。
如果你需要在 `onApply` 过程中去 commit，可以调用日志迭代器的 `Iterator#commit` 方法，将当前 apply 的 log index 确认提交。然后就可以调用  `readCommittedUserLog` 确保可以读取到，代价就是无法回滚到 commit 之前的位置了。

**Comment by hanzhihua** [comment]
问一下，onApply回滚是什么意思，是指状态机apply发生异常，还是获取日志为null，另外怎么回滚呢？

**Comment by killme2008** [comment]
> 问一下，onApply回滚是什么意思，是指状态机apply发生异常，还是获取日志为null，另外怎么回滚呢？

这个方法

https://github.com/sofastack/sofa-jraft/blob/fdf737850097eb1bf20d34b8caaa0bb6f0c92ad7/jraft-core/src/main/java/com/alipay/sofa/jraft/Iterator.java#L90

**Comment by hanzhihua** [comment]
哦，明白了，现在没有用到这个，目前好像没有用到，如果apply失败了，就需要人工解决了
