### ISSUE TITLE
proposal: Auto commit mode for applying log iterator

### ISSUE THREAD

**Issue by killme2008** [sofastack/sofa-jraft#957]
The current log [Iterator](https://github.com/sofastack/sofa-jraft/blob/master/jraft-core/src/main/java/com/alipay/sofa/jraft/Iterator.java) is used to apply a batch of raft logs to state machine. After the batch is applied to state machine and returns from `StateMachine#onApply` method, these logs are considered **committed**.

And while iterating the logs in iterator:
1. We can call `Iteartor#setErrorAndRollback` to rollback applied logs and halt the state machine.
2. Or call `Iteartor#commit` to commit the logs already applied.

If we want to commit every log while applying, we should call `commit` method everytime:

```java
while(it.hasNext()) {
    ByteBuffer data = it.getData();
    // apply data to state machine
   ......
   it.commit();
   it.next();
}
```

I think we can add an auto-commit mode to simplify the code:

```java
// Enable auto-commit mode
it.setAutoCommit(true);

while(it.hasNext()) {
    ByteBuffer data = it.getData();
    // apply data to state machine
   ......
   it.next();
}
```

After enabling auto-commit mode by `it.setAutoCommit(true)`, the iterator will call `commit` automatically when calling `hasNext()` that returns `true`.

**Comment by 1294566108** [comment]
Hello, I am interested in this issue. My specific implementation process is as follows: 

（1）we can declare a `setAutoCommit (boolean status)` method in the **Iterator** interface. 
![image](https://user-images.githubusercontent.com/91858554/230736146-87bfdad6-6fd3-4cf8-a31f-a0a0ec7045f6.png)


（2）In the **IteratorImpl** class, we need to declare two variables of Boolean type. The first is `autoCommit`, which is used to declare whether to enable the autocommit function, and the second is `lastCommit`, which indicates whether the previous iterator has been committed. 
![image](https://user-images.githubusercontent.com/91858554/230736177-ea83db99-7e77-4dc2-8671-19d1995355ed.png)


（3）So the code for the modified `hasNext` method is shown **in the following figure**：
Each time the hasNext method is called in the loop, the method will perform additional checks：
<3.1> Whether automatic submission is enabled;
<3.2> Whether the last loop has been submitted (the lastCommit field defaults to true in the first loop); 
<3.3> Whether there were errors in the last loop
<3.4>Then obtain whether the iterator has any elements that have not been traversed
<3.5>Finally, set `lastCommit` to false, indicating that this loop has not been submitted yet
![image](https://user-images.githubusercontent.com/91858554/230736113-029bd600-5169-460f-837a-a467c9990fed.png)

（4）We also need to modify the commit method **as follows**：
This means that after we submit, the previous submission status will become submitted
![image](https://user-images.githubusercontent.com/91858554/230736708-d95c208a-f3f4-44cb-ba7d-8013f168ec18.png)

**Comment by killme2008** [comment]
@1294566108 Cool, please create a PR, thanks.

**Comment by 1294566108** [comment]
Okay, I have submitted the PR, could you please help review it
