### ISSUE TITLE
是否可以提供一个类似zk的snapCount的配置

### ISSUE THREAD

**Issue by a364176773** [sofastack/sofa-jraft#958]
### Your question

目前使用下来貌似只看到了一个时长的配置项，在长时间，或者低流量的情况下，可能没有必要做snapshot，而高流量下为了保证宕机回复的时间，可能需要将时间设置的比较短，这样就不能比较好的预估一个能接受的流量范围去做snapshot的配置，个人认为最好可以跟zk一样将时间或次数任一达标后制作一次快照

### Environment

- SOFAJRaft version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by killme2008** [comment]
`Iterator#commitAndSnapshotSync ` 就是用来做这个事情的

https://github.com/sofastack/sofa-jraft/blob/fdf737850097eb1bf20d34b8caaa0bb6f0c92ad7/jraft-core/src/main/java/com/alipay/sofa/jraft/Iterator.java#L79

**Comment by a364176773** [comment]
原来是要这样使用呀，我还以为jraft框架层面托管，我们只需配置呢 @killme2008

**Comment by a364176773** [comment]
谢谢
