### ISSUE TITLE
readIndex 使用了是的commitedIndex,而不是使用读请求归属的index

### ISSUE THREAD

**Issue by hanzhihua** [sofastack/sofa-jraft#959]
### Your question

我注意到线性读 readIndex 使用了是的commitedIndex,而不是使用读请求归属的index，这个符合规范吗？

### Environment

- SOFAJRaft version: 1.2.6
- JVM version (e.g. `java -version`): 1.8
- OS version (e.g. `uname -a`): 4.9
- Maven version: 3.5
- IDE version:

**Comment by killme2008** [comment]
sorry，规范是什么？ 满足线性一致读的约束即可。什么是 readIndex 可以自行阅读一些论文或者文章。

**Comment by hanzhihua** [comment]
哦，主要是我看了一些文章比较readIndex解决方案，比如使用跟写操作一样的日志，或者用心跳、lease,但我有点疑惑的是使用日志方式应该是用读取时刻生成的index，而不是使用心跳方式的committedIndex?
