### ISSUE TITLE
RheaKV中的RocksDB为何不支持选择其他压缩方式和压缩风格？

### ISSUE THREAD

**Issue by a364176773** [sofastack/sofa-jraft#965]
### Your question

```
        if (!Platform.isWindows()) {
            opts.setCompressionType(CompressionType.LZ4_COMPRESSION) //
                .setCompactionStyle(CompactionStyle.LEVEL) //
                .optimizeLevelStyleCompaction();
        }
```

### Your scenes

Describe your use scenes (why need this feature)

### Your advice

Describe the advice or solution you'd like

### Environment

- SOFAJRaft version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by a364176773** [comment]
貌似可以靠 `StorageOptionsFactory.registerRocksDBOptions` 注册进去，这样就不会走default了？

**Comment by killme2008** [comment]
是的，可以设置自己的选项。
