### ISSUE TITLE
Invalid cross-device link

### ISSUE THREAD

**Issue by qiujiayu** [sofastack/sofa-jraft#966]
### Describe the bug

Suppressed: java.nio.file.AtomicMoveNotSupportedException: /home/xxx -> /opt/xxxx/snapshot_42621: Invalid cross-device link
		at java.base/sun.nio.fs.UnixCopyFile.move(UnixCopyFile.java:414)
		at java.base/sun.nio.fs.UnixFileSystemProvider.move(UnixFileSystemProvider.java:266)
		at java.base/java.nio.file.Files.move(Files.java:1432)
		at com.alipay.sofa.jraft.util.Utils.atomicMoveFile(Utils.java:375)

### Environment

- SOFAJRaft version: 1.3.13

**Comment by killme2008** [comment]
It's expected, I don't think it's a bug.

**Comment by qiujiayu** [comment]
> It's expected, I don't think it's a bug.

But we hope to support this feature.

**Comment by sunng87** [comment]
> > It's expected, I don't think it's a bug.
> 
> But we hope to support this feature.

It will break the promise of API, and impact the correctness of jraft. I think it's not a good idea to do this.

**Comment by fengjiachun** [comment]
There is no need to do this within the jraft framework. After `onSnapshotSave` is completed, the user-level code can implement the `cross device copy`.
