### ISSUE TITLE
`LOG` file keep growing risk

### ISSUE THREAD

**Issue by chenzhiguo** [sofastack/sofa-jraft#973]
### Describe the bug

File `LOG` in the directory `raft_data/raft_data_region_-1_8182/log/` keeps growing, resulting in a large file. Is there any way to automatically clear or cancel the writing of this file? Such unlimited growth in the online environment is risky.

### Expected behavior
Control no output or periodic cleaning
### Actual behavior
Keep growing

Can I delete this file directly? Or run `echo "" > LOG` to clean file content.  @fengjiachun @killme2008

**Comment by killme2008** [comment]
The log will keep growing unless you enable snapshot.

Please read the jraft user guide before using jraft, thank you.
