### ISSUE TITLE
快照snapshot执行后，raft log并未实时物理删除，释放磁盘空间

### ISSUE THREAD

**Issue by tdxafpdq** [sofastack/sofa-jraft#978]
### Your question

![image](https://user-images.githubusercontent.com/122855723/233912407-ca90e2f2-9634-42a5-8846-92c1212cc325.png)
>>你可以关闭定时机制，自行控制，通过 Node#snapshot 方法

>>[sofa-jraft/jraft-core/src/main/java/com/alipay/sofa/jraft/Node.java](https://github.com/sofastack/sofa->>jraft/blob/9787367ef1b15de2ea0d10aac2b5d9f4d4302f39/jraft-core/src/main/java/com/alipay/sofa/jraft/Node.java#L271)

>>Line 271 in [9787367](https://github.com/sofastack/sofa-jraft/commit/9787367ef1b15de2ea0d10aac2b5d9f4d4302f39)

 >>void snapshot(final Closure done); 
Node#snapshot执行之后，raft log文件【000390.log】并没有释放空间；
通过debug调试发现，重启服务调用到RocksDBLogStorage#openDB()时，【000390.log】被物理删除了。
请问，不重启服务，怎么物理删除【000390.log】，释放磁盘空间？

也就是说：
jraft执行快照后，调用RocksDBLogStorage#truncatePrefix()方法，raft log从rocksDB删除了
但是查看/log目录 发现并没有真正释放磁盘空间
当重启服务，调用到RocksDBLogStorage#openDB()时，才真正释放了磁盘空间
怎么实现快照时，实时释放磁盘空间？

### Your scenes

快照机制snapshot启动策略 #972 ==》追问

### Environment

- SOFAJRaft version:1.3.10.bugfix_2
- JVM version (e.g. `java -version`):1.8.0_291
- OS version (e.g. `uname -a`):
- Maven version:3.6.3
- IDE version:IDEA2020.1

**Comment by killme2008** [comment]
请去学习下 rocksdb 的基本知识再来提问。 https://blog.csdn.net/Gloria_y/article/details/118600651

这是rocksdb 的  wal，可以通过  `setMaxTotalWalSize` 来调整，默认 1G，想设置可以通过可以通过 `StorageOptionsFactory`。

https://github.com/sofastack/sofa-jraft/blob/9787367ef1b15de2ea0d10aac2b5d9f4d4302f39/jraft-core/src/main/java/com/alipay/sofa/jraft/util/StorageOptionsFactory.java#L154

**Comment by tdxafpdq** [comment]
收到，多谢指点！

**Comment by killme2008** [comment]
确保使用的是 jraft 1.3.10 及以上版本，更早之前版本在删除 sst 方面还不够快。

**Comment by tdxafpdq** [comment]
1.3.10.bugfix_2

**Comment by tdxafpdq** [comment]
debug调试发现：
