### ISSUE TITLE
AppendEntries with an entry with mismatched terms

### ISSUE THREAD

**Issue by asad-awadia** [sofastack/sofa-jraft#981]
What should we do if a new follower that is replicating gets stuck on a particular transaction on `Node {} reject term_unmatched AppendEntriesRequest`?

Should jraft the library handle that? should we do some manual work to fix it?

Our replication gets stuck at https://github.com/sofastack/sofa-jraft/blob/26977b062d1a514e0f1590224b0405c5e93599a6/jraft-core/src/main/java/com/alipay/sofa/jraft/core/NodeImpl.java#L1963 

The leader gets stuck at 'too many pending responses'

Should the logs on the follower get truncated?

### Environment

- SOFAJRaft version: 1.3.11
- JVM version (e.g. `java -version`): 11
- OS version (e.g. `uname -a`): Ubuntu
- Maven version: 3.5.4

**Comment by asad-awadia** [comment]
@killme2008 
@a364176773 
@1294566108

**Comment by killme2008** [comment]
The log lag is too large ` 134469-133620=849`, I think there must be some other errors or warnings before this log.And the replicator may be disconnected or in probe state.

Looks like the replicator processing the append entries requests too slowly.  You can send a signal to get the metrics of jraft by `kill -s <pid>`. Then a file will be generated at the java program working directory named`node_metrics.log`.

Some metrics related to `append-entries`:

* handle-append-entries: The TPS and time consumption for a follower to handle the log replication request
* handle-append-entries-count: the number log entries to be replicated by the follower in each batch. 

You can find more info at jraft user guide `7. Metrics monitoring`:

https://www.sofastack.tech/en/projects/sofa-jraft/jraft-user-guide/

**Comment by killme2008** [comment]
The term is large too. In 849 logs, the term was increased from 467 to 916.

Looks like the cluster is not stable, and many elections happen. Is it expected?

**Comment by asad-awadia** [comment]
>Looks like the cluster is not stable, and many elections happen. Is it expected?

yes it is our test cluster that gets used a lot by QA

**Comment by asad-awadia** [comment]
does having really large raft payload entries cause issues? we have entries that are 100MB+ in size

**Comment by killme2008** [comment]
> does having really large raft payload entries cause issues? we have entries that are 100MB+ in size

Yes, the bolt RPC framework and  netty that JRaft is using has some default limitations.

You can try to change these System properties.

-Dbolt.netty.buffer.low.watermark | 32 × 1024
-- | --
-Dbolt.netty.buffer.high.watermark | 64 × 1024
